### ISSUE TITLE
Child agency master agent invitation and invitation accept

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#1]
An agent with appropriate permissions (may be need to add new) should have an ability to invite a master agent of a child agency.

Invited person should have ability to accept the invitation and register with an agency.

Remarks

There are endpoints returning agent and agency invitations. May be need to rethink them to return the new kind of invitations or make a separate endpoint for this.

**Comment by Raibo** [comment]
https://github.com/happy-travel/agent-app-project/issues/127

**Comment by sergeyf-QA** [comment]
**Summary:**
child agency may be invited and registered

**OK on DEV.**
