### ISSUE TITLE
Add a setting to set deadline shift in dates for a specified agency

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#100]
In current implementation of availability search in all steps dates in cancellation policies are shifted to 1 or 3 days to the past, depending on ContractKind.
Need to allow administrator to specify this shift explicitly, for an agency.
If this setting is specified, it overrides deadline shift, depending on contract kind:

[https://github.com/happy-travel/edo/wiki/Counterparties-%5C-Counterparty-kinds-and-their-contracts](Contract kinds and deadline shifts)

_Look at DeadlinePolicyProcessor class and its usages + AccommodationBookingSettings class for more details_

**Comment by mingazhev** [comment]
@konstyefremov please add a comment for how to test this new feature

**Comment by konstyefremov** [comment]
> @konstyefremov please add a comment for how to test this new feature

resoved with Sergey in discord

**Comment by sergeyf-QA** [comment]
**Summary:**
now, there is an opportunity to change deadline buffer directly by admin for an agency by setting "customDeadlineShift" as x<0 or null in PUT /{culture}/api/{v}/admin/agencies/{agencyId}/system-settings/availability-search 

**OK on DEV.**
