### ISSUE TITLE
The Hbpro-connector response to the mapper contains a locality with a province or state in brackets. 

### ISSUE THREAD

**Issue by oleg-n-k** [happy-travel/agent-app-project#1002]
The Hbpro-connector response to the mapper contains a locality with a province or state in brackets. 
Info in brackets must be removed.

**Comment by sergeyf-QA** [comment]
**Summary:**
- now there is no district or state name in '()' at found accommodations in results of executing GET {{ _.hotelbookProConnector.baseUrl }}/api/1/accommodations?skip=0&top=100

**OK on DEV.**
