### ISSUE TITLE
Enable HTTP/2 and HTTP/3 protocols and update to .NET6

### ISSUE THREAD

**Issue by DFSko** [happy-travel/agent-app-project#1004]
For now all our web apis supports only http 1.1 protocol.
Need to add this settings to all `appsettings.json` everywhere

```json
"Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http1AndHttp2AndHttp3"
    }
  }
```

- In project file set target version - net6
- In dotnet-tools.json file update dotnet-ef version to 6.0.0
- In all EF models change DateTime to DateTimeOffset
- Update all nuget packages
- Add migration
- Update docker and yaml files

---

- [x] #1005
- [x] #1006
- [x] #1007
- [x] #1008
- [x] #1009
- [x] #1010
- [x] #1011
- [x] #1012
- [x] #1013
- [x] #1014
- [x] #1015
- [x] #1016
- [x] #1017
- [x] #1018
- [x] #1019
- [x] #1020
- [x] #1021
- [x] #1022
- [x] #1023
- [x] #1024
- [x] #1025
- [x] #1037

**Comment by DFSko** [comment]
all projects updated to net6

**Comment by sergeyf-QA** [comment]
**Summary:**
- project updated where it is needed

**OK on DEV.**
