### ISSUE TITLE
Put metrics to a separate port 

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#1026]
- [x] #1143
- [x] #1105
- [x] #1027
- [x] All connectors
    - [x] #1152
    - [x] etg-connector
    - [x] #1149
    - [x] #1150
    - [x] #1151
    - [x] #1153
    - [x] #1148
    - [x] #1154
    - [x] #1147
    - [x] #1145
    - [x] #1146
    - [x] #1144

Need to add a second URL for metrics and restrict requests to allow metrics only from specified port.

**Comment by evm-andrey** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0

**Comment by DFSko** [comment]
done

**Comment by sergeyf-QA** [comment]
**Summary:**
- api for /health and /metrics return 404

**OK on DEV.**
