### ISSUE TITLE
Direct API review results

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#1029]
- [x] #1031
- [x] #1032
- [x] #1030
- [x] #1033
- [ ] Use own BookedRoom model instead of model from "Data" in "Booking" model
- [x] #1041
- [x] #1063
- [x] #1036
- [x] #1035
- [x] #1068
- [x] #1065
- [x] #1067
- [x] #1066
- [x] #1086
- [x] #1085
- [ ] Check BookedRoom to have the same structure and nesting as in RoomContract. Fix if the nesting and structure differs

**Comment by DFSko** [comment]
BookedRoom model already exists and using

**Comment by DFSko** [comment]
done
