### ISSUE TITLE
Error while creating booking

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#1034]
1. Search as
`Apart Hotel Volga - 15.02-17.02 - 2 adults - 1 room`

2. Try to create booking by any payment method 

**AR**: 
```
ReferenceCode: "DEV-HTL-AE-000UW5-01"
SearchId: "5eacf742-723a-46b4-8de5-95662e407799"
StackTrace: "   at lambda_method153(Closure , NpgsqlTypeHandle
detail: "Can't write CLR type HappyTravel.Edo.Notifications.Enums.NotificationTypes with handler type Int32Handler"
instance: "/en/api/1.0/accommodations/bookings/book-by-account"
requestId: "0HMEK6DQK12TL:00000002"
spanId: "92ca6182fde8c74d"
status: 500
title: "Internal Server Error"
traceId: "5096337fd6a83241bcb86b7867b24517"
```

[sentry](https://sentry1.happytravel.com/organizations/happytravel/issues/4213/?query=is%3Aunresolved)
[kibana](https://logs-dev.happytravel.com/app/discover#/doc/74b82510-a78b-11eb-a6b0-c1009595f0bf/fluentd-edo-2022.01?id=Hr2bRH4BB3MRHKe7d2ph)

**Comment by sergeyf-QA** [comment]
**Summary:**
- no sentry error while booking creation

**OK on DEV.**
