### ISSUE TITLE
Add booking payment method to summary bookings notifications

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#1038]
Payment method for bookings summary notifications is added to every model. @Raibo can tell how the model looks like now.
Need to add the payment methods to the table:
![image](https://user-images.githubusercontent.com/43397444/148896764-eca9342d-554a-440f-a720-b7d92c424fb0.png)

**Comment by ViTsvetkova** [comment]
@DenisSychev please close if it done

**Comment by DenisVelinen** [comment]
Payment method and Status have been added to the email template. This data is displayed above the table (see pic.)
<img width="657" alt="Снимок экрана 2022-04-25 в 14 04 12" src="https://user-images.githubusercontent.com/17127277/165288185-92121411-2d42-41ae-8107-e61ed7852df3.png">

**Comment by DenisVelinen** [comment]
This was done as part of task #989
