### ISSUE TITLE
Add normalized names for countries, cities and hotels in columbus-connector database

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#106]
Need add normalized names for countries, cities and hotels in columbus-connector database

**Comment by sergeyf-QA** [comment]
**Summary:**
Now in "Hotels" table of Columbus DB are 
"NormalizedCityName" (cities start from big letter)
"NormalizedCountryName" ("The United Arab Emirates" - all words start from big letter + "The")
"NormalizedHotelName" (all hotel names start from big letter)
columns.

**OK on DEV.**
