### ISSUE TITLE
Remove sending nationality and residency in booking request

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#1064]
We do not need these fields from frontend side, we use the fields that were passed on the 1-st step search.

**Comment by sergeyf-QA** [comment]
**Summary:**
- in requests of 
POST https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings
POST https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/book-by-account
POST https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/book-for-offline
are no nationality and residency

**OK on DEV.**
