### ISSUE TITLE
Can not pay using payment link by Payfort

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1069]
**How to reproduce:**
- create a new Payment link by admin choosing Payfort as payment system
- try to pay the link

**Actual result:**
- can not pay using payment link by Payfort
https://edo-dev.happytravel.com/en/api/1.0/external/payment-links/FxscSkPANky64su5cYFasA/ngenius/pay/refresh-status returns 
{"status":400,"detail":"Method Not Allowed"}

**Expected result:**
- successful payment, perhaps there is a wrong link?

**Comment by mingazhev** [comment]
Looks like a frontend bug

**Comment by sergeyf-QA** [comment]
**Summary:**
- now it is possible to pay by payfort

**OK on DEV.**
