### ISSUE TITLE
Need a possibility to copy a booking details from the UI

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1070]
Below you can see the quotation to the agent:
11.02.2022-13.02.2022, HOTEL NAME, Premier Room, 2A, BB, 100 USD

We need to have a possibility to copy from our UI:
- Hotel name 
- Dates 
- Occupancy 
- Deadline 
- And the total rates

**Comment by ViTsvetkova** [comment]
![image](https://user-images.githubusercontent.com/90184684/151939263-df6c47b7-c2bf-4c6d-a882-8da44ebb6938.png)
Our office requests the possibility to copy  the main Accomodation info (the hotel name, searching dates, occupancy, deadline and the total rates) from the 1st search and the 2nd search stages.

**Comment by sergeyf-QA** [comment]
**Summary:**
- 'Copy' button works fine and copy 
Hotel name
Dates
Occupancy
Deadline
And the total rates
at 1st and 2nd search steps

**OK on DEV.**
