### ISSUE TITLE
Add notification settings management for admins

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1072]
Need to add notification settings management for admins

**Comment by sergeyf-QA** [comment]
**Summary:**
- notification management settings are added to the main admin page (uses GET https://edo-dev.happytravel.com/en/api/1.0/admin/notifications/settings)
- saving changes executes PUT https://edo-dev.happytravel.com/en/api/1.0/admin/notifications/settings 


**OK on DEV.**
