### ISSUE TITLE
Error when switching to second step of search [Rakuten]

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#1073]
Search as:
1. `Japan - 24.02-26.02 RU - 1 room`
2. Choose 'Test Hotel Cancellation Policy' 
https://logs-dev.happytravel.com/app/discover#/doc/74b82510-a78b-11eb-a6b0-c1009595f0bf/fluentd-edo-2022.01?id=COLxbH4BkBK-qnlsUB6q

**Comment by DFSko** [comment]
fixed in https://github.com/happy-travel/data-formatters/pull/20

**Comment by sergeyf-QA** [comment]
**Summary:**
- no such error now

**OK on DEV.**
