### ISSUE TITLE
Add additional information to the counterparty table.

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#109]
On https://manage-dev.happytravel.com

1. Log in and go to Counterparties list (click on Counterparties button).

The list of counterparties doesn't contain important information, which is important for understanding the current status of the counterparty.

You need to add:
- a column that show the state (Active or Inactive).
- a column that show the status (Unverified, Verified read only, Fully verified).
- an administrator can search these statuses and states (using the search field).

**Comment by DenisSychev** [comment]
On https://manage-dev.happytravel.com
The list of counterparties contains counterparties that are in an inactive state. For example, "Third user company". Try to find this counterparty using the Search field.
State search doesn't work (see pic. https://drive.google.com/file/d/19iRzGeq2axjOHIKUM5Bn-D-w-zGCdtah/view?usp=sharing ).

**Comment by mingazhev** [comment]
I've added @Raibo to manage this, looks like he knows how to do that best

**Comment by Raibo** [comment]
At the moment I took the task, columns were already there, search not.
But search implemented on the front end. @cyberkarma I guess it's up to you.

**Comment by DenisSychev** [comment]
Was done and works in https://manage-dev.happytravel.com
