### ISSUE TITLE
Add descriptions to cancellation policies and display them in the agent application

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1093]
Need to add descriptions to cancellation policies and display them in the agent application

- [x] #1094
- [x] #1098
- [x] #1095
- [x] #1096
- [x] #1097

**Comment by sergeyf-QA** [comment]
**Summary:**
- "remarks" is sent from back-end side to front-end and are shown on the 3-rd search step
- tested on HBPro hotels because now remarks are available there only

**OK on DEV.**
