### ISSUE TITLE
Add additional information to the counterparty page.

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#110]
On https://manage-dev.happytravel.com
1. Log in and go to Counterparties list (click on Counterparties button);
2. Go to counterparty information page (any counterparty).

The counterparty page doesn't show the name of counterparty - this is very inconvenient.

It's necessary to show the counterparty's name on the page. For example, right after its id.

**Comment by sergeyf-QA** [comment]
**Summary:**
now there is a Counterparty name on the Counterparty page

**OK on DEV.**
