### ISSUE TITLE
500 error when trying to find an offer in a test hotel from ETG.

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#1102]
On 
In any browser

**Steps.**
1. Try to find offers from Test Hotel(Do Not Book), Belogorsk, The Russian Federation (Accommodation_10745974);
For example,
```
{
    "checkInDate": "2022-02-25T00:00:00Z",
    "checkOutDate": "2022-03-02T00:00:00Z",
    "roomDetails": [
        {
            "adultsNumber": 1,
            "childrenNumber": 0
        }
    ],
    "nationality": "RU",
    "residency": "RU",
    "htIds": [
        "Accommodation_10745974"
    ]
} 
```
2. Note the search result.

**Result.**
500 error when trying to find an offer in a test hotel from ETG.
```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.6.1",
    "title": "Internal Server Error",
    "status": 500,
    "detail": "Nullable object must have a value.",
    "instance": "/en/api/1.0/accommodations/availabilities/searches/aa5c74ce-4a51-4a49-b75f-415aa08c40c2",
    "spanId": "e6f61fc5b69024a9",
    "traceId": "16f7e8b1ffabab10e72b0a36641efe6f",
    "requestId": "0HMEVVRVUIO74:00000002",
    "SearchId": "aa5c74ce-4a51-4a49-b75f-415aa08c40c2",
    "x-request-id": [
        "6469cfb9e0e9ce1076dfe1d3776146f0"
    ],
```
**Expectations.**
1. There mustn't be 500 errors;
2. If an error does occur, it shouldn't be shown to the agent, but should be handled and the agent should be shown something like "no offers, try other search parameters" or etc.

**Comment by DenisSychev** [comment]
More details about the error in Sentry by ID: 828263fbe3e144a7812c2ea466536ce4

**Comment by DFSko** [comment]
fixed in https://github.com/happy-travel/edo/pull/1338

**Comment by sergeyf-QA** [comment]
**Summary:**
- is no 500 error while search test hotel of ETG

**OK on DEV.**
