### ISSUE TITLE
Add missing percentage property to cancellation policy

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1103]
Need to add missing percentage property to cancellation policy

**Comment by sergeyf-QA** [comment]
**Summary:**
- "Percentage" is added to "CancellationPolicies" table and to PUT {{ _.komoro.baseUrl }}/api/1.0/properties/8/cancellation-policies/2 and to POST {{ _.komoro.baseUrl }}/api/1.0/properties/8/cancellation-policies

**OK on DEV.**
