### ISSUE TITLE
Need to amend the names of the permissions of checking reports

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1111]
BookingReportGeneration =>BookingReportGenegation
AccountsReportGeneration => FinanceReportGenegation
CompanyReportGeneration => MarketingReportGeneration

**Comment by konstyefremov** [comment]
> BookingReportGeneration =>BookingReportGenegation AccountsReportGeneration => FinanceReportGenegation CompanyReportGeneration => MarketingReportGeneration

Can you check the first line again? It has no name to which it should be renamed.

**Comment by ViTsvetkova** [comment]
the first permission shouldn't be renamed.
