### ISSUE TITLE
Add Booking Summary Notification Period Option To Settings

### ISSUE THREAD

**Issue by alexander-plekhanov** [happy-travel/agent-app-project#1113]
Add a payment summary for all booking payments for a certain day in the future (3 days by default). 
Add an ability to vary notification period from 7 to 1 day by an agent.
If the summary shows that the account balance of an agency will be negative after that future payment, a warning must be added to the notification.
Payment processor should invoke this procedure once per day.

**Comment by ViTsvetkova** [comment]
https://track.happytravel.tech/issue/HP-476/Deadline-approaching-Credit-Limit-Bookings
