### ISSUE TITLE
Error 400 when proceeding to the 3 step of the Illusions booking offer

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#1114]
On https://dev.happytravel.com/

**Steps.**
1. Login any agent;
2. Make a search with details:

> Tai Pan Hotel, Bangkok, Thailand
> Feb 26 – Feb 28
> 1 Guest
> RU-RU nationality and residency

3. Go to the second step of search;
4. Find a Illusions' booking offer;
5. Try to book it.

**Result.**
Error 400 when proceeding to the 3 step of the Illusions booking offer.

**Expectations.**
Offers from Illusions can be booked without errors. If there is an error at the supplier, it has to be handled so that the agent doesn't show an incomprehensible code.

**Comment by DFSko** [comment]
i guess this task is not actual for now

**Comment by sergeyf-QA** [comment]
**Summary:**
- on PROD works fine.

**OK on DEV.**
