### ISSUE TITLE
Remove all saved credit cards (Payfort) and stop they support

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#1115]
On https://dev.happytravel.com/

Some agents have saved credit cards in the system. These were only used when working with Payfort. After switching to Ngenius they are no longer used and no longer work. The saved cards should be removed from the system and not allowed to save credit cards.

**Comment by DenisSychev** [comment]
Link to back-end part #1116

**Comment by sergeyf-QA** [comment]
**Summary:**
- no saved cards during credit card payment

**OK on DEV.**
