### ISSUE TITLE
Remove structures and fix methods that use saved Credit Card data

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#1116]
It was decided to remove the ability to save Credit Cards at checkout and also remove the ability to use previously saved Credit Card details

Remove method references on the front-end 
/cards
/cards/${cardId}
/payments/accommodations/bookings/cards/saved/pay
isSaveCardNeeded is no longer sent in the payment request
the list of saved cards is not used
the "save card for future purchases" checkbox is no longer used
the remember_me field on Payfort always sends 'NO'

**Comment by DenisSychev** [comment]
Link to front-end part #1115

**Comment by sergeyf-QA** [comment]
**Summary:**
- removed saved cards usage from front-end and back-end

**OK on DEV.**
