### ISSUE TITLE
Make appropriate adjustments in the admin panel to use the new endpoints

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1122]
After completing tasks 1119 - 1121, you need to make adjustments in the admin panel to use the new endpoints and permissions.

**Comment by ViTsvetkova** [comment]
@AlexeyShok could you please add more information to the task description for developers and QA team?

**Comment by AlexeyShok** [comment]
This has already been made possible under duplicative tasks
