### ISSUE TITLE
Use payment methods that are available for contract kind

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#113]
More info there
https://github.com/happy-travel/edo/wiki/Counterparties-%5C-Counterparty-Kinds-and-Their-Contracts

Need to change the logic to form payment methods in valuation response, this should be enough but maybe additional validation during booking will be required.

**Comment by sergeyf-QA** [comment]
**Summary:**
now for different contracts types are available such payments methods:
CreditCardPayments (3 in DB) - Credit Card, Offline
CashPayments (1 in DB) - Credit Card, Offline
CreditPayments (2 in DB) - Bank transfer, Credit Card

**OK on DEV.**
