### ISSUE TITLE
Remove "Accommodation in" from a search result header by hotel name

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#1138]
On https://dev.happytravel.com/

If an agent has made a **search by hotel name**, only the hotel name should be shown in the search result header.

Now "Accommodation in" is shown in the search result header before the hotel name (see scrn only_hotel_name).
![only_hotel_name](https://user-images.githubusercontent.com/17127277/152497359-c47d46a4-e9b3-4b15-929f-f7aede0eebc2.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- now there is no "Accommodation in" from a search result header by hotel name
- "Accommodation in" exists in case of wide search

**OK on DEV.**
