### ISSUE TITLE
Add mapper's admin endpoint for adding corrections to an accommodation

### ISSUE THREAD

**Issue by oleg-n-k** [happy-travel/agent-app-project#1142]
Add mapper's admin endpoint for adding corrections to an accommodation

**Comment by wnlstk** [comment]
The method is works. Manually entered values ​​are sent and recorded to the database in the Accomodations table in the AccommodationWithManualCorrections field.

**Comment by wnlstk** [comment]
The method is not work:

Accommodation_11065106
{
	"errors": {
		"Contacts": [
			"The Contacts field is required."
		],
		"Location": [
			"The Location field is required."
		],
		"Schedule": [
			"The Schedule field is required."
		]
	},
	"type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
	"title": "Bad Request",
	"status": 400,
	"instance": "/en/api/1.0/admin/mapper/management/accommodations/Accommodation_11065106/manual-correction",
	"spanId": "cd50cd02d08b2710",
	"traceId": "7ec68887ad3fc2e2853d0f63a7aa1eb8",
	"requestId": "0HMGT44SR65JF:00000002"
}

**Comment by oleg-n-k** [comment]
fixed
