### ISSUE TITLE
Make a control on the frontend to select the account manager from the list

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1163]

**Comment by sergeyf-QA** [comment]
@arsensimdev 
after saving changes and reloading a page there is no saved data
**Expected:**
previously saved data should be in account manager field on agency Details page

**Comment by sergeyf-QA** [comment]
**Summary:**
- added new account manager field on agency Details page with ability to save changes

**OK on DEV.**
