### ISSUE TITLE
Make a set of endpoints in order to set the account manager for the agency

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1164]
PUT {{ edo.baseUrl }}/en/api/{v:apiVersion}/admin/agencies/:agencyId/account-manager

**Comment by sergeyf-QA** [comment]
**Summary:**
- PUT /{culture}/api/{v}/admin/agencies/{agencyId}/account-manager sets an "AccountManagerId" to the "Agencies" table

**OK on DEV.**
