### ISSUE TITLE
Return all cancellation policies with time in UTC (for all connectors)

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#1170]
- [x] #1285
- [x] #1286
- [x] IWTX
- [x] ETG
- [x] Rakuten
- [x] Jumeirah
- [x] TGX Darina
- [x] #1287
- [x] Hotelbeds
- [x] HB Pro
- [x] TGX BookMe
- [x] TGX Roibos
- [x] TGX Accor
- [x] TGX Nuitee
- [x] Hyperguest
- [x] TGX Avra Tours
- [ ] etc...

**Comment by DFSko** [comment]
finished in all existed connectors

**Comment by sergeyf-QA** [comment]
**Summary:**
- Replaced DateTime with DateTimeOffset, so, cancellation policies have time in UTC

**OK on DEV.**
