### ISSUE TITLE
Change netstorming connector to use redis-based cache instead of memory-based

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#1175]

**Comment by kirillta** [comment]
The connecter uses Redis from the start. @mingazhev what did you meant here?

**Comment by mingazhev** [comment]
@DFSko @konstyefremov maybe I heard incorrect?
There was a problem with sync cache usage. I thought that it was caused by using IMemoryFlow

**Comment by kirillta** [comment]
It might happen in a specific class, but not as wide as it declared here

**Comment by DFSko** [comment]
This task is actual?
I haven't found any IMemoryFlow usages
