### ISSUE TITLE
Create a service to collect and show all services EventIds in one place

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#118]
All our services have there own log event id ranges, typically all of them are listed in LogEvents.json file in solution.
Need to develop a service (or a script) to automatically collect event ids from all the services and show in a one place to make log searches simple.
The implementation details are not defined so there may be different approaches.
Please organize a discussion with a team if needed

**Comment by konstyefremov** [comment]
Done https://github.com/happy-travel/log-events-scraper
