### ISSUE TITLE
Add a possibility to create a payment link report

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1189]
Finance team should have a possibility to see payment results for a period via special report.
Parameters that they can see there:
- payment status
- date and time of the payment
- amount
- currency
- payment gateway
- service type
- invoice number
- a person who generated a link

**Comment by mingazhev** [comment]
This may need saving payment link creator (if not saving now)

**Comment by konstyefremov** [comment]
Notes for QA:

1) Added "AgentId" field to "PaymentLinks" table. 
2) When the payment link is created by calling 
POST api/{v:apiVersion}/external/payment-links
AgentId is saved to the payment link table

**Comment by DenisVelinen** [comment]
1. It's incorrect to add AgentId to the PaymentLinks table because the administrator generates the payment links. The administrator isn't always an agent. In this case there will be no value.

**Comment by konstyefremov** [comment]
The endpoint is 
/admin/reports/payment-link-report

**Comment by DenisVelinen** [comment]
There is no sorting in the file, so it's very difficult to navigate through the data. Needs to sort by the time the payment link was created. 
![2022-07-05_19 29 21](https://user-images.githubusercontent.com/17127277/177496312-3ee4558e-22e9-40a3-b285-e0daa8b25864.png)

**Comment by DenisVelinen** [comment]
The data in the report file is sorted by the date the link was created ("Created" column in the DB) from the recent to the first.
