### ISSUE TITLE
List of errors for Columbus 

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#119]
1. On first/second/third steps of the search
**ER**: The hotel name is returned in lower case
**AR**: `"name": "HILTON DUBAI THE WALK"`

2. On first/second/third steps of the search 
**ER**: The hotel rating is returned to the existing one
**AR**: This value is returned for all options `"rating": "NotRated"`

3. On first/second/third steps of the search 
**ER**: Add article before `"country": "The United Arab Emirates"`
**AR**: `"country": "United Arab Emirates"`

4. Add search by field _rooms.type_
 ```
"rooms": [
        {
            "adultsNumber": 2,
            "isExtraBedNeeded": true,
            "type": "Single",
            "childrenAges": []
        }
    ]
```

_Different types -_ `RoomTypes { NotSpecified, Single, TwinOrSingle, Twin, Double, Triple, Quadruple, Family, } `

5. Add search by field `"isExtraBedNeeded"`

**Comment by oleg1std** [comment]
I have requested clarification about 4 and 5 from support. Will be implemented after their response.
