### ISSUE TITLE
Direct API | Remove deadline and "isAdvancePurchaseRate" from Getting accommodations, Room selection, Booking Evaluation

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1190]
According to https://github.com/happy-travel/agent-app-project/issues/1085 and https://github.com/happy-travel/agent-app-project/issues/1066
Remove deadline and "isAdvancePurchaseRate" from responses of
GET https://api-dev.happytravel.com/api/1.0/availabilities/searches/{searchId}
GET https://api-dev.happytravel.com/api/1.0/availabilities/searches/{searchId}/accommodations/{accommodationId}
GET https://api-dev.happytravel.com/api/1.0/availabilities/searches/{searchId}/accommodations/{accommodationId}/room-contract-sets/{roomContractSetId}

**Comment by DFSko** [comment]
RoomContractSet doesnt have Deadline and IsAdvancePurchaseRate. Only RoomContract

**Comment by sergeyf-QA** [comment]
**Summary:**
-  Deadline and IsAdvancePurchaseRate is in Rooms only now

**OK on DEV.**
