### ISSUE TITLE
Add a new permissions for booking view for booking managers and finance managers

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#1219]
- [x] Add a special permission for booking and finance managers
- [x] Check UI to support the permission from frontend side

**Comment by mingazhev** [comment]
Added a permission from frontend and backend side

**Comment by mingazhev** [comment]
May be this will need @alexander-plekhanov help if something will not work as expected

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
can you remove cancel and discard buttons for finance manager role on booking page?

**Comment by alexander-plekhanov** [comment]
@sergeyf-QA clarify pls. We don't hide buttons for any permission. We show permission-related actions for some permission. So can you pls provide a list of permissions that gives an opportunity to see this button. Thx.

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
permission that gives an opportunity to see these button is **Booking Management** permission
