### ISSUE TITLE
After the validity of search result has expired, the agent sees an empty content area.

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#124]
On http://dev.happytravel.com/
In Chrome, Safari.

**Steps.**
1. Log in some agent who can search accommodations;
2. Do any search (so that there is a result) and then do nothing for about 10 minutes or more;
3. Try to choose someone options.

**Result.**
After the validity of search result has expired, the agent sees an empty content area (see pic. https://drive.google.com/file/d/16pTyoJczaq7XHqfbvbk764PN9rbaYDAH/view?usp=sharing ).

**Expectations.**
As hotel offers have an expiry date, you must either show the agent the page with the search form, or restart the search with the previously specified parameters OR just show agent a message saying that the offers have expired (I think there was some text already).

---

- [x] #1451
- [x] #1464

**Comment by alexander-plekhanov** [comment]
It's a complicated feature that should be discussed first. I can fix it buy some excuse-message from my side but I'm not sure that it's the solution we need.

**Comment by alexander-plekhanov** [comment]
As we discussed earlier, this task needs a complex solution.

**Comment by ViTsvetkova** [comment]
https://track.happytravel.tech/issue/HP-528/Need-to-return-another-screen-at-the-second-step-of-search-if-therere-no-offers
