### ISSUE TITLE
Check and fix if needed markup validation

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#1244]
Validation rules:
- Global markup cannot be negative
- Agency-level markup in admin panel can be positive or negative. If negative, cannot lead markup to become negative
- Agency-level markup in agent app cannot be negative
- Agent level markup in agent app cannot be negative

**Comment by AlexeyShok** [comment]
Since the validation has already been done and the validation rules have changed, this task is irrelevant
