### ISSUE TITLE
The uploaded contract file is not shown in the interface.

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#125]
On https://manage-dev.happytravel.com

**Steps.**
1. Log in and go to Counterparties list (click on Counterparties button);
2. Find the "The Clouds company";
3. Go to counterparty information page.

**Result.**
The counterparty had a contract file loaded, but this is not shown in the interface.

**Expectations.**
If a contract file has already loaded, it should be shown.
If a contract file has not loaded yet, the "Download Contract" button should be hidden or prevented from clicking on.

**Comment by sergeyf-QA** [comment]
**Summary:**
If a contract file has already loaded there are two buttons 'Download Contract' and 'Upload Another Contract' and title 'Contract'
If a contract file has not loaded yet, there are no "Download Contract" and 'Upload Another Contract' buttons. Except them is 'Upload Contract' button and title 'Contract (No contract uploaded)'

**OK on DEV.**
