### ISSUE TITLE
Add supplier priorities to the sunpu.

### ISSUE THREAD

**Issue by hasmikharutyunyan** [happy-travel/agent-app-project#1251]
1. Add existing supplier priorities to the sunpu.
2. Make possible to get priorities from other services.
3. Create api for priorities management in sunpu
Supplier priorities example
`{
    "name": [
        "columbus",
        "jumeirah",
        "darina",
        "etg",
        "directContracts",
        "netstorming",
        "illusions",
        "rakuten",
        "travelgateXTest",
        "yalago",
        "paximum",
        "hotelbookPro",
        "hotelBeds",
        "bronevik",
        "bookMe",
        "roibos",
        "avraTours"
    ],
    "photos": [
        "hotelBeds",
        "columbus",
        "jumeirah",
        "darina",
        "etg",
        "directContracts",
        "netstorming",
        "illusions",
        "rakuten",
        "travelgateXTest",
        "yalago",
        "paximum",
        "hotelbookPro",
        "bronevik",
        "bookMe",
        "roibos",
        "avraTours"
    ],
    "rating": [
        "columbus",
        "jumeirah",
        "darina",
        "etg",
        "directContracts",
        "netstorming",
        "illusions",
        "rakuten",
        "travelgateXTest",
        "yalago",
        "paximum",
        "hotelbookPro",
        "hotelBeds",
        "bronevik",
        "bookMe",
        "roibos",
        "avraTours"
    ],
    "category": [
        "columbus",
        "jumeirah",
        "darina",
        "etg",
        "directContracts",
        "netstorming",
        "illusions",
        "rakuten",
        "travelgateXTest",
        "yalago",
        "paximum",
        "hotelbookPro",
        "hotelBeds",
        "bronevik",
        "bookMe",
        "roibos",
        "avraTours"
    ],
    "schedule": [
        "columbus",
        "jumeirah",
        "darina",
        "etg",
        "directContracts",
        "netstorming",
        "illusions",
        "rakuten",
        "travelgateXTest",
        "yalago",
        "paximum",
        "hotelbookPro",
        "hotelBeds",
        "bronevik",
        "bookMe",
        "roibos",
        "avraTours"
    ],
    "contactInfo": [
        "columbus",
        "jumeirah",
        "darina",
        "etg",
        "directContracts",
        "netstorming",
        "illusions",
        "rakuten",
        "travelgateXTest",
        "yalago",
        "paximum",
        "hotelbookPro",
        "hotelBeds",
        "bronevik",
        "bookMe",
        "roibos",
        "avraTours"
    ],
    "locationInfo": [
        "columbus",
        "jumeirah",
        "darina",
        "etg",
        "directContracts",
        "netstorming",
        "illusions",
        "rakuten",
        "travelgateXTest",
        "yalago",
        "paximum",
        "hotelbookPro",
        "hotelBeds",
        "bronevik",
        "bookMe",
        "roibos",
        "avraTours"
    ],
    "propertyType": [
        "columbus",
        "jumeirah",
        "darina",
        "etg",
        "directContracts",
        "netstorming",
        "illusions",
        "rakuten",
        "travelgateXTest",
        "yalago",
        "paximum",
        "hotelbookPro",
        "hotelBeds",
        "bronevik",
        "bookMe",
        "roibos",
        "avraTours"
    ],
    "roomAmenities": [
        "columbus",
        "jumeirah",
        "darina",
        "etg",
        "directContracts",
        "netstorming",
        "illusions",
        "rakuten",
        "travelgateXTest",
        "yalago",
        "paximum",
        "hotelbookPro",
        "hotelBeds",
        "bronevik",
        "bookMe",
        "roibos",
        "avraTours"
    ],
    "additionalInfo": [
        "columbus",
        "jumeirah",
        "darina",
        "etg",
        "directContracts",
        "netstorming",
        "illusions",
        "rakuten",
        "travelgateXTest",
        "yalago",
        "paximum",
        "hotelbookPro",
        "hotelBeds",
        "bronevik",
        "bookMe",
        "roibos",
        "avraTours"
    ],
    "typeDescription": [
        "columbus",
        "jumeirah",
        "darina",
        "etg",
        "directContracts",
        "netstorming",
        "illusions",
        "rakuten",
        "travelgateXTest",
        "yalago",
        "paximum",
        "hotelbookPro",
        "hotelBeds",
        "bronevik",
        "bookMe",
        "roibos",
        "avraTours"
    ],
    "textualDescriptions": [
        "columbus",
        "jumeirah",
        "darina",
        "etg",
        "directContracts",
        "netstorming",
        "illusions",
        "rakuten",
        "travelgateXTest",
        "yalago",
        "paximum",
        "hotelbookPro",
        "hotelBeds",
        "bronevik",
        "bookMe",
        "roibos",
        "avraTours"
    ],
    "accommodationAmenities": [
        "columbus",
        "jumeirah",
        "darina",
        "etg",
        "directContracts",
        "netstorming",
        "illusions",
        "rakuten",
        "travelgateXTest",
        "yalago",
        "paximum",
        "hotelbookPro",
        "hotelBeds",
        "bronevik",
        "bookMe",
        "roibos",
        "avraTours"
    ]
}`

**Comment by sergeyf-QA** [comment]
**Summary:**
- GET /api/{v}/supplier-priorities returns a list of suppliers priorities
- PUT /api/{v}/supplier-priorities changes a list of suppliers priorities

**OK on DEV.**
