### ISSUE TITLE
Need to implement different currencies on the Agent app

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1252]
Agents have to have a possibility to see rates and pay for a booking by different currencies.
HT has GBP, USD, EUR, CNH and AED accounts. The preferable currency is USD.
We are checking with each supplier their currency preferencies.

If the agent has 2 currencies allowed by us they can make payments and have 2 different statements of account per each currency.

We need to have an option for the agents to choose the currency of their choice before making a booking and the system will generate them an invoice with the Bank details of the currency to pay for the booking.

- [x] #1508
- [x] #1509
- [x] #1779
- [x] #1783
- [x] #1551
- [x] #1577 
- [x] #1552
- [x] #1553
- [x] #1554
- [x] #1556
- [x] #1555
- [x] #1806
- [x] #1784
- [x] #1825

**Comment by ViTsvetkova** [comment]
Have to add CNY and AED currency also.
If the agent has 2 currencies allowed by us they can make payments and have 2 different statements of account per each currency.

**Comment by nikolaeva31** [comment]
Need to check reports

**Comment by ViTsvetkova** [comment]
https://github.com/happy-travel/agent-app-project/issues/1922

**Comment by sergeyf-QA** [comment]
@DaniyarAskarov 
could you please check these reports
Agencies report - balance is for usd only
Payable To Supplier Report - the numbers in the report do not match the numbers in bookings
Direct Connectivity Agency Wise Report - the numbers in the report do not match the numbers in bookings
