### ISSUE TITLE
Add materialized settings for available suppliers for agencies and agents

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1264]
Need to add materialized settings for available suppliers for agencies and agents. An example of the logic for working with materialized settings can be viewed in the notification center in edo. 

To get the root agency settings, we get the full list of available suppliers from the sunpu service. The administrator can choose which of the resulting list of suppliers will be available to the root agency. 

The root agent of the root agency, in turn, can specify to each of its child agencies which of the list of suppliers of the root agency the child agency can work with.

In turn, the root agent of the child agency can limit each of its agents the list of suppliers with which it can work.

- [x] #1265
- [x] #1266
- [x] #1407
- [x] #1408
- [x] #1477
- [x] #1478
- [x] #1409
- [x] #1267
- [x] #1268
- [x] #1269
- [x] #1270
- [x] #1337
- [x] #1480

**Comment by konstyefremov** [comment]
_Notes:_

On sunpu the supplier can have one of 3 working modes. 

Disabled - 0 
TestOnly - 1 
Enabled - 2 

- If a supplier is **Disabled**, then it will be completely disabled in materialization. Even if the agency has it enabled.
- If a supplier is **TestOnly**, then it should be explicitly enabled. If it's not enabled in the agency, then it will not be used.
- If a supplier is **Enabled**, then it will be enabled for every agency. Even if it has no explicit settings.

**Comment by konstyefremov** [comment]
|              | Enabled | Disabled | Absent |
|--------------|---------|----------|--------|
| **Disabled** | hide    | hide     | hide   |
| **TestOnly** | true    | false    | false  |
| **Enabled**  | true    | false    | true   |
