### ISSUE TITLE
Add the ability to enable and disable suppliers for the root agency in the admin panel

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1266]
Need to add the ability to enable and disable suppliers for the root agency in the admin panel. 
Need to add a tab with all suppliers on an agency page.
![image](https://user-images.githubusercontent.com/90184684/168068862-9afc7dd5-10b0-487d-bead-2e44ab8b9bf9.png)
It should be possible for root agencies to enable and disable any supplier. For child agencies, you just need to show the current settings without the ability to change them.

**Comment by sergeyf-QA** [comment]
**Summary:**
- 'Suppliers' tab is added to the agency page
- GET https://edo-dev.happytravel.com/en/api/1.0/admin/agencies/{agencyId}/suppliers is called when admin goes to 'Suppliers' tab
- 'Save' button calls PUT https://edo-dev.happytravel.com/en/api/1.0/admin/agencies/{agencyId}/suppliers and changes are saved
- suppliers enables/disables well

**OK on DEV.**
