### ISSUE TITLE
Add supplier's materialized settings for agents

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1269]
It is necessary to add the column EnabledSuppliers to the table "AgentSystemSettings" to the database to store the settings of suppliers by agency. You also need to add the following endpoints:
GET /{culture}/api/{v}/admin/agencies/{agencyId}/agents/{agentId}/suppliers
PUT /{culture}/api/{v}/admin/agencies/{agencyId}/agents/{agentId}/suppliers

**Comment by DaniyarAskarov** [comment]
PR: https://github.com/happy-travel/edo/pull/1764
Insomnia: Edo -> Admin -> Agents -> Suppliers
Not tested yet

GET /{culture}/api/{v}/admin/agents/{agentId}/suppliers
PUT /{culture}/api/{v}/admin/agents/{agentId}/suppliers

Test cases:

Test new endpoints
Start search and check if suppliers was materialized by each level (Sunpu, root agency, child agency, agent)

IMPORTANT:
/admin/agencies/:agencyId/agents/:agentId/system-settings/availability-search model need to be changed and need to notice front-end!!! Enabled suppliers need to be deleted from model and data base in future.

**Comment by sergeyf-QA** [comment]
**Summary:**
- the column EnabledSuppliers is added to the table "AgentSystemSettings"
- GET and PUT endpoints work well
- migration in table "AgentSystemSettings" at the "EnabledSuppliers" column was done (old suppliers still stay enabled, all other - disabled)
- supplier is disabled in Sunpu -> accommodations of this supplier are not available in search regardless agency and agent settings
- supplier is enabled in Sunpu, no supplier settings in agency or agent settings -> accommodations of this supplier are available in search

- supplier is enabled in Sunpu, supplier is disabled in agency settings, no agent settings -> accommodations of this supplier are not available in search
- supplier is enabled in Sunpu, supplier is disabled in agency settings, supplier is enabled in agent settings -> accommodations of this supplier are not available in search
- supplier is enabled in Sunpu, supplier is enabled in agency settings, supplier is disabled in agent settings -> accommodations of this supplier are not available in search
- supplier is enabled in Sunpu, supplier is enabled in agency settings, supplier is enabled in agent settings -> accommodations of this supplier are available in search

- supplier is enabled in Sunpu, supplier is enabled in agency settings, subagency has no settings, supplier is enabled in subagency agent settings -> accommodations of this supplier are available in search
- supplier is enabled in Sunpu, supplier is enabled in agency settings, subagency has no settings, supplier is disabled in subagency agent settings -> accommodations of this supplier are not available in search
- supplier is enabled in Sunpu, supplier is enabled in agency settings, supplier is enabled in subagency settings, supplier is disabled in subagency agent settings -> accommodations of this supplier are not available in search
- supplier is enabled in Sunpu, supplier is enabled in agency settings, supplier is enabled in subagency settings, supplier is enabled in subagency agent settings -> accommodations of this supplier are available in search
- supplier is enabled in Sunpu, supplier is disabled in agency settings, supplier is enabled in subagency settings, supplier is enabled in subagency agent settings -> accommodations of this supplier are not available in search

**OK on DEV.**
