### ISSUE TITLE
400 error when trying to invite a child agency

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#127]
**How to reproduce:**

- go to the agent app as an user who has rights to invite a child agency
- on https://dev.happytravel.com/settings/child-agencies/invite fill all fields and click on 'Invite Child Agency' button

**Actual result:**
- POST https://edo-dev.happytravel.com/en/api/1.0/agency/invitations/send returns 
`{"errors":{"ChildAgencyRegistrationInfo.City":["The City field is required."],"ChildAgencyRegistrationInfo.Phone":["The Phone field is required."],"ChildAgencyRegistrationInfo.Address":["The Address field is required."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"Bad Request","status":400,"instance":"/en/api/1.0/agency/invitations/send","spanId":"8c45ed94eed2dd48","traceId":"f2d8a94722d3294c83f7729999883067","requestId":"0HM7PMB8AP9N7:0000000C"}`

**Expected result:**
- it needs to decide what to do here, perhaps we need make come data like city, country etc as non-required?

**Comment by Raibo** [comment]
Made fields not required while creation of the invitation.
When the invitation is being accepted, they are still required (because it is not possible to create agency without them)

**Comment by sergeyf-QA** [comment]
**Summary:**
now, there is no an error during child agency invitations.

**OK on DEV.**
