### ISSUE TITLE
Change markups to sum percents independently on each level

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#1272]
Current logic sums all the percents from all the levels, which is incorrect.
Percents must be added to each other only at the single beneficiary level. Between the beneficiary levels markups should apply to the results of previous step.
Beneficiary levels:
1. HappyTravel - global and normal agency markups
2. Agency - agent markups and subagency markups

Level 2 can be repeated for subagencies - each subagency can have markups for the agent and for the subagency

**Comment by AlexeyShok** [comment]
Closed because markup logic was rewritten in other tasks
