### ISSUE TITLE
Change text of the error alert of saving markups

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1273]
@alexander-plekhanov 
could you please change text from 'Bad Request' to "The field Percent must be between 0.1 and 100." of the error alert of saving markups when user enters markup out of 0.1 and 100 diapason?
![Screenshot at Mar 14 12-34-53](https://user-images.githubusercontent.com/74529212/158145019-f7f7b4b9-d1ba-41d1-a089-9753fd4dceed.png)

**Comment by alexander-plekhanov** [comment]
@arsensimdev pls implement validators for markup field. [0, 100] when positive only and [-100, 100] when negative values allowed.

**Comment by sergeyf-QA** [comment]
@arsensimdev 
could you please add checking for 0..0.1 diapason?

**Comment by sergeyf-QA** [comment]
**Summary:**
- validation for 0.1...100 diapason works well

**OK on DEV.**
