### ISSUE TITLE
Create a notification to an Account manager if a markup was set up or changed

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1277]
An Account manager should receive a notification immediately when a root agency get a mark up or the agency markup is changed

**Comment by DaniyarAskarov** [comment]
Insomnia: Edo -> Admin -> Markups
Test case:
1. Add/Modify/Delete markups which are not connected directly with agencies should notify all account managers.
2. Set account manager to agency then Add/Modify/Delete agency destination markup. Notification have to be sended to this account manager.

**Comment by sergeyf-QA** [comment]
**Summary:**
- notifications work only for 
POST /{culture}/api/{v}/admin/location-markups
PUT /{culture}/api/{v}/admin/location-markups/{policyId}
DELETE /{culture}/api/{v}/admin/location-markups/{policyId}
- in case markup is connected with an agency then only it account manager receives notifications about agency markups
- in case markup is not connected with an agency then all account managers receives notifications about markups changes

**OK on DEV.**

**Comment by DenisVelinen** [comment]
A one template was made, which is generated by itself, depending on which Markup event occurred.
Template ID: d-1fffdcff817f4ec395b244d600ab832e
