### ISSUE TITLE
Sending email for bookings via NotificationCenter

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#128]
Need to switch sending email for booking stages (sending voucher, sending invoice and other) to NotificationCenter

**Comment by DenisSychev** [comment]
A notification centre is available at https://dev.happytravel.com/, at https://edo-dev.happytravel.com/signalr/notifications/agents.
There you will find notifications of booking status changes and sending emails.
No notifications on some emails - this going to described in another task.
