### ISSUE TITLE
Rewrite the documentation of markups

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1283]
https://github.com/happy-travel/edo/wiki/Agencies-%5C-Markup-Policies
https://github.com/happy-travel/edo/wiki/Agencies-%5C-Markups
Don't forget to rewrite the documentation of markups when we add the Global destination markups

**Comment by DaniyarAskarov** [comment]
## What markups are?

_Markup_ is a difference between supplier’s and displayed prices.
See more details on the original [Markups](https://github.com/happy-travel/edo/wiki/Agencies-%5C-Markups) page.


## How do they work?

### What a single markup does?

Any markup is usually meant to rise the displayed price, but also can decrease it, acting like a discount.
> ❗ The total sum of markups can't be less than zero. If it happened, the total sum automatically would set to zero.

> ℹ️ Markup can contain two kind of value (percent, fix). But to date, only percent markups are available for applying to price.

Markup can apply by two important criteria, which variants decribe different markups:
1. Subject scope (Depends on agency, which is client) - Global, Market, Country, Locality, Agency, Agent
2. Destination scope (Depends on hotel, which being booked)- Global, Market, Country, Locality, Accommodation

### How they combine?
 
There will always be sum different markup policies at a time, so they are combined together. Order doesn't matters. Only those markups which correspond to condition will apply to the total sum. Conditions are described by information about agency (client) and hotel (destination). 

### Here is an example

Lets say, the original price is 100 USD.
Also there are following markup policies:

|Policy #|Value |Type     |SubjectScopeType |SubjectScopeId|DestinationScopeType|DestinationScopeId|Description                                 |
|--------|------|---------|-----------------|--------------|--------------------|------------------|--------------------------------------------|
|1       |4     |Percent  |Global           |              |Global              |                  |For each bookings                           |
|2       |-2    |Percent  |Global           |              |Market              |2                 |For supplies from market (2)                |
|3       |1     |Percent  |Agency           |1             |Market              |2                 |For supplies from market (2) only agency (1)| 
|4       |4     |Percent  |Agency           |2             |Market              |3                 |For supplies from market (3) only agency (2)|
|5       |-3    |Percent  |Market           |3             |Global              |                  |For all agencies from market (2)            |

According to given parameters, Let's imagine:
Agency with Id = 1, searching or booking accommodation in country which from Market with Id = 2. There are markups which applies to this situation: #1, #2, #3. If current agency's location was from Market = 3, Markup with Id = 5 would apply too. But in our case agency isn't from Market with Id = 3.

After all operations(4% + (-2%) + 1% = 3% extra), final price is rounded to greater whole number. Final price is $103.

**Comment by DaniyarAskarov** [comment]
@AlexeyShok, @kirillta

**Comment by AlexeyShok** [comment]
Everything is ok except: final price is rounded to greater whole number. This is not true/

**Comment by AlexeyShok** [comment]
All ok

**Comment by kirillta** [comment]
LGTM

**Comment by DaniyarAskarov** [comment]
Done
