### ISSUE TITLE
Add global destination markups

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1290]
It is necessary to add Destination Markups to the global markups (percentage only). These markups are set according to the market where the booked hotel is located. There can be only one markup of this type per region. When calculating the final price, this markup is added to the total global markup and location agent global markup. This markup can be negative, but the sum of it and the total global markup and destination global markup must not be less than 0. The range of values is from 0.1 to 100 percent.

**Comment by DaniyarAskarov** [comment]
Insomnia: Edo -> Admin -> Markups -> Location Markups - There crud methods to add Destination location markups

Destination market markup defines by marketId if it equal to destinationScopeId. MarketId was determined by CountryCode which takes from mapper.

Test flow:
1. Add destination market markup
2. Start availablity search with htId in added market area
3. Chech if markup was applied

**Comment by DaniyarAskarov** [comment]
For location markups:
 {
  "description": "Test",
  "functionType": 1,
  "value": 2,
  "currency": "USD",
  "locationScopeId": "3", - MarkretId, CountryHtId, LocalityHtId
  "locationScopeType": 7 - Options: Market(7), Country(2), Locality(3)
}

For destination location markups:
 {
  "description": "Test",
  "functionType": 1,
  "value": 2,
  "currency": "USD",
  "destinationScopeId": "3", - MarkretId, CountryHtId, LocalityHtId
  "destinationScopeType": 5 - Options: Market(5), Country(2), Locality(3)
}

For editing both of them:
{
  "description": "Test2",
  "functionType": 1,
  "value": 2,
  "currency": "USD"
}

**Comment by sergeyf-QA** [comment]
@DaniyarAskarov 
POST /{culture}/api/{v}/admin/location-markups
{
  "description": "serg test",
  "functionType": 1,
  "value": -20,
  "currency": "USD",
  "destinationScopeId": "4",
  "destinationScopeType": 5
}
returns 
{
  "status": 400,
  "detail": "Destination markup policy with DestinationScopeId 3 already exists!"
}

It is allowed to create markup only in case  "destinationScopeId": "0"

**Comment by sergeyf-QA** [comment]
Also
the rule 'The range of values is from 0.1 to 100 percent.' does not work for PUT and check POST too please

**Comment by sergeyf-QA** [comment]
**Summary:**
1) CRUD operations work fine for destination location markups at
POST /{culture}/api/{v}/admin/location-markups
GET /{culture}/api/{v}/admin/location-markups
PUT /{culture}/api/{v}/admin/location-markups/{policyId}
DELETE /{culture}/api/{v}/admin/location-markups/{policyId}

2) it is possible to add values of markups only in range of -100..-0.1 & 0.1..100

3) it is not possible to add destination markup for marketId in case there is already existed markup with the same "destinationScopeId"

4) destination markup is applied well

**OK on DEV.**
