### ISSUE TITLE
Add global Destination markups to Admin Panel

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1293]
It is necessary to add the ability to add, modify and delete global Destionation markups in the Admin Panel

Result: an admin can set up a mark up for all agencies by the Destination (by the market)
E.g. if an agent from CIS market searches hotels we will add a mark up +x%

**Comment by sergeyf-QA** [comment]
**Summary:**
- global destination markup CRUD works well
- global destination markup applies well

**OK on DEV.**
