### ISSUE TITLE
Add endpoints to getting and update Availability Restrictions for TravelClick channel

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1295]
Need to add endpoints to getting and update Availability Restrictions for TravelClick channel

**Comment by AlexeyShok** [comment]
I checked. The error could not be repeated. Possibly incorrect request header settings?

**Comment by sergeyf-QA** [comment]
**Summary:**
POST {{ _.komoro.baseUrl }}/api/1.0/travel-click/availability-restrictions
POST {{ _.komoro.baseUrl }}/api/1.0/travel-click/availability-restrictions/update
work fine w/o errors

**OK on DEV.**
