### ISSUE TITLE
Migrate all connector updater settings to Consul

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1297]
Need to migrate connector updater settings (logging and worker settings) to Consul. Need to add new key in Consul: connector_name-updater. For example for "hotelbook-pro-connector" its named "hotelbook-pro-connector-updater". Settings example:

```
hotelbook-pro-connector-updater
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "Workers": {
    "WorkersToRun": "LocationUpdater",
      "LocationUpdateOptions": {
    	 "UpdateMode": "IncrementalAvailableOnly"
      }
  }
}

```
- [x] #1300
- [x] #1303
- [x] #1302
- [x] #1301
- [x] #1298
- [x] #1299 
- [x] #1304
- [x] #1305
- [x] #1306
- [x] #1308
- [x] #1309

**Comment by sergeyf-QA** [comment]
**Summary:**
- all pointed updaters settings were migrated to Consul

**OK on DEV.**
