### ISSUE TITLE
Direct Connectivity Reports

### ISSUE THREAD

**Issue by kirillta** [happy-travel/agent-app-project#13]
We need two monthly reports on direct connectivity accommodations

First one:
> For the hotel/vendor –wise report , we would require the following information as of now. Please check & let me know if you can extract all these details. This will be required for all the bookings done through our booking system, even when Columbus is integrated for FIT contracts. The report should be in excel* format, so that we will be able to filter based on required information like hotels, check in /out date, guest name etc.

Happytravel.com Booking Reference number | Happytravel.com Proforma Invoice No. | Hotel Name | Hotel Confirmation No. | Room Type | Guest Name | Arrival Date | Departure Date | Length of stay | Amount Excl. of VAT (in AED) | VAT Amount (in AED) | Total Amount (in AED)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Second one:
> Also we would require a monthly report from this month for the sales to the agents, based on the check-out date so at the end of the month we have the summary of the bookings for which we need to do tax invoice in our accounting system. Information required as below. Currently we have to update manually in an excel to keep track of the HT system bookings, as we do not have access to the back office.

Booking Date | Booking Reference number | Proforma Invoice No. | Agent Name | Agent Category (Cash/Credit) | Guest Name | Hotel Name | Room Type | Arrival Date | Departure Date | Length of Stay | Amount (USD) | Hotel Confirmation No. | Payment Status (Paid/Not Paid/Credit)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

> Attached the excel format for both the reports. Once we have the report & we start working on them  we can check if some additional info may be required.

_*According to Excel format, I supposed .csv is OK_

**Comment by mingazhev** [comment]
[Report format.xlsx](https://github.com/happy-travel/agent-app-project/files/6042087/Report.format.xlsx)

**Comment by DFSko** [comment]
Done
