### ISSUE TITLE
Return default payment type in agent info endpoint

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#130]
Need to return default payment type based on Counterparty contract kind.
More info about counterparty default payment types can be found there:

https://github.com/happy-travel/edo/wiki/Counterparties-%5C-Counterparty-Kinds-and-Their-Contracts

This is needed for frontend to show a price for default payment method in 1-st and 2-nd step availabilty search (when the actual payment method is unknown)

**Comment by sergeyf-QA** [comment]
**Summary:**
"defaultPaymentType" is returned in
GET /{culture}/api/{v}/admin/counterparties/{counterpartyId}/agencies
GET /{culture}​/api​/{v}​/agency
GET /{culture}/api/{v}/admin/agencies/{agencyId}/child-agencies

**OK on DEV.**

**Comment by sergeyf-QA** [comment]
**Summary:**
in table "AgentAgencyRelations" in column Type relationships are set as
        Regular = 0,
        Master = 1
e.g. 78 agent of 801 agency has type 1, 217 agent of 801 agency has type 0

**OK on DEV.**
