### ISSUE TITLE
Execute typical search requests and collect the results

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#131]
On Production server need to execute a list of typical wide availability search scenarios and collect the results in a persistent storage, like a file, database, etc.
Search scenarios:
1. Whole country (UAE, Italy)
2. Large city (Dubai, Rome, Moscow)
3. Small city (3-4 cities)
4. Hotel (need 3-4 hotels that return available results).

These results will be used in further database benchmarks to select a proper search results database.
For help with getting the data (probably, directly from the Redis) please contact @evm-andrey 

Results can be stored as JSON files separated by scenarios.

**Important:**
New search flow must be used ("Experimental features" in agent settings is enabled).

**Comment by DFSko** [comment]
Done
