### ISSUE TITLE
Add endpoints to add, modify and remove markets

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1323]
Need to add endpoints to add, modify and remove markets:
POST
PUT
DELETE

**Comment by DaniyarAskarov** [comment]
Admin endpoints for managing markets were added.
Insomnia: Edo -> Admin -> Locations.

**Comment by sergeyf-QA** [comment]
**Summary:**
- 
GET {{ edo.baseUrl }}/:culture/api/1.0/admin/locations/markets
POST {{ edo.baseUrl }}/:culture/api/1.0/admin/locations/markets
PUT {{ edo.baseUrl }}/:culture/api/1.0/admin/locations/markets/:marketId
DELETE {{ edo.baseUrl }}/:culture/api/1.0/admin/locations/markets/:marketId
work well

**OK on DEV.**

**Comment by DaniyarAskarov** [comment]
Insomnia: Edo -> Admin -> Locations
Tested through: unit tests, insomnia
