### ISSUE TITLE
Weird 'Sark' country in Nationality and Residency fields

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1328]
**How to reproduce:**
- on https://dev.happytravel.com/ try to find 'Sark' country

**Actual result:**
- Weird 'Sark' country is in Nationality and Residency fields
![Screenshot at Mar 31 16-31-26](https://user-images.githubusercontent.com/74529212/161066829-f01aff66-29ea-4a49-adb8-94832f03eac1.png)

**Expected result:**
- remove 'Sark' country

**Comment by ViTsvetkova** [comment]
minor
