### ISSUE TITLE
Add bank commission and total price to booking model

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1334]
The booking model has a TotalPrice property that stores the total amount of the booking. Two more fields need to be added: Price and BankCommission. Add the current commission value to Consul BankCommissionPercentage = 2.

**Comment by DFSko** [comment]
https://github.com/happy-travel/edo/pull/604

**Comment by DaniyarAskarov** [comment]
Description: Add bank commission and total price with commission for each searches steps and booking registration when agency's ContractKind = 2(CreditCardPayments)
PR: https://github.com/happy-travel/edo/pull/1722
Insomnia: Edo -> Agent -> Availabilities -> Start availability search
Tested through unit tests
Test case:
Start two similar availability searches by two different agencies. First agency must have ContractKind = 2(CreditCardPayments), the second agency must have ContractKind = 1(OfflineOrCreditCardPayments) or 3(VirtualAccountOrCreditCardPayments). Then you need to check if commission was applied to final prices for the first agency where ContractKind = 2(CreditCardPayments).

**Comment by sergeyf-QA** [comment]
**Summary:**
- comission +2% works only for CreditCardPayments agencies

**OK on DEV.**
