### ISSUE TITLE
Add CountryCode to MapperContracts and receive it from mapper

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1340]
Need to add CountryCode to model HappyTravel.MapperContracts.Internal.Mappings.Internals.Location in MapperContracts. Too need to add receive CountryCode from Nakijin

**Comment by DaniyarAskarov** [comment]
Test case: 
Need to test {mapperBaseUrl}/api/{v:apiVersion}/location-mappings endpoint with different htIds(accommodation, country, locality, localityZone). Expectation: all of them need to return countryCode

**Comment by sergeyf-QA** [comment]
**Summary:**
- {mapperBaseUrl}/api/{v:apiVersion}/location-mappings endpoint returns countryCode in response for different htIds(accommodation, country, locality).

**OK on DEV.**
