### ISSUE TITLE
Add a dashboard Top suppliers by search

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1349]
For analytics.happytravel.com and dev-analytics need to add some dashboard with the information about top suppliers by search

**Comment by DFSko** [comment]
We doesn't have information about supplier in search steps, only in bookings

**Comment by sergeyf-QA** [comment]
**Summary:**
- TOP All Suppliers by Booking table is added to the  General Search and Booking Stats dashboard

**OK on DEV.**
