### ISSUE TITLE
No agencyAccountId parameter in response object at /admin/counterparties/{counterpartyId}/agencies

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#135]
On https://manage-dev.happytravel.com
In Chrome, Firefox, Safari.

**Steps.**
1. Log in and go to Counterparties list (click on Counterparties button);
2. Open the developer panel in the browser;
3. Go to some counterparty information page;
4. Find /agencies request in the browser's developer panel and see the response.

**Result.**
No agencyAccountId parameter in response object at /admin/counterparties/{counterpartyId}/agencies

**Expectations.**
All agency-related requsts use agencyAccountId, so nothing will work if it's not there.
For example,
```
{
  "status": 400,
  "detail": "No value found for DisplayedPaymentOptions settings"
}
```
```
{
  "status": 400,
  "detail": "Could not find availability search settings for agency with id 838"
}
```

**Comment by AlexeyShok** [comment]
Added two new endpoints:
GET api/{v:apiVersion}/admin/{agencyId}/agency-accounts Gets agency accounts list
PUT api/{v:apiVersion}/admin/{agencyId}/agency-accounts/{agencyAccountId} Changes an agency account activity state

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
could you please use these added endpoints on front-end side when we arrive to counterparty page?
Thanks.

**Comment by sergeyf-QA** [comment]
**Summary:**
GET api/{v:apiVersion}/admin/{agencyId}/agency-accounts
PUT api/{v:apiVersion}/admin/{agencyId}/agency-accounts/{agencyAccountId}
work well

**OK on DEV.**
