### ISSUE TITLE
Add ability to change supplier priority to the admin panel

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1355]
You need to add a tab with supplier priority settings. Suggested format - table, columns - setting type, rows - supplier. Other design is possible.

GET en/api/1.0/admin/suppliers/priority
PUT en/api/1.0/admin/suppliers/priority

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
- change Name priority order
- save
- change Photos priority order
- save
- check Name priority order again 

Actual results:
- Name priority order is not saved

**Comment by sergeyf-QA** [comment]
**Summary:**
- now it is possible to change order of supplier settings at Name, Accommodation Amenities, Additional Info, Category, Contact Info, Location Info, Photos, Rating, Room Amenities, Schedule, Property Type, Textual Descriptions, Type Description

**OK on DEV.**
