### ISSUE TITLE
Add endpoints to getting and update Rates for TravelClick channel

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1357]

**Comment by sergeyf-QA** [comment]
@AlexeyShok 
POST {{ _.komoro.baseUrl }}/api/1.0/travel-click/rates
POST {{ _.komoro.baseUrl }}/api/1.0/travel-click/rates/update
return 500 error

{
	"type": "https://tools.ietf.org/html/rfc7231#section-6.6.1",
	"title": "Internal Server Error",
	"status": 500,
	"detail": "'<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.",
	"instance": "/api/1.0/travel-click/availability-restrictions/update",
	"spanId": "6db1ba0fccc282c1",
	"traceId": "23529527e986892c6ed0328389182426",
	"requestId": "0HMIO1QCTJRQU:00000002"
}
