### ISSUE TITLE
Remove the list of bookings from the counterparty page.

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#136]
On https://manage-dev.happytravel.com
In Chrome, Firefox, Safari.

**Steps.**
1. Log in and go to Counterparties list (click on Counterparties button);
2. Go to The Clouds company counterparty information page;
3. Scroll down the page and note the Bookings section.

**Result.**
A list of bookings has on the counterparty page.

**Expectations.**
Since the bookings are agency related, it is correct to show the list of bookings only on the agency page. Bookings should belong to the agency on whose page they appear.

**Comment by sergeyf-QA** [comment]
**Summary:**
now there is no bookings list on counterparty page

**OK on DEV.**
