### ISSUE TITLE
Add deadline shift setting for agent

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1366]
Need to add deadline shift setting for agent. You need to add the deadline shift setting for the agent, similar to the one for the agency. The resulting deadline offset is: global preferred payment method deadline shift + agency deadline shift + agent deadline shift. The resulting shift cannot be less than zero, if it is less than return zero and write an error message to the log. The deadline shift for an agent can be less than zero.
- [x] #1367
- [x] #1368

**Comment by DenisVelinen** [comment]
The ability to set a deadline shift has been added for the agency and for the agent.
There is a suspicion that the shift doesn't work for the agent - this will be fixed with in another task.
