### ISSUE TITLE
Markup implementation. Stage 2

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1370]
Here are the tasks for the second stage of the implementation of markups. Only percentage markups are to be realized, fixed amount markups will be made in the third step. Also, we do not yet make the logic of multiplying the total markups of different levels, since global markups and markups for root agencies are at the same level (according to the ideas of the office staff).

- [x] #1373
- [x] #1374
- [x] #1375
- [x] #1376
- [x] #1378
- [x] #1379
- [x] #1380
- [x] #1381
- [x] #1377

**Comment by sergeyf-QA** [comment]
done
