### ISSUE TITLE
Enhancement of an API agent registration by a button

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1371]
https://github.com/happy-travel/agent-app-project/issues/1280
Please add:
* Allow to hide or show a password of an API agent
*  Increase size of copy buttons (password and login name)

**Comment by sergeyf-QA** [comment]
**Summary:**
- password is hidden by default
- an agent may click on 'Show' button to look at the password
- Copy Password to Clipboard copies password
- Copy Name to Clipboard copies Name

**OK on DEV.**
