### ISSUE TITLE
Add an email notification about creation of API ConnectionCredentials

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1372]
https://github.com/happy-travel/agent-app-project/issues/1280
Have to send an email notification to a System Administrator (admin role) that Agency XXX ID YYY have created of API connection credentials.
This notification is not mandatory.

**Comment by DenisVelinen** [comment]
The email template ID: d-e5fea914c416484db417a5336f45a743

**Comment by sergeyf-QA** [comment]
**Summary:**
- an email notification about creation of API ConnectionCredentials is taken by an admin with System Administrator role only

**OK on DEV.**
