### ISSUE TITLE
Markup by the country where the agency is located

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1373]
It is necessary to add markup by the country where the agency is located (percentage only). These markups are set according to the country where the agency is located. There can be only one markup of this type per country. When calculating the final price, this markup is added to the other exists markups. This markup can be negative, but the sum of it and the the other exists markups must not be less than 0. The range of values is from 0.1 to 100 percent.

**Comment by DaniyarAskarov** [comment]
PR: https://github.com/happy-travel/edo/pull/1672
Insomnia: Edo -> Admin -> Markups -> Location Markups
Tested through unit tests and insomnia

Test case:
1) Add country location markup through POST endpoint ../admin/location-markups and check validators
2) Start availability search by agency from country which markup was added before
3) Check if markup was applied

**Comment by DaniyarAskarov** [comment]
Adding country location markup:
  POST ../admin/location-markups
  JSON example:
  {
  "description": "test",
  "functionType": 1,
  "value": 20,
  "currency": "USD",
  "locationScopeId": "RU",
  "locationScopeType": 2
  }

**Comment by sergeyf-QA** [comment]
**Summary:**
- CRUD for markups by the country where the agency is located work well
- markup applies well with prices


**OK on DEV.**
