### ISSUE TITLE
Markup by country of location of the hotel for a specific supplier

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1376]
It is necessary to add markup applied according to the country where the hotel is located for a specific supplier (percentage only). There can be only one markup of this type per country and supplier combination. When calculating the final price, this markup is not added to the sum of the previous markups. This is the second level markup and it applies to the amount including all previous markups.. This markup can not be negative. The range of values is from 0.1 to 100 percent.

**Comment by DaniyarAskarov** [comment]
PR: https://github.com/happy-travel/edo/pull/1678
Insomnia: Edo -> Admin -> Markups -> Supplier Markups
Tested through unit tests

Test case:

Add supplier destination country markup through POST endpoint ../admin/supplier-markups and check validators
Start availability search for hotel from country for specific supplier which markup was added before
Check if markup was applied (NOTE: second level markups applies to calculated price with result of first level
)
JSON example:
{
"description": "test",
"value": 5,
"destinationScopeId": "RU",
"destinationScopeType": 2,
"supplierCode": "jumeirah"
}

**Comment by nikolaeva31** [comment]
#1443
