### ISSUE TITLE
Implement discounts to be applicable to certain agents

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#138]
Discounts are the things like markups, but are applied to certain global markups to lower our bonus.

**Comment by sergeyf-QA** [comment]
@mingazhev 
1) GET /{culture}/api/{v}/admin/agencies/{agencyId}/discounts
does not result for exact agency, it always returns Discounts with 3,4,5 ID
2) POST /{culture}/api/{v}/admin/agencies/{agencyId}/discounts/{discountId}/activate
does not activate chosen discounts
3) PUT /{culture}/api/{v}/admin/agencies/{agencyId}/discounts/{discountId} does not update discounts in 'Discounts' table
4) POST /{culture}/api/{v}/admin/agencies/{agencyId}/discounts/{discountId}/deactivate does not deactivate discounts in 'Discounts' table

**Comment by mingazhev** [comment]
All the discount logic do work on production but there are some problems that Sergey mentioned, @Raibo could you please check?

**Comment by sergeyf-QA** [comment]
**Summary:**
- GET /{culture}/api/{v}/admin/agencies/{agencyId}/discounts
- POST /{culture}/api/{v}/admin/agencies/{agencyId}/discounts/{discountId}/activate
- PUT /{culture}/api/{v}/admin/agencies/{agencyId}/discounts/{discountId} 
- POST /{culture}/api/{v}/admin/agencies/{agencyId}/discounts/{discountId}/deactivate 
- POST /{culture}/api/{v}/admin/agencies/{agencyId}/discounts
work as prescribed.

**OK on DEV.**
