### ISSUE TITLE
Add markup according to the country where the hotel is located for a specific root agency to Admin Panel

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1380]
It is necessary to add the ability to add, modify and delete markups by the country where the hotel is located for the specific root agency in the Admin Panel

**Comment by sergeyf-QA** [comment]
**Summary:**
- CRUD operations for markups by the country where the hotel is located for the specific root agency are applied
- markups work well

**OK on DEV.**
