### ISSUE TITLE
All agencies with credit line can book within deadline

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1383]
As soon an agency gets a credit line from the office, we should allow them to book within deadline and non refundable offers

Need to add migration: set AprMode = 3, PassedDeadlineOffersMode = 3 for all agencies with ContractKind = 3,
set AprMode = 0, PassedDeadlineOffersMode = 0 for all agrencies with ContractKind = 1 or 2.

**Comment by timur-mut** [comment]
performed on prod.
query for test
```
select a."Id", a."ContractKind", ass."AccommodationBookingSettings" from "Agencies" a
full outer join "AgencySystemSettings" ass on a."Id" = ass."AgencyId"
```

**Comment by sergeyf-QA** [comment]
**Summary:**
- agencies with "ContractKind"=3 have AprMode = 3, PassedDeadlineOffersMode = 3
- agencies with "ContractKind"=1 or 2 have AprMode = 0, PassedDeadlineOffersMode = 0
- agencies which may pay by Virtual account can do that in deadline


**OK on DEV.**
