### ISSUE TITLE
Change SupplierId to SupplierCode in komoro

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1386]
Need to change SupplierId to SupplierCode

**Comment by sergeyf-QA** [comment]
**Summary:**
- "SupplierId" was changed to "SupplierCode" in :
"Properties" table
GET {{ _.komoro.baseUrl }}/api/1.0/properties/suppliers/:supplierCode
GET {{ _.komoro.baseUrl }}/api/1.0/properties
GET{{ _.komoro.baseUrl }}/api/1.0/properties/:propertyId
PUT {{ _.komoro.baseUrl }}/api/1.0/properties/:propertyId
- all pointed endpoints work fine

**OK on DEV.**
