### ISSUE TITLE
Add materialized search and booking settings for agencies

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1390]

**Comment by konstyefremov** [comment]
Change this endpoint:

GET {agencyId}/system-settings/availability-search

It needs to return "materialized settings". 

The logic of "materialization" will differ depending on the entity type.

1. If the agency or root agency DOES NOT HAVE settings, then the following defaults should be used:

```
IsSupplierVisible: false,
IsDirectContractVisible: false,
CustomDeadlineShift: 0,
If an agency has contractKind = 3, then AprMode should be 3 and PassedDeadlineOffersMode should be 3
If an agency has contractKind = 1, then AprMode should be 0 and PassedDeadlineOffersMode should be 0.
```

2. If the root agency HAS settings, then agency's settings should follow these rules:

- If the root agency has "IsSupplierVisible": false, then the agency or agent should also be false. 
- If the root agency has "IsSupplerVisible": true, then the agency's or agent's setting might be true or false.
- Agency or Agent cannot have AprMode higher then the one in RootAgencys. i.e. if rootAgency has aprMode = 2, then agency or agent aprMode might be 0, 1, 2, and NOT 3. 
- the latter applies to PassedDeadlineOffersMode too.

**Comment by sergeyf-QA** [comment]
**Summary:**
- GET {{ edo.baseUrl }}/en/api/1.0/admin/agencies/:agencyId/system-settings/availability-search returns data according the rules described above

**OK on DEV.**
