### ISSUE TITLE
Add materialized search and booking settings for agents

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1391]

**Comment by konstyefremov** [comment]
Change this endpoint

GET agencies/{agencyId}/agents/{agentId}/system-settings/availability-search

The logic should follow these rules https://github.com/happy-travel/agent-app-project/issues/1390#issuecomment-1137383994

**Comment by sergeyf-QA** [comment]
**Summary:**
- GET /{culture}/api/{v}/admin/agencies/{agencyId}/agents/{agentId}/system-settings/availability-search for default settings returns 
{
  "aprMode": "Hide",
  "passedDeadlineOffersMode": "Hide",
  "isSupplierVisible": false,
  "isDirectContractFlagVisible": false,
  "additionalSearchFilters": 0,
  "customDeadlineShift": 0
}
- in case agency settings are different from agent ones the endpoint returns agency settings (except "customDeadlineShift")

**OK on DEV.**

**Comment by nikolaeva31** [comment]
#1680
