### ISSUE TITLE
Add to the admin panel the ability to change settings for an agency

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1392]
The name of a subtub is Search and Booking

GET {{ edo.baseUrl }}/en/api/1.0/admin/agencies/:agencyId/system-settings/availability-search
PUT {{ edo.baseUrl }}/en/api/1.0/admin/agencies/:agencyId/system-settings/availability-search

The logic of "materialization" will differ depending on the entity type.

If the agency or root agency DOES NOT HAVE settings, then the following defaults are used:
IsSupplierVisible: false,
IsDirectContractVisible: false, (will see a direct connecivity image

![Image](https://user-images.githubusercontent.com/90184684/171826081-63625ff0-464e-4b51-90c7-33e12b3e684f.png)

)
CustomDeadlineShift: 0,
If an agency has ContractKind = VirtualAccountOrCreditCardPayments, then AprMode should be CardAndAccountPurchases and PassedDeadlineOffersMode should be CardAndAccountPurchases.
If an agency has contractKind = OfflineOrCreditCardPayments, then AprMode should be Hide and PassedDeadlineOffersMode should be Hide.
If the root agency HAS settings, then agency's settings should follow these rules:
If the root agency has "IsSupplierVisible": false, then the agency should also be false.
If the root agency has "IsSupplerVisible": true, then the agency's setting might be true or false.
Agency cannot have AprMode higher then the one in Root Agency. i.e. if rootAgency has AprMode = CreditCardPayments, then agency AprMode might be Hide, DisplayOnly, CardPurchasesOnly, and NOT CardAndAccountPurchases.
The latter applies to PassedDeadlineOffersMode too.

**Comment by alexander-plekhanov** [comment]
In this task we should create a form inside an Agency / Settings tab.

Form that contains: 
1. Switch = Supplier Visible 
2. Switch = Direct Contract Mark Visible
3. Range Selector = Custom Deadline Shift (from -2 (may be changed later) to 3 (may be changed later, contact Backends)
4. Button group of 4 steps = APR Mode  (
    NotDisplay: 1,
    DisplayOnly: 2,
    CardPurchasesOnly: 3,
    CardAndAccountPurchases: 4
)
