### ISSUE TITLE
Add to the admin panel the ability to change settings for an agent

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1393]
The name of a subtub is Search and Booking

GET {{ edo.baseUrl }}/en/api/1.0/admin/agencies/{agencyId}/agents/{agentId}/system-settings/availability-search
PUT {{ edo.baseUrl }}/en/api/1.0/admin/agencies/{agencyId}/agents/{agentId}/system-settings/availability-search

The logic of "materialization" will differ depending on the entity type.

If the agent DOES NOT HAVE settings, then the following defaults are used:
IsSupplierVisible: false,
IsDirectContractVisible: false,
CustomDeadlineShift: 0,
If an agent has ContractKind = VirtualAccountOrCreditCardPayments, then AprMode should be CardAndAccountPurchases and PassedDeadlineOffersMode should be CardAndAccountPurchases.
If an agent has ContractKind = OfflineOrCreditCardPayments, then AprMode should be Hide and PassedDeadlineOffersMode should be Hide.
If the root agency or child agency HAS settings, then agent settings should follow these rules:
If the agency has "IsSupplierVisible": false, then the agent should also be false.
If the agency has "IsSupplerVisible": true, then the agent's setting might be true or false.
Agent cannot have AprMode higher then the one in root or child agency. i.e. if root or child agency has AprMode = CreditCardPayments, then agent AprMode might be Hide, DisplayOnly, CardPurchasesOnly, and NOT CardAndAccountPurchases.
The latter applies to PassedDeadlineOffersMode too.

**Comment by DenisVelinen** [comment]
A Settings tab has been added to the agent page where you can make settings for what the agent will see in the agent application.
