### ISSUE TITLE
Update documentation on agent and agency settings

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1394]

**Comment by konstyefremov** [comment]
Done https://github.com/happy-travel/docs/wiki/Materialization-of-booking-settings

**Comment by suhan3z** [comment]
I have a couple of suggestions for documentation:
1. Describe what each setting does or provide a link if they are already described
2. Give more examples on IsSupplierVisible and IsDirectContractFlagVisible, AprMode and PassedDeadlineOffersMode. Maybe draw tables of how it was as it will be at different settings

**Comment by ViTsvetkova** [comment]
@konstyefremov have you added the suggestions above?

**Comment by konstyefremov** [comment]
The documentation was reworked. Each settings was additionally explained and more examples were added.

**Comment by konstyefremov** [comment]
The link was updated to https://github.com/happy-travel/docs/wiki/booking-settings
