### ISSUE TITLE
Add permision ApiConnectionManagement to Agency Administrator role

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1395]
Need to add permision ApiConnectionManagement to Agency Administrator role

**Comment by timur-mut** [comment]
https://github.com/happy-travel/edo/pull/1780

**Comment by sergeyf-QA** [comment]
**Summary:**
- ApiConnectionManagement permission is added to the Agency Administrator role

**OK on DEV.**
