### ISSUE TITLE
Need to add a notification to an admin in case of booking status is rejected

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1401]
Booking manager have to receive a notification about rejected status of a booking (by email)

**Comment by DaniyarAskarov** [comment]
Related issue with solution: https://github.com/happy-travel/agent-app-project/issues/1398

**Comment by sergeyf-QA** [comment]
**Summary:**
- an agency admin receives notification in case booking becomes Rejected

**OK on DEV.**
