### ISSUE TITLE
Change the rules for payment methods for bookings by agencies

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1403]
Need to change the rules for payment methods for bookings by agencies.

After completing all the tasks, we should get the following:
1) Enum ContractKinds:
NotSpecified = 0 (technical status)
OfflineOrCreditCardPayments = 1 (the agency can pay offline or by card)
CreditCardPayments = 2 (agency can pay by card)
VirtualAccountOrCreditCardPayments = 3 (the agency can pay with an account or a card)

2) Enum PaymentTypes:
NotSpecified = 0
Offline = 1 (the agency wants to pay offline)
CreditCard = 2 (the agency wants to pay by card)
VirtualAccount = 3 (the agency wants to pay with an account)

3) Validation on the backend when changing agency settings. If agency СontractType is OfflineOrCreditCardPayments AprMode must be 0.

4) Validation on the backend when agency verification. When setting the agency contract type to VirtualAccountOrCreditCardPayments, the agency must be set to AprMode = 3 and PassedDeadlineOffersMode = 3

- [x] #1404
- [x] #1405
- [x] #1406
- [x] #1427
- [x] #1421
- [x] #1422

**Comment by sergeyf-QA** [comment]
**Summary:**
- all described tasks are completed

**OK on DEV.**
