### ISSUE TITLE
Add validation in agency verification

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1406]
Need to add set AprMode = 3 and PassedDeadlineOffersMode = 3 in agency verification when the agency contract type is VirtualAccountOrCreditCard.

**Comment by konstyefremov** [comment]
Correction:

Method to change AgencyVerificationService.VerifyAsFullyAccessed()

What needs to be done:

If ContractKind is VirtualAccountOrCreditCard, then set AprMode to 3 and PassedDeadlineOffersMode to 3.

**Comment by sergeyf-QA** [comment]
**Summary:**
- in case an agency is verified as VirtualAccountOrCreditCard then AprMode and PassedDeadlineOffersMode are set to 3.

**OK on DEV.**
