### ISSUE TITLE
Add an intermediate supplier status to sunpu

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1407]
Need to change from boolean IsEnabled to enum EnablementState with values: Disabled, TestOnly, Enabled

**Comment by sergeyf-QA** [comment]
**Summary:**
- "EnablementState" is added to the "Suppliers" table in Sunpu
- "EnablementState" returns in GET {{ _.sunpu.baseUrl }}/api/1.0/suppliers

**OK on DEV.**
