### ISSUE TITLE
Change supplier setting by adding intermediate status

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1409]
Need to change from boolean IsEnabled to enum EnablementState with values: Disabled, TestOnly, Enabled.

Instead of the Enabled column, you need to make the Enablement state column in the table with the list of suppliers.

Added new endpoint: 
set-enablement-state

Removed endpoints:
activate
deactivate

**Comment by ViTsvetkova** [comment]
When a supplier is disabled, this supplier is disabled for each agency.
When a supplier has testOnly status, this supplier is enabled for each agency, but doesn't turn on. An admin can turn on a supplier for tests.
When a supplier is disabled, this supplier is enabled and turned on for every agency.

**Comment by sergeyf-QA** [comment]
**Summary:**
- now it is possible to set Enabled, Disabled and TestOnly states on supplier settings page
- on suppliers list page Enabled State is shown

**OK on DEV.**
