### ISSUE TITLE
Check and fix ueda after completing the 1404, 1405, 1406 tasks

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1422]
Please see the description of changes in the general task

**Comment by sergeyf-QA** [comment]
**Summary:**
- Verification as
OfflineOrCreditCardPayments = 1 (the agency can pay offline or by card)
CreditCardPayments = 2 (agency can pay by card)
VirtualAccountOrCreditCardPayments = 3 (the agency can pay with an account or a card)
works fine on front end on Verification agency page

**OK on DEV.**
