### ISSUE TITLE
Add endpoints to change company banks

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1429]
Need to add CRUD endpoints to change company banks:

GET /{culture}/api/{v}/admin/company/banks
POST  /{culture}/api/{v}/admin/company/banks
PUT /{culture}/api/{v}/admin/company/banks/{bankId}
DELETE /{culture}/api/{v}/admin/company/banks/{bankId}

Provide for a check that does not allow deleting a bank if it has at least one default account.

**Comment by timur-mut** [comment]
https://github.com/happy-travel/edo/pull/1748

**Comment by sergeyf-QA** [comment]
@timur-mut 
1) GET /{culture}/api/{v}/admin/company/banks returns all banks with id "0"
2) remove "id" from request body of POST and PUT endpoints
3) record from "CompanyAccounts" table may be removed in case I remove connected bank from the "CompanyBanks"

**Comment by sergeyf-QA** [comment]
**Summary:**
- were created "CompanyBanks" and "CompanyAccounts" tables
- CRUD operations work well
- in case a bank has at least one default account this bank can not be deleted
- in case other bank is deleted then connected record in "CompanyAccounts" table is deleted too

**OK on DEV.**
