### ISSUE TITLE
Add endpoints to change company bank accounts

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1430]
Need to add CRUD endpoints to change company bank accounts

GET /{culture}/api/{v}/admin/company/banks/{bankId}/accounts
POST  /{culture}/api/{v}/admin/company/banks/{bankId}/accounts
PUT /{culture}/api/{v}/admin/company/banks/{bankId}/accounts/{accountId}
DELETE /{culture}/api/{v}/admin/company/banks/{bankId}/accounts/{accountId}

Provide a check that does not allow deleting a default account. Endpoint to change should not change the IsDefault property. When adding a new account, the IsDefault property must be set to false.

**Comment by timur-mut** [comment]
https://github.com/happy-travel/edo/pull/1756

**Comment by sergeyf-QA** [comment]
**Summary:**
- CRUD endpoints work well
- impossible to delete default account
- PUT endpoint can not change the IsDefault property
- when adding a new account, the IsDefault property is set to false

**OK on DEV.**
