### ISSUE TITLE
Add endpoint to set default bank account for the currency

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1431]
Need to add endpoints to set default bank account for the currency

POST  /{culture}/api/{v}/admin/company/banks/{bankId}/accounts/{accountId}/set-default

There can only be one default account for each currency. When setting an account as default for all other accounts in the same currency, IsDefault must be set to false.

**Comment by timur-mut** [comment]
https://github.com/happy-travel/edo/pull/1770

**Comment by sergeyf-QA** [comment]
**Summary:**
- POST /{culture}/api/{v}/admin/company/banks/{bankId}/accounts/{accountId}/set-default sets company bank account as default
- when setting an account as default for all other accounts in the same currency, IsDefault is set to false, so, there can only be one default account for each currency

**OK on DEV.**
