### ISSUE TITLE
Add the ability to change company banks in the admin panel

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1432]
Endpoints:
GET /{culture}/api/{v}/admin/company/banks
POST /{culture}/api/{v}/admin/company/banks
PUT /{culture}/api/{v}/admin/company/banks/{bankId}
DELETE /{culture}/api/{v}/admin/company/banks/{bankId}

The permission "Company Account Management" is required

**Comment by ViTsvetkova** [comment]
@AlexeyShok could you add some task description?

**Comment by sergeyf-QA** [comment]
**Summary:**
- the permission "Company Account Management" is required to access Bank details
- it is possible to add banks, to change them and delete
- it is impossible to delete a bank if it has at least one default account



**OK on DEV.**
