### ISSUE TITLE
Add the ability to change company bank accounts and set default bank accounts in the admin panel

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1433]
Endpoints:
GET /{culture}/api/{v}/admin/company/banks/{bankId}/accounts
POST /{culture}/api/{v}/admin/company/banks/{bankId}/accounts
PUT /{culture}/api/{v}/admin/company/banks/{bankId}/accounts/{accountId}
DELETE /{culture}/api/{v}/admin/company/banks/{bankId}/accounts/{accountId}

The permission "Company Account Management" is required

**Comment by ViTsvetkova** [comment]
@AlexeyShok we need a task description here.

p.s. waiting for a design

**Comment by sergeyf-QA** [comment]
**Summary:**
- when adding a new account, the IsDefault property is set to false
- when setting an account as default for all other accounts in the same currency, IsDefault is set to false, so, there can only be one default account for each currency
- it is impossible to delete a bank if it has at least one default account
- it is impossible to set isDefault to false
- the permission "Company Account Management" is required to access Bank details

**OK on DEV.**
