### ISSUE TITLE
Add an amount receivable from the agent for each booking to the Full booking report

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1437]
Need to add the amount receivable from the agent for each booking-the amount charged from the agent to the Full booking report.

Must be cleare where is the supplier price and here is the booking agent price. Columns name should be renamed.

**Comment by timur-mut** [comment]
https://github.com/happy-travel/edo/pull/1725

**Comment by sergeyf-QA** [comment]
**Summary:**
- BookingAmount column is added to the Full booking report

**OK on DEV.**
