### ISSUE TITLE
Add recalculation of the amount of the booking depending on the payment method

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1438]
If the agent in the agent application selects a different payment method, the total amount of the booking and the commission amount must be recalculated. The currently selected payment method must be saved in the booking. You need to add an endpoint to recalculate the cost of the booking.

**Comment by DaniyarAskarov** [comment]
PR: https://github.com/happy-travel/edo/pull/1728
Insomnia: Edo -> Agent -> Bookings
Tested through unit tests and debugging

Test case:
Send request to new endpount for recalculating price with/without commission. Request returns accomodationBookingInfo with new prices. Compare with old prices.

**Comment by sergeyf-QA** [comment]
**Summary:**
- POST {{ edo.baseUrl  }}/en/api/1.0/accommodations/bookings/{referenceCode}/price/recalculate recalculates booking amount according to comission 2%

**OK on DEV.**
