### ISSUE TITLE
A Booking manager can get a voucher from the admin panel

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1440]
Booking manager can load a voucher from the booking page.
A voucher getting automatically void on cancellation.

- [x] #1475
- [x] #1474
- [x] #1546
- [x] #1670

**Comment by sergeyf-QA** [comment]
**Summary:**
- Voucher is allowed for Booking Manager
- Voucher downloads and works fine
[Voucher-DEV-HTL-AE-0006U6-01.pdf](https://github.com/happy-travel/agent-app-project/files/9307726/Voucher-DEV-HTL-AE-0006U6-01.pdf)


**OK on DEV.**
