### ISSUE TITLE
Add endpoint to change agency contract kind

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1448]
Need to add endpoint to change agency contract type. The reason for the change must be stated. The event must be saved in the audit log. If there is a change to the contract type VirtualAccountOrCreditCardPayments, AprMode = 3 and PassedDeadlineOffersMode = 3 must be set. If the contract type is changed to OfflineOrCreditCardPayments, AprMode = 0 and PassedDeadlineOffersMode = 0 must be set.
PUT api/{v:apiVersion}/admin/agencies/{agencyId}/contract-kind

**Comment by sergeyf-QA** [comment]
**Summary:**
- PUT api/{v:apiVersion}/admin/agencies/{agencyId}/contract-kind works fine
- in case "contractKind": 3 AprMode and PassedDeadlineOffersMode are set to 3
- in case "contractKind": 1 AprMode and PassedDeadlineOffersMode are set to 0
- case "contractKind": 2 will be done in another ticket in future

**OK on DEV.**
