### ISSUE TITLE
Add the ability to change the agency contract type on the Details tab of the agency page

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1449]
Need to add the ability to change the agency contract type on the Details tab of the agency page

Endpoint:
PUT {{ edo.baseUrl }}/en/api/{v:apiVersion}/admin/agencies/:agencyId/contract-kind

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
- change contractkind
- open conractkind popup again
**Result:**
- previous contractkind is shown in conractkind popup

**Comment by sergeyf-QA** [comment]
**Summary:**
- contract type may be changed in admin panel in agency settings

**OK on DEV.**
