### ISSUE TITLE
Allow to input a booking reference code by any letter case

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1452]
Need to allow to input a booking reference code by any letter case while on the [Booking by Reference Code](https://manage-dev.happytravel.com/bookings/find)

If it's possible add a placeholder

**Comment by DenisVelinen** [comment]
Booking. Reference Code can be entered in any character case and all options will work equally.
For example, HTL-AE-000WF5-01 or htl-ae-000wf5-01 or hTl-aE-000wF5-01
