### ISSUE TITLE
Add a list of users with an account manager role to the account manager filter field

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1456]
Should be possible to select an account manager from the account manager list in the ACCOUNT MANAGER NAME field

![image](https://user-images.githubusercontent.com/90184684/170231246-796e3578-eb75-44c6-9894-d1ed0a0a0898.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- account manager filter field has account manager list
- search by them works well

**OK on DEV.**
