### ISSUE TITLE
500 error at GET /root-agencies

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1462]
**How to reproduce:**
- go to https://manage-dev.happytravel.com/agencies
- into the NAME QUERY field put **_default_**
- into the COUNTRY NAME QUERY put **_Islands_**
- click on Search

**Actual result:**
- https://edo-dev.happytravel.com/en/api/1.0/admin/agencies/root-agencies?%24filter=contains(tolower(name)%2Ctolower(%27default%27))%20and%20contains(tolower(countryName)%2Ctolower(%27Islands%27))&%24orderBy=created%20desc&%24top=100&%24skip=0
returns
{"type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","title":"Internal Server Error","status":500,"detail":"Exception has been thrown by the target of an invocation.","instance":"/en/api/1.0/admin/agencies/root-agencies","spanId":"367860b7c549aa6c","traceId":"1bcd618ac84df3f6cf334451745ca837","requestId":"0HMHU9MMCVIKK:0000000E","x-request-id":["51fcc214f045dff574207b9fa48e840d"],"StackTrace":"   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span\u00601\u0026 arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\n   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.LimitResults(IQueryable queryable, Int32 limit, Boolean parameterize, Boolean\u0026 resultsLimited)\n   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplyPaging(IQueryable result, ODataQuerySettings querySettings)\n   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext)\n   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeNextActionFilterAsync\u003Eg__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeNextResourceFilter\u003Eg__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilder.\u003C\u003Ec.\u003C\u003CBuildPipeline\u003Eb__8_0\u003Ed.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at HappyTravel.Edo.Api.Infrastructure.Middlewares.AgentRequestLoggingMiddleware.InvokeAsync(HttpContext context, IAgentContextInternal agentContextService) in /src/Api/Infrastructure/Middlewares/AgentRequestLoggingMiddleware.cs:line 39\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpRequestDurationMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpRequestCountMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpInProgressMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"}

**Expected result:**
- no error
- successful search results

**Comment by DenisVelinen** [comment]
Users have already saw this error https://happytravel.freshdesk.com/a/tickets/503

**Comment by DenisVelinen** [comment]
Is it possible to use a predictions method with a certain type in the fields?

For example, in the **COUNTRY NAME QUERY** field, while filling out the field, tooltips will appear as in the agent application (preferably only with "type": "Country" https://osaka-dev.happytravel.com/api/1.0/predictions/search?text=%7B%7BcountryName%7D%7D&types=Country).

In the **CITY NAME QUERY** field, when filling out the field, prompts will appear, as in the agent application (preferably only with the values of cities "type": "Locality" https://osaka-dev.happytravel.com/api/1.0/predictions/search?text=%7B%7BcountryName%7D%7D&types=Locality)

**Comment by alexander-plekhanov** [comment]
@DenisVelinen it's possible to add htId locality selectors but we need to add htId field to model in response in api first

**Comment by konstyefremov** [comment]
@DenisVelinen I fixed the query to odata here.

**Comment by konstyefremov** [comment]
The issue was solved by @DFSko

**Comment by sergeyf-QA** [comment]
**Summary:**
- there is no 500 error while searching on https://manage-dev.happytravel.com/agency/list

**OK on DEV.**
