### ISSUE TITLE
Don't allow to book in case account balance <0

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1465]
**How to reproduce:**
- log in as an agent with agency account < 0
- try to book using Account Balance

**Actual result:**
- front-end allows to book using Account Balance in case account balance <0

**Expected result:**
- for such case could you don't call /book-by-account endpoint and show meaningful error message in popup?

**Comment by alexander-plekhanov** [comment]
In our data model in contract we have a field called 'availablePaymentMethods'. 

We don't store any payment availability logic on frontend so it's not an frontend issue.

**Comment by AlexeyShok** [comment]
Fixed in task 1566

**Comment by nikolaeva31** [comment]
#1566
