### ISSUE TITLE
Add a special permission to allow see pax names

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1467]
We must hide pax names from admins which don't have a special permission

**Comment by timur-mut** [comment]
https://github.com/happy-travel/edo/pull/1796

**Comment by sergeyf-QA** [comment]
@timur-mut 
when View Pax Names permission is enabled then pax names in bookings are still not shown

**Comment by sergeyf-QA** [comment]
**Summary:**
- when View Pax Names permission is enabled then pax names in bookings are shown
- when View Pax Names permission is disabled then pax names in bookings are not shown

**OK on DEV.**
