### ISSUE TITLE
Add a new Agency report

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1470]
New marketing report (MarketingReportGeneration)
Need to add the following data:
Id, Name, Created, IsActive, City, CountryCode, ContractKind, Balance, Agency settings, Available suppliers, Global agency markup, IsContractloaded

**Comment by sergeyf-QA** [comment]
@konstyefremov 
Created field is no added to the Agency report GET /{culture}/api/{v}/admin/reports/agencies-report

**Comment by konstyefremov** [comment]
Created field was added

**Comment by konstyefremov** [comment]
I've added the following settings to the report:

AprMode, PassedDeadlineOffersMode, IsSupplierVisible, IsDirectContractFlagVisible, CustomDeadlineShift, AvailableCurrencies

**Comment by sergeyf-QA** [comment]
@konstyefremov 
in Agency report 
CustomDeadlineShift and AvailableCurrencies return wrong data.
E.g. for 975 agency
 "customDeadlineShift": -4,
  "availableCurrencies": []
 but it shows 
 0,USD

**Comment by sergeyf-QA** [comment]
**Summary:**
- agency report returns 

`AgencyName,AgencyId,RootAgencyId,Created,Balance,City,CountryCode,ContractKind,Suppliers,GlobalMarkup,IsActive,IsContractLoaded,AprMode,PassedDeadlineOffersMode,IsSupplierVisible,IsDirectContractFlagVisible,CustomDeadlineShift,AvailableCurrencies`

data


**OK on DEV.**
