### ISSUE TITLE
Add admin endpoint to get booking voucher

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1474]
Need to add admin endpoint to get booking voucher. To receive a voucher, administrator need have a BookingManagement permission. The endpoint must return a voucher in PDF format.

**Comment by timur-mut** [comment]
https://github.com/happy-travel/edo/pull/1817

**Comment by sergeyf-QA** [comment]
@timur-mut 
1) Booking Status, Additional Services should be shown w/o {} symbols in pdf voucher
2) in Booked By: should be shown agency of agent who made a booking
3) be no Supplier Details and Guest Details titles
4) in Room Occupancy should be how much people will be in booking
5) there is no Confirmation number
6) there is no Mr. or Ms or Mrs in Guest Name field
7) Additional services does not show data, just some infojunk

Examples of expected vouchers
[Voucher2.pdf](https://github.com/happy-travel/agent-app-project/files/8843017/Voucher2.pdf)
[Voucher.docx](https://github.com/happy-travel/agent-app-project/files/8843020/Voucher.docx)


Actual voucher

[voucher-pdf-1654503247826.pdf](https://github.com/happy-travel/agent-app-project/files/8843012/voucher-pdf-1654503247826.pdf)
