### ISSUE TITLE
Add endpoint to change supplier EnablementState to edo

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1477]
Need to add endpoint to change supplier EnablementState to edo
PUT {{ _.edo.baseUrl }}/api/1.0/admin/suppliers/{supplierId}/set-enablement-state

**Comment by sergeyf-QA** [comment]
@konstyefremov 
it is possible to enter any number into the "state" field in PUT 
/{culture}/api/{v}/admin/suppliers/{code}/set-enablement-state
