### ISSUE TITLE
Remove unused EnabledSuppliers property from agency and agent settings

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1480]
Need to remove unused EnabledSuppliers property from agency and agent settings

**Comment by DaniyarAskarov** [comment]
EnabledSuppliers property in agency system settings was already deleted by @konstyefremov

**Comment by sergeyf-QA** [comment]
**Summary:**
- EnabledSuppliers property is removed from agency and agent settings and from "AgentSystemSettings" and "AgencySystemSettings" tables

**OK on DEV.**
