### ISSUE TITLE
Add a tab Settings on Agency page instead of Supliers

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1485]
We expect to see a tab Settings (general agency aettings) here instead of a Supliers tab
![image](https://user-images.githubusercontent.com/90184684/171821910-be2f9414-388c-4265-bf6b-e4767235e68a.png)

Switching of suppliers should be a sub-tub

Then can add an account manager field to set up an account manager 
The subtab is called Account Manager

AgencyManagement permission is required

**Comment by sergeyf-QA** [comment]
**Summary:**
- Settings tab now is instead of the Suppliers tab
- AgencyManagement permission is required for seeing that tab
- at the Settings tab are Account manager and Available Suppliers


**OK on DEV.**
