### ISSUE TITLE
Add ContractKind to the agency admin endpoint

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1488]
Need to add ContractKind property to the agency admin endpoint

GET {{ edo.baseUrl }}/en/api/1.0/admin/agencies/:agencyId

**Comment by sergeyf-QA** [comment]
**Summary:**
- GET {{ edo.baseUrl }}/en/api/1.0/admin/agencies/:agencyId returns "contractKind" of agencies well

**OK on DEV.**
