### ISSUE TITLE
Implement a simple fast solution since we have to solve the problem with non-saving filters

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1489]
We have to solve this task:
https://github.com/happy-travel/ueda/issues/253

Please find fast and simple solution (e.g. open a booking details/agency details on a new page)

This solutions isn't the final solution. It will a temporary fix.

**Comment by ViTsvetkova** [comment]
@alexander-plekhanov Please make a short comment-report for QA when you finish the task

**Comment by alexander-plekhanov** [comment]
Done. Now table rows open new tab with content. If something is not work, please contact.

**Comment by sergeyf-QA** [comment]
**Summary:**
- Now table rows open new tab with bookings, also back button is not shown on booking page

**OK on DEV.**
