### ISSUE TITLE
Return accommodation photo url in rich booking model (to show on frontend side)

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#149]

**Comment by sergeyf-QA** [comment]
**Summary:**
in SignalR logs and in responses of 
GET /{culture}/api/{v}/accommodations/bookings/{bookingId} , 
GET /{culture}/api/{v}/accommodations/bookings/refcode/{referenceCode}
GET /{culture}/api/{v}/admin/bookings/{referenceCode}
GET /{culture}/api/{v}/admin/agents/{agentId}/accommodations/bookings 
GET /{culture}/api/{v}/admin/counterparties/{counterpartyId}/accommodations/bookings
GET ​/{culture}​/api​/{v}​/admin​/agencies​/{agencyId}​/accommodations​/bookings
images links are presented


**OK on DEV.**
