### ISSUE TITLE
Issue when log in as an active agent from inactive agency

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1493]
**How to reproduce:**
- try to login as an active agent from inactive agency

**Actual result:**
- when log in as an active agent from inactive agency user is on Agent Information page 
![Screenshot at Jun 08 03-04-43](https://user-images.githubusercontent.com/74529212/172504921-80f665d6-4c29-46f6-a47c-1820c1340cee.png)

**Expected result:**
- user should stay on log in page
- red message should be shown about that agency is inactive

**Comment by ViTsvetkova** [comment]
https://track.happytravel.tech/issue/HP-472/Need-to-create-new-view-for-a-deactivated-agent-agency
