### ISSUE TITLE
Add a lead passenger info to the booking table

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1495]
A booking manager has to see a lead passenger name (title, first name, last name) and a number of passengers at the booking table

![Image](https://user-images.githubusercontent.com/90184684/172638840-eb9a781c-3d2a-420c-8b27-1331b559ab76.png)

**Comment by AlexeyShok** [comment]
Backend gives all the necessary information. This must be done at the front.

**Comment by alexander-plekhanov** [comment]
https://edo-dev.happytravel.com/en/api/1.0/admin/accommodations/bookings
model do not have any necessary information - neither main guest details nor guests count

**Comment by konstyefremov** [comment]
MainPassengerName was added
TotalPassengers will be added later

**Comment by sergeyf-QA** [comment]
**Summary:**
- example of how GET https://edo-dev.happytravel.com/en/api/1.0/admin/accommodations/bookings returns needed data
"mainPassengerName":"Mr. epke kep",
"totalPassengers":2

**OK on DEV.**
