### ISSUE TITLE
Need to add a pagination to each view

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1496]
Need to add a pagination to each view in the admin panel:
an Agency page
a Booking page

Then we can count how much results is got by a filtering
e.g.  how many bookings have a rejected status:

![Image](https://user-images.githubusercontent.com/90184684/172641432-62d85cbd-bb8d-4549-b3b7-f3a770d7c57b.png)

**Comment by AlexeyShok** [comment]
OData enabled for Agency and Booking. Pagination is implemented by a request from the front. Pagination for reports should be implemented at the front. It is not advisable to connect pagination for suppliers now, there are less than 50 of them.

**Comment by sergeyf-QA** [comment]
**Summary:**
on agency and booking list screens:
![image](https://user-images.githubusercontent.com/74529212/187627778-66761e75-71c1-423e-a139-6bb0b44658e8.png)


**OK on DEV.**
