### ISSUE TITLE
Add to StaticData table a list of company currencies available for payment

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1508]
Need add to table StaticData a list of company currencies (AvailableCurrencies) available for payment. Now we have accounts in GBP, USD, EUR, CNH and AED. You also need to add missing account details to the edo database on dev and prod using endpoints.

Remove from Consul company data.
Change in invoce using company name to Name from StaticData table.
Add admin endpoint PUT for change static data (company name, address and currencies list).

**Comment by DaniyarAskarov** [comment]
PR: 

Test cases:
 1) Check Voucher and Invoice generation

**Comment by nikolaeva31** [comment]
@DaniyarAskarov Make fields mandatory

**Comment by DaniyarAskarov** [comment]
Done!
