### ISSUE TITLE
PUT /{agencyId}/system-settings/availability-search does not allow to send "aprMode": "NotDisplay"

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1513]
**How to reproduce:**
- try to execute PUT /{agencyId}/system-settings/availability-search with "aprMode": "NotDisplay" , e.g. for 1200 agency

**Expected result:**
- "aprMode": "NotDisplay" should be available to send

**Actual result:**
- {"errors":{"aprMode":["Error converting value \"NotDisplay\" to type 'System.Nullable`1[HappyTravel.Edo.Common.Enums.AgencySettings.AprMode]'. Path 'aprMode', line 1, position 23."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"Bad Request","status":400,"instance":"/en/api/1.0/admin/agencies/1200/system-settings/availability-search","spanId":"8a6ac4b3e33cb153","traceId":"ed0676102df30cd229ba42a32a88d0b5","requestId":"0HMIEP0FBO8I9:00000003"}

**Comment by AlexeyShok** [comment]
There is no such value NotDisplay in the AprMode enum. It's a bug on the front.
    public enum AprMode
    {
        Hide = 0,
        DisplayOnly = 1,
        CardPurchasesOnly = 2,
        CardAndAccountPurchases = 3
    }

**Comment by sergeyf-QA** [comment]
**Summary:**
- now it is possible to send by PUT /{agencyId}/system-settings/availability-search "aprMode":  Hide

**OK on DEV.**
