### ISSUE TITLE
UI issue at the agencies Settings page

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1514]
**How to reproduce:**

- open any agency Settings page e.g. https://manage-dev.happytravel.com/agency/1200/settings on wide screen

**Expected result:**
![image](https://user-images.githubusercontent.com/74529212/174033436-c865a2bb-6f7e-4f00-82b3-91222a989027.png)

**Actual result:**
![image](https://user-images.githubusercontent.com/74529212/174033397-3f3a7cee-bc50-4832-b1eb-cd533f7f2b62.png)

**Comment by DenisVelinen** [comment]
On dev. environment https://manage-dev.happytravel.com/ elements are placed on different lines when the browser window is wide.
