### ISSUE TITLE
Add a completed status on a Booking Management panel

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1524]
https://github.com/happy-travel/agent-app-project/issues/1523

Add a nes booking status - completed - on the booking management panel

A completed status means that a booking is completed:

- a booking is confirmed - booking status is Confirmed
- a booking is payed - booking payment status is Captured
- CheckOut + 2 days.

Completed is a final status, we can't refresh a status of suh kind of bookings.

**Comment by DenisVelinen** [comment]
Bookings in Completed status have added in the system.
In particular task, in UI it's now possible to filter bookings by Completed status on Booking Management page https://manage-dev.happytravel.com/bookings 
As the Completed status is final, there is no status update button for bookings.
