### ISSUE TITLE
Incorrect sorting by DATE and by ACCOUNT MANAGER on Agencies page

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#1527]
On the Agencies page https://manage-dev.happytravel.com/agency/list

Sorting by DATE (OLD FIRST) doesn't work correctly because the interface shows the oldest agency with ID 984 (creation date 2021-07-06T16:29:43.840875+00:00). But there is an older agency in the database with ID 769 (creation date 2020-01-06T20:46:15.686337+00:00) and it's in the ID search result.

The sorting by ACCOUNT MANAGER looks very strange. I expect the table to be sorted in alphabet order of managers' names, but it isn't (see screen)

![Image](https://user-images.githubusercontent.com/17127277/174677605-90e8629b-6215-4b11-99da-e5a2842ff51c.png)

**Comment by alexander-plekhanov** [comment]
Once we implement paging this issue will be fixed automatically.
