### ISSUE TITLE
No cancellation policy added

### ISSUE THREAD

**Issue by wnlstk** [happy-travel/agent-app-project#1535]
How to reproduce:
- go to https://pms-dev.happytravel.com/ ;
- click to Property ;
- choose the Armani Hotel Dubai and click to 8 ;
- click to Cancellation Policies ;
- click the button Add Cancellation Policy ;
- fill up information:
From Date = 1-Apr-22
To Date = 28-Dec-22
Seasonality Or Event = no data
Deadline = 1
Percentage = 100
No Show = 1
Then click button Save.
Expected result:
Add Cancellation Policy is done
Actual result:
Bad request. No cancellation policy added.

GET {{ _.komoro.baseUrl }}/api/1.0/no-show-policies

**Comment by AlexeyShok** [comment]
Fixed on backend. It is necessary to pass propertyId from the frontend in the request body

**Comment by sergeyf-QA** [comment]
@AlexeyShok 
when executing case from ticket description then there is another issue
POST https://komoro-dev.happytravel.com/api/1.0/properties/8/cancellation-policies returns {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"Bad Request","status":400,"detail":"\u0027Property Id\u0027 must not be empty.","instance":"/api/1.0/properties/8/cancellation-policies","spanId":"556c2bf555b91299","traceId":"e752347fc767f4b79c209c950f4d4c6c","requestId":"0HMJ3QIF3BRU8:00000003"}

though property ID is in the link

**Comment by ViTsvetkova** [comment]
@suhan3z could you please comment?

**Comment by sergeyf-QA** [comment]
**Summary:**
- Cancellation police saves well

**OK on DEV.**
