### ISSUE TITLE
Ping Result as unnecessary pop-up window

### ISSUE THREAD

**Issue by wnlstk** [happy-travel/agent-app-project#1536]
How to reproduce:
- On 'Welcome page'-> Index-> click to the button 'Ping Travel Click'
Result:
Ping Result
<OTA_PingRS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" Version="" 
TimeStamp="2022-06-21T08:11:27.8891716Z" 
xmlns="http://www.opentravel.org/OTA/2003/05"
><Success /><EchoData /></OTA_PingRS>
Solution:
Hide the window with Ping Result or make it more beautifully.

**Comment by ViTsvetkova** [comment]
@AlexeyShok front can't pars xml

**Comment by AlexeyShok** [comment]
Need to remove this button

**Comment by sergeyf-QA** [comment]
**Summary:**
- the button 'Ping Travel Click' is removed from the Welcome page

**OK on DEV.**
