### ISSUE TITLE
Add data entry check when adding a new country

### ISSUE THREAD

**Issue by wnlstk** [happy-travel/agent-app-project#1537]
How to reproduce:
- go to https://pms-dev.happytravel.com/ ;
- click to Countries ;
- click to button 'Add Country;
- fill up information:
Name = 55555
Alpha2 Code = 55
Then click button Save.
Expected result:
Error input data.
Actual result:
Add country is done.

**Comment by sergeyf-QA** [comment]
**Summary:**
- Added checking for Alpha2 Code
- correct format is two letters in capitals

**OK on DEV.**
