### ISSUE TITLE
Create a new dev test Agency for the IT team

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1541]
Have to register new main dev agency for the IT team

email: dev@happytravel.tech

Then have to transfer/invite all IT team members to this agency

**Comment by nikolaeva31** [comment]
Main agent in Test agency https://passbolt.happytravel.com/app/passwords/view/712fe56a-498f-46c3-9090-a3b1bce0ef03

**Comment by ViTsvetkova** [comment]
Acceptable
![image](https://user-images.githubusercontent.com/90184684/175537554-828fce04-3ed4-4cb6-96e9-c8613c8b07e2.png)
