### ISSUE TITLE
Text too close to button or input field in agency verification modal windows

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#1543]
In the modal windows when activating/deactivating an admin or agency, when verifying an agency, the text is too close to the button or to the input field. 

The input field is too short relative to the size of the modal window and the value expected to be entered.

So many of the modal windows in the system have a similarly ugly appearance. 
It would be great to get them all to look the same.

<img width="554" alt="Снимок экрана 2022-06-21 в 17 08 37" src="https://user-images.githubusercontent.com/17127277/175316279-f7b27c25-89b6-45e9-852b-7e6a2731d248.png">

![Image](https://user-images.githubusercontent.com/17127277/174800735-566d589a-9487-40fc-9924-ba08a1c62a8c.png)
![Image](https://user-images.githubusercontent.com/17127277/174800737-a3cf65d7-964b-46b1-9bfc-680a7f86d809.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- fixed for activate/deactivate modals and verification ones

**OK on DEV.**
