### ISSUE TITLE
Add getting voucher in Ueda

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1546]
Need to add getting voucher in Ueda. The voucher is generated for bookings in the Confirmed or Completed status with the payment status Authorized or Captured, otherwise 400 is returned.

Endpoint:
{{ edo.baseUrl }}/en/api/1.0/admin/accommodations/bookings/:bookingId/voucher-pdf

Required permission for admin:
AdministratorPermissions.BookingManagement

**Comment by sergeyf-QA** [comment]
Temporary discarded changes, waiting for backend fixes
