### ISSUE TITLE
If possible, divide the endpoints in the edo swagger into admin and agent

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#156]
It is necessary to find out whether it is possible to divide the endpoints in the edo swagger into admin and agent. If possible, then make a separation.

**Comment by sergeyf-QA** [comment]
**Summary:**
now, admin endpoints are moved to another page in Swagger.

![b51fe05e20e1342f](https://user-images.githubusercontent.com/74529212/116359892-027ec800-a808-11eb-8e28-152cf4344e25.png)

**OK on DEV.**
