### ISSUE TITLE
Insomnia->>Komoro. These methods do not work

### ISSUE THREAD

**Issue by wnlstk** [happy-travel/agent-app-project#1560]
Travelclick:
- Get availability restrictions  400
- Updates availability restrictions 400
- Get inventory 400
- Updates inventory 400
- Gets inventory 400
- Updates rates 400

Country:
- Modifies an existing country 400

Cancellation policies:
- Modifies an existing cancellation policies 400
- Removes a cancellation policies 400

Meal plan:
- Modifies an existing meal plan 404
- Removes a meal plan 400

Property:
- Add a new property 400
- Modifies an existing property 400
- Uploading hotel data from a CSV file - Error

Room:
- Removes a room for the specified property 400

Room Type:
- Adds a new room type 400
- Modifies an existing room type 400

**Comment by AlexeyShok** [comment]
All endpoints returning 401 must use basic authentication

**Comment by wnlstk** [comment]
Travelclick:

Get availability restrictions 400
Updates availability restrictions 400
Get inventory 400
Updates inventory 400
Gets inventory 400
Updates rates 400
Country:

Modifies an existing country 400
Cancellation policies:

Modifies an existing cancellation policies 400
Removes a cancellation policies 400
Meal plan:

Modifies an existing meal plan 404
Removes a meal plan 400
Property:

Add a new property 400
Modifies an existing property 400
Uploading hotel data from a CSV file - Error
Room:

Removes a room for the specified property 400
Room Type:

Adds a new room type 400
Modifies an existing room type 400

**Comment by wnlstk** [comment]
15.08 dev

Meal plan:
Modifies an existing meal plan 404

Property:
Add a new property 400
Modifies an existing property 400
Uploading hotel data from a CSV file - Error : no such file or directory

Room Type:
Adds a new room type 400
Modifies an existing room type 400

**Comment by wnlstk** [comment]
ok on dev !
