### ISSUE TITLE
Add a check-in and check-out data to the Booking page

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1570]
The Reservation team asks to add a check-in and check-out here

![Image](https://user-images.githubusercontent.com/90184684/176119537-b03629c0-e1e7-498d-b861-ee4f54e790fd.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- added Check In / Check Out to the https://manage-dev.happytravel.com/bookings

**OK on DEV.**
