### ISSUE TITLE
"customHeaders" always is sent as null from front-end side when saving suppliers

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1572]
**How to reproduce:**
- go to any supplier page e.g. https://manage-dev.happytravel.com/suppliers/test
- enter anything to Custom Headers field
- click on Save

**Expected result:**
- sent  "customHeaders" should contain entered definition

**Actual result:**
- "customHeaders" is sent as null at PUT /{culture}/api/{v}/admin/suppliers/{code}

**Comment by alexander-plekhanov** [comment]
customHeaders should be json object and it works, so i'd close this as won't fix

**Comment by sergeyf-QA** [comment]
ya, there is no an issue
