### ISSUE TITLE
A Credit Agency can't book with insufficient balance (less than a booking price) within deadline/APR

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1573]
If a room contract set in deadline or APR and agency ContractKind = VirtualAccountOrCreditCardPayments we added a room contract set validation.
If the final price of a room contract set is more than the amount on the agency's balance, it is necessary to remove the virtual account from the list of available payment methods.
We can add the following notification on the front: Your agency has an insufficient balance. Please contact with your Happy Travel manager.

https://github.com/happy-travel/agent-app-project/issues/1566

**Comment by ViTsvetkova** [comment]
done

**Comment by sergeyf-QA** [comment]
**Summary:**
- If the final price of a room contract set is more than the amount on the agency's balance, the virtual account is removed from the list of available payment methods.

**OK on DEV.**
