### ISSUE TITLE
Return a list of all countries without multilingualism

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1574]
Need to remove multilanguage from a list of all countries in admin endpoint

**Comment by DaniyarAskarov** [comment]
Countries by market id was changed to slim version and endpoint for list of all countries was added
PR: https://github.com/happy-travel/edo/pull/1934
Insomnia: Edo -> Admin -> Locations -> (Get list of all countries/Get countries by market id)
Tested through insomnia

Multilanguage was deleted from this endpoint

**Comment by sergeyf-QA** [comment]
**Summary:**
- GET /{culture}/api/{v}/admin/locations/countries and GET /{culture}/api/{v}/admin/locations/markets/{marketId}/countries  return data w/o multilingualism


**OK on DEV.**
