### ISSUE TITLE
Fix the layout of the management panel for the mobiles

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1578]
Fix a layout of the admin panel for the mobile version

![Image](https://user-images.githubusercontent.com/90184684/177135423-99d0d564-a85f-42c8-8be3-32f5c65895b9.png)

**Comment by sergeyf-QA** [comment]
**Summary:**

https://user-images.githubusercontent.com/74529212/178503602-0b51c9e5-8bab-45b2-ab81-9ec9c2aba6c6.MP4

**OK on DEV.*
