### ISSUE TITLE
Hide the "Create a new one" link from the login page of the admin app.

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#158]
On https://manage-dev.happytravel.com
In Chrome, Firefox, Safari.

**Steps.**
1. Go to the https://manage-dev.happytravel.com;
2. Note the bottom right-hand side of the login form page.

**Result.**
There is the "Create a new one" link on the login form page that only applies to agents in the agent application. 

**Expectations.**
Hide the "Create a new one" link from the login page of the admin app. System administrators can only receive invitations from other administrators. There is no other way to become an administrator.

**Comment by alexander-plekhanov** [comment]
May be will be fixed in future. Not a bug.
