### ISSUE TITLE
It is impossible to remove the last country from the market

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1592]
**How to reproduce:**
- go to https://manage-dev.happytravel.com/markups/markets
- open xxxxxs market
- try to remove the last country Belarus from the market
- Save changes

**Expected result:**
- allow to save changes to the market in case there are no countries inside

**Actual result:**
- PUT https://edo-dev.happytravel.com/en/api/1.0/admin/locations/markets/31/countries returns {"status":400,"detail":"'Country Codes' must not be empty."}

**Comment by DaniyarAskarov** [comment]
PR: https://github.com/happy-travel/edo/pull/1979
Insomnia: Edo -> Admin -> Locations
Tested through insomnia

Validations were added to fobidden crud unknown market!
