### ISSUE TITLE
Add a lead passenger info to the booking table

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1593]
A booking manager has to see a lead passenger name (title, first name, last name) and a number of passengers at the booking table

![image](https://user-images.githubusercontent.com/90184684/178482973-00e1f57b-e2fb-4ff6-8f74-10bb4d221c1b.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- Booking manager may see a lead passenger name (title, first name, last name) and a number of passengers at the booking table

**OK on DEV.**
