### ISSUE TITLE
Incorrect screen after payment interruption

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#1603]
Steps:
1. Сreate booking without deadline
2. Pay by account balance 
3. Open created booking and push "Pay now by Card"
4. Back to booking page from payment page (payment didn't make)

**AR**:  Get third step of search (to fill in data as for new booking). 
![Screenshot 2022-07-14 at 13 33 40](https://user-images.githubusercontent.com/38030865/178963153-b5b69c9d-9aff-4f61-83de-ec8702d52c2d.png)

**Comment by alexander-plekhanov** [comment]
moved

**Comment by wnlstk** [comment]
https://track.happytravel.tech/issue/HP-549/Payment-interruption-issues
