### ISSUE TITLE
Add the ability to view and change the IsDirectContract property in Ueda

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1608]
A new IsDirectContract property has been added to the SlimSupplier and ReachSuppler models. It is necessary to add the ability to view and change this property in Ueda.

**Comment by sergeyf-QA** [comment]
**Summary:**
- 'Direct Contract' column is added to suppliers list https://manage-dev.happytravel.com/suppliers/
- 'Is Direct Contract' flag is on a supplier page

**OK on DEV.**
