### ISSUE TITLE
404 error when trying to go to the counterparty page.

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#161]
On https://manage-dev.happytravel.com
In Chrome, Firefox, Safari.

**Steps.**
1. Log in and go to Counterparties list (click on Counterparties button);
2. Open the developer panel in the browser;
3. Go to some counterparty information page;
4. Find the /USDbalance request in the developer panel in the browser.

**Result.**
The request /USDbalance has status 404.

**Expected.**
Either the method is wrong or it doesn’t work correctly. But in either case, the administrator must have access to the counterparty information.

**Comment by sergeyf-QA** [comment]
**Summary:**
now, in case 400 error of USD/balance response the counterparty page is accessable

**OK on DEV.**
