### ISSUE TITLE
On bookings list passengers names are visible w/o View Pax Names permission

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1610]
**How to reproduce:**
- log in as an admin w/o View Pax Names permission
- go to the https://manage-dev.happytravel.com/bookings list
- check passengers names
- open any booking and check passengers names there

**Expected result:**
- passengers names in the booking list are masked by `***` like on a booking page

**Actual result:**
- in the booking list names are not masked though on a booking page they are

**Comment by DaniyarAskarov** [comment]
PR: https://github.com/happy-travel/edo/pull/2025
Insomnia: Edo -> Admin -> Bookings -> GET requests
Tested through insomnia

Affected:
/admin/agencies/:agencyId/accommodations/bookings
/admin/agents/:agentId/accommodations/bookings

**Comment by sergeyf-QA** [comment]
**Summary:**
GET /admin/agencies/:agencyId/accommodations/bookings
GET /admin/agents/:agentId/accommodations/bookings
return "mainPassengerName":"Ms. *** ***" in case View Pax Names permission is off

**OK on DEV.**
