### ISSUE TITLE
Add all Pax names to a Reservation List

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1611]
Booking manager should do a search by a pax name 
View Pax Names permission is required 

![Image](https://user-images.githubusercontent.com/90184684/179519678-43b5b62d-4e2e-4bac-a799-a1afa0a49db5.png)

- [ ] backend 
- [ ] frontend

**Comment by ViTsvetkova** [comment]
@AlexeyShok please add your comment why we decided to postpone it. (must change models before creating a pax name filter)

**Comment by AlexeyShok** [comment]
In the current implementation, we cannot use Odata to search these fields. To solve the problem, you must first migrate EdoContracts to System.Text.Json. This migration will require changes to edo, the mapper, all connectors and possibly other services.

**Comment by mikheevaksenia** [comment]
moved to youtrack https://track.happytravel.tech/issue/HP-21
