### ISSUE TITLE
Add IsDirectContract to supplier endpoints in edo

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1612]

**Comment by sergeyf-QA** [comment]
**Summary:**
- "isDirectContract" is added to 
GET /{culture}/api/{v}/admin/suppliers
POST /{culture}/api/{v}/admin/suppliers
GET /{culture}/api/{v}/admin/suppliers/{code}
PUT /{culture}/api/{v}/admin/suppliers/{code}

**OK on DEV.**
