### ISSUE TITLE
Highlight the deadline policy for agents

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1619]
Need to highlight (design) the deadline policy for agents (1st and 2nd search step)

![Image](https://user-images.githubusercontent.com/90184684/179735367-6f2d9128-3b0d-45c2-bc2f-dfb8929cf0a5.png)

VR: **https://www.figma.com/file/Zs6p45yqg4P5F27ELBykAK/Happy-Pravel-Admin?node-id=107%3A18203**

**Comment by sergeyf-QA** [comment]
**Summary:**
- within deadline
![image](https://user-images.githubusercontent.com/74529212/180995904-f50c626e-e467-4093-9e07-5767d120f8fe.png)


- not in deadline
![image](https://user-images.githubusercontent.com/74529212/180995850-e5a8dc53-5fb0-410a-af13-0036c14be6b0.png)


**OK on DEV.**
