### ISSUE TITLE
Any agent from the agent application can authorize in the admin panel.

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#162]
On https://manage-dev.happytravel.com
In Chrome, Firefox, Safari.

There are three agents with different agency status:
– Read Only https://passbolt.happytravel.com/app/passwords/view/e2d28859-a5e8-433f-a256-e8c04a3bb923 
– Pending Verification https://passbolt.happytravel.com/app/passwords/view/8c5098fb-20b8-4b2f-bb60-e62f683a1937 
– Full Access https://passbolt.happytravel.com/app/passwords/view/234e4b0d-d430-4b00-8136-4f5935e70834 

**Steps.**
1. Authorize any of these agents in the admin panel.

**Result.**
Any agent from the agent application can authorize in the admin panel and do as an administrator (see pic. https://drive.google.com/file/d/182TkStGqNtw73rAiKYNG1YlzTLoRIuEj/view?usp=sharing ). For example, none of the agents listed are administrators, but they were able to log in.

**Expected.**
Only administrators - those who have been invited to become administrators - can log in to the admin panel.

**Comment by mingazhev** [comment]
I've added an endpoint to return current administrator info:

{{ edo.baseUrl }}/en/api/1.0/admin/administrators/current

It returns OK (200) with administrator information or NoContent (204) if there is no registered administrator for current identity user

@alexander-plekhanov please have a look

**Comment by sergeyf-QA** [comment]
**Summary:**
now Read Only, Pending Verification and Full Access can not login to admin panel, only admin agent can.

**OK on DEV.**
