### ISSUE TITLE
Do not submit a multi-room search request if the supplier does not support it

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1627]
If an agent wants to book multiple rooms, only the connectors that support multi-room booking should send a search request. You need to check the supplier setting before sending a search request.

**Comment by ViTsvetkova** [comment]
https://track.happytravel.tech/issue/HP-542/TechDebt-Do-not-submit-a-multi-room-search-request-if-the-supplier-does-not-support-it
