### ISSUE TITLE
Add UI for offline payment method

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#163]
Here is backend method task:
https://github.com/happy-travel/agent-app-project/issues/111

To execute offline payment method it is needed to use endpoint:

`api/{v:apiVersion}/accommodations/bookings/book-for-offline`

the same as account booking but ends with `book-for-offline` (model is the same)

**Comment by sergeyf-QA** [comment]
**Summary:**
when Offline booking is chosen then it calls api/{v:apiVersion}/accommodations/bookings/book-for-offline from front end and send needed info

**OK on DEV.**
