### ISSUE TITLE
Add new voucher template for admin panel

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1632]
Need to add new voucher template for admin panel. If necessary, add missing data to the data model to fill in the voucher template.
https://discord.com/channels/567473798144851988/567474373162827797/999667831442505759

**Comment by DaniyarAskarov** [comment]
Template:
[case.pdf](https://github.com/happy-travel/agent-app-project/files/9180635/case.pdf)

**Comment by sergeyf-QA** [comment]
**Summary:**
- GET {{ edo.baseUrl }}/en/api/1.0/admin/accommodations/bookings/{bookingId}/voucher-pdf returns voucher like in example

**OK on DEV.**

**Comment by DaniyarAskarov** [comment]
> 

Done!

**Comment by sergeyf-QA** [comment]
**Summary:**
- GET {{ edo.baseUrl }}/en/api/1.0/admin/accommodations/bookings/{bookingId}/voucher-pdf returns voucher

**OK on DEV.**
