### ISSUE TITLE
Attempt to make a booking within deadline ended with a SCHEDULE_DATE: INVALID_VALUE error with status 400

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#1633]
On http://happytravel.com/
**Steps.**
**Note: Repetition of steps should be agreed with PM and/or СТО as this is a production environment.**
1. Search these parameters:
```
{
    "checkInDate": "2022-10-26T00:00:00Z",
    "checkOutDate": "2022-10-29T00:00:00Z",
    "roomDetails": [
        {
            "adultsNumber": 1,
            "childrenNumber": 0
        }
    ],
    "nationality": "AE",
    "residency": "AE",
    "htIds": [
        "Accommodation_5637484"
    ]
}
```
Where Accommodation_5637484 is **Hotel Flor Los Almendros, Paguera, Spain**

2. Open the developer panel in browser;

3. Make a booking a contract with within deadline.

**Expectations.**
The booking will complete without any errors and your account will be debited with the booking amount.

**Result.**
Booking failed
```
{ "status": 400,
    "detail": "SCHEDULE_DATE: INVALID_VALUE"
}
```
Error details https://logs.happytravel.com/app/discover#/doc/d9804df0-e80f-11eb-bbd4-c3d108d86f4e/fluentd-edo-2022.07?id=a2NKIYIB_8juHl3Q_ND4
Amount has been debited from the account balance:
Successfully processes payment changes. Old payment status: NotPaid. New payment status: Captured. Payment: 'HTL-ES-000EM5-01'.
Booking reference code: 'HTL-ES-000EM5-01'.
Vcc issue started for booking HTL-ES-000EM5-01
Successfully charged money for a booking with reference code: 'HTL-ES-000EM5-01'
Generated invoice number R1755/2022 for booking HTL-ES-000EM5-01

**Comment by nikolaeva31** [comment]
Error wasn't reproduced
