### ISSUE TITLE
New voucher in pdf

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1647]
Need to change a current voucher to the new one. Agents can download it in pdf and send to email. Change an email template.
- [x] #1662
- [x] #1663
- [x] #1714
- [x] #1716
- [x] #1664
- [x] #1665
- [x] #1666
- [x] #1710

**Comment by sergeyf-QA** [comment]
New voucher in pdf is added to the admin panel and the agent app.
