### ISSUE TITLE
Global Markup should be applied to all agencies in the Agent App

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1652]
Global Markup should be applied to all agencies (Direct API Agencies and Web Agencies)

**Comment by AlexeyShok** [comment]
Made as part of the task  https://github.com/happy-travel/agent-app-project/issues/1599

**Comment by nikolaeva31** [comment]
Markup is used for searching in direct-api. 

Error when creating booking - https://github.com/happy-travel/edo/issues/2069 
(Separate task)
