### ISSUE TITLE
Replace the endpoint for sending a voucher with a new one in PDF format

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1665]
Need to replace the endpoint for sending a voucher with a new one in PDF format

**Comment by sergeyf-QA** [comment]
**Summary:**
- sending voucher calls POST /{culture}/api/{v}/accommodations/bookings/{bookingId}/supporting-documents/voucher/pdf/send endpoint

**OK on DEV.**
