### ISSUE TITLE
Do not allow offline payments to non-offline agencies

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1669]
Add a check for the type of agency contract when making offline payments.
Endpoint:
POST api/{v:apiVersion}/admin/payments/offline/accommodations/bookings/{bookingId}

**Comment by sergeyf-QA** [comment]
**Summary:**
- in case the type of agency contract kind is not OfflineOrCreditCardPayments when making offline the
POST /{culture}/api/{v}/admin/payments/offline/accommodations/bookings/{bookingId} returns
{
  "status": 400,
  "detail": "Could not complete booking. Invalid agency contract kind: VirtualAccountOrCreditCardPayments"
}

**OK on DEV.**
