### ISSUE TITLE
Add logging of changes in the activity status of accounts

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#167]
Need add logging of changes in the activity status of agency and counterparty accounts

**Comment by sergeyf-QA** [comment]
**Summary:**
when admin executes
​POST /{culture}​/api​/{v}​/admin​/counterparties​/{counterpartyId}​/deactivate
POST /{culture}/api/{v}/admin/counterparties/{counterpartyId}/activate
POST /{culture}/api/{v}/admin/agencies/{agencyId}/deactivate
POST /{culture}/api/{v}/admin/agencies/{agencyId}/activate
then logs are written to "ManagementAuditLog" table

**OK on DEV.**
