### ISSUE TITLE
Change voucher template according to business requirements

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1670]
1) We have to remove below details:
* Hotel reservation email address 
* Rate Plan Description: e.g. Check in and check out: Late CheckOut between 12:00 hours until 18:00 hours will be charged 50.00% of 1 nights stay. Late CheckOut between 18:00 hours until 23:59 hours will be charged 100.00% of 1 nights stay
* Amenities: no need
* Rate plan: no need

2) Check in and check out time: we need to show standard only. 15:00 check in, 12:00 – check out.

3) Add: Hotel/Supplier confirmation number

4) Room rate description – change to Meal Plan

5) Room category: just the name of the room type – e.g. Junior Suite Sea view 

AR:
![Снимок экрана 2022-08-01 205338](https://user-images.githubusercontent.com/90184684/182211747-6db2121d-37d2-4ebe-b34c-291d5183b1b7.png)

ER:
![image](https://user-images.githubusercontent.com/90184684/182212300-b380f48a-4631-4e30-b2aa-65bbc92c99b8.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- voucher is redeveloped according to the description

**OK on DEV.**
