### ISSUE TITLE
Do not allow offline payments to non-offline agencies

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1681]
The button for offline payment should be shown only if the contract kind of agency is OfflineOrCreditCardPayments
Validation in endpoint added.
POST api/{v:apiVersion}/admin/payments/offline/accommodations/bookings/{bookingId}

**Comment by sergeyf-QA** [comment]
**Summary:**
- 'Manually Confirm Payment' button is shown for offline bookings only
![image](https://user-images.githubusercontent.com/74529212/190964695-bf42f4f9-0944-4670-bb04-501693868781.png)


**OK on DEV.**
