### ISSUE TITLE
Change booking status on frontend only for agents

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1683]
Changed the list of Reservation Statuses for the Agencies:
 
 Confirmed = Confirmed
 Pending, MCN = Awaiting confirmation
 Cancelled = Cancelled (final status)
 Pending Cancellation = Pending Cancellation 
Discarded = Discarded  (final status)
 Rejected = Rejected  (final status)
 Completed = Completed (final status)

**Comment by sergeyf-QA** [comment]
**Summary:**
- booking statuses from description are applied on booking lists and booking pages

**OK on DEV.**
