### ISSUE TITLE
On the duplicate hotel comparison page, some of the information is presented as JSON

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#169]
On https://manage-dev.happytravel.com
In Chrome, Firefox, Safari.

**Steps.**
1. Log in and go to Duplicates list (click on Duplicates button);
2. Go to some duplicate information page;
4. Scroll down the page and pay attention to the information after the hotel data table.

**Result.**
On the duplicate hotel comparison page, some of the information is presented as JSON.
![RUjYgxaRqH](https://user-images.githubusercontent.com/17127277/116257080-65c31880-a77c-11eb-8d1f-5e85e9befce3.png)

**Expectations.**
All information should be presented as a table or in another form that the agent can understand.

**Comment by cyberkarma** [comment]
Это не ошибка, так и должно быть
