### ISSUE TITLE
Add documentation for commission when paying for a booking with a credit card

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1690]
Need to add documentation for commission when paying for a booking with a credit card. It is necessary to describe what prices the backend sends to the front, their value depending on the type of agency contract. And the logic of price recalculation in case of payment by credit card.

**Comment by DaniyarAskarov** [comment]
@AlexeyShok do we already have documentation for credit card commission?
https://github.com/happy-travel/edo/wiki/Booking-%5C-Credit-Card-Payment-Flow-Price-Circumstances-(not-implemented)#wide-availability-search-and-accommodation-availability-search-steps

**Comment by AlexeyShok** [comment]
Yes, you need to update this information according to the current implementation. And describe in more detail the types of prices and what they are equal to depending on the type of contract. You also need to move this documentation to the docs repository

**Comment by DaniyarAskarov** [comment]
Done! https://github.com/happy-travel/docs/wiki/Booking-%5C-Credit-Card-Payment-Flow-Price-Circumstances

**Comment by sergeyf-QA** [comment]
https://github.com/happy-travel/docs/wiki/Booking-%5C-Credit-Card-Payment-Flow-Price-Circumstances is OK
