### ISSUE TITLE
Change email templates for agencies verification

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1691]
It is necessary to change email templates for changing agency verification states for Read Only, Full Access.
Change all "Counterparty" words to "Agencies" one.

**Comment by DenisVelinen** [comment]
It has been done and works in both environment.
There is example:
![2QyapSaz9e](https://user-images.githubusercontent.com/17127277/190657128-47933afb-ebfc-4011-9dfe-e9d7ccb56412.png)
