### ISSUE TITLE
Create a new conversion funnel dashboard with 2nd and 3rd search step

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1703]
Must create a conversation funnel with the following info:

1. A total search quantity of an Accommodation made by API-Client/Agency (2nd search step)
2. A total response quantity after searching of an Accommodation made by API-Client/Agency >0 (response quantity after 2nd search step; we calculate successful responses only)
3. A total quantity of 3rd search step requests made by API Client/Agency (the 3rd search step)
4. A total booking request quantity made by API Client/Agency (after the 3rd search step)
5. A total response quantity of successful bookings made by API Client/Agency (after the 3rd search step)

![Image](https://user-images.githubusercontent.com/90184684/183583119-fa2a807d-97d0-4363-b1c9-0c6b397c60b3.png)

E.g.
1 = 1000
2 = 500
C(2/1)*100% = 50%
3 = 20
C(3/2)*100% = 4%
4 = 18
C (4/3)*100% = 90%
5 = 15
C (5/4)*100% = 83,3%

**Comment by DFSko** [comment]
Done
