### ISSUE TITLE
Children shouldn't have a title

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1704]
Remove a title of children (Mr/Mrs/etc.) on the 3rd search step:

![Image](https://user-images.githubusercontent.com/90184684/183598389-9f06d521-6bb8-4c98-b847-1d15cf636697.png)

- [x] #1719
- [x] frontend

**Comment by AlexeyShok** [comment]
public enum PassengerTitles
    {
        [Description("")]
        Unspecified = 0,

        [Description("Miss")]
        Miss = 1,

        [Description("Mr.")]
        Mr = 2,

        [Description("Mrs.")]
        Mrs = 3,

        [Description("Ms.")]
        Ms = 4
    }

**Comment by alexander-plekhanov** [comment]
Unfortunately, need changes on backend side. #1719 
Otherwise it creates "Unspecified. John White" passengers.

**Comment by sergeyf-QA** [comment]
@AlexeyShok

**Comment by sergeyf-QA** [comment]
**Summary:**
- now there is no children title on the 3rd search step
![image](https://user-images.githubusercontent.com/74529212/193796377-4090b448-6c44-4573-b43d-c0d42ee64389.png)


**OK on DEV.**
