### ISSUE TITLE
Improve the view of itinerary number on the 3rd search step

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1706]
Try to add information with "i" - "Please use the Itinerary number if you have a confirmed booking and have got a request for an adjected reservation.  It will help to create similar reference codes in the Happy Travel System."

**Comment by sergeyf-QA** [comment]
**Summary:**
- Itinerary Number text from description exists on the 3rd search step

**OK on DEV.**
