### ISSUE TITLE
Add admin endpoint to send PDF voucher

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1710]

**Comment by DenisVelinen** [comment]
Method that sends an email with an attached voucher to PDF is
/{culture}/api/{v}/admin/accommodations/bookings/{bookingId}/voucher-pdf/send
Only works with admin token (the response which the agent's token has status 403).
Sends a voucher for Confirmed and Completed bookings only. For bookings in other statuses response has a status 400 and the text that the voucher isn't available. For example, "Voucher is not allowed for booking status 'Cancelled' ".
