### ISSUE TITLE
Add the ability to add new rate plans

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1720]

**Comment by sergeyf-QA** [comment]
**Summary:**
- POST {{ _.komoro.baseUrl }}/api/1.0/properties/:propertyId/rooms/:roomId/rate-plans allows to create a new rate plan
- in case such rate plan exists in "RatePlans" table it returns 400 error with
"detail": "Adding rate plan has duplicate"

**OK on DEV.**
