### ISSUE TITLE
[Back] Change the logic for Agency Settings (Inheritance for subagencies and agents)

### ISSUE THREAD

**Issue by mikheevaksenia** [happy-travel/agent-app-project#1722]
Requirements: 

Back:
1) Supplier Visible and Direct Contract Mark

When we turn on the Supplier Visible Setting or Direct Contract Mark at the Agency level, this setting should be turned on for all Subagency/Agent on their level.  
An admin can turn off this setting to an Agent/Subagency

When we turn off the Supplier Visible Setting or Direct Contract Mark at the Agency level, this setting should be turned off for all Subagency/Agent on their level. 

**Default Settings:** 
Direct Contract Mark: ON
Supplier Visible Setting: OFF

2) Deadline Shift 

We need to check the Subagency/Agent settings have value = 0 (to make them not shown on the front). 

**Default Settings on the Agency level:** 0 

This setting is always added to the Global Setup of ContractTypes:
CashPayments = -2
CreditCardPeyments = -1
CreditPayments = -1

*If the new Deadline Shift is more than 0, it will be automatically changed to 0.

The logic (levels of Deadline Shift):
1. Global
2. Agency = Global + Agency Setup
3.1. Agent = Agency = Global + Agency Setup
3.2. Subagency = Agency = Global + Agency Setup

**Comment by sergeyf-QA** [comment]
@timur-mut 
1) 
agent **Supplier Visible Setting** or **Direct Contract Mark** settings are not set according to agency settings when I turn on/off on agency level
**Expected:**
When we turn off the Supplier Visible Setting or Direct Contract Mark at the Agency level, this setting should be turned off for all Subagency/Agent on their level.

2)
when I create an agency default settings for Direct Contract Mark and Supplier Visible Setting are OFF
**Expected:**
Default Settings:
Direct Contract Mark: ON
Supplier Visible Setting: OFF

**Comment by sergeyf-QA** [comment]
**Summary:**
- when we turn on the Supplier Visible Setting or Direct Contract Mark at the Agency level, this setting is turned on for all Subagency/Agent on their level
- default Settings for just created agencies:
Direct Contract Mark: ON
Supplier Visible Setting: OFF
- deadline shift works according to the pointed logic

**OK on DEV.**
