### ISSUE TITLE
[Front] Change the logic for Agency Settings (Inheritance for subagencies and agents)

### ISSUE THREAD

**Issue by mikheevaksenia** [happy-travel/agent-app-project#1723]
Requirements:

1) Account Manager 

Account Manager should be no shown on the Subagencies/Agents level. 

2) Deadline Shift

Deadline Shift should be no shown on the Subagencies/Agents level. 

3) Advance Purchase Rate Mode and Passed Deadline Offers Mode.

Card and Account Purchases should be no shown for Offline and Credit Card Contract Types. 

![image](https://user-images.githubusercontent.com/106528059/185375126-46049c7f-cd2b-4da4-9949-2c497854bd68.png)

**Comment by mikheevaksenia** [comment]
#1722

**Comment by sergeyf-QA** [comment]
**Summary:**
- Account Manager is not shown on the Subagencies/Agents level
- Deadline Shift is not shown on the Subagencies/Agents level
- Card and Account Purchases is not shown for Offline, Credit Card Contract Types and for Not Specified subagencies

**OK on DEV.**
