### ISSUE TITLE
400 error during location markup creation

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1730]
**How to reproduce:**
- go to the admin panel and try to create such location markup

description: any
percentage: any
location: market
market: any
destination: market
market: any
{"description":"gffgfg","value":4,"locationScopeType":"Market","destinationScopeType":"Market","locationScopeId":3,"destinationScopeId":11,"functionType":"Percent","currency":"USD"}
or

description: any
percentage: any
location: market
market: any
destination: country
country: any

**Expected result:**
- perhaps markup should be created or we need to remove such ability on front-end?

**Actual result:**
- POST https://edo-dev.happytravel.com/en/api/1.0/admin/location-markups
{"status":400,"detail":"'Destination Scope Id' must be empty., DestinationScopeType must be empty or Global"}

**Comment by DaniyarAskarov** [comment]
@sergeyf-QA There is no any possibilities to add next types of markups : | Market - Market | Market - Country | Country - Market | 
Check tasks and requirements: https://github.com/happy-travel/agent-app-project/issues/1288 ; https://github.com/happy-travel/agent-app-project/issues/1370

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
could you please hide 'Market' and 'Country' at 'Destination' on Location markup creation page in cases in 'Location' 'Market' or 'Country' are chosen?
![Screenshot at Aug 24 09-23-12](https://user-images.githubusercontent.com/74529212/186345914-bf7a7afa-3c1b-4b58-aff0-82f9b0724335.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- now the 'Market' and the 'Country' at the 'Destination' on Location markup creation page are removed in cases in 'Location' 'Market' or 'Country' are chosen
- so, no 400 error during location markups creation

**OK on DEV.**
