### ISSUE TITLE
After transfer money to subagency acc the account is not updated at once on Settings pages

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1731]
**How to reproduce:**
- go to Settings->Subagencies page by agency which has a subagency
- open a subagency page
- try to transfer money from agency account to subagency one

**Expected result:**
- money amount on Settings page should be updated at once user transfers money to his subagency

**Actual result:**
- there are still money amount like before transfer
![image](https://user-images.githubusercontent.com/74529212/186190191-951004bc-1d13-4d66-8949-03f2ff84dd03.png)

**Comment by ViTsvetkova** [comment]
irrelevant task
