### ISSUE TITLE
Add ability to add, modify or remove rate plan types to takato

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1732]
Need to add ability to add, modify or remove rate plan types to takato

Endpoints:
GET {{ _.komoro.baseUrl }}/api/1.0/rate-plan-types
POST {{ _.komoro.baseUrl }}/api/1.0/rate-plan-types
PUT {{ _.komoro.baseUrl }}/api/1.0/rate-plan-types/{ratePlanTypeId}
DELETE {{ _.komoro.baseUrl }}/api/1.0/rate-plan-types/{ratePlanTypeId}

**Comment by sergeyf-QA** [comment]
@AlexeyShok 
POST {{ _.komoro.baseUrl }}/api/1.0/rate-plan-types
{
  "id": 0,
	"code": "Testplantype",
  "name": "Test onlysssss",
	"mealPlan": {
    "id": 1,
    "name": "Room only"
  }
}
returns
[500 error.txt](https://github.com/happy-travel/agent-app-project/files/9437433/500.error.txt)

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
when I try to change and save meal plan at any Rate Plan Type (e.g. for https://pms-dev.happytravel.com/rate-plan-type/4 ) then changes are not saved because sent meal plan name is wrong

**Comment by sergeyf-QA** [comment]
**Summary:**
- it is possible to add, change, update and remove rate plan types on https://pms-dev.happytravel.com/rate-plan-type

**OK on DEV.**
