### ISSUE TITLE
Add ability to add, modify or remove rate plans to takato

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1733]
Need to add ability to add, modify or remove rate plans to takato

Endpoints:
GET {{ _.komoro.baseUrl }}/api/1.0/properties/:propertyId/rooms/:roomId/rate-plans
POST {{ _.komoro.baseUrl }}/api/1.0/properties/:propertyId/rooms/:roomId/rate-plans
PUT {{ _.komoro.baseUrl }}/api/1.0/properties/:propertyId/rooms/:roomId/rate-plans/:ratePlanId
DELETE {{ _.komoro.baseUrl }}/api/1.0/properties/:propertyId/rooms/:roomId/rate-plans/:ratePlanId

**Comment by sergeyf-QA** [comment]
**Summary:**
- it is possible to add, update and remove rate plans

**OK on DEV.**
