### ISSUE TITLE
Add an extra empty field to the booking window with the possibility of sending information to the voucher

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#174]
Add an extra empty field to the booking window with the possibility of sending information to the voucher (225 symbols)

Current problem: We do not have any space to add extra important information and ref number (third part). As an agent, I want to mention any special requests about the booking (connecting rooms, early arrival, late check-out, twin beds, details about children etc.) on a booking page in a Special Requests section in a free text mode and be sure that this information will be sent to the hotel and will be added to the voucher.

Tasks:
- To add a free text window on the last step of the reservation process
- Send all details to the voucher

**Comment by ViTsvetkova** [comment]
moved to youtrack
