### ISSUE TITLE
Replace the first search step query model with komoro contracts model

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1740]
Need to replace the first search step query model with komoro contracts model

**Comment by sergeyf-QA** [comment]
**Summary:**
- KOMORO sent model
{
  "checkInDate": "2022-09-28",
  "checkOutDate": "2022-09-30",
  "accommodationIds": [
    "73769"
  ],
  "rooms": [
    {
      "adultsNumber": 2,
      "childrenAges": [
        
      ],
      "isExtraBedNeeded": false,
      "type": "NotSpecified"
    }
  ]
}

- OpenTravel sent model
{
	"checkInDate": "2022-09-28",
	"checkOutDate": "2022-09-30",
	"filters": "AvailableOnly",
	"nationality": "RU",
	"propertyTypes": "Hotels",
	"ratings": "NotRated, OneStar, TwoStars, ThreeStars, FourStars, FiveStars",
	"residency": "RU",
	"rooms": [
		{
			"adultsNumber": 2,
			"childrenAges": [],
			"isExtraBedNeeded": false,
			"type": "NotSpecified"
		}
	],
	"accommodationIds": [
		    "73769"
	]
}

**OK on DEV.**
