### ISSUE TITLE
Add property chains to komoro

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1750]
Need to add property chains to komoro. Need to add table Chans (Id, Name, Created, Modified), CRUD endpoints for admin app and add ChainId to Properties table and property endpoints.

**Comment by sergeyf-QA** [comment]
@DFSko 
PUT https://komoro-dev.happytravel.com/api/1.0/chains/{chainId} returns 
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "Bad Request",
    "status": 400,
    "detail": "Chain with name stringsss already exists",
    "instance": "/api/1.0/chains/1",
    "spanId": "0b85b0425fdbb81c",
    "traceId": "2985a7377a416b3264d3061b1539a95c",
    "requestId": "0HMKF28EMF8K3:00000003"
}
when I try to update a chain

**Comment by sergeyf-QA** [comment]
**Summary:**
- chains CRUD operations work well

**OK on DEV.**
