### ISSUE TITLE
Add receipt of proforma invoices in PDF format

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1759]
Need to add receipt and sending to email proforma invoices in PDF format
We must get the following info:

- INV number
- the date of the invoice
- Agency name (bill to)
- Agent name (bill to)
- Agency address and phone number
- Arrival date (check-in)
- Departure date (check-out)
- Payment due date (cancellation deadline date)
- Booking ref number (HT ref code)
- Supplier ref code (if exist)
- Client ref code (if exist; for API clients only)
- Leading passenger for each room (name and surname)
- Accommodation name (hotel name)
- Room type (name of the room/contract)
- Price for each room + currency
- Total cost + currency
- Payment status (not paid)
- HT bank details (HT has one bank account for one type of currency) https://happytravelcom-my.sharepoint.com/:x:/g/personal/ksenia_mikheeva_happytravel_com/EWZJi30DkiJKgGrCQ_1rNd0B97skUpnV6OGG70dshUpXng?e=rS0FLK

Template for other countries:
[Proforma  (1).pdf](https://github.com/happy-travel/agent-app-project/files/9725104/Proforma.1.pdf)
Template for CIS 
[Proforma RU (1).pdf](https://github.com/happy-travel/agent-app-project/files/9725103/Proforma.RU.1.pdf)

CIS countries: 
Armenia
Azerbaijan
Belarus
Kazakhstan
Kyrgyzstan
Republic of Moldova
Russian Federation
Tajikistan
Turkmenistan
Uzbekistan

We need to change an email with PI to a customer (agency)
EDO: Booking Invoice
We must send a new format of Proforma-Invoice
https://docs.google.com/document/d/1aL0ALuxTD3bhnVJDHN3bYrhQ7wzzXAevBqFWwCCTBcE/edit

HTML template: 
https://1drv.ms/u/s!ArAOjaIGLOwqir5WJoYo-gJTz4QbmQ?e=RPQJdx

- [x] #1760
- [x] #1761
- [x] #1762
- [x] #1763
- [x] #1764
- [x] #1769
- [x] #1770

**Comment by DenisVelinen** [comment]
The template has already been placed in SendGrid.
EDO: Booking Invoice (with attachment)
Template ID: d-5f634773ce2644248025d59b05357da2
