### ISSUE TITLE
Change field for sending data [Columbus]

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#176]
Current  implementation:

1. Get hotel information from API Columbus from field by method GetHotelDescriptiveInfo 
```
"HotelInfo": {
              "Descriptions": {
                "DescriptiveText":  
```

2. Send this information as parameter 'accommodationAmenities' in method 
`https://edo-dev.happytravel.com/en/api/1.0/accommodations/availabilities/searches/5265ae09-f8e1-409b-a633-91033ef48d0b/results/81ee91ef-5193-45bb-ae6d-b13e527eacc2/accommodation`

**AR**: This doesn't allow information to be displayed correctly on UI:

![Screenshot 2021-04-30 at 07 21 36](https://user-images.githubusercontent.com/38030865/116678324-d99a3680-a9b1-11eb-8dc6-15a9761d64c2.png)

**ER**: Send this information as parameter 'additionalInfo' in method 
`https://edo-dev.happytravel.com/en/api/1.0/accommodations/availabilities/searches/5265ae09-f8e1-409b-a633-91033ef48d0b/results/81ee91ef-5193-45bb-ae6d-b13e527eacc2/accommodation`

**Comment by sergeyf-QA** [comment]
@AlexeyShok 
GetHotelDescriptiveInfo returns for 000526 hotel HILTON DUBAI JUMEIRAH
   "HotelInfo": {
              "Descriptions": {
                "DescriptiveText": "hotel text"
                
However, additionalInfo in https://edo-dev.happytravel.com/en/api/1.0/accommodations/availabilities/searches/1a1300ea-4623-4cef-b9e9-54e27a33dcf0/results/db6f30f3-6db5-410b-9a63-4ef8095f58d1/accommodation for this hotel is empty.

**Comment by sergeyf-QA** [comment]
**Summary:**
info from DescriptiveText is in textualDescriptions
e.g. for 000526 hotel HILTON DUBAI JUMEIRAH
"HotelInfo": {
"Descriptions": {
"DescriptiveText": "hotel text"

is in textualDescriptions: [{description: "hotel text", type: "General"}]

**OK on DEV.**
