### ISSUE TITLE
Need to add chain CRUD operations in takato

### ISSUE THREAD

**Issue by DFSko** [happy-travel/agent-app-project#1765]
Need to add supporting CRUD operations for chains in takato
![image](https://user-images.githubusercontent.com/811811/188117951-ae162deb-c1b6-453a-ae9c-e593a343e51f.png)

**Comment by alexander-plekhanov** [comment]
Front finished. Have an issue in API on PUT method (unable to edit).

**Comment by sergeyf-QA** [comment]
**Summary:**
- front-end for chains is done well https://pms-dev.happytravel.com/chain
- the issue about PUT method is pointed several weeks ago in https://github.com/happy-travel/agent-app-project/issues/1750

**OK on DEV.**
