### ISSUE TITLE
Add 2 new roles to view and edit bookings & view bookings only

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1766]
Need to add a 2 roles to view only and to view and edit bookings. An agent with this role can search, view, pay by card, and cancel bookings. But cannot make new bookings. You need to separate permissions to work with bookings and add a new role by migration.
- [x] #1767
- [x] #1768

**Comment by sergeyf-QA** [comment]
**Summary:**
- added two new roles (**Agent view bookings** and
**Agent view&edit bookings**) into the agent app
- added new **ViewAgencyBookings** permission to all roles
- **Agent view bookings** role has such permissions
AccommodationAvailabilitySearch, ObserveBalance, ViewAgencyBookings, ViewBooking
- **Agent view&edit bookings** role has such permissions
AccommodationAvailabilitySearch, ObserveBalance, AgencyBookingsManagement, ViewAgencyBookings, ModifyBooking, ViewBooking, BookingDocuments
- **Sales agent** role was updated and have
AccommodationAvailabilitySearch, AccommodationBooking, AgencyBookingsManagement, ApiConnectionManagement, ViewAgencyBookings, CreateBooking, ModifyBooking, ViewBooking, BookingDocuments


**OK on DEV.**
