### ISSUE TITLE
Add new roles and permissions for view and edit booking

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1767]
You need to add two roles to the agent application. One role only allows you to search and view existing bookings in the agency. The second role allows you to search, view existing bookings, update their status, pay for them, and cancel them.

To do this, you need to divide the existing AccommodationBooking permision into three permisions: CreateBooking, ModifyBooking, ViewBooking and BookingDocuments. Sales Agent has all four of these permissions. Agent View&Edit Booking has ModifyBooking and ViewBooking permissions. Agent View Only Booking has only ViewBooking permission.

An adjustment is also needed for the Sales Agent role. The Sales Agent must be able to view bookings made by other agents in the agency. Sales Agent should be able to change (update status, delete, pay) bookings made by other agents of the agency.

**Comment by sergeyf-QA** [comment]
@timur-mut 
1) **Agent view&edit bookings**  
GET https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/6064/supporting-documents/invoice
and
POST https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/6064/cancel
return 403

2) **Agent view bookings** 
GET https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/refcode/DEV-HTL-AE-000GZ6-01
returns {"status":400,"detail":"Permission denied"}

**Comment by sergeyf-QA** [comment]
**Summary:**
- added two new roles (**Agent view bookings** and
**Agent view&edit bookings**) into the agent app
- added new **ViewAgencyBookings** permission to all roles
- **Agent view bookings** role has such permissions
AccommodationAvailabilitySearch, ObserveBalance, ViewAgencyBookings, ViewBooking
- **Agent view&edit bookings** role has such permissions
AccommodationAvailabilitySearch, ObserveBalance, AgencyBookingsManagement, ViewAgencyBookings, ModifyBooking, ViewBooking, BookingDocuments
- **Sales agent** role was updated and have
AccommodationAvailabilitySearch, AccommodationBooking, AgencyBookingsManagement, ApiConnectionManagement, ViewAgencyBookings, CreateBooking, ModifyBooking, ViewBooking, BookingDocuments


**OK on DEV.**
