### ISSUE TITLE
Add use of permission to view and edit bookings to the agent application

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1768]
Endpoints:
![Bookings1](https://user-images.githubusercontent.com/23557836/191262414-ca760b7f-52ae-46bd-b1b0-31c281357a57.png)
![Bookings2](https://user-images.githubusercontent.com/23557836/191262749-5edf5687-8077-4c07-acf9-8067a76646df.png)

![BookingSupportingDocuments](https://user-images.githubusercontent.com/23557836/191261811-a7ea5b26-b045-4ca0-90a4-0f8c5124c476.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- added two new roles (**Agent view bookings** and
**Agent view&edit bookings**) into the agent app
- added new **ViewAgencyBookings** permission to all roles
- **Agent view bookings** role has such permissions
AccommodationAvailabilitySearch, ObserveBalance, ViewAgencyBookings, ViewBooking
- **Agent view&edit bookings** role has such permissions
AccommodationAvailabilitySearch, ObserveBalance, AgencyBookingsManagement, ViewAgencyBookings, ModifyBooking, ViewBooking, BookingDocuments
- **Sales agent** role was updated and have
AccommodationAvailabilitySearch, AccommodationBooking, AgencyBookingsManagement, ApiConnectionManagement, ViewAgencyBookings, CreateBooking, ModifyBooking, ViewBooking, BookingDocuments


**OK on DEV.**
