### ISSUE TITLE
Agency update doesn't work because the backend is waiting for the "Preferred Payment Method" value, but there is no way to specify it at the UI

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#1780]
On https://manage-dev.happytravel.com/

**Steps.**
1. Login any admin;
2. Go to the Agencies of menu items;
3. Open browser’s dev. tools;
4. Go into any Agency;
5. Go to the Details tab, make any changes, and try to save it.

**Result.**
Agency update doesn't work because the backend is waiting for the "Preferred Payment Method" value, but there is no way to specify it at the UI
PUT
https://edo-dev.happytravel.com/en/api/1.0/admin/agencies/{agencyId}
Response body
```
{
    "status": 400,
    "detail": "'Preferred Payment Method' must not be empty."
}
```

**Expected.**
Saving agency data works without errors and all entered data is saved.

![Image](https://user-images.githubusercontent.com/17127277/188641597-6f7196ee-45f4-41a1-ac45-3d3d5b16836a.png)

**Comment by ViTsvetkova** [comment]
@AlexeyShok @DenisVelinen Is this field mandatory on backend?

**Comment by DenisVelinen** [comment]
Changing agency details works without requesting a Preferred Payment Method.
