### ISSUE TITLE
Add non refundable setting to rate plan type

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1789]

**Comment by sergeyf-QA** [comment]
**Summary:**
- "isNonRefundable" is added to 
GET https://komoro-dev.happytravel.com/api/1.0/rate-plan-types
POST https://komoro-dev.happytravel.com/api/1.0/rate-plan-types
PUT https://komoro-dev.happytravel.com/api/1.0/rate-plan-types/{typeId}

**OK on DEV.**
