### ISSUE TITLE
Add the exchange rate commission to Edo

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1794]
We need to add a commission of 3% for contracts when we get the price from the hotel/supplier and send it to the customer, not in the same currencies (beside of AED-USD, because for AED-USD, USD-AED we have a FIX rate). 
Example:
Accor Hotel sends us a price in EUR, after that, we use APILayer software to convert this price into USD, but in this case, we don't cover the exchange rate difference.

For such reservations, we need to add 3% to the final price, which showed in EUR.

**Comment by DFSko** [comment]
Edo already has default commission of 5% for all currency pairs, except pairs specified in consul (USD-AED, AED-USD for now)

**Comment by ViTsvetkova** [comment]
> Edo already has default commission of 5% for all currency pairs, except pairs specified in consul (USD-AED, AED-USD for now)

We need 3%, not 5%
check this please

**Comment by DFSko** [comment]
updated currency conversion buffer

https://github.com/happy-travel/currency-converter/pull/21
https://github.com/happy-travel/edo/pull/2176

**Comment by nikolaeva31** [comment]
1. There is no commission for currency `AED`.
2. Commission value is 3%, for example:
Supplier's cost = 10 euro
Rate - `EUR <> USD - 2022-09-13 23:51:38.438 +0300`	= **0.997059**

Then **our final cost = 10x(0.997059 + 3%) + 2%_(Agency markup)_ + 2% _(Bank fee)_ = 10,6846038911** 

![Image](https://user-images.githubusercontent.com/38030865/190014721-ac0a5d92-a13e-43c9-80f9-71146bfbfaa9.png)
