### ISSUE TITLE
Bookings in Discarded status have Pay Now by Card..., Invoice, Cancel... buttons.

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#1805]
On https://dev.happytravel.com/

**Steps.**
1. Login any agent;
2. Go to the Bookings page;
3. Go to any booking in Discarded status;
4. Pay attention to the buttons under the general booking information.

**Result.**
Bookings in Discarded status have Pay Now by Card..., Invoice, Cancel... buttons (see pic,).

![Image](https://user-images.githubusercontent.com/17127277/190133694-a2c737dc-9dc4-4887-8883-3b8604ac0a95.png)

**Expected.**
The Discarded booking status means that the booking has not been with the supplier and it has simply been cancelled in our system, so it cannot be paid by bank card, once again it is cancelled and it is unclear whether an invoice is needed for such a booking at all.

**Comment by ViTsvetkova** [comment]
@alexander-plekhanov the cancel booking button left on UI
![image](https://user-images.githubusercontent.com/90184684/191471188-2061e6a7-d47d-4177-97cc-258f388ce6e4.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- now Discarded bookings have no buttons
![image](https://user-images.githubusercontent.com/74529212/191735242-f6f41ee5-9761-4969-a56d-07090b82144a.png)



**OK on DEV.**
