### ISSUE TITLE
Remove an ability to delete previously selected currencies in agency settings

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#1808]
On https://manage-dev.happytravel.com/

**Steps.**
1. Login any admin;
2. Go to the Agencies page;
3. Go to any agency;
4. Go to Settings tab;
5. Add different currencies to the “Available Currencies” field and save it (click by the “Save Availability Search Settings” button);
6. Try deleting previously added currencies.

**Result.**
The server sends a message that previously added currencies cannot be deleted.
PUT https://edo-dev.happytravel.com/en/api/1.0/admin/agencies/1297/system-settings/availability-search
```
{
  "status": 400,
  "detail": "Request's availability currencies have to contain all the following elements: USD, EUR, AED"
}

```
**Expected.**
Remove the ability to delete previously selected currencies in agency settings as this is a business condition and not allowed in the backend.

**Comment by alexander-plekhanov** [comment]
Tried to fix it. Unfortunately it will take a lot of time. Seems for me like backend validation is enough. I'll set this the lowest priority.

**Comment by alexander-plekhanov** [comment]
moved

**Comment by wnlstk** [comment]
https://track.happytravel.tech/issue/HP-628/Ueda-Minor-Remove-an-ability-to-delete-previously-selected-currencies-in-agency-settings
