### ISSUE TITLE
Fix methods and use them in the admin panel 

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#181]
**Backend**:
1. Methods _Activate agency_ and _Deactivate agency_ return 415 error. 
```
{{ edo.baseUrl }}/en/api/1.0/admin/agencies/890/activate
{{ edo.baseUrl }}/en/api/1.0/admin/agencies/890/deactivate
```

**_AR_**: 
```
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
  "title": "Internal Server Error",
  "status": 415,
  "instance": "/en/api/1.0/admin/agencies/890/deactivate",
  "spanId": "7429cb45c4852444",
  "traceId": "6868b0d863d74543bec1d4b95d35618c",
  "requestId": "0HM8CGA3TG2JA:00000002"
}

```

**Frontend**:
Use these methods in the admin panel. 

**_AR_**: 
<img width="1440" alt="Screenshot 2021-05-05 at 15 11 20" src="https://user-images.githubusercontent.com/38030865/117138984-611de600-adb4-11eb-9cb3-c0e85c2c5002.png">

**Comment by Raibo** [comment]
I can't reproduce the issue. The agency 851 deactivated and activated without issues, if the reason was provided. If the reason was not provided, correct 400 "Reason must be provided" error returned.

Any details on how to reproduce?

**Comment by sergeyf-QA** [comment]
**Summary:**
confirm that issue is not reproduced on dev with any agency
