### ISSUE TITLE
New feature: Reservations (Booking manager) can add an agency without registration process

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1812]
Admins can add ("register') an agency without a registration process.

This feature requires adding an agency name to an invoice when the Reservation team books through HT system for them.
These agencies can't use the Agent app for Accommodation search or booking. 
These agencies will be just like an object to select to an invoice.

What we need to keep in an agency card: 
- Agency name (mandatory)
- Agency TRN (if they are in UAE)
- Agency VAT
- Agency Address (City, Country)
- Agency email
- Agency Phone
- Contact name
- Billing Email (mandatory)

For such Agencies, we don't need verification via email. If the Agency decides to make registration - we can't provide the credentials for the current account, they will need to create a new one. 

We should add the possibility to deactivate such Agencies. 

Who can register such agencies: Account manager, Booking manager

- [x] #1873
- [x] #1874
- [x] #1889
- [x] #1898

**Comment by sergeyf-QA** [comment]
**Summary:**
- page for new agency creation w/o registration https://manage-dev.happytravel.com/agency/create is added
- Super-admin, Account manager and Booking manager can register such agencies
- it is possible to activate/deactivate such agencies

**OK on DEV.**
