### ISSUE TITLE
The list of agency accounts shows incorrect currency symbols

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#1813]
On https://manage-dev.happytravel.com/

**Steps.**
1. Login any admin;
2. Go to the Agencies page;
3. Go to agency with id 770 (use to the ID field for search);
4. Go to Balance tab;
5. Open the list of accounts (drop-down list in the Account field);
6. Note the currency markings on the accounts.

**Result.**
The list of agency accounts shows incorrect currency symbols, in the "Balance" tab, in the drop-down list in the Account field (see pic.)

![Image](https://user-images.githubusercontent.com/17127277/190190287-8f110f3c-4284-49a5-8a14-750e894b8d97.png)

GET https://edo-dev.happytravel.com/en/api/1.0/admin/agencies/770/accounts
```
[
  {
    "id": 474,
    "currency": "AED",
    "balance": {
      "amount": 0.0,
      "currency": "AED"
    },
    "created": "2022-09-14T14:50:26.741676",
    "isActive": true
  },
  {
    "id": 7,
    "currency": "USD",
    "balance": {
      "amount": 10000.0000,
      "currency": "USD"
    },
    "created": "2019-12-26T12:07:35.953986",
    "isActive": true
  },
  {
    "id": 453,
    "currency": "EUR",
    "balance": {
      "amount": 0.0,
      "currency": "EUR"
    },
    "created": "2022-09-13T07:38:18.99979",
    "isActive": true
  },
  {
    "id": 472,
    "currency": "GBP",
    "balance": {
      "amount": 0.0,
      "currency": "GBP"
    },
    "created": "2022-09-14T14:50:26.427019",
    "isActive": true
  },
  {
    "id": 473,
    "currency": "CNY",
    "balance": {
      "amount": 0.0,
      "currency": "CNY"
    },
    "created": "2022-09-14T14:50:26.585168",
    "isActive": true
  }
]
```

**Expected.**
In the list of accounts, the currency symbol should correspond to the currency type.

**Comment by sergeyf-QA** [comment]
**Summary:**
- list of agency accounts is shown correctly
![image](https://user-images.githubusercontent.com/74529212/190960228-1a782e57-52fa-435a-b893-ec4c430893fd.png)

**OK on DEV.**
