### ISSUE TITLE
Set the Currency value according to the selected Account in the balance sheet management form

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#1814]
One agency can have several accounts, each in a different currency. In the balance management form, it is necessary to select a specific Account and Currency, but if the selected currency doesn't correspond to the selected account, the server won't allow such a transaction and will send a "Account and payment currency mismatch" message.
For example,
POST https://edo-dev.happytravel.com/en/api/1.0/admin/agency-accounts/474/replenish
```
{
  "status": 400,
  "detail": "Account and payment currency mismatch"
}
```
**Needs to set the Currency value according to the selected Account in the balance sheet management form.**
![fDO6Gr2BJe](https://user-images.githubusercontent.com/17127277/190202875-1d1ec619-8274-4bf5-9ec3-03e53b8eaafb.png)

**Comment by DenisVelinen** [comment]
On https://manage-dev.happytravel.com/

**Steps.**
1. Login any admin;
2. Go to the Agencies page;
3. Go to agency with id 770 (use to the ID field for search);
4. Go to Balance tab;
5. Take turns selecting the different accounts of this agency;
6. Note the currency markings on the Currency field.

**Expected.**
In the Currency field, the currency should correspond to the selected account.

**Comment by sergeyf-QA** [comment]
**Summary:**
- now a currency is in Account field so there is no an opportunity to make a mismatch
![image](https://user-images.githubusercontent.com/74529212/197463824-9cc34be5-5ca5-45eb-b7de-ae49f6e8e95e.png)


**OK on DEV.**
