### ISSUE TITLE
Add additional passenger cost dependency on MealPlan

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1818]

**Comment by wnlstk** [comment]
on dev

1.When booking "1 adult+1 child" the total cost is different from booking "2 adults". But the price should not be different.


How to reproduce:
first booking data:
- Armani Hotel Dubai, Dubai, The United Arab Emirates
- oct 28-oct 30
- 1 adult+1 child
- Armani Deluxe Room (Standard Room Only)

Total Cost 239,98 $


second booking data:
- Armani Hotel Dubai, Dubai, The United Arab Emirates
- oct 28-oct 30
- 2 adult
- Armani Deluxe Room (Standard Room Only)

Total Cost 179,98 $


Expected result:
first and second total cost are similar

Actual result:
first and second total cost are diffirent

2.When booking "3 adults" the total cost is wrong.


How to reproduce:
first booking data:
- Armani Hotel Dubai, Dubai, The United Arab Emirates
- oct 28-oct 30
- 2 adult
- Armani Fountain Suite (Standard Bed & Breakfast)

Total Cost 299,98 $


second booking data:
- Armani Hotel Dubai, Dubai, The United Arab Emirates
- oct 28-oct 30
- 3 adult

Total Cost 899,98 $

Expected result:
first and second total cost are similar

Actual result:
first and second total cost are diffirent

**Comment by AlexeyShok** [comment]
Fixed

**Comment by wnlstk** [comment]
ok on dev
