### ISSUE TITLE
Implementation of receiving confirmation of receipt of a message and its reading by the user.

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#182]
Need to implement of receiving confirmations from the agent application and the administration panel about receiving a message and reading it by the user. This information should be stored in the database in the Notifications table.

**Comment by sergeyf-QA** [comment]
@AlexeyShok 

when an agent registration  is completed then record in Notifications table appears about that (RegularCustomerSuccessfulRegistration = 13), but this record (Id=658) has wrong email in SendingSettings column: {"Email": {"emails": ["fabirs20@yopmail.com"], "templateId": "d-92c515648e9a406ba7232c206a29512f"},"WebSocket": {}}
**Expected:**
fabirs80@yopmail.com

the same email is when I receive ChildAgencySuccessfulRegistration = 14 notification (Id=659), though this agent/agency was registered for fabirs81@yopmail.com

**Comment by sergeyf-QA** [comment]
**Summary:**
status of receiving or reading the message is changing in Notifications table while sending these statuses from front-end.

**OK on DEV.**
