### ISSUE TITLE
Change the logic for setting the list of available agency currencies

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1825]

**Comment by sergeyf-QA** [comment]
**Summary:**
- creditLimits was renamed to availableCurrenciesWithCreditLimits in PUT /{culture}/api/{v}/admin/agencies/{agencyId}/contract-kind
- availableCurrencies was removed from PUT /{culture}/api/{v}/admin/agencies/{agencyId}/system-settings/availability-search and GET /{culture}/api/{v}/admin/agencies/{agencyId}/system-settings/availability-search
- during contractKind changing to VirtualAccountOrCreditCard there will be created new currency accounts of pointed currencies
- all pointed endpoints work well 

**OK on DEV.**
