### ISSUE TITLE
Add new special permission for booking discounts

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1829]

**Comment by DaniyarAskarov** [comment]
Check if new admin role with permission AdditionalMarkupManagement was created

**Comment by sergeyf-QA** [comment]
**Summary:**
- "Additional Markup Manager" admin role is created
![image](https://user-images.githubusercontent.com/74529212/192492674-c82f9557-f513-4869-8826-740ea0d579a3.png)


**OK on DEV.**
