### ISSUE TITLE
Add new agent markup for Global

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1830]

**Comment by DaniyarAskarov** [comment]
PR: https://github.com/happy-travel/edo/pull/2224
Insomnia: Edo -> Admin -> Markups -> Agents Markups

Endpoints for manage agent markups were added. Kind of markups: Global, Country, Market.

**Comment by sergeyf-QA** [comment]
Done in https://github.com/happy-travel/agent-app-project/issues/1833
