### ISSUE TITLE
Add endpoint for set agent markups

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1833]

**Comment by DaniyarAskarov** [comment]
PR: https://github.com/happy-travel/edo/pull/2224
Insomnia: Edo -> Admin -> Markups -> Agents Markups

Endpoints for manage agent markups were added. Kind of markups: Global, Country, Market.

**Comment by sergeyf-QA** [comment]
**Summary:**
- CRUD /{culture}/api/{v}/admin/agent-markups endpoints work fine
- it is possible to add markup only to an agency which is pointed in Vault in EDO
- it is possible to add markups for Global, Country, Market destination scope types

**OK on DEV.**
