### ISSUE TITLE
Add the ability to set markups by agent in the admin panel

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1834]
The feature: manual amendment to the mark up (discount only) on the Admin Panel for 1-2 people (security).

An admin (X) with special permission (AdditionalMarkupManagement) can create an agent markup (discount) for a destination:

X admin creates markup for Y agent (of the Happy Travel agency) for a Country 

X admin has to set up how many bookings can be created with this markup.

Should think about special permission for this markup only, markup change history and notifications.

Have to check the final booking price. The new booking price mustn't be less than the supplier's price. The final amount of markup couldn't be below ZERO.

Insomnia: Edo -> Admin -> Markups -> Agents Markups

Endpoints for manage agent markups were added. Kind of markups: Global, Country, Market.

**Comment by alexander-plekhanov** [comment]
First iteration is ready.

**Comment by sergeyf-QA** [comment]
Blocked until https://github.com/happy-travel/agent-app-project/issues/1890 be fixed

**Comment by sergeyf-QA** [comment]
**Summary:**
- it is possible to add agent markup on the https://manage-dev.happytravel.com/markups/agent-markups/create
- it is possible to add discount there
- in case discount > other markups then sum of all markups become 0
- agents markups are applied well

**OK on DEV.**
