### ISSUE TITLE
Add 'ReceiveBookingSummary' permission to an agent roles

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1838]
@AlexeyShok 
it is necessary to add 'ReceiveBookingSummary' permission to some agent roles because now it is impossible to send internal summary reports to agents.
This permission is required 
![image](https://user-images.githubusercontent.com/74529212/191471880-7d9ddc27-a127-4557-9e8c-0a03e26d78d1.png)

**Comment by AlexeyShok** [comment]
Agent roles: Agency administrator, Auditor, Accounts manager.
