### ISSUE TITLE
Endpoint for viewing the history of messages sent to the admin

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#184]
It is necessary to implement an endpoint to view the history of messages sent to the admin through the Notification Center.

**Comment by sergeyf-QA** [comment]
@AlexeyShok 
GET /{culture}/api/{v}/admin/notifications returns 
"message": {
      "rootElement": {
        "valueKind": "Object"
      }
      
though in DB

{"status": 3, "bookingId": 2810, "changeTime": "2021-05-04T07:53:06.5671995Z", "checkInDate": "2021-04-22T00:00:00", "checkOutDate": "2021-04-23T00:00:00", "referenceCode": "HTL-NL-000R24-01", "accommodationName": "Hotel B And B Erve Bruggert", "accommodationPhoto": null}

**Comment by sergeyf-QA** [comment]
**Summary:**
GET /{culture}/api/{v}/admin/notifications returns notifications from Notifications DB table for current admins

**OK on DEV.**
