### ISSUE TITLE
Add an endpoint to get a list of available currencies

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1841]
Added new endpoint GET api/{v:apiVersion}/currencies

**Comment by sergeyf-QA** [comment]
**Summary:**
- GET https://komoro-dev.happytravel.com/api/1.0/currencies returns
[
	"NotSpecified",
	"USD",
	"EUR",
	"AED",
	"SAR",
	"CNY",
	"GBP",
	"BHD",
	"THB",
	"KWD",
	"RUB",
	"CHF",
	"JPY",
	"AUD",
	"CAD",
	"CNH",
	"HKD",
	"NZD",
	"OMR"
]

**OK on DEV.**
