### ISSUE TITLE
Create a report of pending bookings

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1843]
Need to get all information about all pending bookings since Jan 2022.
Ref code, supplier name, date and time of creation, date and time of pending status, date and time of next status (if it possible)

**Comment by sergeyf-QA** [comment]
**Summary:**
- report of pending bookings is created https://metabase.happytravel.tech/dashboard/5-bookings-pending-history?date_filter=past12months


**OK on DEV.**
