### ISSUE TITLE
Remove unused properties from Room

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1844]
Need to remove unused properties ExtraAdultSupplement, ChildSupplement and InfantSupplement from Room model and Rooms database table

**Comment by sergeyf-QA** [comment]
**Summary:**
- ExtraAdultSupplement, ChildSupplement and InfantSupplement are removed from Rooms table
- ExtraAdultSupplement, ChildSupplement and InfantSupplement are removed from Rooms property

**OK on DEV.**
