### ISSUE TITLE
Restore the default MealPlan for the room and add its default value to the rate plan

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1845]

**Comment by sergeyf-QA** [comment]
**Summary:**
```
"standardMealPlan": {
    "id": 0,
    "name": "string"
  }
```
is added  to the Rooms endpoints.
In case ratePlans has
"mealPlan": 
{
"id": 51,
"name": "Default"
}
then during calculation living cost of additional adults or children is added cost according to "standardMealPlan"


**OK on DEV.**
