### ISSUE TITLE
500 error at supplements endpoint creation

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1846]
**How to reproduce:**
- goto any room e.g. https://pms-dev.happytravel.com/property/107/room/386
- click 'Add supplements' button
- click 'Save supplements' button

**Expected result:**
- no error, supplements are saved

**Actual result:**
- POST https://komoro-dev.happytravel.com/api/1.0/properties/107/rooms/386/supplements returns 500 error

`{"type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","title":"Internal Server Error","status":500,"detail":"An error occurred while saving the entity changes. See the inner exception for details.","instance":"/api/1.0/properties/107/rooms/386/supplements","spanId":"e139d5b35545e566","traceId":"228b9b1704056aa56811604505c91162","requestId":"0HMKSPKKV6KDH:00000005","x-request-id":[],"StackTrace":"   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable\u00601 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable\u00601 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable\u00601 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList\u00601 entriesToSave, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.\u003C\u003Ec__DisplayClass33_0\u00602.\u003C\u003CExecuteAsync\u003Eb__0\u003Ed.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func\u00604 operation, Func\u00604 verifySucceeded, TState state, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func\u00604 operation, Func\u00604 verifySucceeded, TState state, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func\u00604 operation, Func\u00604 verifySucceeded, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\n   at HappyTravel.Komoro.Api.Services.Statics.SupplementService.\u003C\u003Ec__DisplayClass2_0.\u003C\u003CAdd\u003Eg__Add|1\u003Ed.MoveNext() in /src/HappyTravel.Komoro.Api/Services/Statics/SupplementService.cs:line 75\n--- End of stack trace from previous location ---\n   at CSharpFunctionalExtensions.AsyncResultExtensionsBothOperands.Tap(Task\u00601 resultTask, Func\u00601 func)\n   at HappyTravel.Komoro.Api.Services.Statics.SupplementService.Add(Int32 propertyId, Int32 roomId, Supplement apiSupplement, CancellationToken cancellationToken) in /src/HappyTravel.Komoro.Api/Services/Statics/SupplementService.cs:line 48\n   at HappyTravel.Komoro.Api.AdminAppControllers.SupplementController.Add(Int32 propertyId, Int32 roomId, Supplement supplement, CancellationToken cancellationToken) in /src/HappyTravel.Komoro.Api/AdminAppControllers/SupplementController.cs:line 48\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeActionMethodAsync\u003Eg__Logged|12_1(ControllerActionInvoker invoker)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeNextActionFilterAsync\u003Eg__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeInnerFilterAsync\u003Eg__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"}`

**Comment by AlexeyShok** [comment]
Checked on https://pms-dev.happytravel.com/property/8/room/23 Adding passed without errors.

**Comment by AlexeyShok** [comment]
Checked on https://pms-dev.happytravel.com/property/107/room/386 Adding passed without errors. Please provide a more detailed description of the situation in which the 500 error occurs.

**Comment by sergeyf-QA** [comment]
@AlexeyShok 
I have updated description, the issue appears when I try to send empty supplements in request body

**Comment by sergeyf-QA** [comment]
**Summary:**
- https://komoro-dev.happytravel.com/api/1.0/properties/107/rooms/386/supplements returns 
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"Bad Request","status":400,"detail":"\u0027Meal Plan Id\u0027 must not be empty.","instance":"/api/1.0/properties/107/rooms/386/supplements","spanId":"37511a87c7940d03","traceId":"8e1bda5b0675e826b42b10a1ee199e89","requestId":"0HMLAH5AO74FD:00000003"}

**OK on DEV.**
