### ISSUE TITLE
Add CreditLimitRunOutBalance notification for admins

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1847]
Need to add funds on the balance decrease below thresholds notification to admins (its number in SendGrid: d-83eb602eb17548178854fb0fea5c7617)
Admins which should receive this notification: a booking manager, finance manager, chief finance manager, account manager.

**Comment by sergeyf-QA** [comment]
@DaniyarAskarov 
CreditLimitRunOutBalance notification is not send to admins with booking manager, finance manager, chief finance manager, account manager roles, could you investigate, why and fix the problem please?
Thank you.

**Comment by DaniyarAskarov** [comment]
Fixed!

**Comment by sergeyf-QA** [comment]
**Summary:**
- CreditLimitRunOutBalance notification is sent to **booking manager, finance manager, chief finance manager, account manager** roles
- also work with different currencies limits

**OK on DEV.**
