### ISSUE TITLE
Add GET /admin/account-managers method to ViewAgencies permission

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#1848]
On https://manage-dev.happytravel.com/

1. Authorise an agent with the role of Chief Finance Manager (e.g. https://passbolt.happytravel.com/app/passwords/view/9b1672fa-624f-40c4-b75c-c359e53655d1);
2. Go to Agencies.

**Result.**
A "Sorry, you don`t have enough permissions" message is shown in the UI. 
A method to get the account managers list needed to fill out the ACCOUNT MANAGER field was requested and returned a 403 status response.
GET https://edo-dev.happytravel.com/en/api/1.0/admin/account-managers

For ACCOUNT MANAGER searches to work correctly, the GET /admin/account-managers method must be in the ViewAgencies perminssion.

**Comment by sergeyf-QA** [comment]
**Summary:**
- now, when I log as Chief Finance Manager admin there is no "Sorry, you don`t have enough permissions" message on Agencies page because GET /admin/account-managers method returns 200 response

**OK on DEV.**
