### ISSUE TITLE
Add a usage counter to the markup by agent

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1849]
The administrator sets the number of times the markup is applied. At the end of the booking creation flow, the counter is decremented by one. When the value 0 is reached, the markup is deactivated. Provide entries in the log for changing markups of all events: creating a markup, decreasing the counter by 1 with remembering the reference code of the reservation where it was applied, deactivating the markup when the counter is reset.

**Comment by ViTsvetkova** [comment]
https://track.happytravel.tech/issue/HP-544/Add-a-usage-counter-to-the-markup-by-agent
