### ISSUE TITLE
Add documentation for AccommodationBookingSettings

### ISSUE THREAD

**Issue by Raibo** [happy-travel/agent-app-project#185]

**Comment by Raibo** [comment]
### What are these setting for
This settings control accommodation search and booking. They are different for each agent, agency and counterparty.
The instance contains following settings:

- `EnabledConnectors`. When searching, only results from this connectors will be seen to the user.
- `PassedDeadlineOffersMode`. The user only see bookings with passed deadline date if this setting is set to `true`.
- `AprMode`. Tells whether the user can see and whether they can buy bookings with _advanced purchase flag_.
- `IsMarkupDisabled`. Markups will not be applied to booking costs if this setting is set to `true`.
- `IsSupplierVisible`. The user will see suppliers in search UI if this setting is set to `true`.
- `CancellationPolicyProcessSettings`. Currently this tells how many days deadline dates are shifted towards the past for bookings.
- `IsDirectContractFlagVisible`. The user will see the _DirectContractFlag_ if this setting is set to `true`.
- `AdditionalSearchFilters`. Contains such flags as "AvailableOnly", "ExcludeNonRefundable", "DirectContractsOnly", etc. This flags will cut bookings that does not meet the requirements. This is bit mask enum, so multiple flags may be set simultaneously, in which case bookings will be checked against every flag in this setting.

### Where are this settings stored
There are three places. `AgentSystemSettings`, `AgencySystemSettings` and `CounterpartySystemSettings`. If no source contains a value for a given setting, there may be a default value.

The only setting taken from `CounterpartySystemSettings` is `CancellationPolicyProcessSettings`. There is an option to override this with `AgentSystemSettings`'s value, but this should be used only as an exception.

Other settings are taken from `AgentSystemSettings` and `AgencySystemSettings`, both of which may or may not contain different values for the same setting. Therefore, they are merged together with priority to `AgentSystemSettings` for non-boolean settings and with conjunction (logic "or") for boolean settings.

### Details on how settings are merged
To simplify, all settings can be divided to following groups:

1.  With priority.
Settings are `EnabledConnectors`, `AprMode`, `PassedDeadlineOffersMode`.
Value is taken from the **first place** where the value is set for the setting in the following order: `AgentSystemSettings`, `AgencySystemSettings`, Default value.

2. Boolean.
Settings are `IsMarkupDisabled`, `IsSupplierVisible`, `IsDirectContractFlagVisible`.
If the setting is `true` in `AgentSystemSettings` or in `AgencySystemSettings`, then the value merges as `true`.
If both sources either have `false` value, of have no value, then the value merges as `false`.

3. Others
`AdditionalSearchFilters` are taken from `AgentSystemSettings`. If there is no value, then Default.
`CancellationPolicyProcessSettings` are meant to be taken from `CounterpartySystemSettings`, but if there is value for this setting in `AgencySystemSettings` (which is for exceptional cases only), then it will be taken instead.

**Comment by mingazhev** [comment]
1. PassedDeadlineOffersMode and APrMode are enums. Need to describe their available values
2. IsMarkupDisabled - may need to have additional warning. Like "all the markups are not applied, including global" and "need to be very careful with this setting".
3. AdditionalSearchFilters - it will be better to say that these filters apply to existing search filters during availability search. And it can be said that mostly it is used to add additional filter "DirectContractsOnly"

**Comment by Raibo** [comment]
Fixed
