### ISSUE TITLE
Juniper returns the error "XML seems to be incomplete or wrong" (Code: JP_SEARCH_BOOKDATE) from the search

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#1859]
On dev. environment (https://dev.happytravel.com/)
**Steps:**
1. Log in any agent in agent’s app;
2. Open browser’s dev. tools;
3. Do search with that parameters:

> Dubai, The United Arab Emirates
> Today till 3 days in future
> 1 adult
> Nationality: Jordan
> Residency: Saudi Arabia

For example,
```
{
    "checkInDate": "2022-09-29T00:00:00Z",
    "checkOutDate": "2022-10-02T00:00:00Z",
    "roomDetails": [
        {
            "adultsNumber": 1,
            "childrenNumber": 0
        }
    ],
    "nationality": "JO",
    "residency": "SA",
    "htIds": [
        "Locality_607184"
    ]
}
```
4. Found the GET /state response
For example GET https://edo-dev.happytravel.com/en/api/1.0/accommodations/availabilities/searches/f082d7fa-e891-4ba7-8d70-fea591e38c94/state
```
{
    "id": "f082d7fa-e891-4ba7-8d70-fea591e38c94",
    "taskState": "PartiallyCompleted",
    "resultCount": 0,
    "error": "Request to GetHotelAvailabilityInfo returned 'Error 105. Missing Param Error. CountryCode/InfoSource is not Present.'"
}
```
**Result:**
In example the Juniper supplier returns the error "XML seems to be incomplete or wrong" (Code: JP_SEARCH_BOOKDATE) from the search
```
{
    "id": "f082d7fa-e891-4ba7-8d70-fea591e38c94",
    "taskState": "PartiallyCompleted",
    "resultCount": 429,
    "error": "Code: `JP_SEARCH_BOOKDATE`, Text: ` XML seems to be incomplete or wrong. Reservation out of date`, Type: ``; Request to GetHotelAvailabilityInfo returned 'Error 105. Missing Param Error. CountryCode/InfoSource is not Present.'"
}
```

**Comment by nikolaeva31** [comment]
Error wasn't reproduced for 'Juniper' supplier
