### ISSUE TITLE
Add simple tabs to Counterparty and Agency pages

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#186]
Need to place each logical part to a separate tab for easier understanding, navigation and usage

**Comment by sergeyf-QA** [comment]
@cyberkarma 
1) on Agency page are no tabs
2) tabs on Counterparty pages are wrong imagened, could you please make them like we have tabs on Settings screen of the main app?

**Comment by sergeyf-QA** [comment]
@cyberkarma 
could you please on Counterparties and Agensies pages:
1) to make a grey line under tabs as full width screen?
2) to left align tabs to the other screen elements 

look at how these are realised on https://dev.happytravel.com/settings/child-agencies 
![Screenshot at May 28 14-10-19](https://user-images.githubusercontent.com/74529212/119975667-ce412780-bfbe-11eb-9870-b4441bad6162.png)

**Comment by cyberkarma** [comment]
![image](https://user-images.githubusercontent.com/46620536/120289465-c0e7ae00-c2da-11eb-902f-94ada33c8618.png)
Done

**Comment by sergeyf-QA** [comment]
**Summary:**
now there are tabs on Counterparties and Agencies pages

**OK on DEV.**
