### ISSUE TITLE
Add documentation for agent markups

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1860]

**Comment by DaniyarAskarov** [comment]
Main page with all markups(modified with agent markups): https://github.com/happy-travel/edo/wiki/Agencies-%5C-Markup-Policies
Page for specific restrictions/validations for agent markups: https://github.com/happy-travel/docs/wiki/Agent-Markup-Flow

**Comment by DaniyarAskarov** [comment]
@ViTsvetkova done

**Comment by ViTsvetkova** [comment]
https://github.com/happy-travel/edo/wiki/Agencies-%5C-Markup-Policies
1)What markups are?
Markup is a difference between a supplier and displayed prices. _Markup is counting %._

2) How do they work?
What a single markup does?
Any markup is usually meant to rise the displayed price but also can decrease it, acting like a discount.
The total sum of markups can't be less than zero. If it happened, the total sum automatically would be set to zero.
Markup can contain two kinds of value (percent, fix). But to date, only percent markups are available for applying to price - _remove. now we have only %._

3) Markup can apply to three important criteria, which variants describe different markups:
Location scope (Depends on the agency, which is a client) - Global, Market, Country, Locality, Agency, Agent
Destination scope (Depends on the hotel, which is booked)- Global, Market, Country, Locality, Accommodation
Supplier code (Depends on the supplier, which provides room sets) - This criteria involves calculation in markups' second level

4) How do they combine?
There will always be sum of different markup policies at a level, so they are combined together. Order doesn't matters. Only those markups which correspond to condition will apply to the total sum. Conditions are described by information about agency (client), hotel (destination) and supplier. There are two markup's applying levels. - please amend:

There are two kinds of markups:
- The first-level markup
- The second-level markup
All markups of the same level are combined with each other (sum).
The sum of the first level markups applies to the price from the Supplier.
The second-level markups apply to the "updated price with the first level markup".
The first level:
- Global markup
- Location markup for a specific Market
- Destination markup for a specific Market
- Agency destination markup for a specific Market
- Location markup for a specific Country
- Destination markup for a specific Country
- Agency destination markup for a specific Country. 
The second level contains Supplier destination markup for a specific Country. 

The second markup level applies to the total result after the first level calculates with a primary price.

ℹ️ For example: 
Primary price = $100
First markups' level = 10% (global 2% + Destination markup for a specific Market 4% +Agency destination markup for a specific Country)
Second markups' level = 50%
Total price after applying the first markups' level: (100 x 10) / 100 + 100 = $110
Then second markups' level applying to result of the previous stage: (110 x 50) / 100 + 110 = $165

According to the given parameters:
Agency with Id = 1, searching or booking accommodation in the country which from Market with Id = 2. 
There are markups which apply to this situation: #1, #2, #3. 
If the current agency's location was from Market = 3, Markup with Id = 5 would apply too. But in our case agency isn't from Market with Id = 3.
After all operations (4% + (-2%) + 1% = 3% extra). The final price is $103.

**Comment by DaniyarAskarov** [comment]
@ViTsvetkova done
