### ISSUE TITLE
Add a new dashboard for Invalid and Rejected bookings

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1861]
We need to monitor how many Invalid/Rejected bookings we have in the system.

We have to count such bookings for each supplier (add a filter for each API-Supplier)

All data could be in a table with the following columns:
API Supplier - %Invalid - % Rejected (% from all bookings with Invalid/Rejected status due to the chosen dates)

**Comment by ViTsvetkova** [comment]
@DFSko please add a column with total number of supplier bookings. + need to amend % data: we need to check % of all bookings

**Comment by sergeyf-QA** [comment]
**Summary:**
- https://metabase.happytravel.tech/dashboard/6-invalid-and-rejected-bookings?dates=past7weeks
![image](https://user-images.githubusercontent.com/74529212/193534563-4e823ca5-056c-4b1b-90f1-f0f779c052fc.png)


**OK on DEV.**
