### ISSUE TITLE
500 error when going to the 3rd search step

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1862]
**How to reproduce:**
- look for
Fairmont The Palm, Dubai, The United Arab Emirates (Accommodation_11064736)
dates in deadline
1 guest
RU-RU
- go to the 3rd search step

**Expected result:**
- no error

**Actual result:**
GET https://edo-dev.happytravel.com/en/api/1.0/accommodations/availabilities/searches/c67c4236-bd9e-4b50-9575-75da3ea40259/results/Accommodation_11064736/room-contract-sets/6d252301-bdec-4d26-832b-618c111090bc returns 
`{"type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","title":"Internal Server Error","status":500,"detail":"Status(StatusCode=\u0022Unknown\u0022, Detail=\u0022Exception was thrown by handler.\u0022)","instance":"/en/api/1.0/accommodations/availabilities/searches/c67c4236-bd9e-4b50-9575-75da3ea40259/results/Accommodation_11064736/room-contract-sets/6d252301-bdec-4d26-832b-618c111090bc","spanId":"51ecb1e62906a56b","traceId":"52c3ae2a6f604728adcdae4a5cdb58a7","requestId":"0HML2LM1QD8PQ:00000013","SearchId":"c67c4236-bd9e-4b50-9575-75da3ea40259","x-request-id":[],"StackTrace":"   at ProtoBuf.Grpc.Internal.Reshape.UnaryTaskAsyncImpl[TRequest,TResponse](AsyncUnaryCall\u00601 call, MetadataContext metadata, CancellationToken cancellationToken) in /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 560\n   at HappyTravel.Edo.Api.Services.Connectors.SupplierGrpcConnector.\u003C\u003Ec__DisplayClass3_0.\u003C\u003CGetExactAvailability\u003Eb__0\u003Ed.MoveNext() in /src/Api/Services/Connectors/SupplierGrpcConnector.cs:line 74\n--- End of stack trace from previous location ---\n   at HappyTravel.Edo.Api.Services.Connectors.SupplierGrpcConnector.ExecuteWithLogging[TResult](String step, Func\u00601 funcToExecute) in /src/Api/Services/Connectors/SupplierGrpcConnector.cs:line 163\n   at HappyTravel.Edo.Api.Services.Accommodations.Availability.Steps.BookingEvaluation.BookingEvaluationService.GetExactAvailability(Guid searchId, String htId, Guid roomContractSetId, String languageCode) in /src/Api/Services/Accommodations/Availability/Steps/BookingEvaluation/BookingEvaluationService.cs:line 300\n   at HappyTravel.Edo.Api.Controllers.AgentControllers.AvailabilitiesController.GetExactAvailability(Guid searchId, String htId, Guid roomContractSetId) in /src/Api/Controllers/AgentControllers/AvailabilitiesController.cs:line 188\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeActionMethodAsync\u003Eg__Logged|12_1(ControllerActionInvoker invoker)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeNextActionFilterAsync\u003Eg__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeInnerFilterAsync\u003Eg__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeNextResourceFilter\u003Eg__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilder.\u003C\u003Ec.\u003C\u003CBuildPipeline\u003Eb__8_0\u003Ed.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at HappyTravel.Edo.Api.Infrastructure.Middlewares.AgentRequestLoggingMiddleware.InvokeAsync(HttpContext context, IAgentContextInternal agentContextService) in /src/Api/Infrastructure/Middlewares/AgentRequestLoggingMiddleware.cs:line 39\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpRequestDurationMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpRequestCountMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpInProgressMiddleware.Invoke(HttpContext context)\n   at Sentry.AspNetCore.SentryTracingMiddleware.InvokeAsync(HttpContext context) in /_/src/Sentry.AspNetCore/SentryTracingMiddleware.cs:line 192\n   at Sentry.AspNetCore.SentryTracingMiddleware.InvokeAsync(HttpContext context) in /_/src/Sentry.AspNetCore/SentryTracingMiddleware.cs:line 192\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"}`

**Comment by AlexeyShok** [comment]
@sergeyf-QA Is this issue still relevant? I can't find more than one offer for this hotel from Columbus supplier (according to the specified HtId only this supplier, hotel code 000511)

**Comment by nikolaeva31** [comment]
There is no hotel on dev from Jumeirah
