### ISSUE TITLE
Remark for all Marriott properties

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1863]
Please check the below, we had this remark in the system for supplier IWTX - for all Marriott properties only
 
Now I don’t see this remark
 
**Breakfast & extra bed for extra person is chargeable**

https://happytravel.freshdesk.com/a/tickets/693

**Comment by nikolaeva31** [comment]
Duplicates https://track.happytravel.tech/issue/HP-70/Add-a-special-remark-for-the-Marriott-chain-from-Illusions-about-extra-charge-for-3rd-person-in-the-room
