### ISSUE TITLE
Add the opportunity to change the Payment Settings on a Subagency/Agent level

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1871]
Subagencies have to inherit the same contract kind as their root agency.

Payment settings:
Add the opportunity to change the Payment Settings on a Subagency/Agent level.
Description:
For VirtualAccountOrCreditCardPayments Contract Type the Payment Method should be chosen from CreditCard and CreditLimit + CreditCard.
For OfflineOrCreditCardPayments Contract Type, the Payment Method should be chosen from Offline + CreditCard.
For CreditCardPayments Contract Type, the Payment Method is CreditCard only and can’t be edited.

Default Settings for Payment Setting: Credit Card for all types of contracts

**Comment by DaniyarAskarov** [comment]
Test cases:
1) Create new root agency. Check if system settings and payment settings setted well.
2) Invite child agency. Check if contract kind and settings inherited well.
3) Invite agent to child agency. Check if payment settings inherited well.
4) Check if child agency's and child agent's payment settings can be updated restricted by root agency's payment settings
5) Check if payment settings affect to third search step (restricts allowed payment methods)
6) Check if root agencies contract kind change affects to child agencies and his agent's payment settings

**Comment by sergeyf-QA** [comment]
**Summary:**
- payment settings are inherited from root agency to a child one
- payment settings are inherited from root agency to an invited child agent
- when changing contract kind of the root agency payment settings are changed according to new contract kind
- existed agencies have right payment settings and search works well
- payment settings affect to third search step
- these endpoints work fine
PUT /{culture}/api/{v}/agency/child-agencies/{agencyId}/payment-settings
GET /{culture}/api/{v}/agency/child-agencies/{agencyId}/payment-settings
GET /{culture}/api/{v}/agency/current/payment-settings
PUT /{culture}/api/{v}/agency/agents/{agentId}/payment-settings
GET /{culture}/api/{v}/agency/agents/{agentId}/payment-settings
GET /{culture}/api/{v}/agency/agents/current/payment-settings


**OK on DEV.**

**Comment by DaniyarAskarov** [comment]
Reminder: Run endpoint to fulfill old agencies and agents payment settings

**Comment by DaniyarAskarov** [comment]
There was a bug after realise the following action was made: For a few agent's system settings were inherited from thier agency system settings. I attach a file with list of this agents. @mikheevaksenia ask for checking at least ten agent's settings to be ensure that they were inherited well. 
[Агенты для изменения.csv](https://github.com/happy-travel/agent-app-project/files/9901436/default.csv)
