### ISSUE TITLE
Add endpoint to add agency

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1873]
Admins can add ("register') an agency without a registration process.

This feature requires adding an agency name to an invoice when the Reservation team books through HT system for them.
These agencies can't use the Agent app for Accommodation search or booking.
These agencies will be just like an object to select to an invoice.

What we need to keep in an agency card:

Agency name (mandatory)
Agency TRN (if they are in UAE)
Agency VAT
Agency Address (City, Country)
Agency email
Agency Phone
Contact name
Billing Email (mandatory)
For such Agencies, we don't need verification via email. If the Agency decides to make registration - we can't provide the credentials for the current account, they will need to create a new one.

We should add the possibility to deactivate such Agencies.

Who can register such agencies: Account manager, Booking manager

**Comment by timur-mut** [comment]
new endpoint url - `edo.baseUrl`/en/api/1.0/admin/agencies/without-registration

**Comment by sergeyf-QA** [comment]
@timur-mut 
1) Allow to use this endpoint for booking manager too
2) Add **Agency email** and **Contact name** fields please

**Comment by sergeyf-QA** [comment]
**Summary:**
- now only Account manager may use this endpoint
- POST edo.baseUrl/en/api/1.0/admin/agencies/without-registration registrates an agency w/o registration
- Agency name, Billing Email, Legal Address and Agency Address are mandatory

**OK on DEV.**
