### ISSUE TITLE
Remove account creation in USD for all agencies at the ReadOnly verification stage

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1875]
Need to remove account creation in USD for all agencies at the ReadOnly verification stage

**Comment by DaniyarAskarov** [comment]
Test cases: 
 1) Create root agency and verify it to ReadOnly stage
 2) Check if virtual accounts weren't created
 3) Check if agency in ReadOnly stage works properly without accounts
 4) Check search stages

**Comment by sergeyf-QA** [comment]
**Summary:**
- virtual accounts weren't created for root agency in ReadOnly state
- search work well or such agencies

**OK on DEV.**
