### ISSUE TITLE
Markup summary table/dashboard

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1876]
We need to monitor all markups that we have in the system: Global, Destination, Locality, Agency, Agent, Market etc.
So please prepare a data that can show when and for whom a markup has been set or deleted.
It will be helpful if we can filter markups by a supplier, agency, locality, destination.

**Comment by DFSko** [comment]
done

**Comment by sergeyf-QA** [comment]
**Summary:**
- markups dashboard is implemented here https://metabase.happytravel.tech/dashboard/7-markups

**OK on DEV.**
