### ISSUE TITLE
Subagency registration | Tax registration number is mandatory

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1878]
**How to reproduce:**
- invite a subagency
- try to finish registration

**Expected result:**
- Tax registration number should be not mandatory field

**Actual result:**
- 'Get started' button is disabled
- it is possible to enable 'Get started' button in case of user puts Tax registration number and removes it

**Comment by nikolaeva31** [comment]
`TRN` field is required for different regions (for example, UAE)
<img width="539" alt="Screenshot 2022-10-30 at 21 10 52" src="https://user-images.githubusercontent.com/38030865/198894378-225abf8a-8a60-49d4-8d89-985ff561d474.png">
