### ISSUE TITLE
Add UI for getting and managing booking by reference code

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#188]
Need to use the endpoint from the following ticket:

https://github.com/happy-travel/agent-app-project/issues/187

How it should look like:
1. A separate button and page to find booking by reference code
2. When pressing a button (if booking found), booking should be shown. All the buttons to manage booking should be shown there

As for method, endpoints and results, please discuss with @Raibo

**Comment by sergeyf-QA** [comment]
@cyberkarma 
1) rename REF CODE to REFERENCE CODE
2) on https://manage-dev.happytravel.com/bookings set width of search field and search button to normal definitions, not the whole screen as it is now
3) on booking page 'Back' button does not work at all - perhaps it it better to remove it and add breadcrumbs?
4) 'Go over' button is not clickable except it 'Go over' text label
5) there is no booking reference code on booking page
6) Cancel, Discard, Manually Complete Payment, Confirm Payment don't work

**Comment by sergeyf-QA** [comment]
**Summary:**
- bookings may be found by REFERENCE CODE on https://manage-dev.happytravel.com/bookings
- on booking page all needed info from booking existed and Cancel, Discard, Manually Complete Payment, Confirm Payment buttons work well

**OK on DEV.**
