### ISSUE TITLE
Add Deadline approaching (Credit Limit Bookings) notifications to admins

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1884]
Add the Deadline approaching (Credit Limit Bookings) notification to admins (Booking manager, Finance manager)

Rules:

This notification should send only in the case when the booking amount is more than the amount on the current agency's virtual balance (should work for each currency for multi-currencies agencies).  

Notification should send
Before 7 days 
Before 3 days
Before 1 day

*We do not send the notifications fro Cancelled, Discarded, Rejected, Invalid bookings. 

Text for e-mail template:

Dear colleague,

We have not received payment for the booking (reference code {{referenceCode}}) from Agency Name  {{AgencyName}} with contract type - {{ContractType}} . The current balance of the credit limit of the agency is less than the booking amount. If the required payment is not received, the reservation will be auto-cancelled on {DeadlineDate}. Please, contact the Agent  {{AgentContact Details}}.

**Comment by DenisVelinen** [comment]
EDO: Deadline approaching (Admin)
Template ID: d-41d711e38da542f7b0630975a7a2a057

**Comment by ViTsvetkova** [comment]
@AlexeyShok Could you please add this notification to agents? 
email topic: Deadline approaching (Credit Limit Bookings)
Template ID: d-1e69b16152ef45f08426574e19ee8d3c

**Comment by DenisVelinen** [comment]
The template has been added and works on dev. and prod. environments.
