### ISSUE TITLE
Add a page for registering agencies to the admin panel

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1889]
Admins can add ("register') an agency without a registration process.

This feature requires adding an agency name to an invoice when the Reservation team books through HT system for them.
These agencies can't use the Agent app for Accommodation search or booking.
These agencies will be just like an object to select to an invoice.

What we need to keep in an agency card:

Agency name (mandatory)
Agency TRN (if they are in UAE)
Agency VAT
Agency Address (City, Country)
Agency email
Agency Phone
Contact name
Billing Email (mandatory)
For such Agencies, we don't need verification via email. If the Agency decides to make registration - we can't provide the credentials for the current account, they will need to create a new one.

We should add the possibility to deactivate such Agencies.

Who can register such agencies: Account manager, Booking manager

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
1) 
- open Create New Agency page
- click back button
**Result:**
- I am on the main page
**Expected:**
- I am on the agencies list page

2)
Billing Email should be mandatory

3)
![image](https://user-images.githubusercontent.com/74529212/196194670-7dd61888-4230-4e2e-870f-398069f4e57f.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- page for new agency creation w/o registration https://manage-dev.happytravel.com/agency/create is added
- Super-admin, Account manager and Booking manager can register such agencies
- it is possible to activate/deactivate such agencies

**OK on DEV.**
