### ISSUE TITLE
Change endpoints to set and get agency and agent system settings

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#189]
1. Current endpoints allows to get and the settings "as is".
We need to change endpoint for getting settings in the following way:

Instead of list of suppliers: 
```
 "enabledSuppliers": [
    "Illusions", "ETG", "Netstorming"
  ],
```

We should return an object (or dictionary)

```
{ 
"Illusions": true,
"Columbus": false,
....
"ETG": true
}
```

to allow frontend to show all of them, not only enabled. Or null if the setting is not set.

2. If agent and agency exists but settings are not set, need to return "NoContent" status instead of "BadRequest" as it done now

**Comment by sergeyf-QA** [comment]
**Summary:**
GET /{culture}​/api​/{v}​/admin​/agencies​/{agencyId}​/system-settings​/availability-search
POST ​/{culture}​/api​/{v}​/admin​/agencies​/{agencyId}​/system-settings​/availability-search
DELETE ​/{culture}​/api​/{v}​/admin​/agencies​/{agencyId}​/system-settings​/availability-search
GET /{culture}/api/{v}/admin/agencies/{agencyId}/agents/{agentId}/system-settings/availability-search
POST /{culture}/api/{v}/admin/agencies/{agencyId}/agents/{agentId}/system-settings/availability-search
DELETE /{culture}/api/{v}/admin/agencies/{agencyId}/agents/{agentId}/system-settings/availability-search
works fine

OK on DEV.
