### ISSUE TITLE
Vouchers of Credit Agencies

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1892]
Have to allow to download vouchers for Virtual Account contract kind agencies before booking payment.
ER:
An agency contract kind 3 books a room(s) -> gets confirmation of a booking -> the can see a "voucher" button and download it.

Admins (booking managers) also can download a voucher in this case.

- [x] #1894
- [x] #1895
- [x] #1896

**Comment by sergeyf-QA** [comment]
done
