### ISSUE TITLE
Add ability to change payment setting of agents

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1893]
Description:
For VirtualAccountOrCreditCardPayments Contract Type the Payment Method should be chosen from CreditCard and CreditLimit + CreditCard.
For OfflineOrCreditCardPayments Contract Type, the Payment Method should be chosen from Offline + CreditCard.
For CreditCardPayments Contract Type, the Payment Method is CreditCard only and can’t be edited.
*In the case of Credit Limit Payment on Subagency/Agent level during the reservation, the payment is debited from the Agency Balance.

Default Settings for Payment Setting: Credit Card for all types of contracts

**Comment by ViTsvetkova** [comment]
Agency administrator and Accounts manager can set up payment settings of agents
This activity should required a special permission ChildAgencyAccountManagment.

**Comment by sergeyf-QA** [comment]
**Summary:**
- Agency administrator and Accounts manager can set up payment settings of agents on agent page
- For VirtualAccountOrCreditCardPayments Payment Methods 
Account
Credit Card
For OfflineOrCreditCardPayments Payment Methods 
Offline
CreditCard.
For CreditCardPayments the Payment Method is CreditCard only and block is not shown on UI
![image](https://user-images.githubusercontent.com/74529212/200612883-7cbabd26-a6e0-43c8-bc83-d38b3960144e.png)


**OK on DEV.**
