### ISSUE TITLE
Allow to download and send vouchers before booking payment for agencies with virtual account

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1894]
Agents and admins must be able to download and email the voucher after booking confirmation prior to payment. This is valid only for agencies with contract type VirtualAccountOrCreditCard. The automatic distribution of the voucher by mail remains unchanged: the voucher is sent after the payment for the reservation.

**Comment by sergeyf-QA** [comment]
**Summary:**
- Agents and admins are able to download and email the voucher after booking confirmation prior to payment. This is valid only for agencies with contract type VirtualAccountOrCreditCard.

**OK on DEV.**
