### ISSUE TITLE
Fix in agency app to allow to download and send vouchers before booking payment for agencies with virtual account

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1895]

**Comment by alexander-plekhanov** [comment]
The app don't know the agency contract kind on booking page so that's why a payment status check was removed from this button view condition.

**Comment by sergeyf-QA** [comment]
**Summary:**
- 'Download Voucher' button is shown for Confirmed and Completed bookings only

**OK on DEV.**
