### ISSUE TITLE
Fix in admin panel to allow to download and send vouchers before booking payment for agencies with virtual account

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1896]

**Comment by alexander-plekhanov** [comment]
I've removed the check for booking payment status. I don't know what contract kind agency have on this page and I don't think its' necessary to get agency here just to set button visibility.

**Comment by sergeyf-QA** [comment]
**Summary:**
- 'Download Voucher' button is shown for Confirmed and Completed bookings only

**OK on DEV.**
