### ISSUE TITLE
Add Currency code to Property model

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1897]
It is necessary to add the Currency field on the add/change property page. This field can take values from the list of available currencies, which can be obtained by request GET api/{v:apiVersion}/currencies 
Also, validation has been added to the backend when saving the Supplement by hotel room, checking that the Supplement if it is not null contains the same currency code as set in the hotel settings.

**Comment by sergeyf-QA** [comment]
**Summary:**
- Currency field is added to the add/change property page
![image](https://user-images.githubusercontent.com/74529212/195603236-57c62b0e-2220-4689-a5b9-d327bbae1b1a.png)
- Currency field is added to Room page
![image](https://user-images.githubusercontent.com/74529212/195603645-5f2a6264-3860-4d30-84f4-7b38837686f3.png)

**OK on DEV.**
