### ISSUE TITLE
Add Deadline approaching (Offline Bookings) notifications to admins

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1899]
Add the Deadline approaching (Offline Bookings) notification to admins (Booking manager, Finance manager)

Email template:
https://docs.google.com/document/d/1EhnzevKPLIPFzpRJdXeEBEv8kKweVjR1Ca8Z5zPEMoQ/edit

**Comment by DenisVelinen** [comment]
It has been done and works on DEV environment.
