### ISSUE TITLE
Add parameter 'id' in the response in the method 'Get Agency discounts'

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#190]
1. Send request for getting information about agency discount 
`{{ edo.baseUrl }}/en/api/1.0/admin/agencies/890/discounts`
2. Get response 
```
[
  {
    "discountPercent": 2.0,
    "description": "23",
    "targetMarkupId": 158,
    "targetPolicyDescription": null,
    "isActive": true
  },
  {
    "discountPercent": 2.0,
    "description": "23",
    "targetMarkupId": 158,
    "targetPolicyDescription": null,
    "isActive": true
  }
]
```

**AR**: There is no 'id' parameter for discount in response
**ER**: There is 'id' parameter for discount in response because its necessary for using next methods.

**Comment by sergeyf-QA** [comment]
**Summary:**
now, there is ID in response of GET /{culture}/api/{v}/admin/agencies/{agencyId}/discounts

**OK on DEV.**
