### ISSUE TITLE
Add an agent list of a sub-agency on the sub-agency page in agent app

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1905]
Need to add an agent list of a sub-agency on the sub-agency page in agent app

**Comment by sergeyf-QA** [comment]
**Summary:**
- there is an agent list of a sub-agency on the sub-agency page
![image](https://user-images.githubusercontent.com/74529212/199535169-42ca7ffc-6694-41d8-a279-e002e7081a1d.png)


**OK on DEV.**
