### ISSUE TITLE
Adding a new agency

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1906]
https://github.com/happy-travel/agent-app-project/issues/1812
we have to improve this task:

1) add a validation on backend: if an agency country is UAE - TRN value should be mandatory. 
2) all agency names, address, emails, contact names should be in English alphabet. in addition to the letters of the alphabet, the name may contain other symbols: munbers, dashes, apostrophes, commas, dots, etc.

Validation should be added wherever you can add or change agency settings.

**Comment by sergeyf-QA** [comment]
@timur-mut 
the first point does not work nor while creation nor while agency changes saving
`add a validation on backend: if an agency country is UAE - TRN value should be mandatory.`

**Comment by sergeyf-QA** [comment]
**Summary:**
- if an agency country is UAE - TRN value is mandatory (for creation and updating)
- all agency names, address, emails, contact names may be in English alphabet only, these fields may contain other symbols: numbers, dashes, apostrophes, commas, dots, etc


**OK on DEV.**
