### ISSUE TITLE
Booking List filters

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1910]
Change the logic of Filters in the Booking List:

_All bookings_ - should include all bookings with all statuses (Confirmed, Awaiting Confirmation (ex. MCN, Pending), Pending Cancellation, Rejected, Cancelled, Completed, Discarded. Currently, the filter doesn't include Cancelled, Completed and Discarded Reservations. 
_Cancelled_ - no change needed
_Rejected_ - need to add a new filter. (Currently, we don’t have a such filter.)
_Discarded_ - should be in a separate filter. (Currently, we don’t have a such filter.)
_Future_ - should include all reservations with check-in date in the future in the statuses Confirmed, Awaiting Confirmation. (Currently, the filter includes only Confirmed Reservations.)
_Need Attention_ - should include all Awaiting Confirmation. (Currently includes only ex MCN, doesn't include ex Pending. )
_Complete_ - All Completed Reservations. No changes are needed.

**Comment by alexander-plekhanov** [comment]
I can implement it now from the application side, but we should remake booking loading from API side.

Now the app download all bookings and sort it locally. 
The correct way is to remake API method to provide it as odata list with top skip and add by-page/infinite loader.

**Comment by ViTsvetkova** [comment]
> I can implement it now from the application side, but we should remake booking loading from API side.
> 
> Now the app download all bookings and sort it locally. The correct way is to remake API method to provide it as odata list with top skip and add by-page/infinite loader.

this task should help
https://github.com/happy-travel/edo/issues/2267

**Comment by alexander-plekhanov** [comment]
Implemented without using odata.

**Comment by sergeyf-QA** [comment]
**Summary:**
- all points from description are implemented

**OK on DEV.**
