### ISSUE TITLE
Agent markup logs check

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1911]
Have to check what type of logs we have for

id agent markup 694
it has been created and deleted 19 October

![Image](https://user-images.githubusercontent.com/90184684/196705261-7e7968e3-81d1-46d6-9be0-e10d253d219e.png)

booking DEV-HTL-AE-000A77-01

ER:
1) who and when created a markup
2) has been implemented or not
3) who and when deleted a markup

**Comment by nikolaeva31** [comment]
There're a few mentions of this markup:
1. Applying markup when searching (file)
2. About removing markup without adminId (but not rendered in logs) - https://logs-dev.happytravel.com/app/discover#/doc/97718760-2573-11ed-bcc8-bbc1434ea904/fluentd-nginx-ingress-nginx-ingress-2022.10?id=Kgxk8IMBFWxLmY50RbKP
