### ISSUE TITLE
Connecting Juniper Push to komoro

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#1912]
- [ ] Add static data models to Juniper Channel Manager
- [ ] Add inventory models to Juniper Channel Manager
- [ ] Add rates models to Juniper Channel Manager
- [ ] Extend komoro static models for Juniper support
- [ ] Extend komoro inventory models for Juniper support
- [ ] Extend komoro rates models for Juniper support
- [ ] Implement data upload from Juniper FTP server to channel manager
- [ ] Implement inventory and hotel data update from Juniper channel manager
- [ ] Implement rates and cancellation policy data update from Juniper channel manager
- [ ] Complicate rate calculation based on Juniper data
- [ ] Implement booking creation in Juniper channel manager
- [ ] Implement booking getting in Juniper channel manager
- [ ] Implement booking cancellation in Juniper channel manager

**Comment by DFSko** [comment]
Moved to YouTrack
