### ISSUE TITLE
Amend the Finalized booking report

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1913]
This report needs to the Accounting.

In the Finalized Booking Report, we should see all bookings for the selected period with the following rules:

Check Out Date is inside the specified period (include the first and the last days of the processed report). 

We have to add the following statuses:
- Completed
- Cancelled, only in case we have the penalty (in case the reservation was cancelled without penalty - we don't need to include such reservations)

The last day to select the period on the front should be "yesterday".

**Comment by DaniyarAskarov** [comment]
Changes: 
 1) "Created" field do not affects to query's conditions anymore
 2) AprMode filters removed
 
 Endpoint: api/{v:apiVersion}/admin/reports/finalized-bookings-report

**Comment by sergeyf-QA** [comment]
**Summary:**
changes for 'Finalized bookings report'
- the last day to select the period on the front is "yesterday"
- added completed bookings
- added cancelled bookings, only in case there is the penalty
- AprMode filters removed
- "Created" field do not affects to query's conditions anymore, now report uses CheckOutDate 

**OK on DEV.**
