### ISSUE TITLE
Multicurrency support for CC payments

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1921]
Opportunity of CC payment type should be added for all variety of currencies for MULTI-CUR accounts.

We need to open this function on UI also (currently we don’t allow payment via CC if the preset currency is not USD).

For CC payment type:
In case of an Agent preset any currency despite of USD, we need to add an extra conversion rate.

The logic for conversion:
* AED-USD/USD-AED - 3,6725

* for any other options - 3%

Main task:
https://github.com/happy-travel/agent-app-project/issues/1252

Business logic:
https://miro.com/app/board/uXjVOtY386k=/?moveToWidget=3458764535726202750&cot=14

**Comment by DaniyarAskarov** [comment]
Test cases: 
 1) Run search for any currencies except USD
 2) Check if backend returns CreditCardPrice field in USD with commission
 3) Check if booking with CreditCard procceed in USD currency with commission

**Comment by sergeyf-QA** [comment]
**Summary:**
- creditCardPrice and comission fields are added to all search steps
- creditCardPrice and comission fields are always in USD regardless of search currency
- finalPrice, gross, netPrice are in search currency
![image](https://user-images.githubusercontent.com/74529212/200793148-e99fc954-a208-49ce-aed7-2da2e8b50734.png)
- creditCardPrice for USD currency = finalPrice * 1.02 (our comission for CC)
- creditCardPrice for AED currency = converted to USD finalPrice * 1.02 (our comission for CC)
- creditCardPrice for non-USD and non-AED currencies = converted to USD finalPrice * 1.03 (% of conversion) * 1.02 (our comission for CC)

**OK on DEV.**

**Comment by ViTsvetkova** [comment]
invoice requirements: 
The final rate, when we change the payment method to CC should change adding another 2% to the previous rates. 
We mustn't show the 2% commission as “bank fees”, 
e.g. https://prnt.sc/CfAsPsTM0KjV
