### ISSUE TITLE
Minor enhancement of a booking page view

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1924]
Need to make Invoice/Voucher buttons more compact
Possibly combine

![Image](https://user-images.githubusercontent.com/90184684/198074808-37cdb74e-af73-4bb7-bdcc-c24069171db8.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- voucher and invoice buttons are redeveloped
![image](https://user-images.githubusercontent.com/74529212/201865167-e58a9ec0-ad0c-4a61-9372-e1e7995a9351.png)
![image](https://user-images.githubusercontent.com/74529212/201866591-91d4e53d-c0a1-4b22-8a32-2b2eb97114c7.png)


**OK on DEV.**
