### ISSUE TITLE
Agent Notifications

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1928]
Please investigate current agent notifications.
We need to understand which agent roles receive which notifications

Keep data here:
https://docs.google.com/spreadsheets/d/1aT5CK8YEwOJDxvpjLtaPGlrfCSWZoXYUQnHeN0etSy4/edit#gid=0

**Comment by AlexeyShok** [comment]
https://1drv.ms/x/s!ArAOjaIGLOwqir8DF4EpjPoqdEx3Ag?e=UYLZ4T

**Comment by DenisVelinen** [comment]
The data on mailings to agents are described in the tab in the table https://docs.google.com/spreadsheets/d/1aT5CK8YEwOJDxvpjLtaPGlrfCSWZoXYUQnHeN0etSy4/edit#gid=1101939545
