### ISSUE TITLE
Add logic to process `GiataId` from manual merge.

### ISSUE THREAD

**Issue by hasmikharutyunyan** [happy-travel/agent-app-project#1932]
Must be saved on uncertain matches merge history info about `GiataId`, as now when merged two accommodations `GiataId` is moving from one to another, it is needed for unmerge, add logic to `unmerge` also, move back `GiataId` on `unmerge`

**Comment by nikolaeva31** [comment]
Merged two accommodations, there was GIATA code from main accommodation. 

**AR**: https://mapper-dev.happytravel.com/history/12c79bc1-6dce-47b0-8175-45d42acb62d6 
Second accommodation doesn't have GIATA code -  Accommodation_11068073. 
But main Accommodation_12004242 has GIATA code.
