### ISSUE TITLE
Remove an ability to transfer money to a sub-agency

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1939]
Root Agency can't transfer money to a sub-agency. Sub-agencies pay for bookings from a root agency balance account (virtual account contract kind)
So we need to remove this feature on UI.

**Comment by sergeyf-QA** [comment]
**Summary:**
- now there is no an opportunity to transfer money from root agency to child one
![image](https://user-images.githubusercontent.com/74529212/199535744-d0a25e34-2f02-4959-84ad-eb03c18b434a.png)


**OK on DEV.**
