### ISSUE TITLE
GIATA id code field of a supplier

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1940]
Need to add a field of GIATA id Code of a supplier.
Happy Travel supplier code and GIATA code is different usually.
We need to match GIATA supplier id code and Happy Travel supplier code.

![Image](https://user-images.githubusercontent.com/90184684/199014186-84eed593-4b78-4f69-893e-efd5970a6ab4.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- GIATA SUPPLIER CODE is added to the supplier page
![image](https://user-images.githubusercontent.com/74529212/201844768-af4e4391-26c2-4cd1-a227-e27bf26eb7ca.png)
- giata code is also shown on the suppliers list
![image](https://user-images.githubusercontent.com/74529212/201845471-cffc15a4-3b22-4382-97ab-c2682292f0f2.png)
- adding and editing with giata code work well

**OK on DEV.**
