### ISSUE TITLE
Add an agent name to the BookingSummaryReportForAgent = 24

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#1942]
Related request: https://happytravel.freshdesk.com/a/tickets/763

**Summary of approaching deadlines (next 5 days)** 
To the template d-6c99ec77db8d47ada2c60477e901116b we need to add: 
- An agent name (full name without a title) of each booking: ref code, agent name, accommodation name

![Image](https://user-images.githubusercontent.com/90184684/199453027-90897f3b-03b6-46d5-bac4-5b9096214b98.png)

**Comment by DaniyarAskarov** [comment]
@DenisVelinen per each bookings was added "Agent" field which represents name of agent who booked it.

**Comment by DenisVelinen** [comment]
The "agent" parameter has been added to the email template with ID: d-6c99ec77db8d47ada2c60477e901116b
The email looks that:
![Снимок экрана 2022-11-03 в 17 50 36](https://user-images.githubusercontent.com/17127277/199755728-8a590356-3c4b-4aad-9484-0828e1c8fc60.png)
