### ISSUE TITLE
Send request for getting information about currencies 

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#1943]
Steps:
1. Open https://manage-dev.happytravel.com/bank-details 
2. Choose https://manage-dev.happytravel.com/bank-details/13/accounts 
3. Try to add account 
<img width="1440" alt="Screenshot 2022-11-07 at 11 11 11" src="https://user-images.githubusercontent.com/38030865/200258617-ccda7ac1-5340-48fc-9d1c-d34a00100b70.png">
<img width="1440" alt="Screenshot 2022-11-07 at 11 11 22" src="https://user-images.githubusercontent.com/38030865/200258653-3e2e1e5e-40fa-4924-b2ab-9ac44cccce1d.png">

**AR**: There're no currencies to add which there're in the system
**ER**: When adding an account need to request by endpoint with available currencies in the system - 
`GET URL: https://edo-dev.happytravel.com/en/api/1.0/admin/company/available-currencies`

**Comment by sergeyf-QA** [comment]
**Summary:**
- now all currencies exist on an account creation page:
![image](https://user-images.githubusercontent.com/74529212/200341518-de7fcb8d-66a4-4e21-980f-a690c18c2588.png)


**OK on DEV.**
