### ISSUE TITLE
Country field displays countryId not name

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#1944]
Steps:
1. Open a page https://manage-dev.happytravel.com/mapper 
2. Choose any country 
3. Push 'Search accommodation' button 
4. Open any option from list and go back 

**AR**: The country field displays countryId, not name. 

<img width="1434" alt="Screenshot 2022-11-08 at 08 11 17" src="https://user-images.githubusercontent.com/38030865/200480418-f9ca408f-6946-4f41-9fb4-74d155f6d9b6.png">

**Comment by alexander-plekhanov** [comment]
moved
