### ISSUE TITLE
Adding roles to an agent causes an error

### ISSUE THREAD

**Issue by wnlstk** [happy-travel/agent-app-project#1946]
on dev

How to reproduce:
- login to https://manage-dev.happytravel.com/  
- go to https://manage-dev.happytravel.com/agency/801/agents/716/change-agency
- adding all roles to an agent

Expected result:
- Adding all roles is done

Actual result:
- Bad request 400
- Request URL: https://edo-dev.happytravel.com/en/api/1.0/admin/agencies/801/agents/716/change-agency

**Comment by ViTsvetkova** [comment]
can't reproduce

**Comment by sergeyf-QA** [comment]
The issue is still here
