### ISSUE TITLE
Alphabetical sorting does not work in bookings list

### ISSUE THREAD

**Issue by wnlstk** [happy-travel/agent-app-project#1948]
ON DEV

How to reproduce:
- go to https://dev.happytravel.com/bookings
- click 'Sort by agent'

Expected result:
- Bookings are sorted by agents in name alphabetical order

Actual result:
-Bookings are not sorted by agents in name alphabetical order
![Снимок3](https://user-images.githubusercontent.com/102408868/201042874-2713c027-8032-4664-9419-6c149efe543a.PNG)

**Comment by ViTsvetkova** [comment]
minor
