### ISSUE TITLE
[TechDebt] Find out what is the problem to use dbContrext.Items.RemoveRange() in the Map

### ISSUE THREAD

**Issue by hasmikharutyunyan** [happy-travel/agent-app-project#195]
AccommodationManagementService ->
public async Task<Result> Remove(int accommodationId)

Error:
Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. 
This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. 
If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'DirectContractsDbContext'.

**Comment by kirillta** [comment]
@hasmikharutyunyan please update

**Comment by hasmikharutyunyan** [comment]
> @hasmikharutyunyan please update

This is not done, as problem was in `DirectContracts` project, I think we can keep this issue

**Comment by hasmikharutyunyan** [comment]
not actual for now
