### ISSUE TITLE
405 error when an agency contract uploading

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1954]
**How to reproduce:**
- open any agency page in the admin panel e.g. https://manage-dev.happytravel.com/agency/1380/details
- try to upload contract .pdf file

**Expected result:**
- no errors during contract uploading

**Actual result:**
- though contract is uploaded there is 405 error
https://manage-dev.happytravel.com/agency/1380/true

```
<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

```

**Comment by AlexeyShok** [comment]
Frontend uses incorrect request path https://manage-dev.happytravel.com/agency/1379/true instead of https://edo-dev.happytravel.com/{v:apiVersion}/admin/agencies/{agencyId}/contract-file

**Comment by alexander-plekhanov** [comment]
It was just an extra request from our UI toolkit. Fixed.

**Comment by sergeyf-QA** [comment]
**Summary:**
- no error now during contract uploading

**OK on DEV.**
