### ISSUE TITLE
When "boardBasis":"NotSpecified" then "boardBasis" is not shown on UI

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#1955]
**How to reproduce:**
- try to search on PROD 
Artstudio Nevsky Hotel, Saint Petersburg, The Russian Federation
30-11-2022 – 18-12-2022
2 Adults • 1 Room
UAE UAE
Bronevik supplier
- check "boardBasis" on the front of the 3rd search step and what backed returns

**Expected result:**
- show "Board Basis": Not Specified on ui in this case

**Actual result:**
- "Board Basis" on UI is empty though backend returns "boardBasis":"NotSpecified"
![image](https://user-images.githubusercontent.com/74529212/203717904-6b5b09fb-2a3a-428b-956a-40510b9ab0e0.png)

**Comment by ViTsvetkova** [comment]
transfeedr to youtrack https://track.happytravel.tech/issue/HP-300/Bronevik-Check-and-rematch-suppliers-meal-plans-with-Happy-Travel-board-basis
