### ISSUE TITLE
[TechDept] Find more correct algorythm of for updating room supplier reference codes in EDO Bookings

### ISSUE THREAD

**Issue by hasmikharutyunyan** [happy-travel/agent-app-project#197]
Current algorythm updates booking details from booking and finds corresponding room by it's order, which may cause issues.
Need to reengineer this to make this more solid.

Maybe we need to move room reference code somewhere from remarks

**Comment by kirillta** [comment]
@mingazhev please clarify

**Comment by ViTsvetkova** [comment]
https://track.happytravel.tech/issue/HP-534
