### ISSUE TITLE
[TechDebt] Replace payfort GET callback with POST

### ISSUE THREAD

**Issue by hasmikharutyunyan** [happy-travel/agent-app-project#199]
As support says:

_Payfort is in the transition period of deprecating GET, and It's being slowly enforced in live account as well. 

Hence, I suggest to move to POST now so that it will be easier later. 

You would  need to add a controller on the return_url to accept the response returned as POST method inside the return_url, so you could catch the response. it will be as hidden post form
_

So we need to:
1. Change our implementation to use POST instead of GET
2. Change the settings on DEV environment and test how it works

**Comment by kirillta** [comment]
@alexander-plekhanov isn't that done?

**Comment by ViTsvetkova** [comment]
implemented
