### ISSUE TITLE
[TechDebt] Separate frontend and db models in EDO

### ISSUE THREAD

**Issue by hasmikharutyunyan** [happy-travel/agent-app-project#200]
Model in DB that are used on frontend:
1. SupplierAccommodationId
2. AgencyAccommodationBookingSettings ??
3. AgentAccommodationBookingSettings ??
4. AccommodationLocation
5. BookedRoom
6. CancellationPolicy !!
7. Deadline !!
8. Passenger !!

**Comment by kirillta** [comment]
Done in another way
