### ISSUE TITLE
The report files are saved in PDF

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#205]
On https://manage-dev.happytravel.com
In Chrome, Firefox, Safari.

**Steps.**
1. Log in and go to Download Report page (click on Reports button);
2. Try to download any report.

**Result.**
The report files are saved in PDF.

**Expectations.**
The report files are saved in CSV file format. All GET methods upload file in CSV format.

**Comment by sergeyf-QA** [comment]
'Download report button does not work on https://manage-dev.happytravel.com/reports

**Comment by sergeyf-QA** [comment]
**Summary:**
all reports are saved in CSV format on https://manage-dev.happytravel.com/reports

**OK on DEV.**
