### ISSUE TITLE
Allow counterparty data to be edited while in Pending Verification state

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#206]
On https://manage-dev.happytravel.com
In Chrome, Firefox, Safari.

**Steps.**
1. Log in and go to Counterparties list page (click on Counterparties button);
2. Find and go to any counterparty with Pending verification state;
2.1. Scroll down to Counterparty details block;
2.2. Pay attention to the fields of Counterparty details;
3. Find and go to any counterparty with Full access state;
3.1. Scroll down to Counterparty details block;
3.2. Pay attention to the fields of Counterparty details;

**Result.**
For all counterparties, it is possible to edit details without depending on the current status of the counterparty. Once the contact has been signed, you cannot change the counterparty details because the contract will be broken.

**Expectations.**
Allow counterparty data to be edited while in Pending Verification state. In all other statuses, the counterparty data should be read-only text.

**Comment by sergeyf-QA** [comment]
@cyberkarma 
1) Full Access counterparties have enabled Submit button on details page
**Expected:**
- please do it disabled or remove from the page

2)
when I save changes on details page then it redirects me to counterparties list (that is OK) BUT the edited counterparty changes it place in counterparty list that a bit disorients me as an user
**Expected:**
- don't change counterparty position in counterparties list after saving

3)
Preferred Payment Method may be edited at Full Access and Read Only counterparties
**Expected:**
- Preferred Payment Method should not be edited at Full Access and Read Only counterparties

4)
in case I did not enter Company name and click on Submit could you please show an error message "The Name field is required." from the back-end?

**Comment by sergeyf-QA** [comment]
**Summary:**
counterparty data may be edited while in Pending Verification state. In all other statuses, the counterparty data is read-only text.

**OK on DEV.**
