### ISSUE TITLE
[Draft] Permission system changes

### ISSUE THREAD

**Issue by konstyefremov** [happy-travel/agent-app-project#207]
The current system has good parts and bad parts. 

**Bad Parts**

It's difficult to manage users' permissions. To add a new user we should think about what permissions (out of many) the user should have. To check that the user has correct permissions we also need to keep in the head lots of data. There are also lots of repetitions when we add similar users. Agents, for example, will have the same permissions. 

**Good Parts**

It's easier to write and read the code. The permissions are very detailed and describe specific actions. We only check that the user has a permission. We don't need to think if the user belongs to a specific role, and if this role should have this action available. 

## Proposal

1. Stay with the attributes, but do minor naming refactoring
2. Introduce roles separately. Attach permissions to the roles. 
3. Do not bring roles into the attributes in the code. It will be difficult to manage such a code.
4. The user might belong to one or more roles.
5. (Optional) make it possible for the user to have some permissions outside of his role. Though it might be not a very good idea.

## Details

1. Rename the permissions to the verbs describing specific actions. Prefix them with "Can".

AgentInvitation -> CanInviteAgents
PermissionManagement ->  CanManagePermissions
etc.

2. Rename the attribute [InAgencyPermissions()] to [RequirePermission()]. The code will be easier to read:

Now:

```
[HttpPost("agency/invitations/send")]
[ProducesResponseType((int)HttpStatusCode.NoContent)]
[ProducesResponseType(typeof(ProblemDetails), (int)HttpStatusCode.BadRequest)]
[InAgencyPermissions(InAgencyPermissions.InviteChildAgencies)]

```

Proposal:

```
[HttpPost("agency/invitations/send")]
[ProducesResponseType((int)HttpStatusCode.NoContent)]
[ProducesResponseType(typeof(ProblemDetails), (int)HttpStatusCode.BadRequest)]
[RequirePermission(InAgencyPermissions.CanInviteChildAgencies)]
```

3. Introduce roles. Store them in the database.

Now:

**Table: AgentAgencyRelations**
Name: Username
InAgencyPermissions: 511

Proposal: 

**Table: AgentAgencyRelations**
Name: Username
Role: 1

**Table: Roles**
Id: 1
Name: Supervisor
Permissions: 511

**Comment by mingazhev** [comment]
@konstyefremov looks fine for me, but looks like there is a typo, AgentAgencyRelation can contain multiple roles.

**Comment by mingazhev** [comment]
And as I see we'll move permissions storage to the Role entity. Could you add descriptions from this side?
