### ISSUE TITLE
List and categorize all admin actions (changing something endpoints) 

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#209]
Need to list all endpoints that change something (PUTS, POSTS) and give each endpoint one of the categories:
- Not dangerous (will need to confirmation on frontend side) - like activating or deactivating agency, counterparty and so on. Actions that can be easily undone and will not lead to bad results
- Medium dangerous (will show popup confirmation window on frontend side) - like cancelling, discarding booking and so on
- Very dangerous (will show confirmation window with a timer on frontend side) - like editing global markups

Results may be added to this issue comments and discussed with QA team

**Comment by Raibo** [comment]
[admin endpoints.xlsx](https://github.com/happy-travel/agent-app-project/files/6470088/admin.endpoints.xlsx)
