### ISSUE TITLE
It is not possible to make a booking using the Offline payment method, even if you have permission to do

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#212]
On https://dev.happytravel.com/
In Chrome, Firefox, Safari.

**Description.**
Presumably two days before the deadline it is not possible to pay using the Offline payment method, even if there is an option from the server.
Example.
Test Hotel(Do Not Book), Belogorsk, The Russian Federation
POST https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/book-for-offline
```
{
  "searchId": "9815a626-3aaf-4320-b5a4-3e776e11b4b9",
  "resultId": "28247d14-c68d-4b47-bbb7-340e438db3cd",
  "roomContractSetId": "20ac2b98-b3f6-488e-97ec-22122e028428",
  "nationality": "IT",
  "paymentMethod": "Offline",
  "residency": "IT",
  "mainPassengerName": "Gavino Vecellio",
  "roomDetails": [
    {
      "type": "Single",
      "passengers": [
        {
          "title": "Mr",
          "firstName": "Gavino",
          "lastName": "Vecellio",
          "age": 35,
          "isLeader": true
        }
      ]
    }
  ],
  "features": [],
  "itineraryNumber": ""
}
```

**Result.**
It is not possible to make a booking using the Offline payment method, even if you have permission to do.
```
{
    "status": 400,
    "detail": "Deadline already passed, can not book"
}
```
<img width="1358" alt="Снимок экрана 2021-05-11 в 18 36 08" src="https://user-images.githubusercontent.com/17127277/117877589-69db5400-b2ad-11eb-9d5d-ce0fcfaf0f99.png">

**Expectations.**
It is possible to pay for the booking by all methods sent by the server, as the possibilities are defined within the server.

**Comment by mingazhev** [comment]
@Raibo could you check that deadline validation is equal for getting payment types list and for trying to pay using offline payment?

**Comment by DenisSychev** [comment]
Has been corrected and works at https://dev.happytravel.com
