### ISSUE TITLE
Fix nullability warnings in Rakuten

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#213]
Warnings during build and optional solution analyzis warnings (unused usings and etc.)

**Comment by sergeyf-QA** [comment]
@Raibo 
1)
- look for
 Test Detailed Cp Rates Jp, Tokyo, Japan
 09-06-2021 – 10-06-2021
 1 Adult • 0 Children • 1 Room
Russian Federation
Russian Federation
- pay by card for that
- try to refresh status
 
**Actual result:**
https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/3340/refresh-status

{status: 400,…}
detail: "No parameterless constructor defined for type 'HappyTravel.RakutenConnector.Api.Models.Rakuten.Settings.RakutenBookingContactSettings'.\n"
status: 400
