### ISSUE TITLE
Remove the ability to handle the balance from the agency information page (leave only the display of the current balance status)

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#214]
On https://manage-dev.happytravel.com
In Chrome, Firefox, Safari.

**Steps.**
1. Log in and go to Agency details page (Counterparties list -> Counterparty -> Agency);
2. Scroll down to Balance block.

**Result.**
On the agency data page, there is a block to handle with the agency balance.

**Expectations.**
Remove the ability to handle the balance from the agency information page, because the actual balance is managed on the counterparty page. Leave only the display of the current balance status.

**Comment by sergeyf-QA** [comment]
**Summary:**
now, on Agency details page (Counterparties list -> Counterparty -> Agency) is no handling balance block, only balance value is shown.

**OK on DEV.**
