### ISSUE TITLE
Book-by-account returns 400 error

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#216]
**How to reproduce:**

- try to book by account on DEV env
Test Hotel(Do Not Book), Belogorsk, The Russian Federation
15-05-2021 – 16-05-2021
1 Adult • 1 Children • 1 Room
United Kingdom Of Great Britain And Northern Ireland
United Kingdom Of Great Britain And Northern Ireland

within deadline period

**Actual result:**
https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/book-by-account
returns
`[{"status":400,"detail":"exceed_limit. request: {\"language\":\"en\",\"partner\":{\"partner_order_id\":\"DEV-HTL-RU-000RH4-01\"},\"payment_type\":{\"type\":\"deposit\",\"amount\":\"10\",\"currency_code\":\"USD\"},\"rooms\":[{\"guests\":[{\"first_name\":\"d\",\"last_name\":\"f\",\"is_child\":false},{\"first_name\":\"d\",\"last_name\":\"s\",\"is_child\":true,\"age\":12}]}],\"user\":{\"email\":\"etg-info-dev@happytravel.com\",\"phone\":\"\\u002B79876543210\"}}"}]`
though money are captured

**Comment by mingazhev** [comment]
@oleg1std could you have a look and comment?

**Comment by oleg1std** [comment]
fixed by @kirillta
