### ISSUE TITLE
Add notifications via NotificationCenter for Account

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#219]
We need add SignalR notifications and transfer sending email via NotificationCenter for next events:
1) EDO: Credit card payment received (Agent);
2) EDO: Account balance has been replenished.

A more detailed description can be found here:
https://github.com/happy-travel/edo/issues/472

**Comment by sergeyf-QA** [comment]
**Summary:**
logs are written when:
1) Credit card payment received from the agent (Agent) - type 9 
2) Account balance has been replenished - type 10

**OK on DEV.**
