### ISSUE TITLE
Add notifications via NotificationCenter for Counterparty

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#221]
We need add SignalR notifications and add/transfer sending email via NotificationCenter for next events:

1) EDO: Customer Invitation;
2) EDO: Regular customer succsessful registration;
3) Agency Management.

A more detailed description can be found here:
happy-travel/edo#472

**Comment by sergeyf-QA** [comment]
**Summary:**
1) RegularCustomerInvitation = 11 - record appears in Notifications table when I invite an agent
2) ChildAgencyInvitation = 12 - record appears in Notifications table when I invite a child agency
3) RegularCustomerSuccessfulRegistration = 13 - record appears in Notifications table when an agent registration is completed
4) ChildAgencySuccessfulRegistration = 14 - record appears in Notifications table when an child agency registration is completed

**OK on DEV.**
