### ISSUE TITLE
Add notifications via NotificationCenter for Other

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#222]
We need add SignalR notifications and add/transfer sending email via NotificationCenter for next events:

1) EDO: External payment links;
2) EDO: Payment link paid notification;

A more detailed description can be found here:
happy-travel/edo#472

**Comment by sergeyf-QA** [comment]
**Summary:**
EDO: External payment links=25 - OK
EDO: Payment link paid notification=26 - OK

**OK on DEV.**
