### ISSUE TITLE
Implement booking changes audit log service to store all booking changes

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#23]
This may require introducing a new model for "BookingChange" event and removing or renaming current BookingAuditLog table because it looks like not properly named.
The main usages of this service:
- Show booking history to an agent
- Store all booking changes for an admin

For starting point please use a branch from here:
https://github.com/happy-travel/edo/pull/512

**Comment by sergeyf-QA** [comment]
**Summary:**
- logs of booking operations exist in "BookingStatusHistory" table
- all booking changes (booking, cancellation, rejection etc) are logged there
- admin's executions also are there

**OK on DEV.**
