### ISSUE TITLE
No messages about the finalized booking email in notifications centre

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#230]
On https://dev.happytravel.com/ and https://edo-dev.happytravel.com/signalr/notifications/agents
In Chrome, Firefox, Safari.

**Steps.**
1. Log in https://dev.happytravel.com/ and https://edo-dev.happytravel.com/signalr/notifications/agents (use the same token);
2. Make booking in any hotel;
3. Find all notification which «target":"ReceiveMessage".

**Result.**
Only two messages that relate to bookings made in notifications centre: notification of a change in booking status and notification of an Invoice email, but the agent has still received the Finalized email.
For example.
This booking which reference code DEV-HTL-AD-000QI4-01 was made in TravelGate supplier and pay which Offline method, but only one notification was been in notification centre about email:
<img width="1000" alt="Снимок экрана 2021-05-18 в 12 19 48" src="https://user-images.githubusercontent.com/17127277/118635188-f9b45d00-b7db-11eb-88f1-5a636d6bb18d.png">

**Expectations.**
When a booking is made, the agent receives two emails: Invoice and Finalized and the corresponding notifications should be in notification centre.

**Comment by sergeyf-QA** [comment]
**Summary:**
now there are logs for finelized mail also

**OK on DEV.**
