### ISSUE TITLE
Bring all dates to the unified format in the email templates: dd-month-yyyy, like 10 January 2021

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#232]
Need to make sure that the dates that come in the email templates are in the unified format.
The dates are used in these templates: 

EDO: Credit card payment received (Agent)
Template ID: d-bbcc2c6cd2234441a6153da4b25a691f 

EDO: Credit card payment received (Administrator)
Template ID: d-689036bb7f324423808cf2dead06f7f4

EDO: Last month bookings
Template ID: d-b320c2ae698e4ffaba882afb023d9a10

EDO: Booking Finalized (to Agent)
Template ID: d-ebfa965b92cd431494258bd6b5a8f078

EDO: Booking Finalized (to Reservations)
Template ID: d-9addc6e97b154ce9afdec1305e5eeddf

EDO: Booking cancelled (to Agent)
Template ID: d-da2c6d74ecb0466283f2b5a8116fba0f

EDO: Booking Cancelled (to Reservations)
Template ID: d-378dbbbe87194aa1bb7dfa1338169739

EDO: Bookings Administrator Summary Notification
Template ID: d-0e0a051dfa62481aa54e3e3bc2ee7d0b

Edo: Bookings Due Payment by Date by an Agency
Template ID: d-6c99ec77db8d47ada2c60477e901116b

EDO: Deadline approaching
Template ID: d-1e69b16152ef45f08426574e19ee8d3c

EDO: Booking Invoice
Template ID: d-9baff8dd811749e0afc1ffb80f0c9f1d 

EDO: Booking Voucher
Template ID: d-3e695c9b10ab4e76ba2a1b0611ce2f5b

EDO: Successful payment receipt
Template ID: d-646b7c9a3b61442c9327b43ec77d9ac5

EDO: Payment link paid notification
Template ID: d-5259343712ee4f61923ebd8ae4abafaf

**Comment by DenisSychev** [comment]
#231

**Comment by Raibo** [comment]
Checked date formatting in following places (as required in task description):
 
 | action | template id | vault name | date string formatting place | line |
 | --- | --- | --- | --- | --- |
 | EDO: Booking Voucher | d-3e695c9b10ab4e76ba2a1b0611ce2f5b | bookingVoucherTemplateId | BookingDocumentsMailingService | 39 | 
 | EDO: Booking Invoice | d-9baff8dd811749e0afc1ffb80f0c9f1d | bookingInvoiceTemplateId | BookingDocumentsMailingService | 76 | 
 | EDO: Successful payment receipt | d-646b7c9a3b61442c9327b43ec77d9ac5 | knownCustomerReceiptTemplateId | BookingDocumentsMailingService | 119 | 
 | EDO: Deadline approaching | d-1e69b16152ef45f08426574e19ee8d3c | bookingDeadlineNotificationTemplateId | BookingNotificationService | 81 | 
 | EDO: Credit card payment received (Agent) | d-bbcc2c6cd2234441a6153da4b25a691f | agentCreditCardPaymentConfirmationTemplateId | BookingNotificationService | 118 | 
 | EDO: Credit card payment received (Administrator) | d-689036bb7f324423808cf2dead06f7f4 | adminCreditCardPaymentConfirmationTemplateId | BookingNotificationService | 118 | 
 | EDO: Booking Finalized (to Agent) | d-ebfa965b92cd431494258bd6b5a8f078 | bookingFinalizedTemplateId | BookingNotificationService | 183 | 
 | EDO: Booking Finalized (to Reservations) | d-9addc6e97b154ce9afdec1305e5eeddf | reservationsBookingFinalizedTemplateId | BookingNotificationService | 183 | 
 | EDO: Booking cancelled (to Agent) | d-da2c6d74ecb0466283f2b5a8116fba0f | bookingCancelledTemplateId | BookingNotificationService | 183 | 
 | EDO: Booking Cancelled (to Reservations) | d-378dbbbe87194aa1bb7dfa1338169739 | reservationsBookingCancelledTemplateId | BookingNotificationService | 183 | 
 | Edo: Bookings Due Payment by Date by an Agency | d-6c99ec77db8d47ada2c60477e901116b | bookingSummaryTemplateId | BookingReportsService | 106 | 
 | EDO: Bookings Administrator Summary Notification | d-0e0a051dfa62481aa54e3e3bc2ee7d0b | bookingAdministratorSummaryTemplateId | BookingReportsService | 172 | 
 | EDO: Last month bookings | d-b320c2ae698e4ffaba882afb023d9a10 | bookingPaymentsSummaryTemplateId | BookingReportsService | 232 | 
 | EDO: Payment link paid notification | d-5259343712ee4f61923ebd8ae4abafaf | unknownCustomerReceiptTemplateId | PaymentLinkNotificationService | 42 |

**Comment by DenisSychev** [comment]
Was made and works at https://happytravel.com/
