### ISSUE TITLE
Implement credit card issuing endpoint to allow create a virtual credit card

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#239]
Input:
- Reference code
- Money amount
- DueDate

Output:
- Card type
- Card number
- Card expiry date
- Card holder name
- Card security code

No additional logic required, just issue a card and return it

**Comment by sergeyf-QA** [comment]
**Summary:**
POST /api/{v}/cards creates a cards for bookings with such output:
Card number
Card expiry date
Card holder name
Card security code

there is no card type because card type is always once

**OK on DEV.**

**Comment by DFSko** [comment]
Done
