### ISSUE TITLE
Add IsActive status for removed hotels and change the logic of the incremental update 

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#241]
We need change the logic of the incremental mode of updater. If the hotel is removed from the supplier, then it should be marked as inactive, but should not be removed from the connector. This information should be given to the mapper at the request of GetAccommodations.
It is also necessary to change the logic of loading hotel descriptions. According to information from the Columbus developers, when the hotel description and images change, the LastUpdated field is not updated. Thus, we must always update the information for all hotels with an incremental update.

**Comment by sergeyf-QA** [comment]
**Summary:**
Get Accommodations now has boolean isActive in response

**OK on DEV.**
