### ISSUE TITLE
"Phone" and "fax" fields have restrictions on the format in the counterparty registration form

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#242]
On https://dev.happytravel.com/
In Chrome, Firefox, Safari.

**Steps.**
1. Start registering a new counterparty;
2. After confirming the email address, fill in all required fields, but enter the numbers in "phone" and "fax" fields as they are usually written on websites, business cards, etc. For example, 1-222-333-4455 or +1(222)333-4455

**Result.**
"Phone" and "fax" fields have restrictions on the format in the counterparty registration form (see pic.)
<img width="974" alt="Снимок экрана 2021-05-19 в 17 14 43" src="https://user-images.githubusercontent.com/17127277/119497674-87a8be80-bd6d-11eb-816c-7b049f4bb5c8.png">
POST dev.../en/api/1.0/agent/register-master
```
{
    "status": 400,
    "detail": "'Phone' is not in the correct format."
}
```

**Expectations.**
"Phone" and "fax" fields should have no restrictions on the format in the counterparty registration form.

**Comment by mingazhev** [comment]
@Raibo could you check?

**Comment by sergeyf-QA** [comment]
**Summary:**
now it is possible to enter anything into the Phone and Fax fields.

**OK on DEV.**
