### ISSUE TITLE
Legal address isn't required when registering a new counterparty

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#249]
On https://dev.happytravel.com/
In Chrome, Firefox, Safari.

**Steps.**
1. Try to register a new counterparty;
2. After confirming the email address, fill in all the required fields, but don't fill "Legal address".

**Result.**
Legal address isn't required when registering a new counterparty (see pics.)
<img width="1173" alt="Снимок экрана 2021-05-25 в 15 32 46" src="https://user-images.githubusercontent.com/17127277/119537058-58f10f00-bd92-11eb-85b9-a82813984e10.png">
<img width="538" alt="Снимок экрана 2021-05-25 в 15 33 01" src="https://user-images.githubusercontent.com/17127277/119537068-5bebff80-bd92-11eb-8ba5-fdea860a7924.png">

**Expectations.**
Legal address is required so agent must complete this field. If the field isn't filled the website should display a message and not register a counterparty.

**Comment by sergeyf-QA** [comment]
@konstyefremov 
issue is not fixed

**Comment by konstyefremov** [comment]
I investigated the issue. It's not a backend bug. 

If Legal Address is not filled, but the Company Address is filled, then the Legal Address is taken from the latter. 

See here:
https://github.com/happy-travel/matsumoto/blob/6cc56ac675c60254eac79e5a5000b692d82d466d/src/tasks/signup/signup-finish.js#L35

**Comment by mingazhev** [comment]
Moving to frontend @alexander-plekhanov could you check?

**Comment by sergeyf-QA** [comment]
**Summary:**
Fixed required Legal address field

**OK on DEV.**
