### ISSUE TITLE
Manual booking cancellation

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#25]
/en/api/1.0/admin/accommodations/bookings/{bookingId}/cancel-manually

With a body like:
{
	"cancellationDate": "2021-04-23T18:25:43.511Z",
	"reason": "Support's letter"
}

Calling this endpoint should:
1. Make booking cancelled without any request to supplier
2. Apply cancellation penalties according to the date in "cancellationDate" property (just if booking was cancelled normally in this date)

**Comment by sergeyf-QA** [comment]
**Summary:**
bookings may be cancelled manually by admin only using POST /{culture}/api/{v}/admin/accommodations/bookings/{bookingId}/cancel-manually and applying penalties if it was cancelled within deadline

**OK on DEV.**

**Comment by mingazhev** [comment]
Closing this issue since it is already on prod and was used there successfully
