### ISSUE TITLE
The new counterparty isn’t filled with Nationality and Residency

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#251]
On https://dev.happytravel.com/
In Chrome, Firefox, Safari.

**Steps.**
1.1 Register a new counterparty;
OR
1.2. Log in this agent (this is the counterparty with pending verification status)
https://passbolt.happytravel.com/app/passwords/view/8c5098fb-20b8-4b2f-bb60-e62f683a1937
2. Note the "Nationality" and "Residency" fields;
3. Go to Settings -> Personal page and Note the "Nationality" and "Residency" fields.

**Result.**
The new counterparty isn’t filled with Nationality and Residency (see pic.)
<img width="1121" alt="Снимок экрана 2021-05-26 в 11 35 47" src="https://user-images.githubusercontent.com/17127277/119629536-c5155680-be16-11eb-9e0b-0794885a04f7.png">
<img width="1121" alt="Снимок экрана 2021-05-26 в 11 35 56" src="https://user-images.githubusercontent.com/17127277/119629543-c777b080-be16-11eb-9d3e-7df19bd5cca0.png">

**Expectations.**
Nationality and Residency must be set according to the country filled when registering the counterparty. For example, if the company is from Canada, the Nationality and Residency must be Canada.

**Comment by sergeyf-QA** [comment]
**Summary:**
Nationality, Residency, Country and City are filled by info from 'Company Locality' entered on registration step.

**OK on DEV.**
