### ISSUE TITLE
Check all connector updaters to have stdout logger and sentry connected

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#258]
Sentry projects management is on @evm-andrey side.
In this task it is needed to check the code

**Comment by mingazhev** [comment]
@Raibo could you have a look please?

Need to check:
- Netstorming
- Illusions
- ETG
- Columbus
- Jumeirah
- Travelgate

**Comment by mingazhev** [comment]
@AlexeyShok columbus is for you

**Comment by sergeyf-QA** [comment]
@Raibo 
your turn

**Comment by mingazhev** [comment]
@Raibo
