### ISSUE TITLE
Remove old search flow in EDO

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#262]

**Comment by mingazhev** [comment]
What to test:
Nothing in 1-st and 2-nd step availability search is broken

**Comment by DenisSychev** [comment]
#276

**Comment by mingazhev** [comment]
> 
> 
> #276

This was fixed

**Comment by sergeyf-QA** [comment]
**Summary:**
Search looks fine

**OK on DEV.**
