### ISSUE TITLE
It is necessary to enable VAT number and Billing email to be specified and to be able to change them

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#274]
There are fields in the database for storing VAT number and Billing email. The Billing email going to use to send out invoices after the booking has been paid for. The VAT number could probably be used for personalising vouchers.

Agents and administrators haven't possibility of specifying or changing these values.

It is necessary to enable VAT number and Billing email to be specified and to be able to change them.

**Comment by mingazhev** [comment]
@Raibo could you have a look and decide how to enable this feature? may be we need new endpoints or extend existing

**Comment by Raibo** [comment]
Billing email is already editable at the moment of me taking the task.
Added VAT to be also editable beside other Agency fields.

**Comment by kirillta** [comment]
Then this one goes to frontend

**Comment by sergeyf-QA** [comment]
**Summary:**
PUT https://edo-dev.happytravel.com/en/api/1.0/agency writes VAT# and Billing mail into the DB

**OK on DEV.**
