### ISSUE TITLE
What is your log problem?

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#278]
Please add your comments to this issue, we'll collect and process them to create tasks

**Comment by kirillta** [comment]
Hard to find anything with Kibana. The UI is counter-intuitive.

**Comment by AlexeyShok** [comment]
Kibana must have the same eventId for the same events in different connectors.

**Comment by DFSko** [comment]
maybe we need a simple interface with a select of project and event

**Comment by oleg1std** [comment]
There is a separate tool for logging 
https://logs-dev.happytravel.com/app/logs/stream
It might be used
![image](https://user-images.githubusercontent.com/36402224/121525044-97c4cd00-ca00-11eb-959d-a621afdc8692.png)

**Comment by DFSko** [comment]
added logs dashboard
