### ISSUE TITLE
Different cost of each room and total cost of booking

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#282]
First offer for hotel - Hotel Test Pruebas Travelgate, Andorra La Vella, Andorra (2 rooms)

<img width="1163" alt="Screenshot 2021-06-02 at 05 39 13" src="https://user-images.githubusercontent.com/38030865/120416059-37c98900-c365-11eb-83d7-1c40da7823c6.png">

**Comment by mingazhev** [comment]
Looks like this is related with currency conversion ceiling

**Comment by Raibo** [comment]
It looks similar to https://github.com/happy-travel/agent-app-project/issues/301, but there mismatch only by 1 cent, here mismatch 2 cents, which might be not a rounding issue.

**Comment by mingazhev** [comment]
@nikolaeva31 could you check that is not repeated and close if not?
