### ISSUE TITLE
Error when canceling booking with past deadline

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#283]
1. Find an option with Cancellation deadline button (first step)
`Dubai, The United Arab Emirates - 04.06-05.06 - 2 rooms ` 
`Hotel - Jumeirah Beach Hotel - second offer`
2. Create a booking with this offer where 
```
isAdvancePurchaseRate: false

deadlineDetails: 
date: "2021-05-27T00:00:00Z"
isFinal: true 
```
3. Try to cancel after successful creation

**AR**: Error when canceling booking with past deadline  

https://sentry.happytravel.com/organizations/happytravel/issues/1209/events/c448fad73a904199ab222e64b3bab774/ 

![Screenshot 2021-06-02 at 06 13 51](https://user-images.githubusercontent.com/38030865/120418758-cd671780-c369-11eb-81e1-5c0ef23f5141.png)

**Comment by ViTsvetkova** [comment]
@nikolaeva31 can you reproduce this error still?
