### ISSUE TITLE
Bookings page fails to white screen after opening in new tab

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#293]
**Steps to reproduce:**
1. Open Mozilla Firefox, login as an agent with permissions to see all bookings.
2. Go to Bookings page
3. Open another one Bookings page in new tab
4. Press "show only my bookings" checkbox

**Result:**
White screen and console errors:

![изображение](https://user-images.githubusercontent.com/43397444/120602728-bc4f0100-c464-11eb-8280-02098969008e.png)

**Expected result:**
All works fine on the new tab.

**Comment by sergeyf-QA** [comment]
**Summary:**
All works fine on the new tab.

**OK on DEV.**
