### ISSUE TITLE
Remove all normalization logic from connectors

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#296]
Need to remove normalization library, all it's usages and return non-normalized names and etc. in location controller endpoints.
@Raibo for you is to check and remove from connectors:

Netstorming
Illusions
Etg
Rakuten
Columbus
TravelgateXTest

Please tell @hasmikharutyunyan to check the normalization in mapper once will be done

**Comment by Raibo** [comment]
Nothing to remove in Columbus

**Comment by DenisSychev** [comment]
An internal task that doesn't require testing. 
The data from suppliers now goes to the mapper in its original form.
