### ISSUE TITLE
Booking has status 'Pending'

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#300]
1. Search data:
`Jumeirah Emirates Towers, Dubai, The United Arab Emirates - 10.06 - 11.06 - 1 room - 2 adults`
2. Choose option with cost = $154.90
![Screenshot 2021-06-03 at 18 34 23](https://user-images.githubusercontent.com/38030865/120671822-6c8b2c80-c49a-11eb-83d5-4d6b74218bdc.png)

3. Pay the booking of selected option

**AR**: Booking has status 'Pending' and method 'refresh-status' returns error:
` {"status":400,"detail":"Could not find reservation info for code DEV-HTL-AE-0001N4-01\n"}
`

**Comment by mingazhev** [comment]
This should not repeat, at least on dev
