### ISSUE TITLE
TotalСost is less than cost of rooms when converting currencies 

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#301]
1.  Search data - multi-room booking:
`Hotel Test Pruebas Travelgate, Andorra La Vella, Andorra - 2 rooms`
2. Choose first offer 

**AR**: TotalCost is less than sum of room costs
<img width="1141" alt="Screenshot 2021-06-03 at 18 54 16" src="https://user-images.githubusercontent.com/38030865/120674947-487d1a80-c49d-11eb-8479-46bc6b0c33a8.png">

**Comment by mingazhev** [comment]
Looks like there is some ceiling issue there, @Raibo could you please have a look?

**Comment by Raibo** [comment]
We discussed this problem and came to a conclusion that this one cent mismatch would appear here and there anyway, the only way we could fix it - is by adjusting a price for one of the rooms, which we decided not to do.
It's just how rounding works (And we sum the values before rounding)
