### ISSUE TITLE
Show only your notification settings for admins and agents

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#302]
Now, upon requests to receive a list of notification settings for agents (admins), all settings are received. It is necessary to return only those settings for which there is a default mailing to agents (admins).

**Comment by sergeyf-QA** [comment]
**Summary:**
settings are returned according to rules from attached file
[message.txt](https://github.com/happy-travel/agent-app-project/files/6631979/message.txt)
by
GET /{culture}/api/{v}/notifications/settings  for agents
GET /{culture}/api/{v}/admin/notifications/settings for admins

**OK on DEV.**
