### ISSUE TITLE
Add notifications for agency management events

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#303]
We need to add notifications for the following events:
Changing the status of the agency's activity. The mandatory notification is sent to the master agent of the agency to email and toast.

**Comment by sergeyf-QA** [comment]
**Summary:**
POST /{culture}/api/{v}/agency/child-agencies/{agencyId}/deactivate
POST /{culture}/api/{v}/agency/child-agencies/{agencyId}/activate
trigger AgencyActivityChanged = 15 notification.

**OK on DEV.**
