### ISSUE TITLE
Add notification about change counterparty verification status 

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#309]
We need notification about change counterparty verification status. The mandatory notification is sent to the master agent of the root agency to email and toast.

**Comment by DenisSychev** [comment]
The task is blocked by this task #345

**Comment by sergeyf-QA** [comment]
**Summary:**
notifications for 
POST /{culture}/api/{v}/admin/counterparties/{counterpartyId}/verify-read-only
POST /{culture}/api/{v}/admin/counterparties/{counterpartyId}/verify-full-access
are in "Notifications" table

**OK on DEV.**
