### ISSUE TITLE
AccommodationUncertainMatches on the production environment 

### ISSUE THREAD

**Issue by oleg-n-k** [happy-travel/agent-app-project#310]
There are 315168 rows in the AccommodationUncertainMatches table.
Analyze and find the cause.

**Comment by ViTsvetkova** [comment]
@hasmikharutyunyan please update the status

**Comment by hasmikharutyunyan** [comment]
> @hasmikharutyunyan please update the status
Now we have no functionality for AccommodationUncertainMatches from admin panel, so it will be done, bu not right now

**Comment by hasmikharutyunyan** [comment]
Not actual for now
