### ISSUE TITLE
Emulate ETG TGX requests to find and repeat problems in EDO or Illusions 

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#311]
Mainly need to catch the problem with database and redis transient errors:
https://sentry.dev.happytravel.com/organizations/happytravel/issues/2071/?project=6&query=is%3Aunresolved&statsPeriod=14d

https://sentry.dev.happytravel.com/organizations/happytravel/issues/1950/events/?project=6&statsPeriod=14d

https://sentry.dev.happytravel.com/organizations/happytravel/issues/2076/?project=6&query=&statsPeriod=30d

https://sentry.dev.happytravel.com/organizations/happytravel/issues/1950/events/?project=6&statsPeriod=14d

**Comment by DFSko** [comment]
@ViTsvetkova i guess this task isn't actual for now
