### ISSUE TITLE
Jumeirah "TooManyRequests" requests handling

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#312]
Jumeirah API can return 429 (Too many requests) status if we query their API too often (any endpoint).
Need to handle such situations and make a retry later to get the results.
The common logic from the first glance should be like:
- Make all requests as usual
- If response code 429 is returned, make a queue of requests and allow only fixed number of them to run simultaneosly. If still getting the error, need to limit to a lower threshold and so on until code disappear
- After 429 code is gone, remove request limits

Additionally:
- this situation must be logged.
- need unit tests for the strategy
- request that failed with such error should be retried

**Comment by ViTsvetkova** [comment]
@mingazhev please update, was it done?

**Comment by mingazhev** [comment]
No, looks not actual for now since they never returned us such status
