### ISSUE TITLE
Separate LocationNameNormalizer to two libraries.

### ISSUE THREAD

**Issue by hasmikharutyunyan** [happy-travel/agent-app-project#315]
Needed separate LocationNameNormalizer to two libraries:
1. Normalizer for locations.
2. Name normalizer (string normalization, html, etc.)

**Comment by ViTsvetkova** [comment]
@hasmikharutyunyan is this task still actual?

**Comment by hasmikharutyunyan** [comment]
As we will have new mapper this issue no needed fro now
