### ISSUE TITLE
Netstorming connector updater does not update properties that are used in mapper

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#317]
Updater changes RawHotelInfos table while data from "Hotels" table is returned to mapper.
Need to decide which one to use and remove not used table.

@hasmikharutyunyan may help to choose

**Comment by kirillta** [comment]
@hasmikharutyunyan this one is obsolete, isn't it?

**Comment by hasmikharutyunyan** [comment]
This is not actual, as `netstorming` database structure changed
