### ISSUE TITLE
Fix duplicates in predictions (1)

### ISSUE THREAD

**Issue by oleg-n-k** [happy-travel/agent-app-project#321]
![image](https://user-images.githubusercontent.com/36402224/122081240-9e3fb400-ce07-11eb-9636-ec8dd23f4165.png)
![image](https://user-images.githubusercontent.com/36402224/122081261-a3046800-ce07-11eb-80c5-01b28af5b89d.png)
![image](https://user-images.githubusercontent.com/36402224/122081304-aac40c80-ce07-11eb-9bcd-e3cf2a832b2f.png)
![image](https://user-images.githubusercontent.com/36402224/122081318-ae579380-ce07-11eb-82fb-36d02b77d4e2.png)
![image](https://user-images.githubusercontent.com/36402224/122081353-b283b100-ce07-11eb-9b0f-d2f343407e6d.png)
![image](https://user-images.githubusercontent.com/36402224/122081373-b6173800-ce07-11eb-8c3e-852a265fda91.png)
![image](https://user-images.githubusercontent.com/36402224/122081389-ba435580-ce07-11eb-9f92-63ac1b956429.png)

**Comment by hasmikharutyunyan** [comment]
Done manual merge of accommodations with name `bulgari dubai`. Reasons were - not correcct coordinates, and some not implemented logic of string comparision, for that opened issue https://github.com/happy-travel/agent-app-project/issues/352

**Comment by hasmikharutyunyan** [comment]
For` Mandarin dubai`  previosly done manual merge.

**Comment by hasmikharutyunyan** [comment]
Now for search query `Burj al arab` we have the following results
![Screenshot from 2021-06-22 17-08-23](https://user-images.githubusercontent.com/43600025/122930307-ec5f3500-d37c-11eb-8766-b62982e72fbd.png)
I think nothing to merge here.

**Comment by hasmikharutyunyan** [comment]
For `Royal Mirage Dubai` we have folowing results now
![Screenshot from 2021-06-22 17-13-29](https://user-images.githubusercontent.com/43600025/122931012-8cb55980-d37d-11eb-9a72-605b4f2710a8.png)
Needed indicate concrete hotels, which we must to merge.

**Comment by hasmikharutyunyan** [comment]
For `Bulgary dubai` query in predictions we have the folowing result
![Screenshot from 2021-06-22 17-15-42](https://user-images.githubusercontent.com/43600025/122931510-03525700-d37e-11eb-8f3f-a576cfa94e7c.png)
Nothing to merge.

**Comment by hasmikharutyunyan** [comment]
For `Four seasons` done merge for `Four Seasons Hotel Dubai International Financial Centre, Dubai, The United Arab Emirates` and `Four Seasons Hotel Difc, Dubai, The United Arab Emirates`
But I found that `Four Seasons Resort Dubai At Jumeirah Beach, Dubai, The United Arab Emirates` is not the same hotel, needed double check.
