### ISSUE TITLE
Documentation for isDirectContracts

### ISSUE THREAD

**Issue by Raibo** [happy-travel/agent-app-project#322]

**Comment by Raibo** [comment]
### What is a direct contract
Generally, we book for our clients through a supplier, which means that they add their markup to the overall cost.
With Illusions supplier however, we have an additional agreement, which allows us to make a deal directly with a hotel, without the supplier's additional markup. This only works for a limited number of rooms inside a limited number of accommodations.

**Direct contract** means that we have a given room listed in the agreement, so that it is booked without Illusion's markup.

### Details
We have all the rooms listed in a separate table - `DirectConnectivityContractTokens`. Each token specifies AccommodationCode and ContractTokenId.
AccommodationCode tells which hotel
ContractTokenId tells which room.

It is possible that the accommodation is listed as a direct contract, but the room is not, then direct contract does not apply.
In order for this to work, both hotel and room must match.

In table `Accommodations` we have a column `HasDirectContract`. It is updated every time `DirectConnectivityContractTokens` is updated.
This flag means that the accommodation has rooms with direct contract. (There could still be some rooms without direct contract in such accommodation)

**Comment by mingazhev** [comment]
I like this, please add to the docs or ask @kirillta to help.
And you've mentioned that this flag may not work correctly on production (is not filled).
Could you please pay attention and create an issue if something works incorrect?

**Comment by Raibo** [comment]
Added https://github.com/happy-travel/agent-app-project/issues/437 for what I mentioned.

**Comment by Raibo** [comment]
Wiki page https://github.com/happy-travel/docs/wiki/Booking-%5C-Direct-contract-(illusions)

**Comment by kirillta** [comment]
LGTM
