### ISSUE TITLE
Documentation for isFinalDeadline

### ISSUE THREAD

**Issue by Raibo** [happy-travel/agent-app-project#323]

**Comment by Raibo** [comment]
### Deadline and IsFinal
Deadline is a date, after which a client can not return the full price when they cancel a booking. Though, it may be possible to refund partially. (this depends on [cancellation policies](https://github.com/happy-travel/edo/wiki/Booking-%5C-Deadline-and-Cancellation-Policies))

The flag `isFinal` is set when we know for sure that the displayed deadline date is correct.

### When a deadline may be not final
When we perform a search, many things are cached, so that the values shown are roughly same, but not always exactly. 
Differences may occur if something have changed since last time the data was cached.

### What this flag does
The flag is used by front end. If `isFinal` is false, then a button is shown, which retrieves a final exact deadline.

**Comment by mingazhev** [comment]
Mainly ok for me, but will be more clear if there were a screen with this frontend button.
Please add this to our docs or ask devops or @kirillta to help with that

**Comment by Raibo** [comment]
Wiki page https://github.com/happy-travel/docs/wiki/Booking-%5C-IsFinalDeadline-property

**Comment by kirillta** [comment]
LGTM
