### ISSUE TITLE
Documentation for ManualAdditionalRemarks

### ISSUE THREAD

**Issue by Raibo** [happy-travel/agent-app-project#324]

**Comment by Raibo** [comment]
Manual additional remarks are manually set information notes, bound to hotels.
They are used to store information, which can be important, but is not included in supplier's additional remarks.

For example, a hotel might include additional mandatory fees for services, or other details, which are important.

**Comment by mingazhev** [comment]
Please add examples, you can ask QA team or in discord for real-world cases. Will be very useful

**Comment by Raibo** [comment]
Wiki page https://github.com/happy-travel/docs/wiki/Booking-%5C-Manual-Additional-Remarks

**Comment by Raibo** [comment]
No examples were ever found, so I close the task.
