### ISSUE TITLE
Edit agency roles endpoints

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#329]
Need to add CRUD operations to manage the roles, available for admins only.
Role can be deleted only if it is not used anywhere

**Comment by Raibo** [comment]
GET `en/api/1.0/admin/agent-roles`
POST `en/api/1.0/admin/agent-roles`
PUT `en/api/1.0/admin/agent-roles/:roleId`
DELETE `en/api/1.0/admin/agent-roles/:roleId`

**Comment by sergeyf-QA** [comment]
**Summary:**
GET /{culture}/api/{v}/admin/agent-roles returns all available roles for agents
POST /{culture}/api/{v}/admin/agent-roles creates an agent role
PUT /{culture}/api/{v}/admin/agent-roles/{roleId} edits an existing role
DELETE /{culture}/api/{v}/admin/agent-roles/{roleId} deletes an agent role

**OK on DEV.**
