### ISSUE TITLE
Failed booking creates booking with WaitingForResponse status

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#33]
Steps to reproduce:
1. Find any hotel in dev, ETG (other than test hotel in belogorsk)
2. Try to book

Result:
Error is raised, but actually booking is created and have WaitingForResponse status.

Expected result:
Booking is not shown or have invalid status

**Comment by sergeyf-QA** [comment]
@mingazhev 
when I tested then I at first case I saw the issue but on 2nd one - there was no error, could you please look again?
Thanks.

**Comment by mingazhev** [comment]
No error should be now. Contracts and booking failure codes are fixed. May be tested with ETG again

**Comment by sergeyf-QA** [comment]
@mingazhev 
now 
https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/book-by-account
https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/DEV-HTL-RU-000HO4-01/finalize
returns
{"status":400,"detail":"sandbox_restriction"}

**Comment by mingazhev** [comment]
this is ok and fine. bad if booking goes to pending status instead
