### ISSUE TITLE
Add an endpoint to edit admin roles

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#334]
Need to add endpoints for CRUD operations against admin roles, the same as for agents. Maybe we'll need additional permission for that

**Comment by DenisSychev** [comment]
AdministratorRoles
GET /{culture}/api/{v}/admin/administrator-roles
POST /{culture}/api/{v}/admin/administrator-roles
PUT /{culture}/api/{v}/admin/administrator-roles/{roleId}
DELETE /{culture}/api/{v}/admin/administrator-roles/{roleId}
