### ISSUE TITLE
Trim passenger names before sending booking request

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#337]
Need to remove whitespaces around last and first names before sending a booking request to connector

**Comment by sergeyf-QA** [comment]
**Summary:**
now, mainPassengerName has no spaces around last and first names in request of POST https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings
e.g. mainPassengerName: "f1 l1"

**OK on DEV.**
