### ISSUE TITLE
Search error when choosing a location

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#338]
1. Enter and choose 'Italy, Italy'
```
Request URL: https://edo-dev.happytravel.com/en/api/1.0/accommodations/availabilities/searches

{"checkInDate":"2021-06-26T00:00:00Z","checkOutDate":"2021-06-27T00:00:00Z","roomDetails":[{"adultsNumber":2,"childrenNumber":0}],"nationality":"RU","residency":"RU","htIds":["Locality_654062"]}
```

**AR**: Get an error:
`{"status":400,"detail":"Could not find requested search locations"}`

![Screenshot 2021-06-19 at 08 54 57](https://user-images.githubusercontent.com/38030865/122740913-1e916980-d28d-11eb-9c04-c6e1d3dd062e.png)

**Comment by ViTsvetkova** [comment]
@nikolaeva31 please close if it was resolved
