### ISSUE TITLE
Modify the MergeLocationInfo method. Localities and Localities zone must be retrived from the DB

### ISSUE THREAD

**Issue by oleg-n-k** [happy-travel/agent-app-project#340]
Modify the MergeLocationInfo method. Localities and Localities zone must be retrieved from the DB

**Comment by hasmikharutyunyan** [comment]
Now Location information in MergeLocationInfo we get from RawAccommodations table ( supplier data).
Needed to change logic, to get location info from Accommodations Locality, LocalityZone relations. The reason is thet Locality, LocalityZone relations we can change manually.
