### ISSUE TITLE
Update logging-related packages in all services

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#342]
Need to:
1. Update stdoutlogger to the latest
2. Include scopes everywhere
3. Add consul kv-client and create a path in consul + add CONSUL_HTTP_ADDR: "https://consul.happytravel.com/" to env in prod 
and CONSUL_HTTP_ADDR: "https://consul-dev.happytravel.com/" in dev yamls

4. Set logging level in appsettings.json as following:

```
"Logging": {
    "LogLevel": {
      "Default": "Warning",
      "HappyTravel": "Information",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
```

in appsettings.Development.json

```
"Logging": {
    "LogLevel": {
      "Default": "Information"
    }
  },
```

5. Check that OpenTelemetry is configured (to allow use TraceId)

Repositories:

https://github.com/happy-travel/jumeirah-connector
https://github.com/happy-travel/edo
https://github.com/happy-travel/nakijin
https://github.com/happy-travel/osaka
https://github.com/happy-travel/travelgatex-connector
https://github.com/happy-travel/netstorming-connector
https://github.com/happy-travel/columbus-connector
https://github.com/happy-travel/etg-connector
https://github.com/happy-travel/iwtx-connector
https://github.com/happy-travel/rakuten-connector
https://github.com/happy-travel/netstorming-updater
https://github.com/happy-travel/kanazawa
https://github.com/happy-travel/gifu
https://github.com/happy-travel/odawara
https://github.com/happy-travel/tsutsujigasaki
https://github.com/happy-travel/uwajima
https://github.com/happy-travel/fukuoka

**Comment by DFSko** [comment]
updated in all listed repositories

**Comment by sergeyf-QA** [comment]
**Summary:**
all connectors were updated
https://github.com/happy-travel/jumeirah-connector
https://github.com/happy-travel/edo
https://github.com/happy-travel/nakijin
https://github.com/happy-travel/osaka
https://github.com/happy-travel/travelgatex-connector
https://github.com/happy-travel/netstorming-connector
https://github.com/happy-travel/columbus-connector
https://github.com/happy-travel/etg-connector
https://github.com/happy-travel/iwtx-connector
https://github.com/happy-travel/rakuten-connector
https://github.com/happy-travel/netstorming-updater
https://github.com/happy-travel/kanazawa
https://github.com/happy-travel/gifu
https://github.com/happy-travel/odawara
https://github.com/happy-travel/tsutsujigasaki
https://github.com/happy-travel/uwajima
https://github.com/happy-travel/fukuoka


**OK on DEV.**
