### ISSUE TITLE
Error while parsing unsuccessful server response from mapper

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#343]
https://sentry.dev.happytravel.com/organizations/happytravel/issues/2227/?environment=Production&query=is%3Aunresolved&statsPeriod=14d

**Comment by mingazhev** [comment]
Testing tips:
Send availability request to EDO-backend and pass there invalid HtId (any string like "some_string", error in sentry should not appear.
Additionally can send a valid but not existing HtId, like "Accommodation_9999999999"

**Comment by sergeyf-QA** [comment]
**Summary:**
now there is no sentry error when POST /{culture}/api/{v}/accommodations/availabilities/searches is executing with wrong HtId.

**OK on DEV.**
