### ISSUE TITLE
Check in date is not validated while searching and this causes errors on connectors

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#344]
Need to add a validation for check in date before starting availabilty search on EDO.

**Comment by mingazhev** [comment]
Testing tips:
Searching for dates in the past should be allowed. Searching for dates starting from today should be allowed

**Comment by sergeyf-QA** [comment]
**Summary:**
now, when "checkInDate" from past is used while executing POST /{culture}/api/{v}/accommodations/availabilities/searches then I receive
{
  "status": 400,
  "detail": "Check in date must not be in the past"
}


**OK on DEV.**

**Comment by mingazhev** [comment]
Already on production
