### ISSUE TITLE
Counterparty deactivation doesn’t work

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#345]
On https://manage-dev.happytravel.com/
In Chrome, Firefox, Safari.

**Steps.**
1. Log in and go to Counterparties list (click on Counterparties button);
2. Find the «The Five counterparty»;
3. Go to counterparty information page;
4. Try to deactivate this counterparty.

**Expectations.**
Counterparty deactivation have to work without errors. Emails have to send after deactivation.

**Result.**
Counterparty deactivation doesn’t work. 
There is a response with status code 500. Detailed description in Sentry ID: 9122c82847e54884946aa6f8cf0b2d96
For example, https://edo-dev.happytravel.com/en/api/1.0/admin/counterparties/173/deactivate
```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.6.1",
    "title": "Internal Server Error",
    "status": 500,
    "detail": "You attempted to access the Value property for a failed result. A failed result has no Value. The error was: Cannot find notification options for the type 'CounterpartyActivityChanged'",
    "instance": "/en/api/1.0/admin/counterparties/173/deactivate",
    "spanId": "e135a9307b1c9e42",
    "traceId": "41507a68d659764889ca03de74cc361e",
    "requestId": "0HM9L8JOOCMQI:00000002",
    "x-request-id": [
        "cab6e5e5636cb855c5668db2a37a2a2a"
    ],...
```
<img width="1298" alt="Снимок экрана 2021-06-22 в 10 16 57" src="https://user-images.githubusercontent.com/17127277/122884345-b8691d00-d346-11eb-871d-aa8da6e0651d.png">

**Comment by sergeyf-QA** [comment]
**Summary:**
https://edo-dev.happytravel.com/en/api/1.0/admin/counterparties/173/deactivate works fine and deactivates an agency.

**OK on DEV.**
