### ISSUE TITLE
An endpoint to show booking changes history to an agent

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#35]
Need to return a reasonable list of booking changes, suitable for an agent.

**Comment by sergeyf-QA** [comment]
**Summary:**
GET /{culture}/api/{v}/accommodations/bookings/{bookingId}/status-history returns list of booking statuses only in borders of Agency where user is in case if he has enabled Agency Bookings Management rights.


**OK on DEV.**
