### ISSUE TITLE
Improve string comparision in mapper

### ISSUE THREAD

**Issue by hasmikharutyunyan** [happy-travel/agent-app-project#352]
Improve comparision of strings in mapping algorithm, to ignore endings. Example Resort and Resorts must be considered as one word. To consider some letters combination `ph` and `f` must be considered as same.

**Comment by ViTsvetkova** [comment]
@hasmikharutyunyan should we close this issue or will you resolve it?

**Comment by hasmikharutyunyan** [comment]
> @hasmikharutyunyan should we close this issue or will you resolve it?

We can close
