### ISSUE TITLE
Add configurable request logging to all connectors

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#356]
Need to:
1. Add request logging package:
https://github.com/happy-travel/http-request-logging-handler/

2. Remove existing request and response logging (if any)
3. Add default setting to appsettings.json (on the root level):

```json
 "RequestLoggingOptions": 
  {
  	"IsEnabled": false
  }
```

for the following connectors:
https://github.com/happy-travel/netstorming-connector - done
https://github.com/happy-travel/columbus-connector - done
https://github.com/happy-travel/etg-connector - done
https://github.com/happy-travel/iwtx-connector - done
https://github.com/happy-travel/rakuten-connector - done

For reference of usage you can look at travelgate-connector or Jumeirah-connector

Additionally need to update the audit logging package to the latest, with new package name:

**Comment by AlexeyShok** [comment]
QA, to check, you need to go to Consul https://consul-dev.happytravel.com (password in Passbolt) and change the value of the following setting:
"RequestLoggingOptions": 
  {
  	"IsEnabled": false
  }
and make sure that if "true", requests are logged, but not if "false".

**Comment by sergeyf-QA** [comment]
**Summary:**
in case setting for connector is set to 'false' in consul logs are not existed, if 'true' - they are.

**OK on DEV.**
