### ISSUE TITLE
Add an endpoint to assign roles to an admin

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#358]
Additional:
Changing roles for administrator should be written to audit log.

Need to add created endpoint URLs to Insomnia and this ticket comments for frontend reference

**Comment by Raibo** [comment]
PUT `en/api/1.0/admin/administrators/:adminId/roles`

**Comment by sergeyf-QA** [comment]
**Summary:**
PUT /{culture}/api/{v}/admin/administrators/{administratorId}/roles
sets existed roles to the pointed admin

**OK on DEV.**
