### ISSUE TITLE
Add endpoints to manage administators

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#359]
Need frontent-usable endpoints for:
- Viewing a list of administrator (with assigned roles)
- Activating or deactivating certain administrator

Admin activation and deactivation should be written to management audit log.

Need to add created endpoint URLs to Insomnia and this ticket comments for frontend reference

**Comment by Raibo** [comment]
`/en/api/1.0/admin/administrators`
`/en/api/1.0/admin/administrators/:adminId/activate`
`/en/api/1.0/admin/administrators/:adminId/deactivate`

**Comment by sergeyf-QA** [comment]
**Summary:**
GET /{culture}/api/{v}/admin/administrators returns all administrators information
POST /{culture}​/api​/{v}​/admin​/administrators​/{administratorId}​/activate activates an admin
POST ​/{culture}​/api​/{v}​/admin​/administrators​/{administratorId}​/deactivate deactivates an admin

**OK on DEV.**
