### ISSUE TITLE
Change permission edit endpoints to use agent roles

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#364]
Need to:
1. Return agent role along with agent information (instead of permissions list)
2. Add an endpoint to assign roles to an agent (instead of assigning permissions)

Additionally need to add these endpoints to this ticket comments and to Insomnia

**Comment by mingazhev** [comment]
I think that there should be new endpoints, with preserving old endpoints for now

**Comment by Raibo** [comment]
PUT `/:culture/api/1.0/agency/agents/:agentId/roles`

**Comment by sergeyf-QA** [comment]
**Summary:**
PUT /{culture}/api/{v}/agency/agents/{agentId}/roles updates agent roles

**OK on DEV.**
