### ISSUE TITLE
Try remove or rename InAgencyPermissions column in AgentAgencyRelationsTable

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#366]
Need to change all the usages of this column to roles usage, without actually removing the column for now.

**Comment by mingazhev** [comment]
For getting current Agent, `AgentInfoInAgency` and in `AgentDescription` need to return permissions while in other places roles should be used

**Comment by konstyefremov** [comment]
> For getting current Agent, `AgentInfoInAgency` and in `AgentDescription` need to return permissions while in other places roles should be used

I still cannot find "other places". Roles assignment is already added by Bogdan here - https://github.com/happy-travel/edo/blob/6568a02d29908b8d9231e5acdb961ec11ea41351/Api/Controllers/AgentControllers/AgentsController.cs#L376

Is it enough?
