### ISSUE TITLE
Remove Raw sql when ef core will support queries with dictionaries

### ISSUE THREAD

**Issue by hasmikharutyunyan** [happy-travel/agent-app-project#372]
When will be removed Suppliers enum fully it can be done.

**Comment by ViTsvetkova** [comment]
@hasmikharutyunyan is it still actual task?

**Comment by hasmikharutyunyan** [comment]
> @hasmikharutyunyan is it still actual task?

Yes, but needed some changes in description, I will add

**Comment by hasmikharutyunyan** [comment]
Was checked, ef core not support this yet, for now I think we can close this issue
