### ISSUE TITLE
Filter is reset on the page [/bookings]

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#373]
1. Open page https://dev.happytravel.com/bookings 
2. Select any sorting type except the default in the field 'Sort by' (for example - 'Status')
![Screenshot 2021-06-29 at 21 46 39](https://user-images.githubusercontent.com/38030865/123851233-9f063900-d923-11eb-8eb9-3277612a3923.png)
3. Open any booking and return back

**ER**: Sorting is saved as selected in step 2
**AR**: The parameter for sorting is returned to default value 'Creation Date'

**Comment by nikolaeva31** [comment]
Need to fix

**Comment by alexander-plekhanov** [comment]
Added a saving of top tab state. The rest will require some time.

**Comment by alexander-plekhanov** [comment]
moved

**Comment by wnlstk** [comment]
https://track.happytravel.tech/issue/HP-552/Filter-is-reset-on-the-page-agent-app-bookings
