### ISSUE TITLE
Change agent invitation logic to use roles

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#379]
Every invited agent should have set a list of assigned roles, at least one.
Roles list with ids can be fetched from the endpoint:
`api/{v:apiVersion}/agent-roles`

Endpoints to change the logic - related to agent invitations.
I think that UI should look like a check box list but it's up to you.

**Comment by sergeyf-QA** [comment]
**Summary:**
- now, when I invite an agent then there are roles on https://dev.happytravel.com/settings/agency/invitations/send .
- chosen roles are sent in https://edo-dev.happytravel.com/en/api/1.0/agent/invitations/send at "roleIds" in request.
- if no roles are chosen then there is no opportunity to end an agent invitation.

**OK on DEV.**
