### ISSUE TITLE
Change UI for editing agent permissions to use roles endpoints

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#380]
Editing agent permissions must use roles instead of permissions there:

![изображение](https://user-images.githubusercontent.com/43397444/124116059-f4f3f180-da87-11eb-95f3-2d67009ba18f.png)

One agent can have different roles assigned. Endpoints for role assignments described there. 
https://github.com/happy-travel/agent-app-project/issues/364

I think we don't need to change existing UI there but it is up to you.

**Comment by sergeyf-QA** [comment]
**Summary:**
now instead of permissions are roles on agent settings page.

**OK on DEV.**
