### ISSUE TITLE
Add logic to update Country, Localit, LocalityZone data

### ISSUE THREAD

**Issue by hasmikharutyunyan** [happy-travel/agent-app-project#385]
Needed check and add logic with data update, for example for normalization changes, needed update and publish locations static data.

**Comment by ViTsvetkova** [comment]
@hasmikharutyunyan please close if it was done

**Comment by hasmikharutyunyan** [comment]
> @hasmikharutyunyan please close if it was done

It is not done, but it is not actual, so we can close
