### ISSUE TITLE
In the second step of search, there is no indication of which supplier offer is from (value of "supplier" is null)

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#387]
At https://dev.happytravel.com/
In Chrome, Safari, Firefox browsers.

**Steps:**
1. Log in some agent;
2. Make a search with these parameters:
```
Hilton Dubai Jumeirah Beach, Dubai, The United Arab Emirates
Jul 30 – Jul 31
1 guest
RU-RU (nationality and residency)
```
3. Wait for the search result to appear;
4. Note the line with the supplier value in the room description;
5. Go to hotel details page (the second step of search);
6. Note the line with the supplier value in the room description.

**Expected:**
If we show the offer suppliers in the first step, we should also show them in the second step. The value of "supplier" field must therefore not be null in the model.

**Result:**
In the second step of search, there is no indication of which supplier offer is from (value of "supplier" is null), but there is indication in the first step of search (the "supplier" value has a name of supplier).

**Comment by Raibo** [comment]
I used provided search criteria, but was not able to reproduce the issue.
Supplier was shown for each step.

Here is screenshot
![image](https://user-images.githubusercontent.com/8547320/124703670-221f2480-df0c-11eb-9d99-8b3a835b43e9.png)

**Comment by DenisSychev** [comment]
The situation isn't reproduced on prod. site. So, it could have been dev. environment.
