### ISSUE TITLE
Agents/agencies registration issues

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#390]
1)
- open identity login page
- click on 'Create a new one'
- proceed registration to the entering confirmation code page
- input confirmation code and try to proceed further

**Actual result:**
- I see agent settings page with error

**Expected result:**
- I should see a page where I can put an agent data

2) 
- invite an agency as admin
- proceed registration to the entering confirmation code page
- input confirmation code and try to proceed further

**Actual result:**
- I see just infinity loader

**Expected result:**
- I should see a page where I can put an agency/counterparty data

**Comment by mingazhev** [comment]
1 for @konstyefremov 
2 for @Raibo

**Comment by sergeyf-QA** [comment]
2nd issue is fixed
