### ISSUE TITLE
Error when trying to pay by credit card for a booking that was made using the Offline payment method

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#392]
On https://dev.happytravel.com/
In any browser

**Steps.**
1. Log with this agent https://passbolt.happytravel.com/app/passwords/view/234e4b0d-d430-4b00-8136-4f5935e70834
2. Go to Agency Bookings page and find booking with reference code DEV-HTL-AE-000BQ4-01
3. Open the developer panel in the browser;
4. Pay for this booking by credit card (use "Pay now by Card").

**Expectations.**
The booking payment will without errors as there are no restrictions on credit card payments.

**Result.**
Error when trying to pay by credit card for a booking that was made using the Offline payment method
POST /{culture}/api/{v}/accommodations/bookings/{referenceCode}/finalize
```
{
  "status": 400,
  "detail": "Could not get booking request by reference code {referenceCode}"
}
```

**Comment by Raibo** [comment]
@alexander-plekhanov 
Looks like this is a front-end side issue.

We use button "Pay now by Card" for offline bookings.

At first, these methods are called (and this is correct)
`accommodations/bookings/cards/new/pay` (or equivalent for saved card)
`payments/callback`

Then we expect front end to call this method
`accommodations/bookings/refcode/{referenceCode}/pay-with-credit-card`

But instead this method is called:
`accommodations/bookings/{referenceCode}/finalize`

**Comment by sergeyf-QA** [comment]
@Raibo


when I try to book then
POST https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/book-for-offline
POST https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings 
return

{"type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","title":"Internal Server Error","status":500,"detail":"Object reference not set to an instance of an object.","instance":"/en/api/1.0/accommodations/bookings/book-for-offline","spanId":"2bc7c805822bfc43","traceId":"152cc9ef6c8cb547b302fed9ee4c435d","requestId":"0HMADPGQQKD4M:00000002","x-request-id":["a0830bdf8270661b18bfb2361e9f98e1"],"StackTrace":"   at HappyTravel.Edo.Api.Services.Accommodations.Bookings.Documents.BookingDocumentsService.GenerateInvoice(Booking booking) in /src/Api/Services/Accommodations/Bookings/Documents/BookingDocumentsService.cs:line 101\n   at CSharpFunctionalExtensions.AsyncResultExtensionsLeftOperand.Map[K](Task\u00601 resultTask, Func\u00601 func)\n   at CSharpFunctionalExtensions.AsyncResultExtensionsBothOperands.Check[T](Task\u00601 resultTask, Func\u00602 func)\n   at CSharpFunctionalExtensions.AsyncResultExtensionsBothOperands.Bind[T,K](Task\u00601 resultTask, Func\u00602 func)\n   at CSharpFunctionalExtensions.AsyncResultExtensionsBothOperands.Bind[T,K](Task\u00601 resultTask, Func\u00602 func)\n   at HappyTravel.Edo.Api.Controllers.AgentControllers.BookingsController.BookByOffline(AccommodationBookingRequest request) in /src/Api/Controllers/AgentControllers/BookingsController.cs:line 106\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeActionMethodAsync\u003Eg__Logged|12_1(ControllerActionInvoker invoker)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeNextActionFilterAsync\u003Eg__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeInnerFilterAsync\u003Eg__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeNextResourceFilter\u003Eg__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilder.\u003C\u003Ec.\u003C\u003CBuildPipeline\u003Eb__8_0\u003Ed.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpRequestDurationMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpRequestCountMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpInProgressMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"}

**Comment by mingazhev** [comment]
Not repeated

**Comment by sergeyf-QA** [comment]
**Summary:**
no 500 and 400 errors during account, offline and credit card payments

**OK on DEV.**
