### ISSUE TITLE
Accept and update a hotel confirmation code

### ISSUE THREAD

**Issue by kirillta** [happy-travel/agent-app-project#396]
#### Add API to accept and update hotel confirmation codes

The API updates booking status for direct contracts after hotel staff responses _(and affects PMS services as well)_. Also it adds or updates a confirmation code.

|API parameters  |Mandatory | Description |
|------------------|-------------|--------------|
|Reference Code |Yes |Our system refcode
|Booking Status  |Yes | Amended, Cancelled, Confirmed, or On Request (Pending)
|Confirmation Code | Yes, for positive statuses |Free-form text value provided by hotel
|Hotel Staff Member Name | Yes |Free-form text value 

The code may be overwritten more than one time independently of current booking status. Changes history must be preserved and available from another API method.

_UPD: Ideally, Columbus' status should change after Edo updates as well_

**Comment by AlexeyShok** [comment]
QA: Please test this endpoint {{edo.baseUrl}}/:culture/api/1.0/property-owner/confirmations/:referenceCode with admin credentials. Credentials for hotel confirmation page will be added to another task AA-4xx after discussion with the front.

**Comment by sergeyf-QA** [comment]
**Summary:**
PUT /{culture}/api/{v}/property-owner/confirmations/{referenceCode} writes records about bookings to "BookingConfirmationHistory"

**OK on DEV.**
