### ISSUE TITLE
[TechDebt] Change Project names according our naming rules (Edo.Api)

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#398]
Initial ticket https://happytravel.atlassian.net/browse/NIJO-1138

On https://github.com/happy-travel/edo Api has not changed name according our naming rules.

**Expected result:**
HappyTravel.Edo.Api

**Comment by AlexeyShok** [comment]
https://track.happytravel.tech/issue/HP-657/TechDebt-Change-Project-names-according-our-naming-rules-Edo.Api
