### ISSUE TITLE
Enable and disable child agencies endpoints

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#4]
Additionally need to check that agent cannot work if its agency is disabled

**Comment by Raibo** [comment]
`&& agency.IsActive` is used in AgentContext retrieval, so agent indeed cannot work if its agency is disabled.

**Comment by DenisSychev** [comment]
Shall you as to list methods that have been done under this issue.

**Comment by DFSko** [comment]
POST agency/child-agencies/{agencyId}/deactivate
POST agency/child-agencies/{agencyId}/activate

**Comment by DFSko** [comment]
> Shall you as to list methods that have been done under this issue.

POST agency/child-agencies/{agencyId}/deactivate
POST agency/child-agencies/{agencyId}/activate

**Comment by DenisSychev** [comment]
This feature is blocked by this task https://github.com/happy-travel/agent-app-project/issues/127

**Comment by DenisSychev** [comment]
These methods are available and work at https://dev.happytravel.com
