### ISSUE TITLE
Add an ability to fetch mapper information for "old" (united with other htIds)

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#40]
As discussed we need a separate column with an array of previous htIds (or maybe hotel ids) to be searchable from mapper API:
- From edo side when search with new flow is executed
- From static data endpoints (that can be used in travelgate or vouchers)

**Comment by DenisSychev** [comment]
This is an internal task. Part of a larger task to change the whole search engine. To be tested as part of another task.
