### ISSUE TITLE
Add API for Displaying an Actual Hotel Confirmation Code and History

### ISSUE THREAD

**Issue by kirillta** [happy-travel/agent-app-project#401]
1. Add an endpoint to get an actual booking status for a provided reference code. The endpoint will be used for the admin panel and a hotel confirmation page. No booking details must be provided except a reference code and a status.
2. Add an endpoint for displaying history of confirmation code changes for a certain refcode and/or confirmation code.

**Comment by AlexeyShok** [comment]
1. Get actual booking status and confirmation code
Added new endpoint {{edo.baseUrl}}/:culture/api/1.0/property-owner/confirmations/:referenceCode
Confirmation code added to agent and admin endpoints with full booking information in response, such as:
​/{culture}​/api​/{v}​/accommodations​/bookings​/{bookingId}
/{culture}/api/{v}/accommodations/bookings/refcode/{referenceCode}
​/{culture}​/api​/{v}​/admin​/bookings​/{referenceCode}

**Comment by sergeyf-QA** [comment]
**Summary:**
1) GET /{culture}/api/{v}/property-owner/confirmations/{referenceCode} returns 
{
  "referenceCode": "DEV-HTL-AE-000ZQ4-01",
  "confirmationCode": "testtesr",
  "status": "Pending"
}

2) 
GET /{culture}/api/{v}/accommodations/bookings/{bookingId} 
GET /{culture}/api/{v}/accommodations/bookings/refcode/{referenceCode}
GET /{culture}​/api​/{v}​/admin​/bookings​/{referenceCode}
return confirmation code in, e.g.
"propertyOwnerConfirmationCode": "testtesr"

3) 
GET /{culture}/api/{v}/admin/accommodations/bookings/{referenceCode}/confirmation-history
GET /{culture}/api/{v}/accommodations/bookings/reference-code/{referenceCode}/confirmation-history
return confirmation history of booking

**OK on DEV**
