### ISSUE TITLE
Add a Booking Confirmation Page

### ISSUE THREAD

**Issue by kirillta** [happy-travel/agent-app-project#402]
Add a page to implement #396 API. The page must be accessible for unauthorized users. A reference code may be provided in a query parameter.

Also the page have to display an actual booking state from #401

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
when I try to update the booking on https://dev.happytravel.com/accommodation/confirmation/Osb2dH6pVrShBIMYhPFmKILMRZq3JsujRDFofGl52ik=
it falls with 500 error.
The thing is that when I am updating accommodation on back-end it works well.
Perhaps, the back-end model is different a bit and it is needed to update loaded data model on front-end side too?
