### ISSUE TITLE
When invite an agency, the new agent of it has all roles, regardless of what ones I chosen during invitation

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#411]
- go to https://dev.happytravel.com/settings/child-agencies/invite
- choose any role
- proceed with registration
- check roles of the new agent of created child agency

**Actual result:**
- the new agent has all roles, regardless of what ones I chosen during invitation

**Expected result:**
- needs to decide what to do with that

**Comment by mingazhev** [comment]
@alexander-plekhanov could you please remove roles select from there?
We've decided to not use roles there because it does not make sense, we assign predefined roles for invited master child agent

**Comment by mingazhev** [comment]
@sergeyf-QA Actual result is correct, just need to remove roles select from UI there

**Comment by sergeyf-QA** [comment]
**Summary:**
roles was removed from https://dev.happytravel.com/settings/child-agencies/invite

**OK on DEV.**
