### ISSUE TITLE
Use in bookings routes 'referenceCode' instead of 'bookingId'

### ISSUE THREAD

**Issue by hasmikharutyunyan** [happy-travel/agent-app-project#419]
Need to change the routes only.
May be done partially, in several PRs and steps

**Comment by ViTsvetkova** [comment]
@AlexeyShok please update, was it done?

**Comment by AlexeyShok** [comment]
Not yet. Need to chane endpoints and then fixed on frontend too.

**Comment by ViTsvetkova** [comment]
https://track.happytravel.tech/issue/HP-537/TechDebt-Use-in-bookings-routes-referenceCode-instead-of-bookingId
