### ISSUE TITLE
Add standartized logging to connectors

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#425]
After this task will be done and merged:

https://github.com/happy-travel/agent-app-project/issues/423

Need to add the same logging (by example) to connectors:

ETG- @konstyefremov +
Illusions - @hasmikharutyunyan +
Netstorming - @konstyefremov +
Rakuten - @oleg1std +
Jumeirah - @konstyefremov +
Columbus - @AlexeyShok +

**Comment by sergeyf-QA** [comment]
**Summary:**
- logging to connectors is applied for all pointed connectors

**OK on DEV.**
