### ISSUE TITLE
Evaluation "Price changed" text is shown every time, even when price is not changed

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#427]
**Steps to reproduce:**
1. Search for any option for hotel Jumeirah Emirates Towers
2. Go to third step

**Expected result:**
No warning should be shown because jumeirah returns the same prices on all steps

**Actual result:**
![изображение](https://user-images.githubusercontent.com/43397444/125318333-2fe10980-e353-11eb-8ce4-45f26d04150c.png)

_Testing tips:_
Warning **must** be shown when price was actually changed

**Comment by sergeyf-QA** [comment]
**Summary:**
No warning are in case the same prices on all steps, when price was actually changed warning is shown.

**OK on DEV**
