### ISSUE TITLE
Review Promo-Zs code and add separate issues to fix

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#435]
Need to:
- Download repo https://github.com/happy-travel/hotelbeds-connector/ locally
- Go through the code and list all things to fix in one place (maybe in comments to this task)
- Split the list to pieces that can be done in separate not large pull requests
- Create an issue for each piece in https://github.com/happy-travel/hotelbeds-connector/  repository

The main purpose of creating these issues is to help our colleagues to make a final pluggable-in version of hotelbeds connector

**Comment by oleg1std** [comment]
WideAvailabilitySearchRequestExecutor.cs
line 25: the languageCode parameter can be removed.
line 48:  It's better to rename the local function GetHotelResults. It has the same name as the outer method.
line 50: the sessionId parameter can be discard

**Comment by oleg1std** [comment]
HotelbedsShoppingClient.cs
line 99: the Post method is unused and can be removed
line 111: the contents variable can be removed
line 34, line 42, line 50: the first parameter can be renamed to "request"
line 50: the availabilityId parameter can be removed

**Comment by oleg1std** [comment]
WideAvailabilitySearchService.cs
line 58, line 59: Unused variables

**Comment by oleg1std** [comment]
AccommodationService
line 39: The "OrderBy" must be called before the "Skip", "Take" methods
line 37: An extra line
line 34, line 36: The cancellationToken might be passed into ToListAsync

**Comment by oleg1std** [comment]
MultilingualAccommodationMapper.cs
line 57: "FAXNUMBER" can be declared as a const
line 74, line 180: It's better to remove the commented code or add an additional commentary as the explanation
line 100:  hotelDetails is an unused parameter. Can be removed

**Comment by oleg1std** [comment]
PackageMapper.cs
line 109: The unused parameter "hotel"
line 150: The unused parameter "cancellationPolicy"

**Comment by oleg1std** [comment]
RoomSelectionService.cs
line 51: the commented code can be removed

**Comment by oleg1std** [comment]
BookingService.cs
line 54: unused availabilityRequest
line 58: unused policyId
line 64: unused availabilityId in the upper case

**Comment by mingazhev** [comment]
Marking as done, thanks guys
