### ISSUE TITLE
Booking sales report

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#436]
Need to create sales report based on existing "Full booking report" to be more accurate and useful for our accounts team.
The main idea of this report is to show the actual sales, not including cancelled without penalty, invalid, test bookings.
The two main purposes are:
1. Invoicing agents (asking to pay for the bookings)
2. Cross-checking supplier and hotel invoices (getting what we owe)

To achieve that need to make a _separate_ report with the following changes to existing **Full booking report**:
- Bookings should be filtered by check out date (for refundable bookings) and by creation date (for non-refundable bookings)
- Only bookings that are needed to pay should be shown. This can include confirmed bookings or bookings that were cancelled after deadline
- Additional "Is direct contract" column needed (it is filled for every booking in DB)
- Payable to supplier\hotel - contains the price to pay to the hotel or supplier. It is equal to "Original price" (price without markups and in original currency) if booking is confirmed and is equal to cancellation penalty amount if booking was cancelled after deadline. Cancellation penalty in this case should be calculated from original price, not from the agent's.
- Payable by agent - contains the price that we charge from the agent. It is equal to booking price if booking is confirmed and is equal to cancellation penalty amount if booking was cancelled after deadline. Cancellation penalty in this case should be calculated from the whole agent's price
- Existing "Cancellation penalty" column should be removed (it works incorrect now and does not show needed information)

For any questions about how existing reports work please contact @DFSko

**Comment by Raibo** [comment]
We might want to introduce indexes for `CreationDate` and `CheckOutDate`, since we are pulling data from ever growing table using this columns to filter.

**Comment by Raibo** [comment]
>Bookings should be filtered by check out date (for refundable bookings) and by creation date (for non-refundable bookings)  

Took this literally, but might be that something different was meant there.

**Comment by Raibo** [comment]
I am refactoring `RecordManagers` to become asynchronous, because currently DB queries are made synchronously inside `foreach`, which is not good. 
Also, I need to use client evaluation in new report to filter out required bookings.

**Comment by Raibo** [comment]
>for refundable bookings

I am taking `refundable` as if 100% refund penalty (or check in date) is after current datetime.

**Comment by Raibo** [comment]
>Only bookings that are needed to pay should be shown. This can include confirmed bookings or bookings that were cancelled after deadline

This cuts most of bookings compared to full bookings report

**Comment by nikolaeva31** [comment]
Edit in current implementation:

1.  Field 'PayableToSupplierOrHotel' must be 0 if booking was canceled on dates of difference in deadlines (between edo and supplier)
>  for example, supplier deadline - 29.07.2021 
> edo deadline (+ 1 day or 3 days) - 28.07.2021 
> and booking was canceled on 28.07.2021 then we don't return anything to hotel and the field 'PayableToSupplierOrHotel' value must be 0

2. Make a filter to display bookings correctly 

>  for example, if booking has 'isAdvancePurchaseRate: true' then 'Bookings should be filtered by creation date (for non-refundable bookings)'
> if booking is active and the deadline hasn't passed then 'Bookings should be filtered by check out date (for refundable bookings)'

**Comment by konstyefremov** [comment]
Follow up from a discussion with Vadim:

1. Deadline date for the supplier should be taken from the SupplierOrders table and then compared to the deadline date in the Bookings table. 
2. We should make two queries: bookings by checkout date and bookings by creation date. Then the results should be merged depending on IsAdvancedPurchaseRate in BookedRooms. If it is True, booking should be taken by the creation date. If it's false booking should be taken by the checkout date.

**Comment by konstyefremov** [comment]
> Edit in current implementation:
> 
> 1. Field 'PayableToSupplierOrHotel' must be 0 if booking was canceled on dates of difference in deadlines (between edo and supplier)
> 
> > for example, supplier deadline - 29.07.2021
> > edo deadline (+ 1 day or 3 days) - 28.07.2021
> > and booking was canceled on 28.07.2021 then we don't return anything to hotel and the field 'PayableToSupplierOrHotel' value must be 0
> 
> 1. Make a filter to display bookings correctly
> 
> > for example, if booking has 'isAdvancePurchaseRate: true' then 'Bookings should be filtered by creation date (for non-refundable bookings)'
> > if booking is active and the deadline hasn't passed then 'Bookings should be filtered by check out date (for refundable bookings)'

The first issue should be resolved now.

**Comment by konstyefremov** [comment]
This report will not allow queries for future dates.

**Comment by konstyefremov** [comment]
> Payable to supplier\hotel - contains the price to pay to the hotel or supplier. It is equal to "Original price" (price without markups and **in original currency**) if booking is confirmed and is equal to cancellation penalty amount if booking was cancelled after deadline. Cancellation penalty in this case should be calculated from original price, not from the agent's.

This point was implemented incorrectly. We need to show what we owe in original currency.

**Comment by konstyefremov** [comment]
> 2. Make a filter to display bookings correctly

This also is implemented.

**Comment by sergeyf-QA** [comment]
**Summary:**
Finalized Bookings Report placed on https://manage-dev.happytravel.com/reports looks fine

**OK on DEV.**
