### ISSUE TITLE
Accommodations 'HasDirectContract' flag in illusions needs to be updated on production

### ISSUE THREAD

**Issue by Raibo** [happy-travel/agent-app-project#437]
In table `Accommodations` we have column `HasDirectContract`.
This column must be true for every accommodation listed in `DirectConnectivityContractTokens` with not expired dates.

This column must be updated each time `DirectConnectivityContractTokens` gets updated via loading CSV file.

Currently, on production, all records in `Accommodations` have its `HasDirectContract` false, while there are some accommodations listed in `DirectConnectivityContractTokens`.

These accommodations can be retrieved using following select:
```
SELECT *
FROM "Accommodations" a
WHERE EXISTS (
    SELECT 1 FROM "DirectConnectivityContractTokens" c 
    WHERE C."AccommodationCode" = A."Code" 
    AND (C."DateTo" is null or C."DateTo" > CURRENT_DATE)
  )
```

The reason for this might be one of the following:
1. `HasDirectContract` flag updating mechanism does not work.
2. Since `HasDirectContract` was added, new tokens has not been added even a single time.

It is probably reason 2, because latest `DateFrom` in `DirectConnectivityContractTokens` is 2021-03-26.

**Comment by mingazhev** [comment]
@hasmikharutyunyan could you please have a look?
