### ISSUE TITLE
Error 500 when trying to find out the cancelation deadline from the Columbus

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#438]
On https://happytravel.com/
In Chrome, Safari, Firefox browsers.

**Steps:**

1. Log in some agent;
2. Find accommodation according to these parameters:

> Jumeirah Beach Hotel, Dubai, The United Arab Emirates
> Sep 29 – Sep 30
> 1 guest
> Russian Federation (nationality and residency)

3. Try to find out the cancelation deadline (click on "Cancelation Deadline" button).

**Expected:**
The cancelation deadline request works without errors and  returns the result.

**Result:**
Error 500 when trying to find out the cancelation deadline from the Columbus. More details see in Sentry ID: 5eb21042391a43cb82f9f6a94afef823
![2021-07-12_15 07 57](https://user-images.githubusercontent.com/17127277/125427116-832ae823-4622-473c-89d7-dbf8f9d1d3db.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
the cancelation deadline request works without errors and returns the result.

**OK on DEV.**
