### ISSUE TITLE
Investigate the booking

### ISSUE THREAD

**Issue by konstyefremov** [happy-travel/agent-app-project#439]
Ref code is HTL-US-000RH2-01

The accountants requested to transfer money for it to the agency account. But it has the status 'Not Paid' and is not present in the 'Payments' table.

We need to find out why it's left Not Paid, there are might be some bugs. And if it wasn't paid, probably, deduce this money from the agency account.

**Comment by AlexeyShok** [comment]
{{edo.baseUrl}}/en/api/1.0/admin/accommodations/bookings/:bookingId/refresh-status doesn't work in production, but work on development. I am waiting for the deployment to check the status of this booking.

**Comment by DFSko** [comment]
Cronjob service kanazawa payments requests failed with 401 Unauthorized
