### ISSUE TITLE
No possibility to return to the page with balance, contract and buttons to activate and deactivate the counterparty

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#440]
On https://manage-dev.happytravel.com/ 
In Chrome, Safari, Firefox browsers.

**Steps:**
1. Log in some administrator
2. Find counterparty by name "The Clouds company"
3. Go to the settings for this agency
A page with the counterparty balance, state, status and the option to download or upload a contract will be displayed
4. Click on Counterparty details tab
5. Try to back to page with the balance, status, state and contract.

**Expected:**
It should be possible to get to the page with the counterparty balance, state, status and the option to download or upload a contract. For example, there should be an appropriate tab.

**Result:**
No possibility to return to the page with balance, contract and buttons to activate and deactivate the counterparty

**Comment by sergeyf-QA** [comment]
@cyberkarma 
1)
on 'Contract' page 'Upload Another Contract' and 'Download Contract' buttons should have the same font size

2)
on 'Contract' page should be a space between 'Upload Another Contract' and 'Download Contract' buttons

3)
when I go to 'Verification' tab then I see 'Read only' button for a second, check on https://manage-dev.happytravel.com/counterparties/83/verification

4)
when I walk through the tabs then I see that 'Deactivate' button is shown as 'Activate' for second during tab switching

5)
can not upload a contract using 'Upload Another Contract' button

**Comment by DenisSychev** [comment]
On https://manage-dev.happytravel.com/ 
1. On 'Contract' page 'Upload Another Contract' and 'Download Contract' buttons have the same font size;
2. There is a space between 'Upload Another Contract' and 'Download Contract' buttons on 'Contract' page;
3. There is no Verification tab for counterparty with Full access status;
4. The Activate and Deactivate button has been replaced by a switch and its position doesn't change when tabbing;
5. 'Upload Another Contract' button works.
