### ISSUE TITLE
On the Transfer balance page, the request /child-agencies sends information about another agency

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#442]
On https://manage-dev.happytravel.com/ 
In Chrome, Safari, Firefox browsers.

**Steps:**

1. Log in some administrator;
2. Find counterparty by name "The Clouds company"
3. Open browser dev. tools panel
4. Go to the Balance page (click on Balance tab) then go to Transfer Balance tab
5. Choose Agency #770 in To Agency field
6. Pay attention to the value in Agency account field.
<img width="755" alt="Снимок экрана 2021-07-13 в 23 21 22" src="https://user-images.githubusercontent.com/17127277/125524463-8a8a839d-d62b-4796-a32c-260029f16d83.png">

**Expected:**
The Agency #770 has been have the AgencyAccountsId: 7 so this id must be the value in the Agency account field
<img width="699" alt="Снимок экрана 2021-07-13 в 23 23 32" src="https://user-images.githubusercontent.com/17127277/125524417-600455ab-75d4-4b63-9b57-9dab1ebceafc.png">

**Result:**
On the Transfer balance page, the request /child-agencies sends information about another agency. For example, the request /agencies/770/child-agencies contains information for the agency with id: 975. The request /agencies/975/child-agencies has empty response.

**Comment by Raibo** [comment]
Right now the field "To agency" shows "Agency #770" without any balance, but request to backend is still performed.
The request is correct and backend also return correct data.

Looks like the issue is already fixed.

**Comment by DenisSychev** [comment]
The task is irrelevant because there are no more counterparties, hence no transfer of funds.
