### ISSUE TITLE
Weird additional prices for rooms

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#447]
**How to reproduce:**
- find accommodation using such settings
Bangkok, Thailand
Jul 30 - Jul 31
2 rooms
2 adults + 1child per room
Ru - Ru
- choose 'The Cottage Suvarnabhumi Hotel'
- proceed to 3rd step

**Actual result:**
- on 3rd step are additional small prices for every room
- it comes from back-end in "dailyRoomRates"

{"fromDate":"2021-07-30T00:00:00","toDate":"2021-07-31T00:00:00","currency":"USD","description":"Extra person sharing bed","gross":{"amount":3.26,"currency":"USD"},"finalPrice":{"amount":3.26,"currency":"USD"}
![Screenshot at Jul 14 13-29-44](https://user-images.githubusercontent.com/74529212/125613726-5e5e601b-57aa-436c-9dd2-acfd1df380c4.png)

**Expected result:**
- for every room should be one completed price??
or perhaps we just should show description on the front?

**Comment by konstyefremov** [comment]
Unfortunately, I cannot replicate the bug.

**Comment by sergeyf-QA** [comment]
is not reproducing now
