### ISSUE TITLE
Error 400 when trying to request a deadline

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/agent-app-project#449]
On https://dev.happytravel.com/
In Chrome, Safari, Firefox browser

**Steps:**
1. Log in some agent;
2. Do a search on these parameters:

> Bangkok, Thailand
> Jul 30 – Jul 31
> 1 guest
> GB-GB (nationality and residency)

3. Find the Josh Hotel in search results;
4. Open dev. tools panel in browser;
5. Request a deadline;
6. Find the /deadline request in dev. tools panel in browser.

**Expectations:**
The /deadline request will return the deadline data.

**Result:**
Error 400 when trying to request a deadline.
In the first step the request has a response:
```
{
    "status": 400,
    "detail": "Could not find selected room contract set"
}
```

In the second step the request has a response:
```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "Bad Request",
    "status": 400,
    "detail": "Records Not Found",
    "instance": "/api/1.0/accommodations/availabilities/637619412543262072/room-contract-sets/6163ae64-8cef-4759-a622-b1cf5f53642d/deadline",
    "spanId": "ad6267d4ec621443",
    "parentId": "00-c4ade10c3a7a7749a703675194befdae-1bfaf23b548d9944-00",
    "traceId": "c4ade10c3a7a7749a703675194befdae",
    "requestId": "0HMA51BALM0GN:00000004"
}
```

**Comment by kirillta** [comment]
In general 400 isn't a bug, but deadlines should be available in general. Please, check

**Comment by AlexeyShok** [comment]
@DenisSychev Is this task actual now?

**Comment by AlexeyShok** [comment]
What you need to do: 1) see what connectors this hotel gives; 2) including these providers one by one get this error from the agent application; 3) see what the connector receives from the supplier and understand where the error is: with the supplier or we are processing it incorrectly; 4) if the supplier then prepare logs for sending to the supplier, if we have then fix the bug.

**Comment by konstyefremov** [comment]
The issue was resolved with the following outcome:

Dev on Illusions is broken. 

Illusions use different domain names for different purposes. Wide availability search goes to one domain name. 
Hotel details search goes to another domain name.

We use identical credentials for both servers. This works in a production environment. But on the dev environment it returns "Invalid credentials".

**Comment by AlexeyShok** [comment]
@DenisVelinen  Is this issue still relevant? I checked and did not find any offers from suppliers for which no deadline was specified. So I can't check.

**Comment by nikolaeva31** [comment]
There's no additional deadline request on dev for checking
