### ISSUE TITLE
When inviting an agent, email is specified twice in the request

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#452]
When inviting an agent, email is specified twice in the request. We need to leave only one email in registrationInfo.

**Comment by sergeyf-QA** [comment]
**Summary:**
in https://edo-dev.happytravel.com/en/api/1.0/agent/invitations/send at "registrationInfo" is only one email, e.g. {"agencyId":801,"registrationInfo":{"email":"fabirs110@yopmail.com","firstName":"fab","lastName":"110","position":"qa","title":"Mr"},"roleIds":[2]}

**OK on DEV.**
