### ISSUE TITLE
Need mark email as required to invite agents

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#453]
Email is required to invite agents. Therefore, you need to fix it in the UserDescriptionInfo model. But since this model is used in other endpoints, it is necessary to check so that this fix does not break the work of other endpoints.

**Comment by konstyefremov** [comment]
@alexander-plekhanov on this page **/settings/agency/invitations/send** request will be changed to:

```
 {
    "firstName": "John",
    "lastName": "Doe",
    "position": "Manager",
    "email": "example@company.com",
    "title": "Mr",
    "roleIds": [2]
}
```

**Comment by sergeyf-QA** [comment]
**Summary:**
- Email field is required on /settings/agency/invitations/send
- Sending invitation works fine on front part

**OK on DEV.**
