### ISSUE TITLE
Сan press the inactive button

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#458]
On https://dev.happytravel.com/
In Chrome, Safari, Firefox browser

**Steps:**
1. Log in some agent;
2. Go to Settings;
3. Go to Agency tab, then Agent management tab;
4. Select any agent and go to its settings (click on agent row);
5. Scroll down to the Permissions block;
6. Click on Save changes button.

**Expectations:**
Can’t press the inactive button.

**Result:**
Сan press the inactive button.
![Снимок экрана 2021-07-21 в 14 29 09](https://user-images.githubusercontent.com/17127277/126522489-aacddf16-5d51-4e94-98f9-3dcad21fd31c.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- 'Save changes' button can not be pressed now when inactive
- 'Save changes' button can be pressed when active and changes are saved

**OK on DEV.**
