### ISSUE TITLE
Changing agent permissions does not work correctly if the agent is only one or the last one with change permissions for other agents

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#46]
On http://dev.happytravel.com/
In Chrome, Safari.

**Steps:**
1. Log in this agent https://passbolt.happytravel.com/app/passwords/view/234e4b0d-d430-4b00-8136-4f5935e70834 ;
2. Go to Setting page;
3. The agent has a "PermissionManagement" permission, try changing the permissions of some other agent in that agency.

**Result:**
Changing agent permissions does not work correctly if the agent is only one or the last one with change permissions for other agents – the agent does not have an Agent Management tab in the settings (see pic. https://drive.google.com/file/d/1TsAlOfVI2pnY-cA1McmVCeBDKA5OO98K/view?usp=sharing ).

**Expectations:**
The only or last agent should not lose the permission to change other agents:
- there should be a check that the agent is not the last one to retain "PermissionManagement" and "AgentStatusManagement" permissions (if it is the last one, it should not be allowed to make changes and show a corresponding message when trying);
- the "PermissionManagement" and "AgentStatusManagement" permissions should probably be "bundled" as without the interface it will not show a menu item without "AgentStatusManagement", so the agent will lose the permission.

**Comment by mingazhev** [comment]
For now we'll fix that on frontend side only

**Comment by mingazhev** [comment]
This may need some another discussion, we'll plan a call

**Comment by sergeyf-QA** [comment]
@Raibo 

1)
- login as an agent who has another agent in the agency (2nd agent should have enabled "PermissionManagement" and "AgentStatusManagement" permissions)
- disable for the 2nd agent the "Permission management"
**Result:**
- Agent Status Management is still enabled
**Expected:**
- the "PermissionManagement" and "AgentStatusManagement" permissions should be "bundled"

2)
- if I disable  "AgentStatusManagement" permission myself and there are no any other agents in agency then there is no error message
**Expected:**
- there should be error message like we have when disable "PermissionManagement" permission myself

**Comment by Raibo** [comment]
Added one more bundle to make AgentStatusManagement to also add ObserveAgents permission

**Comment by sergeyf-QA** [comment]
**Summary:**
- if the agent is alone in the agency then he can not deny his 'Permission Management' permission
- 'Permission Management' permission is bundled with 'Agent Status Management' permission
- 'Agent Status Management' permission is bundled with 'Observe Agents' permission 

**OK on DEV.**
