### ISSUE TITLE
The invitations to become an administrator aren’t working

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#460]
On https://manage-dev.happytravel.com/
In Safari, Chrome

**Steps:**
1. Log in some administrator;
2. Go to Admins page;
3. Fill in the fields with the correct data;
4. Press Send invitation button.

**Expectations:**
Clicked by the Send invitation button, an email will be sent to the email address provided.

**Result:**
The invitations to become an administrator aren’t working.
The request has a response code of 400 with a body:
The POST request https://edo-dev.happytravel.com/en/api/1.0/admin/invitations has a response code 400 with a body:
```
{
    "errors": {
        "RoleIds": [
            "The RoleIds field is required."
        ],
        "RegistrationInfo.Title": [
            "The Title field is required."
        ],
        "RegistrationInfo.LastName": [
            "The LastName field is required."
        ],
        "RegistrationInfo.FirstName": [
            "The FirstName field is required."
        ]
    },
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "Bad Request",
    "status": 400,
    "instance": "/en/api/1.0/admin/invitations",
    "spanId": "dc1163f297b4bc4f",
    "traceId": "b89e1f13fb6a974696f1db404af5997b",
    "requestId": "0HMADCEDTNO1N:00000002"
}```

**Comment by sergeyf-QA** [comment]
**Summary:**
The POST request https://edo-dev.happytravel.com/en/api/1.0/admin/invitations sends all input data from the admin invitation page w/o 400 error

**OK on DEV.**
