### ISSUE TITLE
If a contract file doesn't exist an AmazonS3Exception exception is sent to the Sentry

### ISSUE THREAD

**Issue by oleg1std** [happy-travel/agent-app-project#462]
_GET api/{v:apiVersion}/admin/counterparties/{counterpartyId}/contract-file_
If the contract file doesn't exist in the s3 bucket the endpoint returns 400 and sends an exception to the Sentry: _Amazon.S3.AmazonS3Exception The specified key does not exist._
https://sentry.happytravel.com/organizations/happytravel/issues/2494/?project=2&query=is%3Aunresolved

**Comment by sergeyf-QA** [comment]
**Summary:**
- in case a counterparty has contract file GET api/{v:apiVersion}/admin/counterparties/{counterpartyId}/contract-file returns contract file
- in case a counterparty has no contract file GET api/{v:apiVersion}/admin/counterparties/{counterpartyId}/contract-file returns 
{
  "status": 400,
  "detail": "No contract file was uploaded"
}

**OK on DEV.**
