### ISSUE TITLE
Add and configure hotelbeds-connector for dev environment

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#467]
Need to:
1. Add hotelbeds as default enabled connector for EDO and Mapper (in vault)
2. Add a connector to EDO-s connector manager
3. Prepare mapper to work with hotelbeds (if any changes in code needed).

Connector is already on dev and has address is https://hc-dev.happytravel.com

**Comment by hasmikharutyunyan** [comment]
@mingazhev  Could You please provide more informative description.

**Comment by mingazhev** [comment]
@hasmikharutyunyan I've added a bit more description, let's contact in discord if not enough

**Comment by mingazhev** [comment]
This is done as I know
