### ISSUE TITLE
Paid booking remains with Created status and is not displayed on the front

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#469]
Paid booking with Id 3646 reference code DEV-HTL-AE-0001T4-01 in the hotel Hilton Dubai Jumeirah code 000526 remained with the Created status and is not shown in the agent application. At the same time, an error was recorded in the Columbus connector:
https://sentry1.happytravel.com/organizations/happytravel/issues/2529/?environment=Development&project=40&referrer=alert_email

**Comment by nikolaeva31** [comment]
DEV-HTL-TH-000AT4-01 - Illusions

**Comment by AlexeyShok** [comment]
@AlexeyShok - Columbus
@mingazhev - Illusions

**Comment by sergeyf-QA** [comment]
ETG DEV-HTL-RU-000IT4-01
look for 
Test Hotel(Do Not Book), Belogorsk, The Russian Federation
18-08-2021 – 19-08-2021
1 Adult • 0 Children • 1 Room
United Kingdom Of Great Britain And Northern Ireland
United Kingdom Of Great Britain And Northern Ireland

**Comment by sergeyf-QA** [comment]
**Summary:**
now paid bookings does not remains in Created status.

**OK on DEV.**
