### ISSUE TITLE
Change a returning value of the account balance to a list

### ISSUE THREAD

**Issue by kirillta** [happy-travel/agent-app-project#471]
And empty list for counter-parties without an account (not verified)

**Comment by sergeyf-QA** [comment]
**Summary:**
1) GET 
​/{culture}​/api​/{v}​/admin​/counterparties​/{counterpartyId}​/accounts​/{currency}​/balance returns info from "CounterpartyAccounts" as:
[
  {
    "accountId": 306,
    "balance": 4000,
    "currency": "USD"
  }
]

2) GET 
​/{culture}​/api​/{v}​/admin​/counterparties​/{counterpartyId}​/accounts returns list of accounts, also isActive was added, e.g.
[
  {
    "id": 306,
    "currency": "USD",
    "balance": {
      "amount": 4000,
      "currency": "USD"
    },
    "isActive": true
  }
]

**OK on DEV.**
