### ISSUE TITLE
The counter-party details response for the admin panel not contains location info

### ISSUE THREAD

**Issue by kirillta** [happy-travel/agent-app-project#472]

**Comment by sergeyf-QA** [comment]
**Summary:**
I can change counterparty data by
PUT /{culture}/api/{v}/admin/counterparties/{counterpartyId}
only in case he has status Pending or ReadOnly. If counterparty is verified changes are not implemented.
GET /{culture}/api/{v}/admin/counterparties/{counterpartyId} shows data well

**OK on DEV.**
