### ISSUE TITLE
The Agency section issues at the admin panel

### ISSUE THREAD

**Issue by kirillta** [happy-travel/agent-app-project#478]
1. Agency/Balance content miss
2. Agency/Agency Settings must be moved to a counter-party level
3. Agency/Bookings. A refresh status button needed
4. Agency/Bookings. Control buttons not reflect actual booking state (f.i. one may close a closed booking)

**Comment by DenisSychev** [comment]
On https://manage-dev.happytravel.com/

1. Has been done;
2. Not relevant because there are no more contragencies;
3. Has been done;
4. Has been done.
