### ISSUE TITLE
HBpro connector. Preliminary steps

### ISSUE THREAD

**Issue by oleg-n-k** [happy-travel/agent-app-project#480]
- Create a project for HBpro-connector
- Add sentry, stdout logger,  Fukuoka logger, tracing, error handling, Redis, db, vault, other needed things
- Add controllers with the needed endpoints without an exact implementation

**Comment by sergeyf-QA** [comment]
**Summary:**
- static endpoints work fine on Hotelbook Pro Connector
- error processing  in Insomnia also works fine

**OK on DEV.**
