### ISSUE TITLE
HBpro-connector. Wide availability search (1 step) 

### ISSUE THREAD

**Issue by oleg-n-k** [happy-travel/agent-app-project#482]
Implement the wide availability search (1 step) on the HBpro-connector

Documentation: **https://api.hbpro.expert/docs/**

**Comment by sergeyf-QA** [comment]
blocked until 1st search step be fixed on supplier side

**Comment by sergeyf-QA** [comment]
**Summary:**
1st search step works well at HotelBook Pro Connector.

**OK on DEV.**
