### ISSUE TITLE
Add tracing and extended Kanazawa, Uwajima, TgxChannel (and extend sentry errors)

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#485]
Looks like kanazawa and uwajima do not write tracing information to sentry.

https://sentry1.happytravel.com/organizations/happytravel/issues/2543/?project=7&query=is%3Aunresolved
https://sentry1.happytravel.com/organizations/happytravel/issues/2496/?environment=Production&project=34&query=is%3Aunresolved&statsPeriod=14d

Need to check and add if needed

**Comment by DFSko** [comment]
Done

**Comment by sergeyf-QA** [comment]
**Summary:**
now in Sentry spanId and traceId are written for Kanazawa, Uwajima, TgxChannel

**OK on DEV.**
