### ISSUE TITLE
'Accommodation does not exist' error

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#488]
**How to reproduce:**
- try to look for
Hilton Dubai Jumeirah, Dubai, The United Arab Emirates
05-08-2021 – 06-08-2021 (today is 04.08)
1 Adult • 0 Children • 1 Room
United Arab Emirates
- tap any room on 2nd search step

**Actual result:**
- GET https://edo-dev.happytravel.com/en/api/1.0/accommodations/availabilities/searches/40ec9c72-8f94-41de-b7c9-7f9f38edbb25/results/undefined/accommodation returns 

{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"Bad Request","status":400,"detail":"Accommodation does not exists","instance":"/api/1.0/accommodations/undefined","spanId":{"valueKind":"String"},"parentId":{"valueKind":"String"},"traceId":{"valueKind":"String"},"requestId":{"valueKind":"String"}}

**Comment by DFSko** [comment]
Problem is not reproducible

**Comment by sergeyf-QA** [comment]
agree - now there is no an issue
