### ISSUE TITLE
500 error while playing with predictions

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#490]
**How to reproduce:**
- actually it is hard to reproduce but I catch this issue when tried to enter several times any string into the search fields

**Actual result:**
- https://osaka-dev.happytravel.com/api/1.0/predictions?query=%5BTEST%5D%20Detailed%20CP%20rates%20JP&sessionId=8c820ff2-fe41-4928-9bba-2e621d24e1ee returns 500 error

https://sentry.happytravel.com/organizations/happytravel/issues/2575/?project=4&query=is%3Aunresolved&statsPeriod=14d

**Comment by kirillta** [comment]
Can't repro
