### ISSUE TITLE
Change VCC issue for Jumeirah

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#492]
Jumeirah support says:

```
Jumeirah prefers VCC to be activated as follows:
•	For bookings with Flexible cancellation policy – VCC should be activated on arrival date and remain active for 30 days after checkout.
•	For bookings with Non-Refundable cancellation policy such as Advance Purchase Rate – VCC should be activated on the booking date and VCC will be active till check out

```

This means that we need to change our VCC issue logic to correspond, especially for non-refundables.

**Comment by DFSko** [comment]
https://github.com/happy-travel/jumeirah-connector/pull/52

**Comment by sergeyf-QA** [comment]
blocked until Jumeirah hotels be available on dev

**Comment by sergeyf-QA** [comment]
**Summary:**
•	For bookings with Flexible cancellation policy – VCC is activated on arrival date and remain active for 30 days after checkout.
•	For bookings with Non-Refundable cancellation policy such as Advance Purchase Rate – VCC is activated on the booking date and VCC will be active till check out


**OK on DEV.**
