### ISSUE TITLE
Try to implement ngenius integration as switchable from payfort

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#494]
Need to try ngenius implementation not breaking existing payfort.
Integration must be switchable between payfort and ngenius.
All existing operations such as authorize, capture and etc. must be supported

**Comment by DFSko** [comment]
implemented on dev

**Comment by sergeyf-QA** [comment]
**Summary:**
authorize, capture and finalize work fine.

**OK on DEV.**
