### ISSUE TITLE
Wide availability search returns no results

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#50]
**Steps to repro:**
Search for hotels in Dubai with the new search flow (experimental features on)
![изображение](https://user-images.githubusercontent.com/43397444/111271555-2b317080-8653-11eb-99ce-99423aea3904.png)

**Results:**
https://sentry.dev.happytravel.com/organizations/happytravel/issues/1664
+
![изображение](https://user-images.githubusercontent.com/43397444/111271540-24a2f900-8653-11eb-8596-1ee1a83e9888.png)

**Expected result:**
Results are available, no error is thrown

**Comment by DFSko** [comment]
In second screen you viewing CORS request (method OPTIONS)
You can find results in next request, with GET method

**Comment by sergeyf-QA** [comment]
Summary:
now  at the new search, there is no https://sentry.dev.happytravel.com/organizations/happytravel/issues/1664 error during wide search, results are also returned

OK on DEV.
