### ISSUE TITLE
Add "free of charge" option to Cancel-manually request

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#500]
Sometimes supplier can cancel the booking free of charge without any cancellation policies. 
We need a case to support such situation and refund all the money in this situation

**Comment by mingazhev** [comment]
Need to check if this is possible without huge changes

**Comment by ViTsvetkova** [comment]
@mingazhev do we need this option? Can we implement it?

**Comment by ViTsvetkova** [comment]
https://track.happytravel.tech/issue/HP-535/Add-free-of-charge-option-to-Cancel-manually-request
