### ISSUE TITLE
Agents lose their roles during agency changing

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#501]
**How to reproduce:**
- as an admin change agency for any agent by POST /{culture}/api/{v}/admin/agencies/{agencyId}/agents/{agentId}/change-agency

**Actual result:**
- roles are lost (NULL in AgentRoleIds column at "AgentAgencyRelations" table)

**Expected result:**
- agents should not lose their roles during agency changing

**Comment by kirillta** [comment]
Also, an agent must not keep their master status after a transfer

**Comment by sergeyf-QA** [comment]
@mingazhev 
>Also, an agent must not keep their master status after a transfer

master role is transfered when changing agency

**Comment by mingazhev** [comment]
I've changed the model and now need to specify the roles.
Additionally, fixed the issue with relation type (Master)

**Comment by sergeyf-QA** [comment]
**Summary:**
- POST /{culture}/api/{v}/admin/agencies/{agencyId}/agents/{agentId}/change-agency moves the agent to another agency with roles which I need to set in request
- while agent transfer he loses his Master role if he had it in previous agency

**OK on DEV.**
