### ISSUE TITLE
Return correct paymentStatus for paid bookings from balance

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#502]
1. Create booking with past deadline and choose payment method - `'Account balance'`
`The Cottage Suvarnabhumi, Bangkok, Thailand - date {+ one week from current date}`

2. Check that money was debited from balance
3. Open booking's page and click 'Invoice' button

**AR**: Get incorrect parameter 
`paymentStatus: "NotPaid"`

![Screenshot 2021-08-16 at 17 23 28](https://user-images.githubusercontent.com/38030865/129579290-ecc0b714-586f-48f0-9aaf-d6b5c469c8f5.png)

**Comment by Raibo** [comment]
The final decision was to remove storage of payment status from invoice data altogether and pull it dynamically whenever the invoice is generated.

To QA: please pay additional attention for possible front end issues (datatype which is sent to frontend is changed, though, it **should** be okay).
Also pay attention to payment procedures (account and credit card), because invoice generation is involved there too.

**Comment by sergeyf-QA** [comment]
@Raibo 
1) book within deadline period using acc or card
The Cottage Suvarnabhumi Hotel, Bangkok, Thailand
11-09-2021 – 12-09-2021
1 Adult • 0 Children • 1 Room
United Arab Emirates
**Actual result:**
POST https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/book-by-account
POST https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/DEV-HTL-TH-000Q55-01/finalize
return
{"status":400,"detail":"sandbox_restriction"}
and payment is not completed

2)
invoice 
GET https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/4027/supporting-documents/invoice returns 401 for such bookings

**Comment by Raibo** [comment]
1. This is a supplier's error, when they don't allow development booking confirmation for some their specific reason. (Judging on error text, this is somehow connected with the fact that this is a test enviroment)
2. This looks like "Unauthorized" error, when you don't provide token, the counterparty does not have "FullAccess" verification or agent is trying to get invoice from another agency's booking.

When I test invoices myself, I can't reproduce any issues. 
If this problem persists, please provide me with credentials of a test agent owning the problematic booking.

**Comment by sergeyf-QA** [comment]
**Summary:**
okay with the 1st issue and 2nd issue is not reproduced anymore

**OK on DEV.**
