### ISSUE TITLE
In the calendar, there is no option to select a date in the past

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#510]
On https://manage-dev.happytravel.com/
In Safari, Chrome

**Steps:**
1. Log in some administrator;
2. Go to Reports page;
3. Click on by date in any block of a report;
4. Try to choose any date in past (for example, a month before).

**Expectations:**
The calendar should allow you to choose a date in the past. 

**Result:**
In the calendar, there is no option to select a date in the past (see pic. no_option_to_select_past_date).
<img width="701" alt="no_option_to_select_past_date" src="https://user-images.githubusercontent.com/17127277/130369080-87217187-fd9c-4d91-8a12-28f7ffc2740e.png">

**Comment by sergeyf-QA** [comment]
**Summary:**
now there is a button to go to previous months on the calendar at reports.

**OK on DEV.**
