### ISSUE TITLE
The counterparty in Read Only state has a Read Only button

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#511]
On https://manage-dev.happytravel.com/
In Safari, Chrome

**Steps:**
1. Log in some administrator;
2. Go to Counterparties page;
3. Find any counterparty in Read Only state (for example, DenisTestSeventy-fifth agency);
4. Select the Verification tab;
5. Note the set of buttons to move the counterparty to a certain state.

**Expectations:**
There shouldn’t be a button that moves the counterparty to the state in which it already exists.

**Result:**
The counterparty in Read Only state has a Read Only button (see pic. readOnly_button).
<img width="997" alt="readOnly_button" src="https://user-images.githubusercontent.com/17127277/130369125-18091b8f-f872-4623-adbc-bd8a66314d69.png">

**Comment by sergeyf-QA** [comment]
**Summary:**
now there is no 'Verify Read Only' button at Verification tab for Read-Only counterparties.

**OK on DEV.**
