### ISSUE TITLE
Counterparty information is hidden when you go to Balance tab -> Transfer balance

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#514]
On https://manage-dev.happytravel.com/
In Chrome, Safari, Firefox browsers.

**Steps:**
1. Log in some administrator;
2. Find counterparty by name "The Clouds company»;
3. Go to the Balance tab;
4. Go to the Transfer balance tab;

**Expected:**
The counterparty information should be visible when in all tabs of the counterparty settings. 

**Result:**
Counterparty information is hidden when you go to Balance tab -> Transfer balance (see pic. information_is_hidden).
![information_is_hidden](https://user-images.githubusercontent.com/17127277/130479711-35368b94-d659-428f-841b-832ee620db94.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
now counterparty page has counterparty info

**OK on DEV.**
