### ISSUE TITLE
Don't request the /system-settings/availability-search method when going to the agency page

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#515]
On https://manage-dev.happytravel.com/
In Chrome, Safari, Firefox browsers

**Steps:**
1. Log in some administrator;
2. Find counterparty by name "The Clouds company";
3. Go to the Agencies page (click on "Agencies" tab);
4. Open browser dev. tools panel;
5. Go to the some Agency details page (click on the agency’s name row);
6. Find the /system-settings/availability-search request in browser dev. tools panel

**Expected:**
It was decided to remove the settings from the agency page, so  it is no longer necessary to request a method /system-settings/availability-search

**Result:**
Going to the page makes request for /system-settings/availability-search for agency

**Comment by sergeyf-QA** [comment]
**Summary:**
now method /system-settings/availability-search is not requested while going to the Agency page

**OK on DEV.**
