### ISSUE TITLE
The button in the modal window to confirm counterparty deactivation doesn’t work 

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#518]
On https://manage-dev.happytravel.com/
In Chrome, Safari, Firefox browsers.

**Steps:**
1. Log in some administrator;
2. Find counterparty by name "The Clouds company»;
3. Try to deactivate the counter-agency (move the switch).

**Expected:**
The counterparty deactivation confirmation button should be active and click on it should work - provided that the Conformation field is filled in.

**Result:**
The button in the modal window to confirm counterparty deactivation doesn’t work (see pic. button_deactivation_doesnt_work).
![button_deactivation_doesnt_work](https://user-images.githubusercontent.com/17127277/130590005-5b1e8459-6d27-4464-8e4e-27214fb3bdc0.png)

**Comment by sergeyf-QA** [comment]
@cyberkarma 
Activate button calls a deactivate alert.
![Screenshot at Sep 13 11-33-15](https://user-images.githubusercontent.com/74529212/133051113-474f67ee-1e07-44ce-9cf4-d807deec9b3d.png)

**Expected:**
Activate button should call an activation alert.

**Comment by sergeyf-QA** [comment]
**Summary:**
Activation/deactivation work fine.

**OK on DEV.**
