### ISSUE TITLE
Switch counterparty activation/deactivation always changes position without depending on administrator action

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#520]
On https://manage-dev.happytravel.com/
In Chrome, Safari, Firefox browsers.

**Steps:**
1. Log in some administrator;
2. Find counterparty by name "The Clouds company»;
3. Deactivate the counter-agency (move the switch);
4. Close the modal window without taking any action inside it.

**Expected:**
If the change of counterparty activity hasn’t been confirmed by the administrator, the switch position shouldn’t be changed.

**Result:**
Switch counterparty activation/deactivation always changes position without depending on administrator action.

**Comment by sergeyf-QA** [comment]
**Summary:**
now, when I did not confirm deactivation, then deactivation did not happen

**OK on DEV.**
