### ISSUE TITLE
The success or failure of the balance transfer isn’t shown in the interface

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#521]
On https://manage-dev.happytravel.com/
In Chrome, Safari, Firefox browsers.

**Steps:**
1. Log in some administrator;
2. Find counterparty by name "The Clouds company»;
3. Go to the Balance tab then Transfer Balance subtab;
4. Fiil in all required fields;
5. Open dev. tools panel in browser;
6. Click on the Transfer button and note the UI reaction;
7. Find the /transfer request in dev. tools panel in browser.

**Expected:**
The system must show the administrator the result of their actions, so that they can understand their success or failure.

**Result:**
The success or failure of the balance transfer isn’t shown in the interface.

**Comment by sergeyf-QA** [comment]
**Summary:**
now, if all fields are not filled then 'Transfer' button is disabled.
In case all fields are filled and button is pressed then there is green Done message after successful money transfer.

**OK on DEV.**
