### ISSUE TITLE
Add an endpoint to get agency information

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#53]
Need to return all non-system and human-readable fields for an agency

**Comment by sergeyf-QA** [comment]
**Summary:**
GET /{culture}/api/{v}/agency returns 
"name": "string",   
"address": "string",   
"countryCode": "string",   
"countryName": "string",   
"city": "string",   
"phone": "string",   
"fax": "string",   
"postalCode": "string",   
"website": "string",   
"billingEmail": "string",   
"vatNumber": "string"

**OK on DEV.**
