### ISSUE TITLE
Error while updating status [HotelBeds]

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#531]
1. Create booking (for example, 'DEV-HTL-AE-000B15-01')
"Dubai, The United Arab Emirates - 1 room - 02.09 -04.09"
2. Booking has 'Pending' status

**AR**: Booking doesn't change status 

**[Kibana](https://logs-dev.happytravel.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',key:kubernetes.container_name,negate:!f,params:(query:travelgatex-connector),type:phrase),query:(match_phrase:(kubernetes.container_name:travelgatex-connector))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',key:log_level,negate:!f,params:(query:Debug),type:phrase),query:(match_phrase:(log_level:Debug))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',key:scope.SearchId,negate:!f,params:(query:'3c8af48e-f861-4669-a406-96631f1262fa'),type:phrase),query:(match_phrase:(scope.SearchId:'3c8af48e-f861-4669-a406-96631f1262fa')))),index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',interval:auto,query:(language:kuery,query:%22DEV-HTL-AE-000B15-01%22),sort:!(!(created_at,asc))))**: scope.SearchId: 3c8af48e-f861-4669-a406-96631f1262fa

`Failed to refresh status for a booking with reference code: 'DEV-HTL-AE-000B15-01' while getting info from a supplier. Error: You attempted to create a failure result, which must have an error, but a null error object (or empty string) was passed to the constructor. (Parameter 'error')`

**Comment by mingazhev** [comment]
@Raibo could you please have a look and tell if the bug is on EDO on HotelBeds side?
If it is hotelbeds-connector issue we'll redirect it to Promo-Z team

**Comment by Raibo** [comment]
Hotelbeds connector returns 404 error because there is no endpoint there with address
`https://hc-dev.happytravel.com/api/1.0/accommodations/bookings/{referenceCode}`
only `https://hc-dev.happytravel.com/api/1.0/bookings/{referenceCode}`

**Comment by Raibo** [comment]
For QA: in this task I only made EDO correctly react to an error. Error will still appear until the connector is fixed, but the error itself should have proper description.

**Comment by sergeyf-QA** [comment]
**Summary:**
now there is GET http://hc-dev.happytravel.com/api/1.0/accommodations/bookings/{referenceCode} and it works well, so error does not appear, so, it looks like connector was fixed.
[Kibana logs with 200 status](https://logs-dev.happytravel.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',key:kubernetes.container_name,negate:!f,params:(query:travelgatex-connector),type:phrase),query:(match_phrase:(kubernetes.container_name:travelgatex-connector))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',key:log_level,negate:!f,params:(query:Debug),type:phrase),query:(match_phrase:(log_level:Debug))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',key:scope.SearchId,negate:!f,params:(query:'3c8af48e-f861-4669-a406-96631f1262fa'),type:phrase),query:(match_phrase:(scope.SearchId:'3c8af48e-f861-4669-a406-96631f1262fa')))),index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',interval:auto,query:(language:kuery,query:%22DEV-HTL-AE-000B15-01%22),sort:!(!(created_at,asc))))


**OK on DEV.**
