### ISSUE TITLE
Error when getting rooms for accommodation [HotelBeds]

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#534]
1. Find hotel 
`'Citymax Hotel Bur Dubai - 11.10-14.10 - 2 rooms - RU'`
2. Go to the second step 

**AR**: `Error executing connector request to https://hc-dev.happytravel.com/api/1.0/: 'Value cannot be null. (Parameter 'source')', status code: '500'`

[**Kibana**](https://logs-dev.happytravel.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',key:kubernetes.container_name,negate:!f,params:(query:travelgatex-connector),type:phrase),query:(match_phrase:(kubernetes.container_name:travelgatex-connector))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',key:log_level,negate:!f,params:(query:Debug),type:phrase),query:(match_phrase:(log_level:Debug))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',key:scope.SearchId,negate:!f,params:(query:'59bdf43a-14aa-409d-b472-3a3471b60311'),type:phrase),query:(match_phrase:(scope.SearchId:'59bdf43a-14aa-409d-b472-3a3471b60311')))),index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',interval:auto,query:(language:kuery,query:''),sort:!()))

![Screenshot 2021-09-01 at 08 07 34](https://user-images.githubusercontent.com/38030865/131615198-d634e3bb-55de-47c4-a861-e3008be3e399.png)

**Comment by mingazhev** [comment]
@Raibo This may be related to the issue you previously found, could you check?

**Comment by Raibo** [comment]
Can't reproduce the issue

**Comment by sergeyf-QA** [comment]
**Summary:**
it looks like already fixed.

**OK on DEV.**
