### ISSUE TITLE
Weird refundable amount for production bookings 

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#538]
Somehow refundable amount in `SupplierOrders` table is much larger than needed and less than zero

![image](https://user-images.githubusercontent.com/43397444/131732065-c214d73c-74ac-4732-b7bd-9a8103a723fd.png)

Need to investigate why and fix if needed.

**Comment by sergeyf-QA** [comment]
@Raibo 
when refunded money are 50% from the cost then in RefundableAmount is still 0.0 though money were already reverted
for testing you may 
make a booking using
- Hotel Test Pruebas Travelgate
- dates within deadline period
- book & pay by acc
- then cancel this booking

**Comment by sergeyf-QA** [comment]
**Summary:**
now RefundableAmount in SuppliersOrders table shows data according to the rule:
Price-Price*Cancellation% / 100

**OK on DEV.**
