### ISSUE TITLE
Add a UI to shown and edit agency information

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#54]
Need a UI for backend endpoints:

https://github.com/happy-travel/agent-app-project/issues/52
https://github.com/happy-travel/agent-app-project/issues/53

Agency information will be visible for everybody in an agency, editable by a user with special permissions (for permission names please contact backend task assignee)

**Comment by sergeyf-QA** [comment]
**Summary:**
now I can edit on front-end side 
Address
Phone
Fax
PostalCode
Website
VAT
Billing email

**OK on DEV.**
