### ISSUE TITLE
Documentation for agent roles in EDO

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#544]
1. What are roles
2. Which are used in system and their meaning
3. Built in roles and permissions 
4. How to set roles, which roles are assigned by default in different cases

**Comment by Raibo** [comment]
**Agent roles**

**What are roles**
Most actions, which can be done using the API, require permission to be performed by agents.
A role is a collection of such permissions, that can be assigned to an agent.
When a role is assigned to an agent, this agent receives all the permissions that this role contains.

**Why do we need roles**
Roles make managing agents permissions easier.
A single role typically contains all required permissions to perform a certain type of activity. (For example, sales agent)
Without roles, one would need to assign all required permissions individually, while with roles it is possible in one go.

**Existing roles description**
- Agency administrator  
Permission to assign roles, which basically means every permission. (Agent with this role can assign whatever role they need to themselves)
Invite new agents, invite child agencies
Toggle agents activity (inactive agent can't act)
Management of agency's bookings
Upload images
Markup management
- Auditor  
Observe agents, markups, invitations (of new agents and child agencies), counterparty contract (only for root agencies), child agencies.
- Accounts manager  
Observe agency virtual account balance, payments history.
Perform transfer from agency's financial account to child agencies.
- Sales agent  
Perform availability search and booking.

**How to assign roles**
Go to Menu(top right corner) -> Agency -> Agents management and select an agent.
Following page provides roles assignment for selected agent.

Agency administrator role is required to assign roles.

**Comment by Raibo** [comment]
@mingazhev 
>Built in roles and permissions

I don't get what this one means

**Comment by mingazhev** [comment]
> (For example, sales agent)
What sales agent can do and what permissions? I think will be more clear to add
> Agency administrator and others
Need to change formatting a bit, to highlight role names
> Go to Menu(top right corner) 
Please add a screenshot there

**Comment by Raibo** [comment]
>change formatting a bit  

done
>add a screenshot  

done

>What sales agent can do and what permissions

Sales agent can literally search and book. Permissions are `ccommodation Availability Search`, `Accommodation Booking`
I have nothing to add here.

As for other roles, their descriptions contain what they can do. 
If I were to add permission name next to each action they can perform, it would appear similar to how it appears with "Sales agent", just longer. 
Or maybe I get it wrong, and we should discuss this.

**Comment by Raibo** [comment]
Added to docs

https://github.com/happy-travel/edo/wiki/Agent-roles
