### ISSUE TITLE
Disable the 'Book&' button on click

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#546]
**AR**: On the first click request is sent, but the button is active and the user doesn't understand that the booking is in progress. As a result, two reservations are created. 

![Screenshot 2021-09-02 at 13 18 17](https://user-images.githubusercontent.com/38030865/131827092-c216a911-bcc0-49f7-9d54-58d03e8f4b70.png)

**Comment by alexander-plekhanov** [comment]
I close this task as we have another one that fixes it better. 
https://github.com/happy-travel/agent-app-project/issues/754
