### ISSUE TITLE
Round off 'Percentage' parameter 

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#550]
Round off 'Percentage' parameter because we can get such case:

![Screenshot_2021-09-02_at_07](https://user-images.githubusercontent.com/38030865/131997289-7144c42e-0e66-4cb6-8c25-7a9f1acd7ec9.png)

![Screenshot 2021-09-03 at 14 25 48](https://user-images.githubusercontent.com/38030865/131998187-c43ef006-3d3e-4946-841a-f805c2930967.png)

```
"roomContractSet": {
    "id": "1513971b-37d0-4a1d-9d0d-0c273b1ff81b",
    "rate": {
            ...
    },
    "deadline": {
      "date": "2021-09-26T00:00:00",
      "isFinal": true,
      "policies": [
        {
          "fromDate": "2021-09-26T00:00:00",
          "percentage": 99.99982984139514
        }
      ],
      "remarks": []
    },
    "isAdvancePurchaseRate": false,
    "rooms": [
      {
         ...
        "deadline": {
          "date": "2021-09-26T00:00:00",
          "isFinal": true,
          "policies": [
            {
              "fromDate": "2021-09-26T00:00:00",
              "percentage": 99.99982984139515
            }
          ]
```

**Comment by mingazhev** [comment]
Looks like related with 
https://github.com/happy-travel/agent-app-project/issues/584

**Comment by sergeyf-QA** [comment]
**Summary:**
"percentage" is round off now.

**OK on DEV.**
