### ISSUE TITLE
Docs for accommodation search logs

### ISSUE THREAD

**Issue by Raibo** [happy-travel/agent-app-project#554]

**Comment by Raibo** [comment]
**Accommodation search logs**

This guide shows how to turn on request logging for connectors, perform accommodation search, and then use searchId to access the search logs to troubleshoot accommodation search.

The searchId is the same across all connectors, therefore log events is shown from all connectors (in which request logging was turned on while performing search)


**Instructions**

1. Make sure that RequestLogging is enabled for connectors, for which you want search events to be logged.  
This is configured in Consul (https://consul-dev.happytravel.com/ui/dc1/kv)
Consul requires credentials to log in, which should be available in Passbolt (https://passbolt.happytravel.com)
.
When logged in Consul, find Key/Value (on the top of the page) -> select connector -> in json find `RequestLoggingOptions.IsEnabled` -> set `true`.
(after you are finished, turn this option off, these logs, if left on, take much storage space and accumulate quickly)

2. Perform the search and copy the requestId.
Search for accommodations but with browser's debug window on and logging requests.
Find the request made after clicking button "Search" which contains guid. 
.
For example: https://edo-dev.happytravel.com/en/api/1.0/accommodations/availabilities/searches/fb9eef05-9afe-4f0f-a533-30c63f631adc?top=10&skip=0
Here `fb9eef05-9afe-4f0f-a533-30c63f631adc` is the searchId. 
Copy this value.
.
When you have the searchId, continue the accommodation search normally. (Or in whatever fashion you need to troubleshoot your current issue)

3. Retrieving the logs.
Go to Elastic (https://logs-dev.happytravel.com) and proceed to Discover.
Insert following value into the filter field: `scope.SearchId: "your-searchId"` (with quotes)
.
For example, for the searchId from previous example, this looks like this: `scope.SearchId: "fb9eef05-9afe-4f0f-a533-30c63f631adc"`
.
Don't forget to set timing settings correctly.

4. Turn RequestLoggingOptions off.
Elastic should now show all the logs from all connectors, for which logging was on during the accommodation search.
Don't forget to turn RequestLoggingOptions off after you finish.

**Comment by mingazhev** [comment]
-- Perform the search and copy the requestId.
This is not clear which request id. This should be a search id returned from some endpoint
-- https://edo-dev.happytravel.com/en/api/1.0/accommodations/availabilities/searches/fb9eef05-9afe-4f0f-a533-30c63f631adc?top=10&skip=0
This is the second request, we may get search id from the first POST request, id is returned in a body

**Comment by Raibo** [comment]
Fixed
