### ISSUE TITLE
Move VCC creation logic from Jumeirah-connector to EDO

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#558]
Need to
1. Create and pass VCC with booking request if it was needed in evaluation response
2. Fix scopes and needed clients on identity
3. Remove all this logic from Jumeirah-connector

**Comment by mingazhev** [comment]
Testing tips - check that Jumeirah credit card bookings still work

**Comment by sergeyf-QA** [comment]
@mingazhev 
when I make a Jumeirah booking using credit card and account then
https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/DEV-HTL-AE-000285-01/finalize
https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/book-by-account
returns
500 error

https://sentry1.happytravel.com/organizations/happytravel/issues/3507/?referrer=webhooks_plugin

**Comment by DFSko** [comment]
errors on amex side

**Comment by sergeyf-QA** [comment]
**Summary:**
- now there are no errors during bookings at /finalize and /book-by-account.
- Jumeirah credit card bookings still work

**OK on DEV.**
