### ISSUE TITLE
Add supplier reference codes to voucher e-mail notifications

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#561]
Add fields from models implemented there:
https://github.com/happy-travel/agent-app-project/issues/560

**Comment by DenisSychev** [comment]
Supplier reference code has been added to the Voucher email.
The code is placed in the general booking information box.
The example:
<img width="668" alt="Снимок экрана 2021-11-21 в 22 31 10" src="https://user-images.githubusercontent.com/17127277/142776371-5595107f-a47d-453d-abaa-b7d206029674.png">
