### ISSUE TITLE
Add supplier reference codes to voucher UI form

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#562]
Add and show fields from there:
https://github.com/happy-travel/agent-app-project/issues/560

**Comment by sergeyf-QA** [comment]
**Summary:**
Supplier Reference Code is shown in Voucher when "supplierReferenceCode" in response of GET /en/api/1.0/accommodations/bookings/{bookingId}/supporting-documents/voucher is filled

**OK on DEV.**
