### ISSUE TITLE
Add a table with "admin credit limit notification settings" and admin API to set values in it

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#567]
Admin should be allowed to set credit limit reminder settings for an agency account by agency and account id. 
These settings should be placed in a separate table and contain a model. Model should contain an array of items where each item should present an amount for notifcation.

**Comment by sergeyf-QA** [comment]
**Summary:**
 - BalanceNotificationSettings table exists
- GET /en/api/1.0/admin/agency-accounts/{agencyAccountId}/balance-notification-settings takes data from the BalanceNotificationSettings table
- PUT /en/api/1.0/admin/agency-accounts/{agencyAccountId}/balance-notification-settings writes data to the BalanceNotificationSettings table

**OK on DEV.**
