### ISSUE TITLE
Add notification center logic

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#57]
Need to add some notification center to be an interface for agent notification.
Notifications should be sent to e-mail (with using existing mailsender for now), to signalR or to both (depending on agent preferences from):
https://github.com/happy-travel/agent-app-project/issues/56

**Comment by DenisSychev** [comment]
The Notification Center is available and work at https://edo-dev.happytravel.com/signalr/notifications/agents

**Comment by DFSko** [comment]
Done
