### ISSUE TITLE
Sales report improvements

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#572]
Meaning of current version of sales report is bookings that are payable to supplier.

1. Rename to FinalizedBookingsReport
2. Remove Payment method
3. Remove payment status column
5. Move Supplier name column after Accommodation name

**Comment by sergeyf-QA** [comment]
**Summary:**
- GET /{culture}/api/{v}/admin/reports/finalized-bookings-report is renamed
- Payment method column is removed
- Payment status column is removed
- Supplier name column  is moved after Accommodation name

**OK on DEV.**
