### ISSUE TITLE
SupplerWiseDirectConnectivityReport improvements

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#576]
1. Rename to PayableToSupplierDirectConnectivityReport
2. Filter by supplier order's PayableToSupplierDate column instead of booking created date column
3. Include only confirmed bookings and bookings cancelled after deadline

**Comment by sergeyf-QA** [comment]
**Summary:**
- {{ edo.baseUrl }}/en/api/1.0/admin/reports/direct-connectivity-report/supplier-wise was changed to {{ edo.baseUrl }}/en/api/1.0/admin/reports/direct-connectivity-report/payable-to-supplier
- filtering works by supplier order's PaymentDate column
- only confirmed bookings and bookings cancelled after deadline are in report
- 
**OK on DEV.**
