### ISSUE TITLE
Add api tp get all accommodations with 'Duplicate' deactivation reason with their actual pairs.

### ISSUE THREAD

**Issue by hasmikharutyunyan** [happy-travel/agent-app-project#579]

**Comment by ViTsvetkova** [comment]
@hasmikharutyunyan please close if it was done

**Comment by hasmikharutyunyan** [comment]
> @hasmikharutyunyan please close if it was done

It is not done, it may be needed for admin panel, but not now.

**Comment by hasmikharutyunyan** [comment]
As we will have new mapper this issue no needed fro now
