### ISSUE TITLE
Add an implementation for SignalR service

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#58]
Need to implement a service from the draft:

https://github.com/happy-travel/agent-app-project/issues/55

Including sending notifications, storage etc., all the things that needs to make it work

**Comment by sergeyf-QA** [comment]
**Summary:**
SignalR service is applied, logs work after connection on https://gourav-d.github.io/SignalR-Web-Client/dist/

**OK on DEV.**
