### ISSUE TITLE
Investigate cancellation policy anomalies 

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#584]
Some bookings have weird cancellation policies:
```
HTL-RU-000VT2-01 101.00000000000001
HTL-AE-000YR2-01 100.00000000000001
HTL-AE-0007R2-01 100.00035601505232
HTL-TR-000KP2-01 - 98.80039851168088
```
Need to investigate each case, find and fix the issue

**Comment by DFSko** [comment]
added rounding and condition for percents greater than 100
i guess percentage less than 100 is valid value
