### ISSUE TITLE
Trying to request a deadline in the second step from the Columbus  offer results in "Internal Server Error".

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#585]
**Steps:**
1. Log in some agent;
2. Do a parameter search for Fairmont The Palm, Dubai, The United Arab Emirates
Some future dates (for example, Nov 26 – Nov 27)
1 Guest
Russian Federation (nationality and residency).
3. Select offer from Columbus;
4. Go to second step;
5. Request a deadline (click on Cancelation Deadline button).
 
**Expectations:**
The deadline query should run without errors and return the date as a result.

**Result:**
Trying to request a deadline in the second step from the Columbus  offer results in "Internal Server Error" (see in attach files).
Sentry ID: ad479fbfdd5d4cfc894b8e53dae6aa71
Sentry ID: 88456110267847f39bdb253d899d142f
![request_a_deadline](https://user-images.githubusercontent.com/17127277/133080945-f701bd03-cc1b-4260-b15c-98b626e9413e.png)

**Comment by oleg1std** [comment]
The issue is related to the missing cancellation policies for the contract rate.
Cancellations policies must be added to the contract on https://webqnex-dev.happytravel.com/

**Comment by sergeyf-QA** [comment]
**Summary:**
Cancellation policies for Hilton Dubai Jumeirah, Dubai, The United Arab Emirates opens well

**OK on DEV.**
