### ISSUE TITLE
Invited agent needs to be verified

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#592]
**How to reproduce:**
- invite an agent to the existed agency
- complete new agent registration
- try to find any accommodation

**Actual result:**
- Invited agent needs to be verified before using

**Expected result:**
- invited agent is invited to the existed agency so, he should not wait for verification

**Comment by konstyefremov** [comment]
When inviting an agent we can assign to him one of the roles. If the assigned role doesn't have AvailabilitySearch permission then this modal is shown:

![image](https://user-images.githubusercontent.com/44425020/133776407-2b0fb844-f389-4170-aaa6-805fbbb742b7.png)

**Comment by konstyefremov** [comment]
Maybe it will be better if the modal will inform that "your account doesn't have search permissions".
Needs to be discussed with @kirillta and @alexander-plekhanov

**Comment by kirillta** [comment]
Doesn't our default permissions include search? They definitely should

**Comment by ViTsvetkova** [comment]
Are going to change the registration flow
