### ISSUE TITLE
Invited agency has no its own name is Settings

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#593]
**How to reproduce:**
- invite an agency
- complete child agency registration

**Actual result:**
- Invited agency has no its own name is Settings on https://dev.happytravel.com/settings/agency
![Screenshot at Sep 15 11-02-55](https://user-images.githubusercontent.com/74529212/133395662-717c05c8-618e-44b1-8d40-889d06706ebe.png)

**Expected result:**
- Invited agency should have its own name is Settings

**Comment by mingazhev** [comment]
Counterparty name is shown while Agency name is needed

**Comment by Raibo** [comment]
Checked the code and requests data.
Looks like correct data is coming from back end, but front end takes counterparty name to this field.

![image](https://user-images.githubusercontent.com/8547320/134821370-cf0b4a83-c203-4897-a275-3d3b3e55f0a5.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
now there is shown child_agency name and info

**OK on DEV.**
