### ISSUE TITLE
Child agencies list UI

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#6]
Implement child agencies list UI for https://github.com/happy-travel/agent-app-project/issues/2

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
could you please remove child agency balance from the child agencies list https://dev.happytravel.com/settings/child-agencies ?

**Comment by sergeyf-QA** [comment]
**Summary:**
Child agency list is available now on https://dev.happytravel.com/settings/child-agencies .

**OK on DEV.**
