### ISSUE TITLE
Splitting request by max 3 hotel codes per request

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#600]
Sarita from Jumeirah asked to split multiple availability search request to bunches of hotel codes, not more than 3 for each.

**Comment by mingazhev** [comment]
How to test:
Check that requests to Jumeirah API does not fail, for single or multiple hotels

**Comment by sergeyf-QA** [comment]
**Summary:**
wide availability search and single one work fine.

**OK on DEV.**
