### ISSUE TITLE
Counterparty 248 account increasedManually notification failed with error Master agent does not exist

### ISSUE THREAD

**Issue by Raibo** [happy-travel/agent-app-project#604]
This is a bug from sentry.

Counterparty 248 account increasedManually notification failed with error Master agent does not exist

https://sentry1.happytravel.com/organizations/happytravel/issues/3512/?environment=Development&project=2&referrer=alert_email

**Comment by Raibo** [comment]
Problem was that some agencies are active on DEV, but have no master or no agents whatsoever.
Such agencies on DEV:
```
"AgencyId"	"CounterpartyId"
"887"	"184"
"1009"	"248"
"779"	"4"
"781"	"8"
"820"	"118"
"1006"	"245"
"857"	"154"
"787"	"46"
```

**Comment by mingazhev** [comment]
Agencies without agents can be removed from dev, with notifying all

**Comment by Raibo** [comment]
Since additional logic is attached to agency and counterparty deactivation, I decided not to use migrations.
Here are SQL queries to load which agencies and counterparties should be deactivated using admin API.

There were also a condition that counterparties without active agencies but verified are to be asked about from the office, but no such counterparties exist on prod.

Load agencies to deactivate:
```
-- ***Deactivate agencies***
SELECT "Id" as "AgencyId"
FROM "Agencies" ag
WHERE "IsActive" = TRUE
AND (SELECT COUNT(1) FROM "AgentAgencyRelations" rel WHERE rel."AgencyId" = ag."Id") = 0 --no agents
AND (SELECT COUNT(1) FROM "Bookings" b WHERE b."AgencyId" = ag."Id") = 0 --no bookings
```

Load counterparties to dectivate:
(This query accounts for agencies for deactivation and may be executed immediately, without deactivating agencies first)
```
-- ***Deactivate counterparties***
SELECT "Id" AS "CounterpartyId"
FROM "Counterparties" C
WHERE "IsActive" = TRUE
AND "State" IN (0, 2) --Pending, Declined
AND (SELECT COUNT(1) FROM "Agencies" ag WHERE ag."CounterpartyId" = C."Id" AND ag."IsActive" = TRUE) = 0 --no active agencies

UNION 

SELECT c."Id" AS "CounterpartyId"
FROM "Agencies" ag
LEFT JOIN "Counterparties" c ON ag."CounterpartyId" = C."Id"
WHERE c."IsActive" = TRUE
AND "State" IN (0, 2) --Pending, Declined
AND (SELECT COUNT(1) FROM "AgentAgencyRelations" rel WHERE rel."AgencyId" = ag."Id") = 0 --no agents
AND (SELECT COUNT(1) FROM "Bookings" b WHERE b."AgencyId" = ag."Id") = 0 --no bookings
```
