### ISSUE TITLE
In the first search step isDirectContract is true but in the second step isDirectContract is false

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#606]
On https://dev.happytravel.com/
In Safari, Chrome

**Steps:**
1. Log in some agent;
2. Open a dev. tools in browser;
3. Do a search by parameters:

> Address Dubai Marina, Dubai, The United Arab Emirates
> Oct 14 – Oct 15
> 1 guest
> Russia (nationality and residency);

4. See the response to the search request;
5. Note the Direct Connectivity mark in the contacts in UI;
6. Go to the second search step;
7. See the response to the search request;
8. Note the Direct Connectivity mark in the contacts in UI.

**Expectations:**
If the isDirectContract is true in the first search step, it should also be true in the second search step.

**Result:**
In the first search step isDirectContract is true but in the second step isDirectContract is false
<img width="1126" alt="Снимок экрана 2021-09-19 в 22 09 44" src="https://user-images.githubusercontent.com/17127277/133973085-83cd0dfb-968e-447b-a0c6-e1add941ec07.png">
.
<img width="1659" alt="Снимок экрана 2021-09-19 в 22 09 53" src="https://user-images.githubusercontent.com/17127277/133973114-681ab3b6-220d-49a3-99a0-206325fc193d.png">

**Comment by DFSko** [comment]
Please check your "IsDirectContractFlagVisible" search setting
