### ISSUE TITLE
There is a error "Invalid ClientCode and Password" in response by the /state request

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#607]
On https://dev.happytravel.com/
In Safari, Chrome

**Steps:**
1. Log in some agent;
2. Open a dev. tools in browser;
3. Do a search by parameters:
> Dubai, The United Arab Emirates
> Oct 14 – Oct 15
> 1 guest
> Russia (nationality and residency);
4. See the responses to the /state request.

**Expectations:**
The presence of an error in the answer requires attention.

**Result:**
There is a error "Invalid ClientCode and Password" in response by the /state request
<img width="1009" alt="Снимок экрана 2021-09-19 в 22 16 59" src="https://user-images.githubusercontent.com/17127277/133974926-87956bba-810a-4a2e-a8fd-5de04fef06d7.png">

**Comment by sergeyf-QA** [comment]
**Summary:**
now there is no error in /state response "Invalid ClientCode and Password"

**OK on DEV.**
