### ISSUE TITLE
Fix production bookings status

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#61]
Here is a list of bookings on production that looks invalid:

HTL-AE-000632-01 
HTL-AE-000Z22-01 
HTL-AE-000J22-01
HTL-AE-000I22-01
HTL-AE-000D22-01

What's the flow to handle them:
1. Get information about actual booking status: from the suppliers admin panel or by writing to support.
If it is Illusions, you can ask for admin panel credentials from @kirillta , support's mail is (Sam):

Samuel Michael Nitz <sam.n@illusions-online.com>
2. Then need try to call admin's Refresh booking status endpoint to try refreshing booking status from the API.
If this will not succeed, need to call an admin endpoint, depending on the actual supplier booking situation:
- If the booking is actually cancelled on supplier, call the admin endpoint "cancel-manually" with providing actual cancellation date (cancelled means that it exists on supplier and cancelled).
- If the booking is not registered on supplier's end, need to call admin endpoint "discard".
- If the booking was actually rejected by supplier, need to call admin endpoint "reject manually"

**Please keep in mind that before calling manual booking update admin endpoints (cancel-manually, discard, reject-manually) we must be totally sure that we are in sync with supplier and it will not charge us money for these bookings. The API may lie, Illusions' admin app may lie too, so you may ask for confirmation from support directly to be confident**

**Comment by Raibo** [comment]
Was cancelled and cancelled-manually:
HTL-AE-000D22-01
HTL-AE-000I22-01
HTL-AE-000J22-01
HTL-AE-000Z22-01

Was no information about at the provider side and discard:
HTL-AE-000632-01
