### ISSUE TITLE
Hbpro-connector. Get deadline info endpoint

### ISSUE THREAD

**Issue by oleg-n-k** [happy-travel/agent-app-project#614]
Implement the endpoint for getting deadline info

**Comment by sergeyf-QA** [comment]
**Summary:**
{{ _.hotelbookProConnector.baseUrl }}/api/1.0/accommodations/availabilities/8c3b54eb4aaa4b1cb31c4def88e0267b/room-contract-sets/a7190b06-0b87-402c-bb18-3a5b41dbf076/deadline returns 
{
  "date": "2021-12-10T22:59:00+00:00",
  "isFinal": true,
  "policies": [
    {
      "fromDate": "2021-12-10T22:59:00+00:00",
      "percentage": 1.0
    }
  ],
  "remarks": [
    null
  ]
}

**OK on DEV.**
