### ISSUE TITLE
Change existing markup agent scope appliance

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#615]
1. Add AgentMarkupScopeType enum:
`Agent, Agency, Counterparty, Country, City, Global`
2. Add two columns to `MarkupPolicies` table: AgentScopeType (of type AgentMarkupScopeType) and string AgentScopeId
3. Add a migration to include these columns
4. Add a migration to fill the new columns values depending on existing AgencyId, CounterpartyId, AgentId.
This should be simple for agency and counterparty related markups but needs some thinking about how to handle markups with both AgencyId and AgentId filled. We'll need to have some complex Id for AgentAgencyRelation here. 
I'd suggest something like:
`{AgentId}-{AgencyId}`

**Comment by konstyefremov** [comment]
Can you elaborate on the (4)?
