### ISSUE TITLE
Add admin endpoints for global markup management

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#62]
Need to add all common markup operations as add, edit, remove+ getting list of global markups (with formulas)

**Comment by DFSko** [comment]
global formula can be only one (not list)

**Comment by sergeyf-QA** [comment]
wait until https://github.com/happy-travel/edo/issues/551 be completed

**Comment by mingazhev** [comment]
Need a separate endpoint family for global markups. The same that is done for agent's and agency's markup

**Comment by sergeyf-QA** [comment]
@DFSko
PUT /{culture}/api/{v}/admin/global-markups/{policyId}
returns
{
"status": 400,
"detail": "Policy with same order is already defined"
}
when I leave order as it was previously,
also needs to fix at all PUT markups endpoints

**Comment by sergeyf-QA** [comment]
**Summary:**
all endpoints for global markup management work all

**OK on DEV.**
