### ISSUE TITLE
The enabledSuppliers object has a supplier with the Unknown name

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#620]
https://edo-dev.happytravel.com/index.html

The PUT methods 
/{culture}/api/{v}/admin/agencies/{agencyId}/system-settings/availability-search
/{culture}/api/{v}/admin/agencies/{agencyId}/agents/{agentId}/system-settings/availability-search
have a supplier named Unknown in the enabledSuppliers objec
<img width="372" alt="Снимок экрана 2021-09-21 в 21 36 41" src="https://user-images.githubusercontent.com/17127277/134229585-415d16f9-0044-4e7b-9b87-2950f323acb0.png">
t

**Comment by DFSko** [comment]
Not a bug

Swagger generates example with all enum values
Unknown is default supplier enum value and not used anywhere
