### ISSUE TITLE
Add disabled hotel codes to not return results in Illusions

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#623]
Need to add a setting in consul to filter (not return) the availability results for a list of hotels in Illusions.
There will be several hotels for now, only for Jumeirah.

**Comment by DFSko** [comment]
Testing tips:

1. Add supplier accommodation code (not htId) to array "HiddenAccommodationsCodes" in consul key "iwtx-connector"
2. Wait a few seconds. Connector settings updated automatically
3. Accommodation should be hidden in first step search

**Comment by sergeyf-QA** [comment]
**Summary:**
works fine with https://consul-dev.happytravel.com/ui/dc1/kv/iwtx-connector/edit and "HiddenAccommodationsCodes": ["8-13849"]

**OK on DEV.**
