### ISSUE TITLE
Documentation on Booking codes

### ISSUE THREAD

**Issue by Raibo** [happy-travel/agent-app-project#628]
Create a doc for Booking codes such as supplier reference code, hotel confirmation number and room reference codes.

**Comment by Raibo** [comment]
**General info**
There are 3 parties involved in accommodation booking: Happy Travel, a supplier and a hotel.

Therefore there are codes for each party (unique for each booking):
| Party | Code | Purpose | When appears |
| ------------- | ------------- | ------------- | ------------- |
| Happy Travel | Reference code | Booking reference | Always |
| Supplier | Supplier reference code | Booking reference  | If not direct contract, in most suppliers |
| Supplier | Room reference code | Booked room reference | If not direct contract, in some suppliers |
| Hotel | Hotel confirmation number | Booking reference | If direct contract or maybe in Rakuten supplier |

Supplier might use Reference code or Hotel confirmation code as a Supplier reference code.

**Reference code details**
This code is generated by Happy Travel system and used for referencing bookings inside the system.

Some suppliers might recognize this code or use it as a Supplier reference code.
For example, Illusions accepts our reference code for booking cancellation.

Some suppliers might provide this code to the hotel. if so, then it is possible to find booking in hotel's system using this code.


**Supplier reference code details**
This code is used by most suppliers as a booking reference.
So, it must be used to find booking in their system or perform actions, e.g. cancel a booking.

Generally is generated by a supplier, but also might be equal to Reference code or to Hotel confirmation number.


**Room reference code details**
Some suppliers generate a distinct code for each booked room.
This code is usually used when a supplier operates booked rooms separately, not accommodation booking as a whole.

Appears in Illusions, Jumeirah.


**Hotel confirmation number details**
This code is used as a booking reference by a hotel.
Happy Travel system needs this code if a booking is a direct contract, in which case it is dealing with a hotel directly.

If a booking is not a direct contract, then a supplier handles communications with a hotel, so suppliers often don't provide a Hotel confirmation number.

**Comment by mingazhev** [comment]
1. Happy Travel - without whitespace
2. I'd place a `Code` like a first column, not the second
3. I'd add a remark what direct contract means there. Direct contracts - contracts that are served through our property management system (now it is Columbus, in future will be own). We have direct contracts in Illusions and Jumeirah through the API, this is the different thing

**Comment by Raibo** [comment]
Added to docs.
https://github.com/happy-travel/edo/wiki/Booking-codes
