### ISSUE TITLE
Add admin endpoints for counterparty markup management

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#63]
Add endpoints to add, remove, edit + getting list of markups for given counterparty (with formulas)

**Comment by sergeyf-QA** [comment]
**Summary:**
now in DisplayedMarkupFormulas table also are logged admin markup operations according to counterparty and agency

**OK on DEV.**

**Comment by mingazhev** [comment]
Need a separate endpoint family for counterparty markups. The same that is done for agent's and agency's markup

**Comment by sergeyf-QA** [comment]
@DFSko 
PUT /{culture}/api/{v}/admin/counterparties/{counterpartyId}/markups/{policyId}
returns 
{
  "status": 400,
  "detail": "Policy with same order is already defined"
}
when I leave order as it was previously
