### ISSUE TITLE
Add VCC engine documentation

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#630]
Need to add domain-targeted doc with the following topics:
1. Why we need VCC engine
2. How it works from our VCC provider side
3. How it works on our side - VCC issuing, deletion, modification. In which case what is happened and what are the parameters.
Which services are involved and how EDO decides to issue or not to issue VCC
4. VCC report logic as a part of VCC engine

For any questions please contact @mingazhev

**Comment by Raibo** [comment]
### What is virtual credit card (VCC)
Virtual credit card can be created based on a real credit card, but with distinct payment credentials and limited money amount.
The spent money are still drawn from the real credit card.
Reasons to make one:

- Credit card limit. You can be sure that no more than that amount will be spent.
- Distinct credentials. You can provide the vendor with VCC credentials and don't show real credentials.
- Can be deleted at any time. If something goes wrong or you are sure that no further spendings ahead, you can delete it.

### Why we need VCC engine

**Comment by Raibo** [comment]
All have been fixed some while age

**Comment by Raibo** [comment]
https://github.com/happy-travel/edo/wiki/VCC-engine
