### ISSUE TITLE
[adminPanel] Update method for counterparty verification

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#65]
1. Open _https://manage-dev.happytravel.com/counterparties/{{countepartyId}}_ for counterparty with ReadOnly
2. Push the button 'Verify'

3. User must choose one option from [ **CashPayments, CreditPayments, CreditCardPayments** ] - make a dropdown list for selection

Using method `/{culture}/api/{v}/admin/counterparties/{counterpartyId}/verify-full-access`

**ER**: Send request with **added** parameter _contractKind_
`{
    "contractKind":  "CashPayments",  
    "reason": "Confirmation of the test counterparty by Denis Dolmatov request"
}`

**Comment by sergeyf-QA** [comment]
**Summary:**
'Verify Cash Payments', 'Verify Credit Payments', 'Verify Credit Card Payments' buttons on https://manage-dev.happytravel.com/counterparties/{{countepartyId}} send POST /{culture}/api/{v}/admin/counterparties/{counterpartyId}/verify-full-access with contractKind parameter according to which button was clicked.

**OK on DEV.**
