### ISSUE TITLE
Add a tutorial on how to invite an agent to an agency

### ISSUE THREAD

**Issue by kirillta** [happy-travel/agent-app-project#654]
The result will be posted as a separate article for agents

**Comment by Raibo** [comment]
### Guide to invite an agent.

1. Click the "Menu" button at the top-right corner of the site. You should now see the menu.
2. Click the "Agency" button below the counterparty information. 
3. Click the "Invitations" button just below the previous button. You should see all the invitations, if there are any.
4. Scroll all the way down.
5. Click the "Invite an agent" button.
<details>
<summary>Scheme</summary>

![image](https://user-images.githubusercontent.com/8547320/135758176-a0984352-f52b-44d0-8181-4a064039f228.png)

</details>

**Comment by kirillta** [comment]
Nice, but could you add a note when one may need an invitation link, and when one needn't?

**Comment by mikheevaksenia** [comment]
First draft https://docs.google.com/document/d/1mkZBorHTpQr20ks09_o42loITmqw1Z_j5obFGuB4Qi8/edit need to be discussed with Designer
