### ISSUE TITLE
Search error [TravelgateXTest]

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#657]
https://logs-dev.happytravel.com/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',key:kubernetes.container_name,negate:!f,params:(query:travelgatex-connector),type:phrase),query:(match_phrase:(kubernetes.container_name:travelgatex-connector))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',key:log_level,negate:!f,params:(query:Debug),type:phrase),query:(match_phrase:(log_level:Debug))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',key:scope.SearchId,negate:!f,params:(query:'41eda8d5-faa9-4a77-9351-86e71f7dbf17'),type:phrase),query:(match_phrase:(scope.SearchId:'41eda8d5-faa9-4a77-9351-86e71f7dbf17')))),index:'74b82510-a78b-11eb-a6b0-c1009595f0bf',interval:auto,query:(language:kuery,query:''),sort:!())

**Comment by DFSko** [comment]
cant reproduce this bug

**Comment by sergeyf-QA** [comment]
can not reproduce the bug, logging is added for this issue, so, in case it appears we will see that
