### ISSUE TITLE
Parameter resultCount is displayed incorrectly

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#66]
1. Open search page 
2. Fill all fields
_Destination: Vienna, Austria
Dates: 20-03-2021 – 21-03-2021
Adults: 1_ 

**AR**: The last request _/en/api/1.0/accommodations/availabilities/searches/{{id}}/state_ returns a parameter resultCount: 114. 
Then next request _/en/api/1.0/accommodations/availabilities/searches/{{id}}_ returns an empty response.

**Comment by nikolaeva31** [comment]
![Screenshot 2021-03-17 at 11 35 55](https://user-images.githubusercontent.com/38030865/111438719-a2c7d400-8715-11eb-8a99-d8d0b015c4e5.png)

**Comment by mingazhev** [comment]
The same time issue happened:

https://sentry.dev.happytravel.com/organizations/happytravel/issues/1340
