### ISSUE TITLE
Infinite number of /balance requests

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#666]
On https://manage-dev.happytravel.com/
In Safari, Chrome

1. Login some administrator;
2. Open the browser dev. tools;
3. Find The Clouds Company in the counterparties list;
4. Go to counterparty details page;
5. Note the /balance requests in the browser dev. tools.

**Expectations:**
The counterparty page has only one place with the balance, so only one query /balance is sufficient.

**Result:**
Infinite number of /balance requests. High load on the server and on the front-end side.
<img width="1160" alt="Снимок экрана 2021-10-01 в 10 14 05" src="https://user-images.githubusercontent.com/17127277/135582113-4c8428e2-a2a9-4502-8424-227401b2c90d.png">

**Comment by sergeyf-QA** [comment]
@cyberkarma 
now there are :
a lot of GET https://edo-dev.happytravel.com/en/api/1.0/admin/counterparties/83
4 GET https://edo-dev.happytravel.com/en/api/1.0/admin/counterparties/83/accounts/USD/balance
2 GET https://edo-dev.happytravel.com/en/api/1.0/admin/counterparties/83/accounts
**Expected:**
all requests should be requested 1 times only

**Comment by DenisSychev** [comment]
The errors described have been fixed or have lost relevance. 
There are errors with re-calling other methods, but these will be described in other tasks.
