### ISSUE TITLE
[UI] Hide button 'Generate Invitation Link' for certain conditions

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#68]
1. Open page {url}/settings/invitations/{codeHash}
**ER**: Don't show the button 'Generate Invitation Link' for all invitation statuses 

2. Show accepted invitations for history (without buttons)

3. Don't show the button 'Disable' and 'Resend' for disabled invitations

**Comment by nikolaeva31** [comment]
<img width="1187" alt="Screenshot 2021-03-17 at 17 53 49" src="https://user-images.githubusercontent.com/38030865/111487881-c4db4980-8749-11eb-86b4-45732ee6f3db.png">

**Comment by mingazhev** [comment]
We've added two additional properties to invitations model: Status (Active, Revoked, Resent, Accepted) and IsExpired (bool).
The logic to implement (as it seems to me):
| Status\Expiration state | Is expired | Is not expired |
| --- | --- | --- |
| Active | Disable, Resend, Generate | Resend, Generate  |
| Revoked | - | - |
| Resent | - | - |
| Accepted | -  | -  |

@nikolaeva31 @alexander-plekhanov if you have other opinions please discuss

**Comment by kirillta** [comment]
happy-travel/matsumoto#45

**Comment by mingazhev** [comment]
Removing this from myself since all looks done from backend side
