### ISSUE TITLE
No validation for spaces in guests' first or last names

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#69]
On http://dev.happytravel.com/
In Chrome, Safari.

Steps:
1. Log in some agent who can booking;
2. Make any booking, but when entering the guests' first and last names add spaces before and after the names;
3. Look up the information about this booking in the database.

Result:
No validation for spaces in guests' first or last names (see pic. https://drive.google.com/file/d/1ozeqt0y7JR2gAtYj5-wnBvudUoO5syFv/view?usp=sharing )

Expectations:
There should be no spaces before or after the first and last names.

**Comment by alexander-plekhanov** [comment]
I think it's better to implement trim on API side.

**Comment by sergeyf-QA** [comment]
@mingazhev 
![Screenshot at Mar 24 17-41-48](https://user-images.githubusercontent.com/74529212/112330111-cf0cc300-8cc8-11eb-9ace-d11428956f22.png)

**Comment by DenisSychev** [comment]
The Last Name field is not handled - you can still put spaces in front of the name and it will be saved in the database.
<img width="903" alt="Снимок экрана 2021-03-25 в 11 22 25" src="https://user-images.githubusercontent.com/17127277/112443160-ad115000-8d5d-11eb-8426-50aaa90906e3.png">

**Comment by mingazhev** [comment]
Looks like Main passenger name comes from frontend request as a single string. We cannot process this on backend side.
@alexander-plekhanov could you manage this from your side?

**Comment by sergeyf-QA** [comment]
**Summary:**
now there are no spaces in requests and responses also as in database

**OK on DEV.**
