### ISSUE TITLE
Header is broken in payment form by direct link

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#70]
On http://dev.happytravel.com/
In Chrome, Safari.

Steps:
1. Go to this link https://dev.happytravel.com/pay/aYO5rEa5hUiHrnpuRzyHTQ (or create new pre-payment link);
2. Scroll the page.

Result:
Header is broken in payment form by direct link (see pic. https://drive.google.com/file/d/1DJN6UGvzcNt7hvnix0fisXfdcrq4Hhbs/view?usp=sharing ).

Expectations:
The header should be fixed to the top of page.

**Comment by sergeyf-QA** [comment]
**Summary:**
now header is scrolling together with the whole page w/o any artifacts

**OK on DEV.**
