### ISSUE TITLE
Rethink about Deactivation Reasons.

### ISSUE THREAD

**Issue by hasmikharutyunyan** [happy-travel/agent-app-project#703]
Now one accommodation can have only one Deactivation Reason. Could be situations when accommodation deactivated by reason 'Merge with other' and 'Duplicate in one Supplier'.

**Comment by ViTsvetkova** [comment]
@hasmikharutyunyan please close if done

**Comment by hasmikharutyunyan** [comment]
> @hasmikharutyunyan please close if done
It is not done

**Comment by hasmikharutyunyan** [comment]
It is partly done, As we will have new mapper this issue no needed fro now
