### ISSUE TITLE
[UI] Disable the email field for editing by invitation link 

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#72]
1. Send invitation to user 'maria.nikolaeva+agent23@happytravel.com'
2. Open invitation link. Field 'email' is filled - 'maria.nikolaeva+agent23@happytravel.com'
3. Edit this field - 'maria.nikolaeva+agent231@happytravel.com'
4. Complete registration 

**AR**: User registered with email 'maria.nikolaeva+agent23@happytravel.com'

**ER**: Disable the email field for editing

**Comment by nikolaeva31** [comment]
step 1 
![Screenshot 2021-03-17 at 18 37 10](https://user-images.githubusercontent.com/38030865/111575859-59808e80-87c0-11eb-9a48-a014b1dc7c05.png)

**Comment by nikolaeva31** [comment]
step 2
![Screenshot 2021-03-17 at 18 38 02](https://user-images.githubusercontent.com/38030865/111575898-6d2bf500-87c0-11eb-8716-776b36277d5c.png)

**Comment by nikolaeva31** [comment]
**AR**
![Screenshot 2021-03-17 at 18 39 24](https://user-images.githubusercontent.com/38030865/111575935-7f0d9800-87c0-11eb-9c4e-7d7e1a9bed51.png)

**Comment by Raibo** [comment]
@nikolaeva31 from my perspective, it is totally OK that an invitee can receive an invitation to one email and then use another email as their login in the system.
It is totally up to them, which email to bind to our service. For example, they may want to have a separate email, dedicated exclusively for our notifications.

**Comment by Raibo** [comment]
In identity user is registered with new email, in Edo with old email.

**Comment by Raibo** [comment]
Disabling email field for editing is a bad idea, users should have option to use email that is different from one that was in an invitation.

**Comment by sergeyf-QA** [comment]
**Summary:**
now, agents are registered for email that was entered on identity page.
Works for agent and child agencies invitations.

**OK on DEV.**
