### ISSUE TITLE
Copy needed models from HappyTravel.Edo.Api

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#723]
Need to copy all the models needed for availability search and booking steps:
1. Wide search
2. Room selection
3. Booking evaluation
4. Booking
5. Booking retrieval
6. Booking cancellation

None of the models should depend on existing Api project models (only enums and contracts dependencies are allowed).
For the first time, no project reference to Api project should exist, to make models strictly independent.

**Comment by DFSko** [comment]
added models as needed

**Comment by sergeyf-QA** [comment]
**Summary:**
Done.

**OK on DEV.**
