### ISSUE TITLE
Disallow double bookings on backend side

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#733]
How this can be done:
1. Add an evaluation id or evaluation token for the model, returned on 3-rd step (random unique value)
2. Require this token to be filled during the booking. Acquire atomic distributed lock in redis for given value.
3. Save this value along with booking request in requests table
4. Check that booking was already registered during this operation. If yes, return OK without doing any changes.
If no, proceed with booking steps

**Comment by DenisSychev** [comment]
When selecting the payment type Pay Later (Offline). After a minute or more I can make reservations with exactly the same parameters.
https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/book-for-offline
For example,
DEV-HTL-RU-0002Q5-01
DEV-HTL-RU-0003Q5-01
DEV-HTL-RU-0005Q5-01
DEV-HTL-RU-0004Q5-01

<img width="964" alt="Снимок экрана 2021-12-01 в 00 22 38" src="https://user-images.githubusercontent.com/17127277/144130756-7c22c316-7428-4c7a-b72b-4590af2f2e51.png">

**Comment by ViTsvetkova** [comment]
@kirillta has accepted this behaviour
