### ISSUE TITLE
Reorder enum in AgentMarkupScopeType

### ISSUE THREAD

**Issue by konstyefremov** [happy-travel/agent-app-project#736]
Currently enum is ordered this way:

NotSpecified = 0,
Global = 1,
Counterparty = 2,
Agency = 3,
Agent = 4,
Location = 5

Need to change order to this :

NotSpecified = 0,
Global = 1,
Location = 2,
Counterparty = 3,
Agency = 4,
Agent = 5,

Then after sorting MarkupPolicies by this enum, we'll get the correct order for applying markups. 

And write a migration to accommodate changes

**Comment by sergeyf-QA** [comment]
**Summary:**
order of applied markups is 
Global = 1,
Location = 2,
Counterparty = 3,
Agency = 4,
Agent = 5,
tested by 


Global = multiplication 1.06,
Location = addition 1000,
Counterparty = multiplication 2,
Agency = addition 1111,
Agent = multiplication 3,
price=19 of Zolotaya Melnitsa Mini Hotel
(((price x 1.06)+1000)*2)+1111)*3 = 9 453,84

**OK on DEV.**
