### ISSUE TITLE
Move all left counterparty properties to agency

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#762]
As a result counterparty should contain only Id and name

**Comment by Raibo** [comment]
https://github.com/happy-travel/agent-app-project/issues/762

Moved `LegalAddress` and `PreferredPaymentMethod` to Agency.
Left `Id`, `Name`, `IsContractUploaded` as is.
Removed other fields.

I will update insomnia when this PR is approved.

**Comment by sergeyf-QA** [comment]
**Summary:**
"Id", "Name", "IsContractUploaded" columns are left "Counterparties" table.
"LegalAddress" and "PreferredPaymentMethod" are in "Agency" table.

**OK on DEV.**
