### ISSUE TITLE
Change counterparty registration to use locality instead of city and country

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#764]
2 fields, filled during registration: City and Country should be replaced with a single one: 
Locality select, from existing predictions control

++ need to use new predictions endpoint with filtering by locality only, e.g.:

`https://osaka-dev.happytravel.com/api/1.0/predictions/search?text=Du&types=Locality`

**Comment by sergeyf-QA** [comment]
**Summary:**
City and Country fields are replaced with the 'Locality select' one on 3rd registration step.

**OK on DEV.**
