### ISSUE TITLE
Move contract loading logic from counterparty to agency

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#765]
Need to move:
1. Endpoints for working with contract (in agent and admin app)
2. Columns in db (with migration)

**Comment by sergeyf-QA** [comment]
**Summary:**
- "IsContractUploaded" exists in "Agencies" table
- PUT api/{v:apiVersion}/admin/counterparties/{counterpartyId}/contract-file and GET api/{v:apiVersion}/admin/counterparties/{counterpartyId}/contract-file are removed
- PUT api/{v:apiVersion}/admin/agencies/{agencyId}/contract-file and GET api/{v:apiVersion}/admin/agencies/{agencyId}/contract-file applied and work fine
- POST  ​/{culture}​/api​/{v}​/admin​/counterparties​/reupload-to-agencies made migration from "IsContractUploaded" of the "Counterparties" table to "Agencies" one well

**OK on DEV.**
