### ISSUE TITLE
Jumeirah | /finalize and /book-by-account return 400 error

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#771]
**How to reproduce:**
- try to book using credit card
Jumeirah Al Qasr, Dubai, The United Arab Emirates
30-10-2021 – 31-10-2021
1 Adult • 0 Children • 1 Room
United Arab Emirates
United Arab Emirates

**Actual result:**
- after the payment https://edo-dev.happytravel.com/en/api/1.0/accommodations/bookings/DEV-HTL-AE-0004G5-01/finalize
returns {"status":400,"detail":"Firewall rejection"}
- the same issue with /book-by-account request

**Expected result:**
- successful payment, no error

**Comment by mingazhev** [comment]
Will not fix this on our side, this is totally their error and we are in touch with their support. Can be considered not as a bug

**Comment by ViTsvetkova** [comment]
The supplier resolved errors from their side

**Comment by sergeyf-QA** [comment]
**Summary:**
- "Firewall rejection" error is fixed while booking

**OK on DEV.**
