### ISSUE TITLE
Fix sentry error in NGenius

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#773]
https://sentry1.happytravel.com/organizations/happytravel/issues/3772/?project=2&referrer=webhooks_plugin

**Comment by DFSko** [comment]
done

**Comment by sergeyf-QA** [comment]
**Summary:**
for such cases 
- apply a big markup like addition 28000000
- try to pay (not in deadline) by acc, e.g
Address Dubai Marina (Columbus)
04-11-2021 – 06-11-2021
2 Adults • 0 Children • 1 Room
Russian Federation
Russian Federation
- pay Not Paid booking by card

{"status":400,"detail":"Amount Limit Exceeded"} is applied

**OK on DEV.**
