### ISSUE TITLE
500 error during agent endpoints execution  using admin token

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#775]
**How to reproduce:**
- use admin token (this admin also should be an agent) from admin panel for logging in Swagger
- try to execute e.g. GET /{culture}/api/{v}/agency/child-agencies/{agencyId}/markup-policies

**Actual result:**
- 500 error 
https://sentry1.happytravel.com/organizations/happytravel/issues/3782/?referrer=webhooks_plugin

**Expected result:**
- no 500 error
- because admin has the same agent then there should be response with data about the agent

**Comment by konstyefremov** [comment]
The description of the bug contains errors. 

Linked sentry errors links to "GET {culture}/api/{v:apiVersion}/agency/agents/{agentId}/markup-policies"
not the URL in the description.
