### ISSUE TITLE
Remove fake ages for adult passengers in bookings

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#776]
Need to add a migration to remove all passenger ages where age is larger than 30 years (in Bookings table)

**Comment by sergeyf-QA** [comment]
**Summary:**
in Bookings table now are now bookings with passenger age>30 years
In testing I used 
WHERE "Rooms" @> '[{"passengers": [{"age": 30}]}]' ;
changing years from 30 up to 110 years.

**OK on DEV.**
