### ISSUE TITLE
Create endpoints to show list of root agencies in admin panel

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#778]
Current admin panel uses a list of endpoints to show counterparties list and to search there, mainly in Counterparties controller.
Need to add the same endpoints (if missing) for agencies in AgenciesController.

++ Need to add new endpoints to this task comments

**Comment by sergeyf-QA** [comment]
**Summary:**
GET /{culture}/api/{v}/admin/agencies/root-agencies returns the list of root agencies only.

**OK on DEV.**
