### ISSUE TITLE
Admin-panel. The current status and state of the counterparty is not shown.

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#78]
On https://manage-dev.happytravel.com
Log in by any administrator.

On the counterparty page it is impossible to understand its current status and state.
Regarding the status and the state of the counterparty, show only reverse action buttons (for example, if the counterparty is inactive, only the Activate button should be shown; if the counterparty is active, only the Deactivate button should be shown).
This should be done to avoid errors, e.g. if you try to verify an already verified counterparty.

POST: https://edo-dev.happytravel.com/en/api/1.0/admin/counterparties/{counterpartyId}/verify-full-access
```
{
  "status": 400,
  "detail": "Verification as fully accessed is only available for counterparties that were verified as read-only earlier"
}
```

POST: https://edo-dev.happytravel.com/en/api/1.0/admin/counterparties/{counterpartyId}/verify-read-only
```
{
  "status": 400,
  "detail": "Verification as read-only is only available for counterparties that are in pending verification step"
}
```

**Comment by mingazhev** [comment]
Now we return verification state and date from backend. Now it's your turn @alexander-plekhanov

**Comment by DenisSychev** [comment]
If the counterpart has a status active, we have to hide the «Verify Readonly» button.
For example «The Clouds company» has the status: active, but there is the  «Verify Readonly» button in the agency. Clicking the button will cause an error
```
{
    "status": 400,
    "detail": "Verification as read-only is only available for counterparties that are in pending verification step"
}
```
See pic. https://drive.google.com/file/d/1yQHr49hMf4qxO5DpCkWrfP2-NYMgpfIC/view?usp=sharing

**Comment by DenisSychev** [comment]
It has been done and is working on https://manage-dev.happytravel.com
