### ISSUE TITLE
Add predictions control filters for location markups

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#781]
Need to add filters for predictions control in location markups creation control (show only localities and countries in predictions).
To achieve this it is needed to add a query param to osaka's request:

`https://osaka-dev.happytravel.com/api/1.0/predictions/search?text=Du&types=Locality&types=Country`

This is the new endpoint, returning prediction sets instead of predictions array as before. Predictions are grouped by type now

++ may be need to update other queries in predictions usage to use the new endpoint

**Comment by sergeyf-QA** [comment]
**Summary:**
- now https://osaka-dev.happytravel.com/api/1.0/predictions/search?text=Du&types=Locality&types=Country  is used at all Add markup popups
- 
so, only cities and countries may be found in all Add Markup popups

**OK on DEV.**
