### ISSUE TITLE
Implement evaluation endpoint

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#782]

**Comment by DFSko** [comment]
done

**Comment by sergeyf-QA** [comment]
can not test because endpoint is not yet available

**Comment by sergeyf-QA** [comment]
**Summary:**
GET https://api-dev.happytravel.com/api/1.0/searches/{searchId}/results/{htId}/room-contract-sets/{roomContractSetId} works fine

**OK on DEV.**
