### ISSUE TITLE
Remove agent context dependencies from services that are not bound to agents directly

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#787]
AgentContext is passed to lots of services as a method parameter.
When we use direct API, there is not agent, there is an API-client concept.
Need to rewrite the services to use some common concept and not to use AgentContext in direct api at all.

**Comment by ViTsvetkova** [comment]
@mingazhev can we close it?

**Comment by mingazhev** [comment]
no, it is still actual, as a part of direct API code quality improvement

**Comment by sergeyf-QA** [comment]
**Summary:**
- looks like main agent app functionality was not hurt

**OK on DEV.**
