### ISSUE TITLE
Admin-panel. The current counterparty balance is not shown.

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#79]
Going to almost each counterparty triggers a GET https://edo-dev.happytravel.com/en/api/1.0/admin/payments/counterparties/{counterpartyId}/balance/{currency} which always has the same result:
```
{
  "status": 400,
  "detail": "Payments with accounts for currency USD is not available for current counterparty"
}
```

**Comment by sergeyf-QA** [comment]
**Summary:**
- in case the counterparty has any balance then the balance is shown on the counterparty page
- in case the server returns 400 then front shows the message

**OK on DEV.**
