### ISSUE TITLE
Check and fix sentry errors in kanazawa (dev)

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#791]
Check and fix kanazawa errors:

https://sentry1.happytravel.com/organizations/happytravel/issues/?project=7&query=is%3Aunresolved&statsPeriod=14d

They may be related to different situations - broken booking, failed booking or other.
Need to investigate and solve each situation separately

**Comment by konstyefremov** [comment]
There is an error in Ngenius payments. According to logs payment went from status Authorized to Captured with the request from the frontend. And simultaneously there was another request coming from webhook which moved the payment from Authorized to Authorized. 

@DFSko tried to fix this problem around a month ago with this PR https://github.com/happy-travel/edo/pull/1056 It contains code that catches statuses Captured / Authorized. But it was removed from the final draft of PR. This problem looks like isn't fixed.

@mingazhev approved moving this task back to @DFSko

**Comment by konstyefremov** [comment]
Summary of other errors. 

1. An error with Payfort. Postponed its resolution due to low priority.
2. Status of Payment wasn't saved properly. This error was fixed around August 31, remains of it were left in the database. 
Fixed this by setting proper status in db.
