### ISSUE TITLE
Remove counterparty-related markups (controllers, types, policies)

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#797]
- Counterparty markup management should be deleted
- Existing counterparty markups should be changed to corresponding root agency markup

**Comment by sergeyf-QA** [comment]
**Summary:**
- Counterparty markup management is deleted
- Existing counterparty markups are changed to corresponding root agency markup in 'MarkupPolicies' table.

**OK on DEV.**
