### ISSUE TITLE
Admin-panel. Account balance transactions do not work

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#80]
Increase manually:
POST: https://edo-dev.happytravel.com/en/api/1.0/admin/payments/counterparty-accounts/{counterpartyAccountId}/increase-manually
```
{
  "status": 400,
  "detail": "Could not find account"
}
```

Decrease manually:
POST: https://edo-dev.happytravel.com/en/api/1.0/admin/payments/counterparty-accounts/{counterpartyAccountId}/decrease-manually
```
{
  "status": 400,
  "detail": "Could not find account"
}
```

Appends money to a counterparty account:
POST: https://edo-dev.happytravel.com/en/api/1.0/admin/payments/counterparty-accounts/{counterpartyAccountId}/replenish
```
{
  "status": 400,
  "detail": "Could not find account"
}
```

Subtracts money from a counterparty account due to payment cancellation:
POST: https://edo-dev.happytravel.com/en/api/1.0/admin/payments/counterparty-accounts/{counterpartyAccountId}/subtract
```
{
  "status": 400,
  "detail": "Could not find account"
}
```

**Comment by Raibo** [comment]
Initially, the problem was that front-end used counterpartyId and agencyId values in requests, instead of their respective accounts' Ids.
Increase and decrease manually for counterparty's account currently work fine.

As for agency accounts, front-end still uses agencyId.
To retrieve agency's accounts Ids, following endpoint can be used
`/en/api/1.0/admin/agencies/814/accounts`

**Comment by sergeyf-QA** [comment]
@Raibo 
now there is a back-end issue:

1) Increase manually, Decrease manually, Replenish and Substract return:

`{"type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","title":"Internal Server Error","status":500,"detail":"42601: zero-length delimited identifier at or near \u0022\u0022\u0022\u0022","instance":"/en/api/1.0/admin/counterparty-accounts/342/increase-manually","spanId":"5b834d1ffed9034a","traceId":"0e9e7e9f801d944093eb59c25f836f96","requestId":"0HM91SLF5ERCF:00000004","x-request-id":["f2aacd1cf6d891b2488452df11ada9db"],"StackTrace":"   at Npgsql.NpgsqlConnector.\u003CReadMessage\u003Eg__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)\n   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)\n   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)\n   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)\n   at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken)\n   at HappyTravel.Edo.Data.EdoContext.ExecuteScalarCommand[T](String commandText) in /src/HappyTravel.Edo.Data/EdoContext.cs:line 168\n   at HappyTravel.Edo.Data.EdoContext.TryAddEntityLock(String lockId, String lockerInfo, String token) in /src/HappyTravel.Edo.Data/EdoContext.cs:line 151\n   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func\u00603 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates\u00601 shouldRetryResultPredicates, Func\u00605 onRetryAsync, Int32 permittedRetryCount, IEnumerable\u00601 sleepDurationsEnumerable, Func\u00604 sleepDurationProvider, Boolean continueOnCapturedContext)\n   at Polly.AsyncPolicy\u00601.ExecuteAsync(Func\u00603 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)\n   at HappyTravel.Edo.Api.Infrastructure.EntityLocker.Acquire(Type entityType, String entityId, String lockerName) in /src/Api/Infrastructure/EntityLocker.cs:line 29\n   at HappyTravel.Edo.Api.Infrastructure.FunctionalExtensions.ResultLockExtensions.WithLock[TResult](IEntityLocker locker, String lockerName, Func\u00601 operation, ValueTuple\u00602[] locks) in /src/Api/Infrastructure/FunctionalExtensions/ResultLockExtensions.cs:line 70\n   at HappyTravel.Edo.Api.Infrastructure.FunctionalExtensions.ResultLockExtensions.WithLock[TResult](IEntityLocker locker, String lockerName, Func\u00601 operation, ValueTuple\u00602[] locks) in /src/Api/Infrastructure/FunctionalExtensions/ResultLockExtensions.cs:line 82\n   at HappyTravel.Edo.Api.Infrastructure.FunctionalExtensions.ResultLockExtensions.BindWithLock[TInput,TOutput](Task\u00601 target, IEntityLocker locker, Func\u00602 func) in /src/Api/Infrastructure/FunctionalExtensions/ResultLockExtensions.cs:line 19\n   at HappyTravel.Edo.Api.AdministratorServices.CounterpartyAccountService.IncreaseManually(Int32 counterpartyAccountId, PaymentData data, ApiCaller apiCaller) in /src/Api/AdministratorServices/CounterpartyAccountService.cs:line 282\n   at HappyTravel.Edo.Api.Controllers.AdministratorControllers.CounterpartyAccountsController.IncreaseMoneyManuallyToCounterpartyAccount(Int32 counterpartyAccountId, PaymentData paymentData) in /src/Api/Controllers/AdministratorControllers/CounterpartyAccountsController.cs:line 120\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeActionMethodAsync\u003Eg__Logged|12_1(ControllerActionInvoker invoker)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeNextActionFilterAsync\u003Eg__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeInnerFilterAsync\u003Eg__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeNextResourceFilter\u003Eg__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilder.\u003C\u003Ec.\u003C\u003CBuildPipeline\u003Eb__8_0\u003Ed.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpRequestDurationMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpRequestCountMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpInProgressMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\n   at HappyTravel.StdOutLogger.HttpContextLoggingMiddleware.Invoke(HttpContext httpContext, ILogger\u00601 logger)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","Severity":"ERROR","InvariantSeverity":"ERROR","SqlState":"42601","MessageText":"zero-length delimited identifier at or near \u0022\u0022\u0022\u0022","Position":52,"File":"scan.l","Line":"1149","Routine":"scanner_yyerror"}`

**Comment by Raibo** [comment]
We tried to reproduce the issue, but with no success. I guess it was a temporary technical issue of some sort, now works reliably.

**Comment by sergeyf-QA** [comment]
@cyberkarma 
could you please make Done popus green? Now they are yellow.
![Screenshot at May 31 17-34-00](https://user-images.githubusercontent.com/74529212/120208927-b7a50580-c236-11eb-9f92-d17b9ead3e41.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
now Increase manually, Decrease manually, Replenish and Substract functions work well on counterparty pages

**OK on DEV.**
