### ISSUE TITLE
PUT ​/{culture}​/api​/{v}​/agency does not write "CountryHtId" & "LocalityHtId" to DB

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#805]
**How to reproduce:**
- execute PUT ​/{culture}​/api​/{v}​/agency with filled "CountryHtId" & "LocalityHtId"

**Actual result:**
- "CountryHtId" & "LocalityHtId" are not written to the "Agencies" table

**Expected result:**
- "CountryHtId" & "LocalityHtId" should be written to the "Agencies" table by PUT ​/{culture}​/api​/{v}​/agency

**Comment by konstyefremov** [comment]
It will be implemented here
https://github.com/happy-travel/agent-app-project/issues/809

**Comment by mingazhev** [comment]
We will not edit locality htId from agent endpoints. This will be available in admin endpoint only, here:
https://github.com/happy-travel/agent-app-project/issues/811
