### ISSUE TITLE
Edit localityHtId of existing agencies

### ISSUE THREAD

**Issue by konstyefremov** [happy-travel/agent-app-project#809]
PUT ​/{culture}​/api​/{v}​/agency

By executing this query we should be able to add localityHtId for the agency.
CountryHtId should be loaded from the mapper.
Provided localityHtId should be validated on existence.

----
UPDATE: this task is incorrect, need to use another endpoint

**Comment by mingazhev** [comment]
Closing task as incorrect: agencies are not supposed to edit their locality
