### ISSUE TITLE
Admin-panel. Booking information is presented as JSON.

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#81]
On https://manage-dev.happytravel.com

Steps:
1. Go to "The Clouds company" counterparty (id: 83).
2. Choose some booking in list.

Result:
Booking information is presented as JSON (see pic. https://drive.google.com/file/d/1nHPWMOoNnkNDqmuTHLCrrcmJlTT7seKj/view?usp=sharing).

Expectations:
The booking information should be formatted in a way that can be easily understood by the administrator. If there is no drawn appearance, you can output just a list of booking parameters, but not code in JSON format.

**Comment by cyberkarma** [comment]
not actual
