### ISSUE TITLE
Credit card details are not hidden in Kibana logs

### ISSUE THREAD

**Issue by Raibo** [happy-travel/agent-app-project#817]
Here is an example of a request where one can observe credit card credentials.
They should be hidden.

Particular place to look to: Request body -> `"card_number":`

Link to Kibana:
https://logs.happytravel.com/app/discover#/doc/d9804df0-e80f-11eb-bbd4-c3d108d86f4e/fluentd-jumeirah-connector-2021.11?id=zomc4HwBIvATEvEiqaaC

**Comment by konstyefremov** [comment]
The issue still persists. Currently card's data is sanitized from logs, but not from audit. The next PR should fix the problem.
