### ISSUE TITLE
Check confirmed jumeirah connector bookings to have supplier references filled

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#821]
Some multi room bookings in jumeirah may partially fail in invisible way for us (https://github.com/happy-travel/agent-app-project/issues/820)

In this task need to check that all bookings for supplier jumeirah (8) in EDO PROD have `supplierRoomReferenceCode` in each room filled and not empty.
SQL script needs to be added to the task comments.

**Comment by Raibo** [comment]
[check_supplier_room_ref_code.txt](https://github.com/happy-travel/agent-app-project/files/7506274/check_supplier_room_ref_code.txt)

**Comment by Raibo** [comment]
There are such bookings on prod.

**Comment by Raibo** [comment]
Added filter condition "Status" = 3

**Comment by Raibo** [comment]
[check_supplier_room_ref_code.txt](https://github.com/happy-travel/agent-app-project/files/7506404/check_supplier_room_ref_code.txt)

**Comment by Raibo** [comment]
No bad bookings on prod
