### ISSUE TITLE
Direct API | POST /bookings returns "isDirectContract": null

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#823]
**How to reproduce:**
- execute POST https://api-dev.happytravel.com/api/1.0/bookings

**Actual result:**
- "isDirectContract": null

**Expected result:**
- "isDirectContract" returns false or true

**Comment by mingazhev** [comment]
@DFSko let's remove this from direct contracts model at all

**Comment by sergeyf-QA** [comment]
**Summary:**
now "isDirectContract"  is no in response of POST https://api-dev.happytravel.com/api/1.0/bookings 

**OK on DEV.**

**Comment by DFSko** [comment]
done
