### ISSUE TITLE
Direct API | POST /bookings returns 400 error when gifu is trying to create a card

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#824]
**How to reproduce:**
- execute https://api-dev.happytravel.com/api/1.0/searches
{
  "checkInDate": "2021-12-24T14:15:22Z",
  "checkOutDate": "2021-12-25T14:15:22Z",
  "filters": "AvailableOnly",
  "nationality": "AE",
  "propertyType": "Hotels",
  "ratings": "NotRated",
  "residency": "string",
  "roomDetails": [
    {
      "adultsNumber": 1,
      "childrenAges": [
        0
      ],
      "isExtraBedNeeded": true,
      "type": "NotSpecified"
    }
  ],
  "htIds": [
    "Locality_607184"
  ]
}
- take the first accommodation htId
- using results from search above execute POST https://api-dev.happytravel.com/api/1.0/bookings

**Actual result:**
- 400 error
[message.txt](https://github.com/happy-travel/agent-app-project/files/7503827/message.txt)

**Expected result:**
- no errors, done booking

**Comment by sergeyf-QA** [comment]
**Summary:**
no 400 issue during booking

**OK on DEV.**

**Comment by DFSko** [comment]
done
