### ISSUE TITLE
Direct API | Client's password is shown in logs

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#825]
**How to reproduce:**
- create your direct api client
- log in and try to execute any endpoint
- go to https://logs-dev.happytravel.com/app/discover and try to find something using your client name as a keyword

**Actual result:**
- in logs also is a client password
![Screenshot at Nov 09 14-22-40](https://user-images.githubusercontent.com/74529212/140915549-e917d785-c0c7-45ad-b67e-691735e387ad.png)

**Expected result:**
- no client password in readable state

**Comment by mingazhev** [comment]
@DFSko could you check what we can do there?

**Comment by sergeyf-QA** [comment]
**Summary:**
client_secret=[hidden]&client_id=serg in logs now

**OK on DEV.**
