### ISSUE TITLE
'Server Request Error' popup appears when accepting new agent invitation

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#829]
**How to reproduce:**
- invite an agent
- click on 'Join HappyTravelDotCom Travel & Tourism LLC' button in invitation letter

**Actual result:**
- 'Server Request Error' popup appears for a second when accepting new agent invitation 

https://user-images.githubusercontent.com/74529212/141122980-14e53b50-b084-461f-abf7-2d6a0df06504.mov

**Expected result:**
- no 'Server Request Error' popup appears when accepting new agent invitation

**Comment by mingazhev** [comment]
@alexander-plekhanov looks like frontend issue, see the requests:

**Comment by mingazhev** [comment]
Link to repeat:

https://u12040071.ct.sendgrid.net/ls/click?upn=rChOrQRk7-2Fsc5DQhcmzX66Lr1rF0vZK6HRHBe6ukJrlbbdtgf-2BMp0MN1AxnwbZHF839cRBI9R3svP5R15BMRDI-2BksrdnF-2B8fkgHod6UZLibG2o5mrGGrPRNSCDCVo3I5IIEV6FetDmBPbh7I99XkuOWohtQZUNeRmS47C4qIwaazMCmYhV0dwUfdlPHS0CDoVhCV7vv7LJgmvWRcgBwPsbpjnMmd-2FS7D5ie4n2F-2BDx4-3DmEIO_BlR-2FlZ3ZpZ19VI-2B1-2B5W5cy5KUw649b0WvIpy3aNhXUWsHe2ViiAbxhE2MUS53Ef5ke45cOR0B2lLXxV64Tyj-2B8qD9vE1Q657V48ukJOXxj-2F2uooeY-2B7fNCcC5Ying1u-2BrBjasgczWkC2nPwgKvfzE-2FwKv1ncPahC73Yaix-2Fd6nJWyKa3MCAaRHJOYg1RRFTT6D3ciSr9fRNh6l-2BXBHolCFxq-2FYQyNIS1z1EIOZ9pXzMgCklj2iTb3SMTeTHEYbsLTcItWVc83iLb6Rj1-2BUCNMaednPJCUaicTPUi8LYc2Rtz4Bgv5jeUXgZ-2B3zGj1WuZVB4o6hgtDXBSJ2BifS00wVT5gDWfUiG8greVn4VPvwXCCH1rMUDh-2BBSalKqfIiVn

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
the issue is still here

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
the issue is reproduced in Firefox browser

**Comment by nikolaeva31** [comment]
Error is reproduced.

**Comment by alexander-plekhanov** [comment]
moved
