### ISSUE TITLE
Check and add if needed NetstormingConnector supplier requests-responses logging

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#83]
I think that rakuten-connector-like approach will be fine enough but maybe there will be another.
Need to optionally log all requests and responses for supplier. Enabling request logging should be set as a separate independent setting.

Need to try make this as best and reusable as possible to introduce to other connectors as a standard.
After doing the task, need to add tips for QA how they can turn on and view the logs

**Comment by DFSko** [comment]
implemented in happy-travel/agent-app-project#356

**Comment by sergeyf-QA** [comment]
**Summary:**
in case setting for connector is set to 'false' in consul logs are not existed, if 'true' - they are.

**OK on DEV.**
