### ISSUE TITLE
Add validation to all incoming request models

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#835]
Every validation must return a readable and clear error message if validation fails

**Comment by sergeyf-QA** [comment]
check these cases also:
1) I still may set wrong Nationality and Residency, like 'RRRRR'
look at booking where "ReferenceCode"='DEV-HTL-000VL5-01'
2) it would be great to add a check that we may add only letters, w/o digits and signs

**Comment by sergeyf-QA** [comment]
**Summary:**
validation looks fine.

**OK on DEV.**
