### ISSUE TITLE
TravelClick connector. Preliminary steps

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#840]
Create a project for TravelClickConnector.
Add sentry, stdout logger, Fukuoka logger, tracing, error handling, Redis, db, vault, other needed things.
Add controllers with the needed endpoints without an exact implementation.

**Comment by sergeyf-QA** [comment]
**Summary:**
project for TravelClickConnector https://github.com/happy-travel/travel-click-connector

**OK on DEV.**
