### ISSUE TITLE
Null reference exception when trying to book expired evaluation result

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#844]
https://sentry1.happytravel.com/organizations/happytravel/issues/3938/

Possible steps to reproduce:
1. Find a hotel in Jumeirah
2. Go to 3-rd step
3. Wait for more than 15 minutes
4. Try to book

**Comment by nikolaeva31** [comment]
Will it be expected result? @mingazhev 
{"status":400,"detail":"Could not find evaluation result"}
