### ISSUE TITLE
HbPro may return result with empty room contract sets

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#847]
https://sentry1.happytravel.com/organizations/happytravel/issues/3925

https://logs-dev.happytravel.com/app/discover#/doc/74b82510-a78b-11eb-a6b0-c1009595f0bf/fluentd-edo-2021.11?id=Fi8AKn0BE0m8udhyn4XK 

Search as:
`Terrasini, Italy - 19.11-21.11 - 1 room - RU`

**Comment by sergeyf-QA** [comment]
**Summary:**
no sentry error while wide availability search a HotelBook Pro accommodations.

**OK on DEV.**
