### ISSUE TITLE
Empty strings in contract info

### ISSUE THREAD

**Issue by DFSko** [happy-travel/agent-app-project#848]
For some accommodations mapper returns array with empty string instead of empty array

Request: GET https://nakijin-dev.happytravel.com/api/1.0/accommodations/Accommodation_11064745
Response:
```
{
...
"contacts": {
        "emails": ["hotelpush@xmltravelgate.com"],
        "faxes": [""],
        "phones": ["971858585"],
        "webSites": [""]
    }
...
}
```

Extexted result: 
```
"contacts": {
        "emails": ["hotelpush@xmltravelgate.com"],
        "faxes": [],
        "phones": ["971858585"],
        "webSites": []
    }
```

**Comment by hasmikharutyunyan** [comment]
moved to `YouTrack`

**Comment by hasmikharutyunyan** [comment]
[Youtrack task](https://track.happytravel.tech/issue/HP-596/Empty-strings-in-contract-info)
