### ISSUE TITLE
Asymmetrical localityZoneHtId and localityZone values

### ISSUE THREAD

**Issue by DFSko** [happy-travel/agent-app-project#849]
For some accommodations mapper returns asymmetrical localityZoneHtId and localityZone values

Request: GET https://nakijin-dev.happytravel.com/api/1.0/accommodations/Accommodation_11064745
Response:
```
...
"location": {
        ...
        "localityZoneHtId": "",
        "localityZone": null,
        ...
    }
...
```

Expected result:

```
...
"location": {
        ...
        "localityZoneHtId": null,
        "localityZone": null,
        ...
    }
...
```

**Comment by hasmikharutyunyan** [comment]
moved to `YouTrack`

**Comment by hasmikharutyunyan** [comment]
[Task in YouTrack](https://track.happytravel.tech/issue/HP-595/Asymmetrical-localityZoneHtId-and-localityZone-values)
