### ISSUE TITLE
Update frontend UI and models to correlate with changed backend logic

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#854]
Changes in models and routes:

...

**Comment by Raibo** [comment]
New registration request example:
```
{
  "agent": {
    "title": "title",
    "firstName": "firstName",
    "lastName": "lastName",
    "position": "position",
    "email": "email"
  },
  agency: {
    "name": "name",
    "address": "address",
    "billingEmail": "billingEmail",
    "fax": "fax",
    "phone": "phone",
    "postalCode": "postalCode",
    "website": "website",
    "vatNumber": "vatNumber",
    "legalAddress": "legalAddress",
    "preferredPaymentMethod": "preferredPaymentMethod",
    "localityHtId": "localityHtId"
  }
}
```

**Comment by Raibo** [comment]
deleted everything starting with "/admin/counterparties/"
get `counterparty/contract-file` moved to `agency/contract-file`

**Comment by sergeyf-QA** [comment]
**Summary:**
were checked info from Agency table at:
1) registration
2) registration of subagencies
3) registration of invited agent
4) agency edit page
5) a hat on the Settings screen
6) the preferred method of payment for the reservation to be set from the agency settings
7) substitution of the country in the nationality / residence of the search immediately after the region

**OK on DEV.**
