### ISSUE TITLE
Error during registration

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#856]
**How to reproduce:**
- try to create a new agent

**Actual result:**
- after 2nd registration step (entering confirmation code) it redirects me to https://dev.happytravel.com/settings for a second that leads to error https://sentry1.happytravel.com/organizations/happytravel/issues/3951/?project=4&referrer=webhooks_plugin

**Expected result:**
- after 2nd registration step (entering confirmation code) I should be at once redirected to 3rd registration one

**Comment by alexander-plekhanov** [comment]
I think it's a kind of a minor bug that happens when you visit /settings page before registration process initialization. I'll fix it but I'm not sure that it happens often.

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
could you look at the attached video with issue please?
I still see blaming setting page
https://user-images.githubusercontent.com/74529212/142586399-72b3b876-bb14-4cbb-9310-4f7ffaad521e.mov

**Comment by sergeyf-QA** [comment]
**Summary:**
- sentry error is fixed, though the reason (screen blaming) is still here, decided do not fix that.

**OK on DEV.**
