### ISSUE TITLE
Discarding a cancelled booking doesn't return all the money if the booking was cancelled previously

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#876]

**Comment by ViTsvetkova** [comment]
@mingazhev could you please update

**Comment by mingazhev** [comment]
@ViTsvetkova issue is actual and needs to be done

**Comment by AlexeyShok** [comment]
The status of the Cancelled booking is final, so it is not possible to Discard such a booking. So I'm closing the issue.

**Comment by nikolaeva31** [comment]
**AR**: When changing a paid booking status from 'Confirmed' to 'Discard' status, the payment is refunded in full to balance account.
