### ISSUE TITLE
Add information about nationality and residency in the third step of the search

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#877]
It is necessary to display information about nationality and residence in the third step of the search. This makes it easier to communicate with the office about search errors.

**Comment by alexander-plekhanov** [comment]
Added to the third step on dev and for HT agency on prod only.

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
- set Nationality to RU
- set Residency to GB
- proceed to the 3rd search step

**Actual result:**
- RU / RU

**Expected result:**
- RU / GB

**Comment by sergeyf-QA** [comment]
**Summary:**
Nationality and Residency is shown on 3rd search step.

**OK on DEV.**
