### ISSUE TITLE
Add an ability to filter rooms by tags, requested by a client

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#88]
With this task need to:
1. Update contracts: replace "Tags" property with IsDirectContract bool flag (in RoomContractSet)
2. Change availability request to allow filter results on connector (to show only direct contracts). Maybe another flag or enum.
3. Implement filtering on Illusions connector to return only direct contracts if needed
3. Add a setting for direct-connectivity-only results. The data from settings will be used to execute connector requests.

P.S. Please keep in mind that some accommodations will have both direct and non-direct contracts. So filtering may be needed to apply on the second step search too.

**Comment by mingazhev** [comment]
How to test (on dev):
1. Set agent system setting with AdditionalSearchFilters
![изображение](https://user-images.githubusercontent.com/43397444/113152804-ee1ece00-924f-11eb-92e0-c31ca9553887.png)

2. Search with this agent in Dubai. Results should contain only Jumeirah Emirates Towers (as it is only direct contract in our dev system)

If setting is not set, all results should be available, without a filter

**Comment by sergeyf-QA** [comment]
**Summary:**
the functionality works according to Vadim's comment.

**OK on DEV.**

**Comment by DFSko** [comment]
Ready for production
