### ISSUE TITLE
Fixe sentry error for hard supplier disable

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#884]
https://sentry1.happytravel.com/organizations/happytravel/issues/3990/?referrer=webhooks_plugin

**Comment by mingazhev** [comment]
Closing, postponed

**Comment by sergeyf-QA** [comment]
**Summary:**
no sentry error when POST /{culture}/api/{v}/admin/accommodations/bookings/{bookingId}/refresh-status executed

**OK on DEV.**
