### ISSUE TITLE
Accelerate the first step of searching for hotel availability by city

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#885]
It is necessary to speed up the first step of searching for the availability of hotels in the city, while saving all hotel offers and without switching to an asynchronous mode of interaction with edo.
Now the search in the city of Verona takes 7 minutes, in the city of Moscow it ends by timeout. 

Expected Result: Search in Verona and Moscow is completed in about 60 seconds

**Comment by sergeyf-QA** [comment]
**Summary:**
the 1st search step for HBPro works less than 60 secs

**OK on DEV.**
