### ISSUE TITLE
Fix sentry issue with ETG booking

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#890]
https://sentry1.happytravel.com/organizations/happytravel/issues/3860/?query=is%3Aunresolved&statsPeriod=14d

need to fix the issue or add more logging if it is not clear what the issue is

**Comment by DFSko** [comment]
Booking created at 06 October in Created status. It was not paid and finalized
After more than month (09 November) booking status was updated manually throught admin panel
Update status failed because booking not finalized

**Comment by sergeyf-QA** [comment]
**Summary:**
nothing was fixed, look at Denis's comment above.

**OK on DEV.**
