### ISSUE TITLE
Bug: After cancellation Columbus booking, the reservation remains in Pending Cancellation status

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#891]
Bug on Columbus production environment. After cancellation, the reservation remains in Pending Cancellation status.
HTL-AE-000U73-01
HTL-AE-000V73-01
HTL-AE-000J63-01

**Comment by AlexeyShok** [comment]
An error was detected on the Columbus side - on the ReadHotelReservation () request, an empty first and last name is returned for all guests except the first. A request was sent to Columbus technical support.

**Comment by sergeyf-QA** [comment]
**Summary:**
now cancelled bookings at Columbus have Cancelled status.

**OK on DEV.**
