### ISSUE TITLE
Add the list of the notifications to the Agent's tab

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/agent-app-project#892]
Need to add the list of the notifications which the Agent has to the Agent's tab
![image](https://user-images.githubusercontent.com/90184684/143852708-e5e495bb-f142-471b-b839-b2e7bf5a42be.png)

**Comment by alexander-plekhanov** [comment]
Added it to the Application Settings tab.

**Comment by sergeyf-QA** [comment]
**Summary:**
on /settings/agent/application now are shown notification types

Notifications that you receive
Booking Voucher
Deadline Approaching
Credit Card Payment Received
Counterparty Account Balance Replenished
Agent Invitation (Email only)
Child Agency Invitation (Email only)
Agent Successful Registration
Child Agency Successful Registration
Agency Activity Changed
Booking Summary Report For Agent (Email only)
External Payment Links (Email only)
Payment Link Paid Notification (Email only)
Counterparty Activity Changed
Agency Verification Changed
Counterparty Account Balance Subtracted
Counterparty Account Balance Increased Manually
Counterparty Account Balance Decreased Manually
Account Balance Management Notification (Email only)
Booking Invoice
Successful Payment Receipt
Booking Cancelled
Booking Finalized
Booking Status Changed (Application only)

**OK on DEV.**
