### ISSUE TITLE
Adding CRUD endpoints for suppliers

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#896]
Need add CRUD endpoints for suppliers as described in https://github.com/happy-travel/docs/wiki/Suppliers-service-(Draft)

GET /suppliers Lists all suppliers in the format: [ { "id": 6, "name": "Columbus", "isEnabled": true, "connectorUrl": "https://wq-dev.happytravel.com" }, { "id": 1, "name": "Etg", "isEnabled": true, "connectorUrl": "https://etg-dev.happytravel.com" } ]

POST /suppliers Adds a new supplier.

PUT /suppliers/{supplierName} Changes the name and / or Url of the supplier

DELETE /suppliers/{supplierName} Deletes the given supplier

PUT /suppliers/{supplierName}/enable Enables the specified supplier

PUT /suppliers/{supplierName}/disable Disables the specified supplier

GET /suppliers/{supplierName} Returns supplier details (contact details of the supplier's technical support, a link to the site with the supplier's API documentation). Available from the admin panel for supplier information

**Comment by sergeyf-QA** [comment]
**Summary:**
- GET ​/api​/{v}​/suppliers gets a list of suppliers
- POST /suppliers adds a new supplier
- PUT /suppliers/{supplierId} changes an info of the supplier
- DELETE /suppliers/{supplierId} deletes the given supplier
- GET /suppliers/{supplierId} Returns supplier details (contact details of the supplier's technical support, a link to the site with the supplier's API documentation)


**OK on DEV.**
