### ISSUE TITLE
400 error when I arrive to agent markup page

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#90]
**How to reproduce:**
- log in as any user
- go to https://dev.happytravel.com/settings/agents
- open console in your browser
- find your user in list and click on him

**Actual result:**
- https://edo-dev.happytravel.com/en/api/1.0/agency/agents/undefined/markups returns 400 error when I arrive to the agent markup page: 
{"errors":{"agentId":["The value 'undefined' is not valid."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"Bad Request","status":400,"instance":"/en/api/1.0/agency/agents/undefined/markups","spanId":"8022f11ba9b7a84e","traceId":"ea951518e9c4da4eaf8332b7a8ae5c5f","requestId":"0HM7FJ2JGVNCI:00000018"}

**Expected result:**
- no 400 error

**Comment by DFSko** [comment]
@mingazhev I think it's a client bug, because as you can see request uri contains 'undefined' parameter
