### ISSUE TITLE
Booking monitoring dashboards

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#902]
**Bryan's thoughts**
Confirmed bookings – date wise selection , booking date ,  as well as travel date , 
Cancelled booking - travel date
Pending bookings -  booking date ,  as well as travel date , 
Supplier wise selection  ( for example if we select jumeirah Mina Salm ….. it will show all bookings for this hotel  ) with option to select travel date wise .. this can have multiple options as below 
 
Supplier wise selection 
confirmed bookings  
cancelled bookings 
Pending Status / Manual correction   
All this with ability to sort by booking date & travel date  

**Initial task**
A table with pending and manual correction needed bookings

- [x] #903
- [x] #904
- [x] #905
- [x] #906
- [x] #907

**Comment by DFSko** [comment]
all tasks completed

**Comment by DenisSychev** [comment]
Some improvements have been described in other tasks:
https://github.com/happy-travel/ueda/issues/216
https://github.com/happy-travel/ueda/issues/217
https://github.com/happy-travel/ueda/issues/218
