### ISSUE TITLE
Write queries to get the details for dashboards (for frontend)

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#905]

**Comment by DFSko** [comment]
@alexander-plekhanov 

Pagination:
Add $top and $skip to query string
For example: /en/api/1.0/admin/agencies/{agencyId}/accommodations/bookings?$top=10&$skip=10

Sorting:
Add $orderBy to query string
$orderBy supports multiple fields separated by comma, direction can be set after field name
For exampe: /en/api/1.0/admin/agencies/{agencyId}/accommodations/bookings?$orderBy=checkinDate desc, created

Filtering:
Add $filter to query string
For exampe: /en/api/1.0/admin/agencies/{agencyId}/accommodations/bookings?$filter=status eq 'ManualCorrectionNeeded'

Get only needed properties:
Add $select to query string
For example: /en/api/1.0/admin/agencies/{agencyId}/accommodations/bookings?$select=id

All OData parameters can be combined
I suggest using library for generating query string 
https://github.com/jaredmahan/odata-query-builder or https://github.com/techniq/odata-query
