### ISSUE TITLE
Implement Pending and Manual correction needed bookings dashboard

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#906]
Implement the dashboard based on @DFSko  instructions:

https://github.com/happy-travel/agent-app-project/issues/905

**Comment by alexander-plekhanov** [comment]
Need to implement extra dashboard.

**Comment by sergeyf-QA** [comment]
**Summary:**
- Pending Bookings dashboard is implemented on https://manage-dev.happytravel.com/bookings/pending
- Manual Correction Needed dashboard is implemented on https://manage-dev.happytravel.com/bookings/mcn
 
**OK on DEV.**
