### ISSUE TITLE
Implement booking dashboards with date selection

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#907]
Need to create the dashboards Bryan asks for (in the parent task)

https://github.com/happy-travel/agent-app-project/issues/902

**Comment by DenisSychev** [comment]
This has been done and is working in a dev. environment.
On the Bookings Management page in the Bookings Created At tab.

But at the moment the filtering of bookings only works by creation date.

**Comment by DenisSychev** [comment]
The agent should only be able to select one day so that they can see a list of bookings made on a particular day.
This will be described in another task.
