### ISSUE TITLE
Direct API | minus children amount and strings are allowed

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#914]
**How to reproduce:**
send minus children amount or any string "childrenNumber" in body of POST https://api-dev.happytravel.com/api/1.0/availabilities/searches
{
    "ids": ["Accommodation_11064745"],
    "checkInDate": "2022-01-29T00:00:00Z",
    "checkOutDate": "2022-01-30T00:00:00Z",
    "roomDetails": [
        {
            "adultsNumber": 1,
            "childrenNumber": -10,
            "type": "NotSpecified"
        }
    ],
    "nationality": "EN",
    "residency": "EN"
}

**Actual result:**
200 OK

**Expected result:**
- 400 error with meaningful error like it is for "adultsNumber"

**Comment by DFSko** [comment]
Request model doesn't have property "childrenNumber" and it value ignored
