### ISSUE TITLE
Administrator with Auditor role cannot list all administrator roles

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#916]
Administrator with Auditor role cannot list all administrator roles.
Endpoint: https://edo-dev.happytravel.com/en/api/1.0/admin/administrator-roles

Expected Result: Any administrator, regardless of role, can get a list of all administrator roles

**Comment by DenisSychev** [comment]
It has been fixed on https://manage-dev.happytravel.com
