### ISSUE TITLE
Update booking `HTL-AE-000JB3-01` in production database

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#919]
The booking does not match with the booking in Jumeirah.
Need to create an SQL script, review with colleagues and run on production with @evm-andrey 

What needs to be done in details:
1. Get confirmation code for the confirmed room and the final supplier price
2. In EDO database:
- Remove not needed rooms from `BookedRooms`
- Change the price accordingly (to contain the price for a single room)
- Change the price in SupplierOrders (to contain the supplier's price for a single room)
- Change the price in Payments (for this payment)
- ... Check if changes needed in other tables
- @kirillta suggests to add audit logs for this operation
3. Add appropriate record into Jumeirah-connector database
4. Refresh booking status from Admin panel in EDO
5. Check that booking is displayed correctly

**Comment by Raibo** [comment]
Here is the booking info:
We have 3 rooms in "Rooms", prices are identical. Therefore all prices can be just divided by 3.
Payment type is Virtual Account.
The room confirmation number is `CI3OM4GK`.
The room to keep is that with passenger `Mr. ALEXEY KIM` (there are 2 such identical rooms in our Booking version, we keep 1)

I suggest the following actions:

1. Increase balance by 29 757.3 manually with comment
2. Change booking status to Confirmed using admin panel.
3. Run the following SQL (change prices, delete unwanted rooms and fill the confirmation code into "Rooms"):
```
update "Bookings"
set "TotalPrice" = round(44635.95/3, 2) --round just to remove redundant zeros
, "Rooms" = '[{"type": "NotSpecified", "price": {"amount": 14878.65, "currency": 1}, "remarks": [{"key": "Description", "value": "Beit Al Bahar 1-Bedroom Royal Villa-130 sqm-2 king beds-free wifi, breakfast"}, {"key": "Policy", "value": "Reservation must be cancelled 21 days prior to arrival to avoid penalty of 100% stay including tax"}, {"key": "Features", "value": "Buffet breakfast included; Complimentary Wi-Fi.; Complimentary access to Wild Wadi waterpark™"}, {"key": "Amenities", "value": "Meal included - breakfast; High speed internet connection; King bed; Bathtub & jacuzzi separate; Upgraded bathroom amenities; High ceilings; Non-smoking"}, {"key": "View", "value": "Ocean view"}, {"key": "Number of beds", "value": "1"}], "mealPlan": "Bed and breakfast", "boardBasis": "BedAndBreakfast", "passengers": [{"age": null, "title": "Mr", "isLeader": true, "lastName": "KIM", "firstName": "ALEXEY"}], "deadlineDate": "2021-11-04T10:00:00+00:00", "deadlineDetails": {"date": "2021-11-04T10:00:00+00:00", "isFinal": true, "remarks": [], "policies": [{"fromDate": "2021-11-04T10:00:00+00:00", "percentage": 100.0}]}, "isExtraBedNeeded": false, "contractDescription": "Beit Al Bahar One Bedroom Royal Villa (NET B2B STD VCC Bed and Breakfast)", "isAdvancePurchaseRate": false, "supplierRoomReferenceCode": "CI3OM4GK"}]' 
where "ReferenceCode" = 'HTL-AE-000JB3-01'

update "SupplierOrders"
set "Price" = round(153688.5/3, 2), "ConvertedPrice" = round(42110.65/3, 2)
where "ReferenceCode" = 'HTL-AE-000JB3-01'
```

Also there questions left:
1. Is there sufficient audit logging involved.
2. What should we do with Jumeirah database

**Comment by Raibo** [comment]
With help of the devops team implemented the fix plan.
