### ISSUE TITLE
Bug: System.ArgumentOutOfRangeException in AvailabilityProcessor.CalculateRoomRate()

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#921]
Need fix bug: System.ArgumentOutOfRangeException in AvailabilityProcessor.CalculateRoomRate() method. See:
https://logs-dev.happytravel.com/app/discover#/doc/74b82510-a78b-11eb-a6b0-c1009595f0bf/fluentd-hotelbook-pro-connector-2021.11?id=xAp7cH0BWCLh1WHloFt6

**Comment by sergeyf-QA** [comment]
**Summary:**
now there is no out of range error on 3rd search step at HotelBookPro,
tested with 'Le Meridien Fairway, Dubai, The United Arab Emirates' hotel

**OK on DEV.**
