### ISSUE TITLE
Add Jumeirah number of units support

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#924]
Jumeirah API supports `Number of units` - count of available rooms.
Need to use this to hide room contract sets that are not fully available.

E.g. when there are 3 same rooms in RoomContractSet, but the number of units equals 1, this means that we can't book the whole set, because there is only 1 room available.
This RoomContractSet should be deleted from results as not available.

For single room booking it is enough to check only the room's number of units and hide it if it is 0.

++ unit tests for the new functionality

P.S. Need to be very careful while writing and reviewing, this is very important supplier and errors may cost a lost.
Please ask @kirillta to carefully review the PR

**Comment by mingazhev** [comment]
Testing tips:
Check that Jumeirah availability search and booking not broken. At least booking fails with "Firewall rejection error" - it is ok on dev for now

**Comment by sergeyf-QA** [comment]
**Summary:**
- `Check that Jumeirah availability search and booking not broken. At least booking fails with "Firewall rejection error" - it is ok on dev for now` - works as described.

**OK on DEV.**
