### ISSUE TITLE
Merge cancellation policies in RoomContractSet's Deadline property

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#93]
Current implementations returns cancellation policies within a room (in Deadline property).
Need to calculate the policies for the whole RoomContractSet and return to frontend.
For example, when there are 2 rooms in a set, where
- Room 1 have 100% penalty after April 4 (room cost 100$)
- Room 1 have 100% penalty after April 10 (room cost 100$)

The whole room contract set must have three policies:
- 50% between April 4 and April 10
- 100% after April 10

+ Tests will be useful there
_Additionally, need to return these new cancellation policies in Travelgate option_

**Comment by DFSko** [comment]
Ready for production
