### ISSUE TITLE
Check and inspect booking statuses history in frontend side

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#931]
We have the booking status change history on frontend side:

![image](https://user-images.githubusercontent.com/43397444/144376437-8d8a0296-19c4-4408-9a21-91c3f93a332d.png)

It may look not very useful for getting information about what was happenning with the booking, e.g.:
When booking is cancelled, it is always shown as `Cancelled by supplier`, while initial operation may be done by agent (agent cancellation request) or API (cancellation during status refresh).

Need to discuss and rethink how to show this better, @AlexeyShok may help with clarifying what each status history record mean (initation, source and etc.)

**Comment by Raibo** [comment]
![image](https://user-images.githubusercontent.com/8547320/146750898-fac3313e-e1b0-47d8-acee-f03f510a9e61.png)
![image](https://user-images.githubusercontent.com/8547320/146750964-510e5f6d-b4c1-437b-8fec-ba1d8fa4a5db.png)

I suggest showing `initiator` field in "Status Changes".
This field is included in the status-history data.

**Comment by alexander-plekhanov** [comment]
Need some assistance in task understanding.

**Comment by AlexeyShok** [comment]
Message examples:
1. Wednesday, 16 February 2022 at 09:22 changed to Confirmed by Supplier from agent Id 691 request

**Comment by ViTsvetkova** [comment]
New suggestion:
In Agent App show the following status update:
Wednesday, 16 February 2022 at 09:22 changed to Confirmed by Supplier from HT Agency agent request
Wednesday, 16 February 2022 at 09:22 changed to Confirmed by Supplier from agent Name Suename request

**Comment by sergeyf-QA** [comment]
**Summary:**
- added showing who does the action and is divided into events of the supplier by colors and format
![image](https://user-images.githubusercontent.com/74529212/188899089-e0af100f-579b-4315-9228-d945ecbbd460.png)

**OK on DEV.**

**Comment by alexander-plekhanov** [comment]
Also fixed on agent side.
