### ISSUE TITLE
Error in rakuten updater

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#934]
https://logs-dev.happytravel.com/app/discover#/doc/74b82510-a78b-11eb-a6b0-c1009595f0bf/fluentd-rakuten-connector-updater-crone-2021.12?id=rFBKc30BOwCh_seVs-rk

`{"message":"Property code list is empty"}`

**Comment by ViTsvetkova** [comment]
@mingazhev was it resolved?

**Comment by nikolaeva31** [comment]
Last error in logs was July 15. 
Not reproduced more.
