### ISSUE TITLE
Remove option to cancel bookings

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/agent-app-project#936]
Remove options: 
1. to cancel bookings 
2. pay by card 
in statuses -` 'Invalid', 'Rejected'`

![Screenshot 2021-12-04 at 21 57 27](https://user-images.githubusercontent.com/38030865/144721362-3fcfd1bc-04ec-4b89-8382-303f9a6d1afc.png)

**Comment by mingazhev** [comment]
This is frontend task, moving to @alexander-plekhanov

**Comment by sergeyf-QA** [comment]
**Summary:**
- now, bookings with Rejected and Invalid statuses have no Pay now by card and Cancel booking buttons

**OK on DEV.**
