### ISSUE TITLE
Weird price calculations with discounts

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#938]
**How to reproduce:**
- add new global markup 
{
  "description": "test",
  "templateId": 1,
  "templateSettings": {
    "addition": 10000
  },
  "order": 1,
  "currency": USD"
}

- check on front that markup is applied OK 
Belogorsk, The Russian Federation
Zolotaya Melnitsa Mini Hotel
17-18 Dec
1 Guest
RU RU
price for first room is 10020.14

- add discount for an agency which does not have any markup and for new created markup
{
  "discountPercent": 5,
  "description": "test",
  "targetMarkupId": "[new_test_markup_id]"
}

- check how discount is implemented on front with the same hotel again

**Actual result:**
![Screenshot at Dec 06 17-49-31](https://user-images.githubusercontent.com/74529212/144866887-0fdfffe6-115f-4fdc-b979-0403147bffab.png)
19x(1.06-1.06x0.05)+(10000-10000x0.05)=9 519,13
where 
19 is cost
1.06 is 1st global markup
10000 is 2nd global markup
0.05 is 5% discount

**Expected result:**
19x1.06+(10000-10000x0.05)=9 520,14

**Comment by DFSko** [comment]
i guess you can markup for agency, agent or location
global markup, then discount, then second markup
