### ISSUE TITLE
Invitations | 'string' role

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#941]
**How to reproduce:**
- go to https://dev.happytravel.com/settings/agency/invitations/send
- check roles

**Actual result:**
- 'string' role exists

**Expected result:**
- in case 'string' role is necessary there, perhaps is it better to rename the 'string' role?

**Comment by Raibo** [comment]
Removed the role

**Comment by sergeyf-QA** [comment]
**Summary:**
- https://dev.happytravel.com/settings/agency/invitations/send page is no 'string' role
- in GET https://edo-dev.happytravel.com/en/api/1.0/agent-roles response os no string role

**OK on DEV.**
