### ISSUE TITLE
Addidng activation/deactivation history

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#944]
It is necessary to add the saving of the history of activations and deactivations of suppliers

**Comment by sergeyf-QA** [comment]
**Summary:**
POST ​/api​/{v}​/suppliers​/{supplierId}​/activate activates specified supplier
POST ​/api​/{v}​/suppliers​/{supplierId}​/deactivate deactivates specified supplier

**OK on DEV.**
