### ISSUE TITLE
Add supplier list to model HappyTravel.Edo.Api.Models.Accommodations

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#950]
Need to add supplier list to model HappyTravel.Edo.Api.Models.Accommodations. The list is needed to be displayed on the front

**Comment by sergeyf-QA** [comment]
**Summary:**
- suppliers list is returned in case "isSupplierVisible": true in availability search settings
GET /{culture}/api/{v}/accommodations/{htId}
GET api/{culture}/accommodations/availabilities/searches/{searchId}/results/{htId}/accommodation
- in case "isSupplierVisible": false in availability search settings these endpoints return
"suppliers": null

**OK on DEV.**
