### ISSUE TITLE
Add IsMultiRoomSupported field to provider model

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#952]
Need to add IsMultiRoomSupported field to supplier model

**Comment by sergeyf-QA** [comment]
**Summary:**
- "IsMultiRoomFlowSupported" column exists in "Suppliers" table of Sunpu DB
- GET /api/{v}/suppliers returns "isMultiRoomFlowSupported" definition
- POST /api/{v}/suppliers writes definitions to "IsMultiRoomFlowSupported" column in "Suppliers" table of Sunpu DB
- PUT /api/{v}/suppliers writes definitions to "IsMultiRoomFlowSupported" column in "Suppliers" table of Sunpu DB

**OK on DEV.**
