### ISSUE TITLE
Fix after completed 954 task: Separation of permissions for managing agencies and agents

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#955]
After the completion of task 954, it is necessary to check the correctness of the front and, if necessary, make adjustments
https://github.com/happy-travel/agent-app-project/issues/954

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
agency balance is not shown on agency page for admin with Finance manager role
remove Change agency tab on agent page for admin with Finance manager role
