### ISSUE TITLE
Add hotel list filter for get accommodation endpoint

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#956]
Need to add hotel list filter for get accommodation endpoint. We will only book with HBPro direct contracts and hotel chains

**Comment by sergeyf-QA** [comment]
**Summary:**
- now HBPro will not give to book on dev not a test hotel. In test mode, booking of the following hotels is allowed: id 1251201, 1251539, 1251542, 1251543, 1251563. Previously, in this case, an error was received from the supplier, now the connector will return the error directly. 
{"status":400,"detail":"In a test environment, bookings are only allowed in test hotels"}
So it is possible to book only test hotels in HBPro.
- GET accommodations sends to mapper only hotels from loaded list (now contains 30066 ones, not 1.3 mln)

**OK on DEV.**
