### ISSUE TITLE
Check that all booking fields are passed correctly in Jumeirah-connector

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#962]
We had a problem with the booking, when the booking in Jumeirah failed with an error validating required fields.
Jumeirah's support recommends to do the following:

_"set children count as “0” and special request as “None” if you don’t have value"_

Need to check if we pass 0 when there are no children in booking and set "None" for special request if it is filled as empty or null now.

**Comment by sergeyf-QA** [comment]
**Summary:**
- impossible to check from qa side
