### ISSUE TITLE
After cancelling a booking with an expired deadline, you receive an email saying "Your payment will be refunded to your account shortly", which is untrue.

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/agent-app-project#97]
On http://dev.happytravel.com/
In Chrome, Safari.

**Steps.**
1. Log in some agent who can booking and who has a real email address;
2. Make a booking for which the deadline has already passed;
3. Cancel this booking;
4. Wait until the email arrives.

**Result.**
The email saying "Your payment will be refunded to your account shortly" that it is untrue, because the cancellation policy will not refunds to the account balance.

**Expectations.**
When a booking is cancelled and there is no refund to the account, you should receive an email with the appropriate text.
It is probably possible to explain that some funds will be returned or no funds will be returned according to the cancellation policy.

**Comment by Raibo** [comment]
After discussion with @kirillta and @DenisSychev, we decided to just write something like "Funds will be returned according to the cancellation policy" in cancellation letters.

**Comment by DenisSychev** [comment]
The text has been added to the email template and works in the system.
Example:
<img width="650" alt="Снимок экрана 2021-11-21 в 23 31 42" src="https://user-images.githubusercontent.com/17127277/142777941-906f5e86-a773-4028-b513-64bcaece8e08.png">
