### ISSUE TITLE
Create the basic infrastructure to mini PMS

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/agent-app-project#976]
Need to create the basic infrastructure to a mini PMS. It is necessary to connect all the necessary resources (database, Sentry, telemetry, logging, Vault, Consul, Redis). The mini PMS must be created in a new Git project (choose name from 100 Japan Castles).

**Comment by sergeyf-QA** [comment]
**Summary:**
- https://github.com/happy-travel/komoro is created in GitHub
- also komoro exists in Vault, Consul, db

**OK on DEV.**
