### ISSUE TITLE
Update projects with libraries to .net6

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#987]
The following projects to be updates:

- [x] #1123
- [x] #1124
- [x] #1125
- [x] #1126
- [x] #1127
- [x] #1128
- [x] #1129
- [x] ~~https://github.com/happy-travel/synxis-connector~~ (already updated)
- [x] ~~https://github.com/happy-travel/execution-time-observer~~ (archived)

**Comment by DFSko** [comment]
done

**Comment by sergeyf-QA** [comment]
**Summary:**
- updated to net6

**OK on DEV.**
