### ISSUE TITLE
Sentry error in tgx-channed on production

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#988]
Static data download failure
https://sentry1.happytravel.com/organizations/happytravel/issues/4156

**Comment by Raibo** [comment]
The problem might be due to EF bug.
If so, then the solution is to use EF version with the bug fixed, which is one of the following:
`3.1.14`, `5.0.5`, `6.0-preview2`

https://github.com/dotnet/runtime/issues/49683#issuecomment-801477869

**Comment by Raibo** [comment]
To QA:
The thing to test is that it did not break anything, and particularly that `/api/settings/review-date/*` endpoints work

**Comment by sergeyf-QA** [comment]
**Summary:**
GET {{ _.tgx.baseUrl }}/api/settings/review-date-ids
GET {{ _.tgx.baseUrl }}/api/settings/review-date/AvailDestinationTree
PUT {{ _.tgx.baseUrl }}/api/settings/review-date/AvailDestinationTree
PUT {{ _.tgx.baseUrl }}/api/settings/review-date/CurrencyInfo
GET {{ _.tgx.baseUrl }}/api/settings/review-date/CurrencyInfo
work fine.

**OK on DEV.**
