### ISSUE TITLE
Add the payment method to summary bookings notifications model

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#989]
Summary notifications should contain payment method for every booking row, both for admins and agents

**Comment by ViTsvetkova** [comment]
@mingazhev was it done or not?

**Comment by DenisVelinen** [comment]
The PaymentType variable has been added to the email templates Bookings Due Payment by Date by an Agency (d-6c99ec77db8d47ada2c60477e901116b) and Summary Notification of Bookings (d-0e0a051dfa62481aa54e3e3bc2ee7d0b).
