### ISSUE TITLE
DirectApi. Requests validation remarks

### ISSUE THREAD

**Issue by oleg-n-k** [happy-travel/agent-app-project#993]
- ~~Request validators exist but aren't used~~ see the comment section
- Add validation of the number of ids and RoomDetails in AvailabilityRequest
- Add validation of AdultsNumber and the number of ChildrenAges in RoomOccupationRequest

**Comment by DFSko** [comment]
All validators used automatically before controllers

**Comment by oleg-n-k** [comment]
.AddFluentValidation(fv =>
                {
                    fv.DisableDataAnnotationsValidation = true;
                    fv.ImplicitlyValidateRootCollectionElements = true;
                    fv.ImplicitlyValidateChildProperties = true;
                    **fv.RegisterValidatorsFromAssembly(Assembly.GetExecutingAssembly());**
                });

**Comment by sergeyf-QA** [comment]
**Summary:**
- added limits for 

children age is from 0 to 100
other: 
"SearchLimits": {
    "MaxCountriesCount": 1,
    "MaxLocalitiesCount": 1,
    "MaxAccommodationsCount": 1000,
    "MaxRoomsCount": 5,
    "MaxGuestsCount": 9
  }

**OK on DEV.**
