### ISSUE TITLE
500 error during global markup adding/deleting

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#994]
**How to reproduce:**
- execute DELETE /{culture}/api/{v}/admin/global-markups/{policyId}
or
POST /{culture}/api/{v}/admin/global-markups with such body
{
  "description": "string",
  "templateId": 2,
  "templateSettings": {
    "addition": 3
  },
  "order": 9,
  "currency": "USD",
  "locationScopeId": "",
  "destinationScopeId": ""
}

**Actual result:**
-  500 error though markups were created/deleted
https://sentry1.happytravel.com/organizations/happytravel/issues/4178/?referrer=webhooks_plugin

**Expected result:**
- global markup creation/deletion w/o errors

**Comment by kirillta** [comment]
#960

**Comment by kirillta** [comment]
Same as #995

**Comment by sergeyf-QA** [comment]
@kirillta
OK for me then.
