### ISSUE TITLE
Can not update global markups

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/agent-app-project#995]
**How to reproduce:**
- execute PUT /{culture}​/api​/{v}​/admin​/global-markups​/{policyId}
{
  "description": "string",
  "templateId": 2,
  "templateSettings": {
    "addition": 3
  },
  "order": 9,
  "currency": "USD"
}

**Actual result:**
{
  "status": 400,
  "detail": "Cannot parse agency id"
}

**Expected result:**
- global markup edition w/o error

**Comment by konstyefremov** [comment]
@mingazhev I think we previously decided to remove markups updates? The user should be able to remove the old markup and add a new one. 

So, the correct solution here is to remove endpoints for editing?

**Comment by konstyefremov** [comment]
We decided to not fix this issue for now. First, there is no editing functionality on frontend. Second, it will be modified to a different flow and reworked entirely - https://github.com/happy-travel/agent-app-project/issues/960#event-5799304144

**Comment by kirillta** [comment]
Closed if no one has any objections. @sergeyf-QA

**Comment by sergeyf-QA** [comment]
@kirillta 
OK for me then.
