### ISSUE TITLE
Refactor Vault secrets

### ISSUE THREAD

**Issue by kirillta** [happy-travel/agent-app-project#997]
Make similar secrets appear alike, i.e. all credentials must have one name and path logic across all projects; fix wording, nesting etc. All non-secret settings must be moved to Consul.

Including following changes:
- [ ] `bronevik-connector`: define and eliminate the difference between `api-connection` and `api-hotels-connection`
- [ ] `edo`: `ElasticSearch` and `elastic` looks similar
- [ ] `gifu`: improve separation between card providers
- [ ] `iwtx`: should use full service name. Most of settings lays on the first level.
- [x] `jumeirah-connector`: `actual-credit-cards` section founds across different secrets. Probably there are do the same.
- [ ] `osaka`: isn't `osaka/predictions-update` the same as `predictions-updater`?
- [x] `rakuten-connector`: isn't this one same with `rtx`?

**Comment by mingazhev** [comment]
`jumeirah-connector: actual-credit-cards` totally removed

**Comment by mingazhev** [comment]
removed `rtx` key from dev vault. there were no such key on production

**Comment by DFSko** [comment]
moved to https://track.happytravel.tech/issue/HP-597
